### ISSUE TITLE
Support parametrized specs

### ISSUE THREAD

**Issue by sslavic** [bazaarvoice/jolt#102]
Please consider supporting parametrized specs. Ideally such spec definition would be light/efficient to reuse with different parameter values. E.g. if one wants to enrich incoming JSON documents with a field whose value is a unique number - one would read spec with defaultr transformation, spec would in place of value have a named or indexed placeholder, and when transforming concrete document one would, besides input JSON and spec, also provide parameter values.

**Comment by milosimpson** [comment]
This can now be done with the Modify transform in Jolt 0.0.22 where you can lookup things from the transform context.

**Comment by rockoder** [comment]
Hey @milosimpson.. looking for something similar where I need to pass date as a parameter to the spec. Could you point to some example which I could refer to?

**Comment by rockoder** [comment]
Was able to work referring this: https://github.com/bazaarvoice/jolt/blob/master/jolt-core/src/test/java/com/bazaarvoice/jolt/ChainrContextTest.java. Thanks.

**Comment by aravindaspirant** [comment]
> This can now be done with the Modify transform in Jolt 0.0.22 where you can lookup things from the transform context.


Hello @milosimpson

I  tried using modify-default-beta operation which is a ContextualTransform, but I am not sure how to read the values from context inside the spec.  Ex: 

```
[
  {
    "operation": "modify-default-beta",
    "spec": {
      "*": "&",
      "payload": {
        "*": "&",
        "new_field": "$context.some_value_from_context"
      }
    }
  }
]

```

OR am i interpreting your comment incorrectly?
