### ISSUE TITLE
Comma separated to array + data transform

### ISSUE THREAD

**Issue by rvt** [bazaarvoice/jolt#107]
Hello,

I have the following input :  "tags" : "131,132",

Can I transform that into a array?

So I get the output: "tags" : ["131","132"],

Then I want to map the number's into my own dataset using a static map, for example:
"131": "foo",
"132": "bar",

So my final output would be: "tags" : ["foo","bar"],

Hope that makes sense..

**Comment by milosimpson** [comment]
Yeah, Jolt is currently just about changing the structure of you JSON data.  You have described a 
1. text based split
2. map of values
3. reassembly into a JSON array

Which Jolt does not really support.
