### ISSUE TITLE
Error: Server Error https://jolt-demo.appspot.com/

### ISSUE THREAD

**Issue by ashokrajab** [bazaarvoice/jolt#1087]
Facing the below error when trying to access the demo app:
<img width="1344" alt="Screenshot 2021-08-16 at 7 24 38 PM" src="https://user-images.githubusercontent.com/13289422/129575064-8630bd79-591f-4a03-a2a9-767c445edb38.png">

**Comment by mishapopov** [comment]
Since last Friday, 14th

**Comment by muhammaddaniyal** [comment]
Any idea when this is supposed to be fixed? Is there any alternative to test the jolt script?

**Comment by leandrodsn** [comment]
is there another option to test jolt codes?

**Comment by leandrodsn** [comment]
Is there another option to test jolt codes?

**Comment by fusion4bass** [comment]
My friend grzesiu threatens to start riots unless the site comes back alive.

**Comment by sharathr1** [comment]
@bvbuild @milosimpson  Could you please provide any updates on this?

**Comment by tufailkhan89** [comment]
I found an alternative to run jolt locally. 
Refer to https://github.com/milosimpson/jolt-demo/tree/master/server

We need https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/appengine-java11/appengine-simple-jetty-main  for running the jolt server war locally (This uses java11, but can be made to run using java 8, by updating property  as below 
```
<maven.compiler.source>8</maven.compiler.source>
<maven.compiler.target>8</maven.compiler.target>
```

**Comment by sharathr1** [comment]
Thanks a lot @tufailkhan89 , It worked !!

**Comment by FlorinCiocirlan** [comment]
Hi, @tufailkhan89
Can you please provide your pom.xml ? I had many trials on running jolt-demo locally but without success.
Error: 

> [ERROR] Failed to execute goal on project server: Could not resolve dependencies for project com.bazaarvoice.jolt:server:war:0.0.1-SNAPSHOT: com.example.appengine.demo:simple-jetty-main:jar:1 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

**Comment by tufailkhan89** [comment]
Get Checkout of https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/appengine-java11/appengine-simple-jetty-main and then change target java (11 to 8 ) version in pom (in module - `appengine-simple-jetty-main`)as 
    <maven.compiler.source>8</maven.compiler.source>
    <maven.compiler.target>8</maven.compiler.target>
and run mvn clean install in this module. Once this is done successfully, then only you can build  https://github.com/milosimpson/jolt-demo/tree/master/server, else it will fail with below error.
@FlorinCiocirlan 

> Hi, @tufailkhan89
> Can you please provide your pom.xml ? I had many trials on running jolt-demo locally but without success.
> Error:
> 
> > [ERROR] Failed to execute goal on project server: Could not resolve dependencies for project com.bazaarvoice.jolt:server:war:0.0.1-SNAPSHOT: com.example.appengine.demo:simple-jetty-main:jar:1 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

**Comment by mahieddine** [comment]
For those who are interested, I've hosted it here 

http://20.199.72.212:8080/#inception

**Comment by mahieddine** [comment]
You can use now http://20.199.72.212/#inception instead and soon it will be available on http://jolt-demo.tech to bookmark it easily
