### ISSUE TITLE
Append/Concat operation/wildcard???

### ISSUE THREAD

**Issue by gsolano777** [bazaarvoice/jolt#111]
Hi, 

First, awesome library!!! I would like to ask if there is any way to append a constant to a specific value.

Like for example I want to take an ID attribute and produce a URL:

input: 
{
    "id" :  "1234"
}

output:
{
   "url": "http://some/url/1234"
}

Thanks!!

**Comment by milosimpson** [comment]
There is not out of the box support for that.  Additionally, I can not think of any "tricky" way to get that to happen.

This would be one of those cases where you would you have to implement a Transform yourself.
