### ISSUE TITLE
Map to Array transformation

### ISSUE THREAD

**Issue by IvanVas** [bazaarvoice/jolt#112]
Hi,

I'm trying to transform the below, unsuccessfully for now. Could you help?
- Input -

```
{
    "SecondaryRatings": {
        "First": "one",
        "Second": "two"
    }
}
```
- Output - 

```
{
    "SecondaryRatings": [
        {
            "name": "First",
            "value": "one"
        },
        {
            "name": "Second",
            "value": "two"
        }
    ]
}
```

Thanks a ton!

**Comment by SUNYTYAGI** [comment]
Hi could you please help to write specs?

input
{
	"a": "100",
	"b": "200",
	"name": "Jimmy"
}

output:
{
    "alphabet":[
      {
        "A":"100",
         "B":"200"
     }
  ],
 "name":"jimmy"
}

**Comment by milosimpson** [comment]
This spec does the transform, it is however kinda fragile.

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "name": "name",
      "a": "alphabet[0].A",
      "b": "alphabet[0].B"
    }
  }
]
```

Fragile, in that it is explictily mapping a -> A and b -> B.   There
