### ISSUE TITLE
Type safety

### ISSUE THREAD

**Issue by p-a-x** [bazaarvoice/jolt#113]
Hi ,

I just want to mention something in the general design what I see as troublesome.

It seems to me that you created your own custom java JSON object definition 
but you didn't create a new type for this. Instead you use Java.lang.Object.

Because everything in Java is java.lang.Object jolt methods like Chainr.fromSpec 
take without any notice just any input object. 

It took me half a day to figure out, that I accidentally put a org.json.JSONObject (the standard json object type in my code) into Chainr.transform. No error, exception or warning appeared, just unexpected output.

Is there a deeper reason to circumvent type safety ?

 Philipp

**Comment by milosimpson** [comment]
Ish.  The "core" of Jolt is pure Java; does not even have a dependency on Jackson.

If it had a dependency on Jackson (which could do the text JSON data to Java type work for me) then yeah, more Type safety would have been good.
