### ISSUE TITLE
Boolean output?

### ISSUE THREAD

**Issue by ismith** [bazaarvoice/jolt#114]
I'm doing something similar to the [hashDefault.json](https://github.com/bazaarvoice/jolt/blob/master/jolt-core/src/test/resources/json/shiftr/hashDefault.json) example, but I can't get it to give me a boolean value.  My nearly-working case is this:

Input:
```
 { "map" :
   {     
     "foo" : "Y",
     "bar" : "N"
   }
 }
```

Spec: 
```
[                                             
  {                                           
    "operation" : "shift",                    
    "spec" :                                  
    {                                         
      "map" : {                               
          "foo" :                             
          {                                   
            "N" : { "#false" : "output-key" },
            "Y" : { "#true" : "output-key" }   
          }                                   
      }                                       
    }                                         
  }                                           
]                                             
```

And of course that gives me `{"output-key" : "true"}`.

I had thought, based on the hashDefault.json example, that removing the # from the "#(true|false)" strings would give me `{"output-key" : true}`, but instead the whole output is `null`.

Is there a way of making the RHS output a boolean literal?

**Comment by milosimpson** [comment]
Not right now.  There may be a tricky way to get that done using the new Transpose logic.   The idea being if you added a boolean true and false to your document, you could reference them to be output.

**Comment by ismith** [comment]
Ah, cute - thanks.
