### ISSUE TITLE
How to do JSON conversion with special characters

### ISSUE THREAD

**Issue by CloudWise-Lukemiao** [bazaarvoice/jolt#1148]
Hello everyone, I want to [{"timestamp":1,"root.dd4.aa":14.5},{"timestamp":1,"root.dd4.bb":14.5}] convert jolt into [{"timestamp": 1, "root.dd4.aa1": 14.5}, {"timestamp": 1, "root.dd4.bb1": 14.5}]。This is a simple example of what I should do.

**Comment by ouxuyong** [comment]
@CloudWise-Lukemiao 我的这个spec可以达到你想要的效果，希望对你有帮助。
另外还有一个jolt教程项目，欢迎大家交流讨论 [jolt-universe](https://github.com/ouxuyong/jolt-universe)。

```json
[
  {
    "operation": "shift",
    "spec": {
      "*": {
        "timestamp": "[#2].timestamp",
        "root.dd4.aa": "[#2].root\\.dd4\\.aa1",
        "root.dd4.bb": "[#2].\\root\\.dd4\\.bb1"
      }
    }
  }
]
```

**Comment by CloudWise-Lukemiao** [comment]
> @CloudWise-Lukemiao This spec of mine can achieve the effect you want, I hope it can help you. In addition, there is a jolt tutorial project, welcome to communicate and discuss [jolt-universe](https://github.com/ouxuyong/jolt-universe).
> 
> ```json
> [
>   {
>     "operation": "shift",
>     "spec": {
>       "*": {
>         "timestamp": "[#2].timestamp",
>         "root.dd4.aa": "[#2].root\\.dd4\\.aa1",
>         "root.dd4.bb": "[#2].root\\.dd4\\.bb1"
>       }
>     }
>   }
> ]
> ```



> @CloudWise-Lukemiao This spec of mine can achieve the effect you want, I hope it can help you. In addition, there is a jolt tutorial project, welcome to communicate and discuss [jolt-universe](https://github.com/ouxuyong/jolt-universe).
> 
> ```json
> [
>   {
>     "operation": "shift",
>     "spec": {
>       "*": {
>         "timestamp": "[#2].timestamp",
>         "root.dd4.aa": "[#2].root\\.dd4\\.aa1",
>         "root.dd4.bb": "[#2].root\\.dd4\\.bb1"
>       }
>     }
>   }
> ]
> ```

Thanks for your help
