### ISSUE TITLE
Does something similar exist in Node?

### ISSUE THREAD

**Issue by gebrits** [bazaarvoice/jolt#121]
Sorry for creating an issue for this. I'm just in dire need of something like this in javascript/node. 
Does anybody know if such a library exists?

**Comment by milosimpson** [comment]
Not that I know of.

**Comment by gebrits** [comment]
@milosimpson: perplexed that such a lib doesn't seem to exist for node. I need to do massive ETL-style  operations on dozens of message-types from various APIs.  Seems to be a massive opportunity for a lib. Oh well preaching to the choir I guess ;)

**Comment by milosimpson** [comment]
If you find one, I will happily link to it.

**Comment by dszczyt** [comment]
See http://jsonpatch.com/
