### ISSUE TITLE
How to generate unique id in Jolt 

### ISSUE THREAD

**Issue by G-Balamurugan** [bazaarvoice/jolt#1233]
How to generate unique id in Jolt , by both as numeric and characters
[
  {
    "operation": "default",
    "spec": {
      "uniqueId": "=uuid()"
    }
  }
]
this is not working

**Comment by gbouget** [comment]
Hello, you need to create a new custom java function.

**Comment by G-Balamurugan** [comment]
thank you

**Comment by G-Balamurugan** [comment]
Can you help me ,  on how to assign the new custom java function value to field in json
