### ISSUE TITLE
Convert boolean values to int

### ISSUE THREAD

**Issue by mordfustang00** [bazaarvoice/jolt#1237]
Good Day. Is there a way to convert boolean values to integer

My input would be:

{
  "value": false or true
}

My expected output should be:

{
  "value": 0 or 1
}

I tried using "toInteger" code but only returns with boolean values (false, true)

**Comment by gbouget** [comment]
With shift + "true" or "false" correspondence. Second step is to tranform a string into an integer : =toInteger calls new [com.bazaarvoice.jolt.modifier.function.Objects](https://github.com/bazaarvoice/jolt/blob/master/jolt-core/src/main/java/com/bazaarvoice/jolt/modifier/function/Objects.java).toInteger() method in java.

```json
[
  {
    "operation": "shift",
    "spec": {
      "value": {
        "true": {
          "#1": "booleanValueAsInteger" // or value or &2
        },
        "false": {
          "#0": "booleanValueAsInteger"
        }
      }
    }
  },
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "booleanValueAsInteger": "=toInteger"
    }
  }
]
```

**Comment by mordfustang00** [comment]
many thanks :)
