### ISSUE TITLE
Does jolt support moving all unknown json keys into one value?

### ISSUE THREAD

**Issue by C-h-e-r-r-y** [bazaarvoice/jolt#124]
I need to move some keys directly and other key (I do not know what exactly) to input value. Exampel below:
````
{
    "myRootKey" : {
        "directMove":"directValue",
        "marker":"THE_MARKER",
        "someTextField":"someString",
        "someObject":{
            "someKey":"value"
        }
    }
}
````
Output should be:
````
{
    "myRootKey" {
        "subKey":{
            "directMove":"directValue",
        }
        "THE_MARKER": {
            "someTextField":"someString",
            "someObject":{
                "someKey":"value"
            }
        }
    }
}
````
This transformation do not works
````
[
    {
        "operation":"shift",
            "spec": {
                "myRootKey" : {
                    "*":"myRootKey.@marker.&"
                }
            }
    }
]
````
I can replace `@marker` with constant key like that `"*":"myRootKey.constant.&"` and all keys is moved into `constant` key, not `marker` value.

**Comment by C-h-e-r-r-y** [comment]
Change issue header and text.

**Comment by milosimpson** [comment]
This spec produces the output you want.   It may or may not be "generic enough" for you, as your use of names like "someText" and "someValue" imply that those fields may be unknown.

```
[
	{
		"operation": "shift",
		"spec": {
			"myRootKey": {
				"directMove": "myRootKey.subKey.&",
				"some*": "myRootKey.@(1,marker).&"
			}
		}
	}
]
```

**Comment by milosimpson** [comment]
Also fixed "better" by https://github.com/bazaarvoice/jolt/pull/176
