### ISSUE TITLE
How to define customised Functions

### ISSUE THREAD

**Issue by G-Balamurugan** [bazaarvoice/jolt#1240]
Whether it is possible to invoke a function in Jolt ,
like invoking a function and assigning the return value to a fields ,
If possible can you guide me with a example

**Comment by gbouget** [comment]
I don't know if it's the best solution, but it works:
1. Create a class that implements com.bazaarvoice.jolt.SpecDriven and com.bazaarvoice.jolt.Transform.
2. In the class variable that links the function name to the method to be executed (Map<String, Function> STOCK_FUNCTIONS), add the name of your custom function (key), and, in the value, the method to be executed that is to extend com.bazaarvoice.jolt.modifier.function.Function.

For further details, you can read https://github.com/bazaarvoice/jolt/issues/1091.

**Comment by priyadharshini13** [comment]
Please unsubscribe me from the email.ThanksPriyaSent from my iPhoneOn 9 Mar 2024, at 14:38, Gaëtan Bouget ***@***.***> wrote:﻿
I don't know if it's the best solution, but it works:

Create a class that implements com.bazaarvoice.jolt.SpecDriven and com.bazaarvoice.jolt.Transform.
In the class variable that links the function name to the method to be executed (Map<String, Function> STOCK_FUNCTIONS), add the name of your custom function (key) and the method to be executed that is to extend com.bazaarvoice.jolt.modifier.function.Function.

For further details, you can read #1091.

**Comment by G-Balamurugan** [comment]
Thank you
