### ISSUE TITLE
Splitting a string which is inside an array of objects

### ISSUE THREAD

**Issue by spnathan-ce** [bazaarvoice/jolt#1241]
I need help in Splitting a String and get the 0th index, the String is contained in a list of objects. The below are the details

Input JSON:
`{
  "data": [
    {
      "key": "name",
      "value": "Nathan"
    },
    {
      "key": "token",
      "value": "123#456#789"
    }
  ]
}`

Rule I am using:

`[
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "data": {
        "*": {
          "key": {
            "token": {
              "list": "=split('#',@(2,value))"
            }
          }
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "data": {
        "*": {
         // I need in help in accessing the list value I created in the modify-overwrite-beta operation
        }
      }
    }
  }
]
`

Expected output:
{
  "tokenValue":"123"
}

Please help on this

**Comment by gbouget** [comment]
There are several solutions, but this is probably the easiest to understand:

```json
[
  { // extract token value
    "operation": "shift",
    "spec": {
      "data": {
        "*": {
          "key": {
            "token": {
              "@(2,value)": "tokenValue"
            }
          }
        }
      }
    }
  },
  { // split on # 
    "operation": "modify-overwrite-beta",
    "spec": {
      "tokenValue": "=split('#',@0)"
    }
  },
  { // get first element of array
    "operation": "modify-overwrite-beta",
    "spec": {
      "tokenValue": "=firstElement"
    }
  }
]
```

![image](https://github.com/bazaarvoice/jolt/assets/12697930/4aba91be-b164-4b77-ad26-d7447af7a916)

**Comment by spnathan-ce** [comment]
Thanks a lot @gbouget

**Comment by spnathan-ce** [comment]
Resolved
