### ISSUE TITLE
Shift keys with null values

### ISSUE THREAD

**Issue by rsdb** [bazaarvoice/jolt#125]
I have been trying to remove elements from an array and have just discovered the ongoing ticket 'Removr should be able to handle arrays'. As a workaround I thought I would shift the element out of the array and then remove it. However I seem to have come across another issue with Shiftr's (non-)handling of nulls. Input:
```
{
	"rating": [
		{
			"primary": {
				"value": 3,
				"b": null
			},
			"quality": {
				"value": 3,
				"b": null
			}
		}
	]
}
```
The following works and moves all the elements out of the array to the root and removes 'b' named elements. 
```
Spec:
[
	{
		"operation": "shift",
		"spec": {
			"*": {
				"*": {
					"*": {
					        "*": {
						        "@": "&"
					       }
					}
				}
			}
		}
	},
	{
		"operation": "remove",
		"spec": {
			"b": ""
		}
	}
]
```
Output:
```
{
  "value" : [ 3, 3 ]
}
```
This version moves just 'value' elements, and removes them. 

Spec:
```
[
	{
		"operation": "shift",
		"spec": {
			"*": {
				"*": {
					"*": {
						"value": "&"
					}
				}
			}
		}
	},
	{
		"operation": "remove",
		"spec": {
			"value": ""
		}
	}
]
```
Output:
```
{ }
```
This version should (I think) remove 'b' keyed elements, but does not. Is this a bug?

Spec:
```
[
	{
		"operation": "shift",
		"spec": {
			"*": {
				"*": {
					"*": {
						"b": "&"
					}
				}
			}
		}
	},
	{
		"operation": "remove",
		"spec": {
			"b": ""
		}
	}
]
```
Output:
```
null
```
Thanks, 

Rob

**Comment by milosimpson** [comment]
Yeah, I don't know what is going on there.  If you know there are certain keys in the array that you know you don't want, you can use Shiftr to just "retain" the ones you want.

Something like this : 
```
[
	{
		"operation": "shift",
		"spec": {
			"rating": {
				"*": {
					"*": {
						"value": "&3--&1--&"
					}
				}
			}
		}
	},
	{
		"operation": "shift",
		"spec": {
			"*--*--*": "&(0,1)[#1].&(0,2).&(0,3)"
		}
	}
]
```

What this is doing is walking thru the data and flattening it all in step 1.  Then in step 2, we un-flatten the data.

**Comment by rsdb** [comment]
Apologies, I only just spotted the response to this post. It's a while ago now but yes I believe this was resolved IIRC, thanks.

**Comment by milosimpson** [comment]
Should be fixed by https://github.com/bazaarvoice/jolt/pull/178
