### ISSUE TITLE
custom conversion of a select field only?

### ISSUE THREAD

**Issue by mpopova-yottaa** [bazaarvoice/jolt#126]
Hi, 
I have a mix of "standard" and not so much fields in my input JSON doc. For example:

    {
	"instantseconds": 1429720551,
	"clientInfo": {
		"ip": "111.111.111.111",
		"userAgent": {
			"type": "COMPUTER"
                }
         }
    }

The "instantseconds" field is a value from the Java 8 Instance.getEpochSecond() call. I don't think JOLT supports this format out of the box. If so - I would need to convert it into some more standard format like Joda's fullDateTime format. However, all the rest of the fields are standard (strings, etc.) - so could be converted by using 'shift' operation easily.

What is the strategy for doing this kind of mixed conversion? Is it possible?

thanks!

Marina

**Comment by milosimpson** [comment]
"Is it possible?  (Out of the box)?" 
* No.

"What is the strategy for doing this kind of mixed conversion?"
* The idea is to use the "Out of the Box" transforms to do as much work as possible, but for specific business logic, you will need to implement your own "Transform".
* https://github.com/bazaarvoice/jolt/blob/master/jolt-core/src/main/java/com/bazaarvoice/jolt/Transform.java
* You can use your own Transform class as part of the chain of transforms like so 
** https://github.com/bazaarvoice/jolt/blob/master/jolt-core/src/test/resources/json/chainr/transforms/loadsGoodTransform.json

**Comment by mpopova-yottaa** [comment]
Milo,
thanks for the quick response.

So , just to clarify, to "chain" the transformations - is this how I would do that:

    [
    {
    "operation": "shift",
	"spec": {
		"id": "newid",
		"_clientInfo": {
			"ip": "client_ip"
		}
	},
    "operation" : "com.bazaarvoice.jolt.chainr.transforms.GoodTestTransform",
	"spec": {
		"a": "b"
	}
    }
    ]


thanks!

**Comment by milosimpson** [comment]
You will want to pass the "instantseconds" thru the shift, and then in the second JavaTransform do the logic of converting the date.

```
[
    {
    "operation": "shift",
    "spec": {
        "instantseconds": "newCustomTime",
        "id": "newid",
        "_clientInfo": {
            "ip": "client_ip"
        }
    },
    {
       "operation" : "com.mpopova-yottaa.JoltTimeTransform",
    }
]
```

Where com.mpopova-yottaa.JoltTimeTransform looks something like : 
```
class JoltTimeTransform implements Transform {

    @Override
    public Object transform( Object input ) {
        // Grab the time out of the incoming Json data / Map
        String secondsString = ((Map) input).get("newCustomTime"); 

        // Todo
        String fixedTime = null; // Your custom date manipulation logic.

        // Overwrite the old value with the new / fixed one.
        ((Map) input).put("newCustomTime", fixedTime); 
    }
}
```

**Comment by mpopova-yottaa** [comment]
Thanks, Milo - worked like a charm! :)

One gotcha on the above pseudo-code: due to the way my JSON is generated, the instantseconds field ["instantseconds": 1429720551] was converted to an Integer object in the input Map, and could not be cast to String as is.

Also, since the value could very well be above the Integer MAX range - I did not want to just assume it will always be an Integer, but leave a possibility for it to be Long as well.
So I just use Number class to cast the value from the Map instead:

    	@Override
	public Object transform(Object input) {
		// Grab the time out of the incoming Json data / Map
		Number eventTimestampObject = (Number) (((Map) input).get("event_timestamp"));

		try {
			long eventTimestampAsSeconds = eventTimestampObject.longValue();
			Instant instantSeconds = Instant.ofEpochSecond(eventTimestampAsSeconds);
     ....

Worked great!
Thanks for the advise,
Marina

**Comment by b-long** [comment]
@mpopova-yottaa @milosimpson I'm attempting something very similar to your `JoltTimeTransform`.  Would you be able to provide an example of unit testing this structure?

**Comment by milosimpson** [comment]
Follow the pattern of the Chainr unit / Integration test.

See ChainrTest https://github.com/bazaarvoice/jolt/blob/master/jolt-core/src/test/java/com/bazaarvoice/jolt/ChainrTest.java#L237

Where it loads a file like https://github.com/bazaarvoice/jolt/blob/master/jolt-core/src/test/resources/json/chainr/integration/firstSample.json
that has an
- input
- spec : where you would add your custom Java Transform
- expected output

And then uses diffy to verify that the Transform produces the expected Json.

**Comment by vectro** [comment]
Is a custom transform still the best way to handle this? Or is there a way to supply new functions to Modifier?

**Comment by milosimpson** [comment]
Yes custom transform is still the best way.   There is not a way to add new functions to Modify.

**Comment by zyongbo** [comment]
for the example of "JoltTimeTransform", does it need to be registered somewhere so that the Chainr is able to recognized it?

**Comment by sudharnath** [comment]
@milosimpson I have need to convert date formats. I have created a Custom spec and Custom transform and using Simpletraversal to get and set the values. But I am having trouble navigating through lists. Please suggest the right approach. Below are the custom spec and CustomTransform

My Source json
`
{
    "data" : {
       "myDateField" : "01-31-2021"
     }
}

`

The Custom Spec
`[
{
   "operation" : "com.custom.transform.DateFormatModifir",
   "spec" : {
         "myDateField" : {
                "path" : "data.myDateField",
                "source" : "MM-dd-yyyy",
                "target"  : "yyyy-MM-dd"
         }
    }
}
]
`

Custom Modifier class

`
public DateFormatModifir extends SpecDriven, Transform {

	Map<Object, Object> specs;

     public DateFormatModifir (Object specs) {
          this.specs = (Map<Object, Object>)specs;
     }
	 
	 @Override
	 public Object transform(){
		Map<Object, Object> values = (Map<Object, Object>) input;
		
		Set<Object> keySet = specs.keySte();
		
		for(Object key : keySet){
			
			Map<Object, Object> spec = (Map<Object, Object>) specs.get(key);
			String path  = (String) spec.get("path");
			
			SimpleTraversal<String> = new SimpleTraversal<String>(path);
			
			Optional<String> data = traversal.get(values);
			
			// .... have the logic to convert the date here 
			//  and setting the formated value as follows
			
			traversal.set(values, targetFormattedDate);
			
			
		}
		
		
	 }

}
`


Now the issue I am facing is to get the path for a field in a list. it does not work for for the following use case 

My Source json
`
{
    "data" : [
		{
			"myDateField" : "01-31-2021"
		},{
			"myDateField" : "01-31-2021"
		}
     ]
}

`

The Custom Spec
`[
{
   "operation" : "com.custom.transform.DateFormatModifir",
   "spec" : {
         "myDateField" : {
                "path" : "data.*.myDateField",
                "source" : "MM-dd-yyyy",
                "target"  : "yyyy-MM-dd"
         }
    }
}
]
