### ISSUE TITLE
need to replace a string using modify-overwrite-beta, REPLACE ABC string from attributes

### ISSUE THREAD

**Issue by naveenpi** [bazaarvoice/jolt#1264]
i have following input:

{
   "attributes": {
       "ABC_BCKHL": "123",
       "ABC_DHBLD": "234",
       "ABC_KKCAJ": "345",
   }
}

EXPECTED OUTPUT:
{
   "attributes": {
       "BCKHL": "123",
       "DHBLD": "234",
       "KKCAJ": "345",
   }
}

Please give the solution using modify-overwrite-beta operation

**Comment by naveenpi** [comment]
i tried something like this but did not work

[{

"operation": "modify-overwrite-beta",
"spec": {
   "attributes": {
       "*": "=substring(@(1,&),5,10)"
   }
}
}]

**Comment by LucaBiscotti** [comment]
Hi @naveenpi, the jolt you made is almost right, there are just some little improvements to do for make it work:

- You can't change the key of a dictionary, but you can make it a value (thanks to the $ wildcard) and then modify it by using the =substring()
- In the substring you have to carefully count the indexes(you missed by one)

So the correct jolt should be something like this:
```
[
  {
    "operation": "shift",
    "spec": {
      "attributes": {
        "*": {
          "$": "@0"
        }
      }
    }
},
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "*": "=substring(@0,4,9)"
    }
},
  {
    "operation": "shift",
    "spec": {
      "*": {
        "$": "attributes.@0"
      }
    }
}
]

``` 

1. exchange the key and the value
2. apply the substring to the value(the original key)
3. exchange again

Hope I helped

**Comment by naveenpi** [comment]
thank you it worked
