### ISSUE TITLE
how to read required attributes from a config file

### ISSUE THREAD

**Issue by naveenpi** [bazaarvoice/jolt#1265]
I have an input like:

{

  "attribute_set":[
      {
         "attribute": "ABC",
         "value": 1
      },
            {
         "attribute": "KFC",
         "value": 1
      },
            {
         "attribute": "OLW",
         "value": 1
      },
            {
         "attribute": "PRIOF",
         "value": 1
      }
     .. 600 more attributes like above
  ]
}

output i need something like this:
The main ask here is i want to maintain the required attributes in config.json file. My jolt should get the required attributes from the file and should give the output. is there a way to embed custom functions in jolt mapping (preferably java)?

{

  "attributes":{
       "ABC": 1,
        "KFC": 1
  }
}

Example jolt i have now:

{
  "attribute_set:" {
    "*": {
        "attribute":
           **"ABC|KFC":{** - // i want this list to come from a config file
               "@(2,value)": "attributes.&1"
           }
    }
  }
}

**Comment by LucaBiscotti** [comment]
Hi @naveenpi quick question to better understand the problem:
Where do you put the required attributes you say you need(like ABC and KFC in your example)?
Are they in the same json file of the input? Are they in the attributes of the file(if you are using nifi)? Or are they manually chosen?
Without this info it's hard to understand how to proceed.
Meanwhile I can suggest you this jolt:
```
[
  {
    "operation": "shift",
    "spec": {
      "attribute_set": {
        "*": {
          "@(0,value)": "attributes.@(0,attribute)"
        }
      }
    }
  }
]

```
What it does is basically to get every attribute and mapping it with its associated value.
If you can let me know how do you intend to pass the required attributes to the process, we can then find the complete solution to this problem

**Comment by dgsarve** [comment]
jkijhihfd

**Comment by dgsarve** [comment]
you can set some default value to mandatory attributes 
{
    "operation": "default",
    "spec": {
      "attribute": "value"
    }
  },
{
    "operation": "modify-overwrite-beta",
    "spec": {
      "attribute": "=concat(@(1,attribute), '')"
    }
  }  also try this new hobby site to generate specs with AI 
[https://powerjolt.azurewebsites.net/](url)

**Comment by thinkcloudmasters** [comment]
[
  {
    "operation": "default",
    "spec": {
      "attributes": "value"
    }
  },
  {
    "operation": "shift",
    "spec": {
      "attributes": "attributes"
    }
  },
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "attributes": "=concat(@(1,attributes), '')"
    }
  }
]

you can also try this jolt AI spec generation site https://powerjolt.azurewebsites.net

**Comment by naveenpi** [comment]
thank you @LucaBiscotti , @thinkcloudmasters
