### ISSUE TITLE
Create multiple output fields form one input field ?

### ISSUE THREAD

**Issue by mpopova-yottaa** [bazaarvoice/jolt#127]
Hi, 

is it possible to generate more than one output field from one source field?

For example, this is what I would like to do:

    	"operation": "shift",
	"spec": {
		"requestURL": "request_url",
		 // "requestURL": "short_request_url", <-- can't do this since it is the same field name in JSON
    }

is there some way to specify something like this:

		"requestURL": "request_url, short_request_url" 

and have the output:

    request_url: "some long url",
    short_request_url: "short version"

?

I guess I could use the same approach as with custom date conversion - and just insert a new field into the resulting Map - but I wonder if there is an "out-of-the-box" way to do that.

thanks!

**Comment by milosimpson** [comment]
Yes, with "shift" you can copy a single input value into multiple output values.  
See https://github.com/bazaarvoice/jolt/blob/master/jolt-core/src/test/resources/json/shiftr/multiPlacement.json

Basically just use an Array, like so :
```
 "spec": {
        "foo": ["a", "b"]   // write whatever value exists at "foo" and writes them to "a" and "b" in the output docuement
    },
```

**Comment by mpopova-yottaa** [comment]
thanks - worked great!

**Comment by LAVA-KUMAR** [comment]
> Yes, with "shift" you can copy a single input value into multiple output values.
> See https://github.com/bazaarvoice/jolt/blob/master/jolt-core/src/test/resources/json/shiftr/multiPlacement.json
> 
> Basically just use an Array, like so :
> 
> ```
>  "spec": {
>         "foo": ["a", "b"]   // write whatever value exists at "foo" and writes them to "a" and "b" in the output docuement
>     },
> ```

**Comment by LAVA-KUMAR** [comment]
@milosimpson  can we assign two different values of keys to one single key as exactly opposition of above solution. For suppose let say input json having two fields called "a":1," b":1  now i want output json with field let say "c" having two values of fields a,b. like: "c":[1,2].Thanks.
