### ISSUE TITLE
Preserving fields order from the spec in the output document

### ISSUE THREAD

**Issue by mpopova-yottaa** [bazaarvoice/jolt#128]
The default behavior of the transformer seems to be to sort all fields alphabetically in the output JSON, based on the fields name.

I would like to preserve the order in which they are described in the JOLT spec.

Is it possible?
thanks!

**Comment by milosimpson** [comment]
No.   In JSON, maps are specified to be unordered, so you really shouldn't rely on them being a particular order.

http://json.org/   -> "An object is an unordered set of name/value pairs. An object begins with {  and ends with }."

The Demo Site tool, http://jolt-demo.appspot.com/ does to a "sort" of the transform output for human readability.   So maybe that is what you are reffering to?   Regardless, I should mention that on the site.

Jolt internally uses LinkedHashMaps, which means that for any given input and spec, it tends to generate the same output ordering.   But that is just an implementation detail, and again should not be relied on.

**Comment by mpopova-yottaa** [comment]
Thanks, Milo!

Yes, I was using the Jolt Transform Demo tool to verify/test my transforms - and assumed that the order displayed there is the final generated JSON's order as well.

One other point that led me to believe there is some custom/default sorting was by seeing the reference in the documentation to the 'sort' operation/DSL - so I assumed that it is for custom sorting of the output... 

thanks!

**Comment by lafiza** [comment]
If the jolt uses the LinkedHashMap internally., why is the order of the field of type array is not maintained in the Spec

**Comment by milosimpson** [comment]
"it tends to generate the same output ordering. But that is just an implementation detail, and again should not be relied on."

Depending on the spec and the combination of wildcard and literal fields to match on, shift can process the data in 4 different "ways" as the system tries to be as "intellijent / efficient" as possible, thus the exact order that comes out of shift can change.
