### ISSUE TITLE
Not able to shift values

### ISSUE THREAD

**Issue by manankapoor88** [bazaarvoice/jolt#129]
Hi,

I am new to jolt. I want to change value and key but want to keep structure similar.
```
{
	"SecondaryRatings": {
		"Design": 4,
		"Price": 2,
		"RatingDimension3": [
			"asdfsadf",
			"erere"
		]
	}
}
```
to 
```
{
	"SecondaryRatings": {
		"Design": 5,
		"Price": 2,
		"new_key": [
			"asdfsadf",
			"erere"
		]
	}
}
```

Please help me out.
Thanks

**Comment by milosimpson** [comment]
At the demo site, http://jolt-demo.appspot.com/ this spec will do what you want.
```
[
	{
		"operation": "shift",
		"spec": {
			"SecondaryRatings": {
				"Design": "SecondaryRatings.Design",
				"Price": "SecondaryRatings.Price",
				"RatingDimension3": "SecondaryRatings.new_key"
			}
		}
	}
]
```

The Shift operation is less about "tweaking" one thing, and more about "for each piece of input data, where does it go in the output".

So you can make the Shift operation, "tweak" something by placing input data into the output, that just happens to match the input format.

Note the solution above is not very generic.   Using wildcards, we can reduce the boiler plate.
```
[
	{
		"operation": "shift",
		"spec": {
			"SecondaryRatings": {
				"*": "&1.&0",
				"RatingDimension3": "&1.new_key"
			}
		}
	}
]
```

**Comment by manankapoor88** [comment]
Thanks a lot for help. now, it is working fine at my end.

Also, I am stuck in one another issue.

I am using array. In that there are two elements both having id attribute. I want to change the id of only first element. I have seen your example "List- to - map" but i am not able to do that.

input:
{
	"Photos": [
		{
			"Id": "327703",
			"Caption": "TEST>> photo 1",
			"Url": "http://bob.com/0001/327703/photo.jpg"
		},
		{
			"Id": "327704",
			"Caption": "TEST>> photo 2",
			"Url": "http://bob.com/0001/327704/photo.jpg"
		}
	]
}


output:

{
  "Photo" : [ {
    "id" : "327703"
  }, {
    "Id" : "327704"
  } ]
}


spec:

[
	{
		"operation": "shift",
		"spec": {
			"Photos": {
				"*": {
					"Id": "Photo[&1].id"
				}
			}
		}
	}
]

**Comment by milosimpson** [comment]
"I want to change the id of only first element."
The following spec will just grab the first element of the Photos array.
Note that Jolt, does not really help with "changing" data, it is is meant for manipulating the structure of Json data.

```
[
	{
		"operation": "shift",
		"spec": {
			"Photos": {
				"0": {
					"Id": "Photo[&1].id"
				}
			}
		}
	}
]
```

**Comment by chaimoumaCJ** [comment]
Hello , how are you !
I need some help please !
I have a complex Json File to flatt it : i wonna shift all the objects to become in the same level !
can anyone help me 
[file.txt](https://github.com/bazaarvoice/jolt/files/1747172/file.txt)
@milosimpson
