### ISSUE TITLE
Is there a way to remove any strings which may be null or whose value is ""?

### ISSUE THREAD

**Issue by dan-s1** [bazaarvoice/jolt#130]
I am new to JOLT but what I am finding annoying is when I write shift spec if the values on LHS are null/"" they get copied over. 
How can I either ignore them or remove them first and then do my shift spec?

**Comment by milosimpson** [comment]
You are the second person to have run into this problem, namely the "shift" operation really doesn't handle RHS nulls well.

The workaround is to three operations
# do a "default" operation, to fill in all "null" values to be an empty string
# in your "shift" match on the empty string and send it to the "trash"
# lastly do a "remove" to remove the "trash"

Example, I have 3 ratings, one legit, one null, one an empty string.
Input
```
{
	"rating": {
		"primary": {
			"value": 3
		},
		"quality": {
			"value": ""
		},
		"sharpness": {
			"value": 5
		}
	}
}
```

Desired Output : Drop the null and empty string ratings.
```
{
  "Ratings" : {
    "sharpness" : {
      "Value" : "5"
    }
  }
}
```

This Spec does that.   To see really see what it is doing, incrementally remove the last transform step, and run it in the demo.
```
[
	{
		"operation": "default",
		"spec": {
			"rating": {
				"*": {
					"value": ""
				}
			}
		}
	},
	{
		"operation": "shift",
		"spec": {
			"rating": {
				"*": {
					"value": {
						"": "TRASH",
						"*": {
							"$": "Ratings.&3.Value"
						}
					}
				}
			}
		}
	},
	{
		"operation": "remove",
		"spec": {
			"TRASH": ""
		}
	}
]
```

**Comment by dan-s1** [comment]
Thanks for the detailed example. I noticed though the example assumes you know which values are empty strings and or null (e.g. rating.primary.value and rating.quality.value) How can I remove items which are empty string or null without knowing their specific paths? The specific use case I have is where I have vendors sending JSON which sometimes will have fields populated with values and other times will have fields either set to null or empty string. I do not know ahead of time whether these fields will be populated with values or null or empty string. Please advise.

**Comment by milosimpson** [comment]
"How can I remove items which are empty string or null without knowing their specific paths?"
 - Given the current tools, it is not possible.   Your best bet would be to write some code that recursively walks the JSON hunting down all the nulls.

"The specific use case I have is where I have vendors sending JSON which sometimes will have fields populated with values and other times will have fields either set to null or empty string."
 - If you know the general "format" of the vendor's JSON, you should be able to build a "default" spec that fills in the things you need.

**Comment by milosimpson** [comment]
Fixed with 
- https://github.com/bazaarvoice/jolt/pull/176 and
- https://github.com/bazaarvoice/jolt/pull/178

**Comment by christophediprima** [comment]
Is this still valid? I cannot make it work!
