### ISSUE TITLE
Not able to use multiple spec's on the basis of conditional statements

### ISSUE THREAD

**Issue by dhruvsinha8** [bazaarvoice/jolt#135]
Hi,

I am new to Jolt. I need to use multiple specs (like shift, remove) on the basis of conditional statements.

For example:

Input:

```
{
    "data": {
        "1234": {
            "clientId": "12",
            "hidden": true
        },
        "1235": {
            "clientId": "35",
            "hidden": false
        }
    }
}
```

Now, on the basis of some conditions, I need to perform remove or shift specs.
eg.

spec:

```
[
    {
        "operation": "shift",
        "spec": {
            "data": {
                "*": {
                    "hidden": {
                        "true": {
                             // Use remove spec here
                        },
                        "false": {
                             // Use shift spec here
                        }
                    }
                }
            }
        }
    }
]
```

I am not able to implement the above task. Can you please let me help me how to do it. Also, if this is not the correct way to do it, then what should I do to make it work on the basis of the specified conditions. 
Kindly provide some solution for the same.

**Comment by milosimpson** [comment]
I think the following spec does what you want:
```
[
	{
		"operation": "shift",
		"spec": {
			"data": {
				"*": {
					"hidden": {
						"false": {
							"@2": "data.&3"
						}
					}
				}
			}
		}
	}
]
```

So the "shift" operation is not adding or removing anything from the provided input.   What it is doing is "walking thru" the input and _copying_ data into an output Json document.  

Thus, in your case here, if you only match the stuff that is "hidden" : false, then that is the only content that gets copied across.

**Comment by dhruvsinha8** [comment]
Thanks for your response. 
I have few concerns and queries.

In the above example, suppose I need different outcomes for different conditions and using a single spec, like:

Input:

{
	"data": {
		"Status": "Success",	// The value of Status may change to Failure as well.
		"1234": {
			"clientId": "12",
			"hidden": true
		},
		"1235": {
			"clientId": "35",
			"hidden": false
		},
		"1236": {
			"clientId": "24",
			"hidden": "none"
		}
	}
}


Condition 1: If the value of "Status" is Success, then I am expecting the below output:

Expected Output:
{
	"Result": [
		{
			"Status": "Success",
			"1234": {
				"clientId": "12"
			}
		}
	]
}

Here, I am expecting a json array with Success and some other info like clientId of 1234.


Condition 2: If the value of "Status" is Failure, then I am expecting the below output:

Expected Output:
{
  "data" : {
    "1234" : {
      "clientId" : "12"		// not to show "hidden" attribute
    }
  }
}

Here, I want to remove the hidden field for this particular condition.


Condition 3: If the value of "hidden" is false, then I am expecting the below output:

Expected Output:
{
	"Array1": [
		{
			"clientId": "35"
		},
		{
			"clientId": "12",
			"hidden": true
		}
	]
}

Here, I want a json array with both true and false values of "hidden", and the value of hidden for false is removed.


Condition 4:

If the value of "hidden" is none, then I am expecting the below output:

Expected Output:
{
  "data" : {
    "1236": [{				// Json Array
		"clientId": "24",
		"hidden": "none"
	},
	{
		"1234": {
			"clientId": "12",
			"hidden": true
		}
	}
	]
  }
}
Here, I want a json array with both true and none values of "hidden", and the key 1234 is also needed here.

I need to implement the above kind of structure using a single spec. Means all the conditions and what needs to be done on what condition is required in a single spec, and only the input varies accordingly. The main focus I have is on Condition 1 above.
So, I was asking that is there a way of using shift and remove in a single spec (like nested, etc), or there is any other solution for the above conditional problem I am having.
Kindly assist.

**Comment by milosimpson** [comment]
The 4 conditions you state don't make sense to me.

What I would expect is something like
```
if ( Status == "Success" ) {
  if ( hidden == "true" ) {
     // show it 
  }
  //etc
}
else if ( Status == "Failed" ) {
  // logic for the Failed case
}
```

"single spec".   It can be a single Jolt spec, which contains a few "operations", yes?

Most likely, it will be [ shift, shift ] or [ shift, shift, remove ]. 
First shift will be an intermediate step based on the "Status", then the 2nd shift will handle the "hidden" fields.

**Comment by dhruvsinha8** [comment]
I am not able to understand how to use multiple operations in a spec.
Let me show you what exactly I am looking for:

Input:
// Status can be changed to "Success/Failure/Unreached"

{
	"Parent": {
		"TimeStamp": "8/27/2015 11:57AM GMT-04:00",
		"version": "1.0",
		"WVersion": "8.0.0.49",
		"Response": {
			"Status": "Success",		
			"PersonNumber": "203",
			"Action": "RetrieveByPersonNumber",
			"AuthorityTask": {
				"StartDate": "8/26/2015",
				"RoleName": "TestRoleProfile",
				"TaskId": "152",
				"TaskString": "Brian: 8/26/2015 - 8/28/2015, TestRoleProfile",
				"RoleProfileId": "151",
				"ProxyMgrName": "Brian",
				"ProxyMgrId": "225",
				"ProxyMgrNumber": "225",
				"EndDate": "8/28/2015",
				"MgrName": "Fryman",
				"MgrId": "203"
			}
		}
	}
}

Now I am expecting the below output:

if(Status == Success),
then the response json should be:

[
	{
		"Authority": [
			{
				"StartDate": "8/26/2015",
				"RoleName": "TestRoleProfile",
				"TaskId": "152",
				"TaskString": "Brian: 8/26/2015 - 8/28/2015, TestRoleProfile",
				"RoleProfileId": "151",
				"ProxyMgrName": "Brian",
				"ProxyMgrId": "225",
				"ProxyMgrNumber": "225",
				"EndDate": "8/28/2015",
				"MgrName": "Fryman",
				"MgrId": "203"
			}
		]
	},
	{
		"Existing": [
			{
				"Name": "TestRoleProfile",
				"Id": "152"
			}
		]
	},
	{
		"Status": "Success"
	}
]

Now,
if(Status == Failure),
then the response json should be:

{
	"ResponseFailed": [
		{
			"Authority": [
				{
					"StartDate": "8/26/2015",
					"RoleName": "TestRoleProfile",
					"TaskId": "152",
					"TaskString": "Brian: 8/26/2015 - 8/28/2015, TestRoleProfile",
					"RoleProfileId": "151",
					"ProxyMgrName": "Brian"
				}
			]
		},
		{
			"Selected": [
				{
					"MgrName": "Brian",
					"MgrId": "225"
				}
			]
		},
		{
			"Status": "Failure"
		}
	]
}

Can you please provide a sample spec for the above json that can give me the output I am expecting here.

**Comment by milosimpson** [comment]
Spec:
```
[
	{
		"operation": "shift",
		"spec": {
			"Parent": {
				"Response": {
					"Status": {
						"*": {
							"@(2,AuthorityTask)": "&"
						}
					}
				}
			}
		}
	},
	{
		"operation": "shift",
		"spec": {
			"Failure": {
				"$": "ResponseFailed[0].Status",
				"StartDate": "ResponseFailed[0].Authority[0].StartDate",
				"RoleName": "ResponseFailed[0].Authority[0].RoleName",
				"TaskId": "ResponseFailed[0].Authority[0].TaskId",
				"TaskString": "ResponseFailed[0].Authority[0].TaskString",
				"RoleProfileId": "ResponseFailed[0].Authority[0].RoleProfileId",
				"ProxyMgrName": "ResponseFailed[0].Authority[0].ProxyMgrName",
				"MgrName": "ResponseFailed[0].Selected[0].MgrName",
				"MgrId": "ResponseFailed[0].Selected[0].MgrId"
			},
			"Success": {
				"$": "Status",
				"StartDate": "Authority[0].StartDate",
				"TaskString": "Authority[0].TaskString",
				"RoleProfileId": "Authority[0].RoleProfileId",
				"ProxyMgrName": "Authority[0].ProxyMgrName",
				"ProxyMgrId": "Authority[0].ProxyMgrId",
				"ProxyMgrNumber": "Authority[0].ProxyMgrNumber",
				"MgrName": "Authority[0].MgrName",
				"MgrId": "Authority[0].MgrId",
				"EndDate": "Authority[0].EndDate",
				"RoleName": [
					"Authority[0].RoleName",
					"Existing[0].Name"
				],
				"TaskId": [
					"Authority[0].TaskId",
					"Existing[0].Id"
				]
			}
		}
	}
]
```

Notice that the spec is an Array with two `"operation": "shift"`.
The first shift, "pivots" the data based upon the "Status".
The second shift, then can match specific output rules against the Status.

**Comment by qwelyt** [comment]
I have a conditional dilemma as well.
I only want a spec to do it's operation if a specified value is present.
Given input like the following:
```json
{
	"class": "my.cass",
	"version": 1,
	"employment": {
		"version": 3,
		"closed": false,
		"from": "2015-08-17",
		"timeBoxId": {
			"id": "8b51957d-a348-4302-a079-ddc4a3623a34"
		},
		"to": null,
		"toBeRemoved": false,
		"value": {
			"extent": "100",
			"form": "PERMANENT_EMPLOYMENT",
			"resource": false
		}
	}
}
```
I want to check what `"version":` has for value (in this case the top-version, the one that equals 1 in this case), and if that value does not match the one specified (say that we are looking for `"version":2` but we get a json where `"version":3`) we just pass the data right through with a `"*" : "&"`.
If it does match (we look for `2` and find `2`), I want to make some transformations on it.
How would this be best implemented?
And can it be done for all operations (shift, remove, default) ?

**Comment by shan1982** [comment]
Hi.. it's really nice tool and reduce lots and lots of code. I am looking for the same sort of one as above but slightly different. I have to change the structure of the output json based on a property which is part of the same object. Example 

{
    "Parent": {
        "TimeStamp": "8/27/2015 11:57AM GMT-04:00",
        "version": "1.0",
        "WVersion": "8.0.0.49",
        "Response": {
            "PersonNumber": "203",
            "Action": "RetrieveByPersonNumber",
            "AuthorityTask": {
             "Status": "Success",        
                "StartDate": "8/26/2015",
                "RoleName": "TestRoleProfile",
                "TaskId": "152",
                "TaskString": "Brian: 8/26/2015 - 8/28/2015, TestRoleProfile",
                "RoleProfileId": "151",
                "ProxyMgrName": "Brian",
                "ProxyMgrId": "225",
                "ProxyMgrNumber": "225",
                "EndDate": "8/28/2015",
                "MgrName": "Fryman",
                "MgrId": "203"
            }
        }
    }
}

here the "status is inside  "AuthorityTask", but the output is as above..

**Comment by shan1982** [comment]
Hi.. it's really nice tool and reduce lots and lots of code. I am looking for the same sort of one as above but slightly different as follows  

Input 

{
	"quote": {
		"car" : {
			"regNumber" : "A1",
			"make" : "Honda",
			"model" : "civic"
		}
		"driver": [
			{
				"firstName": "David",
				"familyName": "Shan",
				"convictions": true,
				"isPolicyHolder": true
			},
			{
				"firstName": "Paul",
				"familyName": "Rik",
				"convictions": true,
				"isPolicyHolder": false
			},
			{
				"firstName": "Mark",
				"familyName": "Dani",
				"convictions": true,
				"isPolicyHolder": false
			}
		]
	}
}

and the expected output..

{
	"insurance" : {
		"car" : {
			"regNumber" : "A1",
			"make" : "Honda",
			"model" : "civic"
		}
		"policyHolder" : {
			"firstName": "David",
			"familyName": "Shan",
			"convictions": true,
		}
		"additionalDrivers" : [
			 {
				"firstName": "Paul",
				"familyName": "Rik",
				"convictions": true
			},
			{
				"firstName": "Mark",
				"familyName": "Dani",
				"convictions": true
			}
		
		]
	}
}

here based on the "isPolicyHolder", we have to move either part of policyholder or additionalDrivers (Array List).

**Comment by milosimpson** [comment]
This Spec does what you want.
```
[
	{
		"operation": "shift",
		"spec": {
			"quote": {
				"car": "car",
				"driver": {
					"*": {
						"isPolicyHolder": {
							"true": {
								"@(2)": "policyHolder"
							},
							"false": {
								"@(2)": "additionalDrivers[]"
							}
						}
					}
				}
			}
		}
	},
	{
		"operation": "shift",
		"spec": {
			"car": "insurance.car",
			"policyHolder": {
				"firstName": "insurance.policyHolder.name",
				"familyName": "insurance.policyHolder.surname",
				"convictions": "insurance.policyHolder.hasNonMotoringConvictions"
			},
			"additionalDrivers": {
				"*": {
					"firstName": "insurance.additionalDrivers[&1].name",
					"familyName": "insurance.additionalDrivers[&1].surname",
					"convictions": "insurance.additionalDrivers[&1].hasNonMotoringConvictions"
				}
			}
		}
	}
]
```

Couple of notes.
1. The "car" wasn't showing up because it wasn't getting pass thru the first Shift.   Hence, the "car": "car" line.
2. This is assuming that "isPolicyHolder" will only ever be "true" once, and that it could be "false" zero, one, or n times.
   Thus, the "false" case we write data to "additionalDrivers[]" to that the additionalDrivers field will always be an array.

**Comment by shan1982** [comment]
Thank you so much for the info, works well. One more query. Actually from the car, i have to properties from two different nodes into one (vehicle)  example.. 
'''
{
	"quote": {
		"car" : {
			"regNumber" : "A1",
			"make" : "Honda",
			"model" : "civic"
		},
		"coverDetail": {
			"CoverLevel": 1,
			"noClaimsDiscount": 0,
			"protectNCD": true,
			"startDate": "2013-02-02",
			"expectedMileage": 2000,
			"businessMileage": 1000
		}
		"driver": [
			{
				"firstName": "nagarajan1",
				"familyName": "shan",
				"convictions": true,
				"isPolicyHolder": true
			},
			{
				"firstName": "nagarajan2",
				"familyName": "shan",
				"convictions": true,
				"isPolicyHolder": false
			},
			{
				"firstName": "nagarajan3",
				"familyName": "shan",
				"convictions": true,
				"isPolicyHolder": false
			}
		]
	}
}

output....

{
	"insurance" : {
		"vehicle" : {
			"regNumber" : "A1",
			"make" : "Honda",
			"model" : "civic",
			"expectedMileage": 2000,
			"businessMileage": 1000
		},
		"coverDetail": {
			"CoverLevel": 1,
			"noClaimsDiscount": 0,
			"protectNCD": true,
			"startDate": "2013-02-02"
		},
		"policyHolder" : {
			"firstName": "nagarajan1",
			"familyName": "shan",
			"convictions": true,
		}
		"additionalDrivers" : [
			 {
				"firstName": "nagarajan2",
				"familyName": "shan",
				"convictions": true
			},
			{
				"firstName": "nagarajan3",
				"familyName": "shan",
				"convictions": true
			}
		
		]
	}
}

'''

**Comment by milosimpson** [comment]
Spec :
```
[
	{
		"operation": "shift",
		"spec": {
			"quote": {
				"car": {
					"*": "vehicle.&",
					"purchaseDate": {
						"*-*-*": {
							"$(0,1)": "vehicle.purchaseYear",
							"$(0,2)": "vehicle.purchaseMonth"
						}
					}
				},
				"coverDetail": {
					"CoverLevel|protectNCD|startDate": "coverDetail.&",
					"noClaimsDiscount": "policyHolder.noClaimsDiscount",
					"expectedMileage": "vehicle.expectedMileage",
					"businessMileage": "vehicle.businessMileage"
				},
				"driver": {
					"*": {
						"isPolicyHolder": {
							"true": {
								"@(2,firstName)": "policyHolder.name",
								"@(2,familyName)": "policyHolder.surname",
								"@(2,convictions)": "policyHolder.hasNonMotoringConvictions"
							},
							"false": {
								"@(2)": "additionalDrivers[]"
							}
						}
					}
				}
			}
		}
	},
	{
		"operation": "shift",
		"spec": {
			"vehicle|coverDetail|policyHolder": "insurance.&",
			"additionalDrivers": {
				"*": {
					"firstName": "insurance.additionalDrivers[&1].name",
					"familyName": "insurance.additionalDrivers[&1].surname",
					"convictions": "insurance.additionalDrivers[&1].hasNonMotoringConvictions"
				}
			}
		}
	}
]
```
The core problem was that you are trying to "merge" data from two sources.  When you do that, it has to be done "property by property".

The convenience "trick" in the first spec of passing the entire Map of the "car" and the "policyHolder" thru the first shift not longer works.

FYI,
```
"vehicle|coverDetail|policyHolder": "insurance.&"  

is the exact same thing as

"vehicle": "insurance.&",
"coverDetail": "insurance.&",
"policyHolder": "insurance.&",

the "|" on the left hand side of the spec is just a convenience thing.
```

**Comment by shan1982** [comment]
It's nice and great work, thank you so much. Actually i have list of clims as part of driving. Since the conditional logic has been moved into the first 'shift', logic for iterate over the clims are not working..

early i had as .....
```
[
    {
        "operation": "shift",
        "spec": {
            "quote": {
                "car": "car",
                "driver": {
                    "*": {
                        "isPolicyHolder": {
                            "true": {
                                "@(2)": "policyHolder"
                            },
                            "false": {
                                "@(2)": "additionalDrivers[]"
                            }
                        }
                    }
                }
            }
        }
    },
    {
        "operation": "shift",
        "spec": {
            "car": "insurance.car",
            "policyHolder": {
                "firstName": "insurance.policyHolder.name",
                "familyName": "insurance.policyHolder.surname",
                "convictions": "insurance.policyHolder.hasNonMotoringConvictions",
				"claims": {
					"*": {
						"claimType": "policyHolder.claims[&1].claimTypeId",
						"incidentDate": "policyHolder.claims[&1].dateOfClaim",
						"affectedNCD": "policyHolder.claims[&1].noClaimsAffected"
					}
				}
            },
            "additionalDrivers": {
                "*": {
                    "firstName": "insurance.additionalDrivers[&1].name",
                    "familyName": "insurance.additionalDrivers[&1].surname",
                    "convictions": "insurance.additionalDrivers[&1].hasNonMotoringConvictions"
                }
            }
        }
    }
]

but with the new spec, it's not working...

[
    {
        "operation": "shift",
        "spec": {
            "quote": {
                "car": {
                    "*": "vehicle.&",
                    "purchaseDate": {
                        "*-*-*": {
                            "$(0,1)": "vehicle.purchaseYear",
                            "$(0,2)": "vehicle.purchaseMonth"
                        }
                    }
                },
                "coverDetail": {
                    "CoverLevel|protectNCD|startDate": "coverDetail.&",
                    "noClaimsDiscount": "policyHolder.noClaimsDiscount",
                    "expectedMileage": "vehicle.expectedMileage",
                    "businessMileage": "vehicle.businessMileage"
                },
                "driver": {
                    "*": {
                        "isPolicyHolder": {
                            "true": {
                                "@(2,firstName)": "policyHolder.name",
                                "@(2,familyName)": "policyHolder.surname",
                                "@(2,convictions)": "policyHolder.hasNonMotoringConvictions"
								"@(2,claims)": {
									"*": {
										"@(2,claimType)": "policyHolder.claims[&1].claimTypeId",
										"@(2,incidentDate)": "policyHolder.claims[&1].dateOfClaim",
										"@(2,affectedNCD)": "policyHolder.claims[&1].noClaimsAffected"
									}
								}
                            },
                            "false": {
                                "@(2)": "additionalDrivers[]"
                            }
                        }
                    }
                }
            }
        }
    },
    {
        "operation": "shift",
        "spec": {
            "vehicle|coverDetail|policyHolder": "insurance.&",
            "additionalDrivers": {
                "*": {
                    "firstName": "insurance.additionalDrivers[&1].name",
                    "familyName": "insurance.additionalDrivers[&1].surname",
                    "convictions": "insurance.additionalDrivers[&1].hasNonMotoringConvictions"
                }
            }
        }
    }
]
```

**Comment by milosimpson** [comment]
With respect to the the integer vs String aspects of the PostCode, you will need to handle that.  
Thus pass the postcode thru both shifts, and then after Jolt does it's thing you write Java code to navigate the JSON object / tree and fix the postCode.

With respect to the claims array.
1. Is it only on the policyHolder, or can it be on the additionalDrivers a well?
2. What happens if there are no claims or only one claim?   Aka is it always in the input and is it always an Array?
3.  Post an example input.

**Comment by shan1982** [comment]
claims are optional and in both the places (policyHolder, additionalDrivers), but for additionalDrivers it's working fine, only the problem is with policyHolder. 

```
{
	"quote": {
		"car": {
			"regNumber": "A1",
			"make": "Honda",
			"model": "civic",
			"purchaseDate": "2012-02-02",
			"postcode": "13 3NP"
		},
		"coverDetail": {
			"CoverLevel": 1,
			"noClaimsDiscount": 0,
			"protectNCD": true,
			"startDate": "2013-02-02",
			"expectedMileage": 2000,
			"businessMileage": 1000
		},
		"driver": [
			{
				"firstName": "David",
				"familyName": "Shan",
				"convictions": true,
				"isPolicyHolder": true,
				"claims": [
					{
						"claimType": 2,
						"incidentDate": "2012-02-02",
						"affectedNCD": true
					}
				]
			},
			{
				"firstName": "Paul",
				"familyName": "Rik",
				"convictions": true,
				"isPolicyHolder": false,
				"claims": [
					{
						"claimType": 2,
						"incidentDate": "2012-02-02",
						"affectedNCD": true
					}
				]
			},
			{
				"firstName": "Mark",
				"familyName": "Dani",
				"convictions": true,
				"isPolicyHolder": false
			}
		]
	}
}


[
    {
        "operation":"shift",
        "spec":{
            "quote":{
                "car":{
                    "*":"vehicle.&",
                    "purchaseDate":{
                        "*-*-*":{
                            "$(0,1)":"vehicle.purchaseYear",
                            "$(0,2)":"vehicle.purchaseMonth"
                        }
                    },
                    "postcode":{
                        "* *":{
                            "$(0,1)":"vehicle.postcodeInCode",
                            "$(0,2)":"vehicle.postcodeOutCode"
                        }
                    }
                },
                "coverDetail":{
                    "CoverLevel|protectNCD|startDate":"coverDetail.&",
                    "noClaimsDiscount":"policyHolder.noClaimsDiscount",
                    "expectedMileage":"vehicle.expectedMileage",
                    "businessMileage":"vehicle.businessMileage"
                },
                "driver":{
                    "*":{
                        "isPolicyHolder":{
                            "true":{
                                "@(2,firstName)":"policyHolder.name",
                                "@(2,familyName)":"policyHolder.surname",
                                "@(2,convictions)":"policyHolder.hasNonMotoringConvictions",
                                "@(2,claims)":{
                                    "*":{
                                        "claimType":"policyHolder.claims[&1].claimTypeId",
                                        "incidentDate":"policyHolder.claims[&1].dateOfClaim",
                                        "affectedNCD":"policyHolder.claims[&1].noClaimsAffected"
                                    }
                                }
                            },
                            "false":{
                                "@(2)":"additionalDrivers[]"
                            }
                        }
                    }
                }
            }
        }
    },
    {
        "operation":"shift",
        "spec":{
            "vehicle|coverDetail|policyHolder":"insurance.&",
            "additionalDrivers":{
                "*":{
                    "firstName":"insurance.additionalDrivers[&1].name",
                    "familyName":"insurance.additionalDrivers[&1].surname",
                    "convictions":"insurance.additionalDrivers[&1].hasNonMotoringConvictions",
                    "claims":{
                        "*":{
                            "claimType":"insurance.additionalDrivers[&1].claims[&1].claimType",
                            "incidentDate":"insurance.additionalDrivers[&1].claims[&1].incidentDate",
                            "affectedNCD":"insurance.additionalDrivers[&1].claims[&1].affectedNCD"
                        }
                    }
                }
            }
        }
    }
]

```

**Comment by milosimpson** [comment]
Ok, the trick was to pass the policyHolder.claims[] thru the first shift, and then process it in the 2nd.

Spec
```
[
	{
		"operation": "shift",
		"spec": {
			"quote": {
				"car": {
					"*": "vehicle.&",
					"purchaseDate": {
						"*-*-*": {
							"$(0,1)": "vehicle.purchaseYear",
							"$(0,2)": "vehicle.purchaseMonth"
						}
					},
					"postcode": {
						"* *": {
							"$(0,1)": "vehicle.postcodeInCode",
							"$(0,2)": "vehicle.postcodeOutCode"
						}
					}
				},
				"coverDetail": {
					"CoverLevel|protectNCD|startDate": "coverDetail.&",
					"noClaimsDiscount": "policyHolder.noClaimsDiscount",
					"expectedMileage": "vehicle.expectedMileage",
					"businessMileage": "vehicle.businessMileage"
				},
				"driver": {
					"*": {
						"isPolicyHolder": {
							"true": {
								"@(2,firstName)": "policyHolder.name",
								"@(2,familyName)": "policyHolder.surname",
								"@(2,convictions)": "policyHolder.hasNonMotoringConvictions",
								"@(2,claims)": "policyHolder.claims"
							},
							"false": {
								"@(2)": "additionalDrivers[]"
							}
						}
					}
				}
			}
		}
	},
	{
		"operation": "shift",
		"spec": {
			"vehicle|coverDetail": "insurance.&",
			"policyHolder": {
				"*": "insurance.policyHolder.&",
				"claims": {
					"*": {
						"claimType": "insurance.policyHolder.claims[&1].claimTypeId",
						"incidentDate": "insurance.policyHolder.claims[&1].dateOfClaim",
						"affectedNCD": "insurance.policyHolder.claims[&1].noClaimsAffected"
					}
				}
			},
			"additionalDrivers": {
				"*": {
					"firstName": "insurance.additionalDrivers[&1].name",
					"familyName": "insurance.additionalDrivers[&1].surname",
					"convictions": "insurance.additionalDrivers[&1].hasNonMotoringConvictions",
					"claims": {
						"*": {
							"claimType": "insurance.additionalDrivers[&3].claims[&1].claimTypeId",
							"incidentDate": "insurance.additionalDrivers[&3].claims[&1].dateOfClaim",
							"affectedNCD": "insurance.additionalDrivers[&3].claims[&1].noClaimsAffected"
						}
					}
				}
			}
		}
	}
]
```

**Comment by milosimpson** [comment]
Interesting... your spec tried to do a thing that Jolt doesn't do but should.
```
{
	"@(2,claims)": {
		"*": {
			"claimType": "policyHolder.claims[&1].claimTypeId",
			"incidentDate": "policyHolder.claims[&1].dateOfClaim",
			"affectedNCD": "policyHolder.claims[&1].noClaimsAffected"
		}
	}
}
```

Namely, use the "@(2,claims)" element to swap the data being matched by the spec, and then continue to recurse down from that new position in the input tree.

**Comment by shan1982** [comment]
thank you so much, everything is working fine. It's really a nice tool..

**Comment by shan1982** [comment]
I am trying to do reverse engineering on the earlier mapping: 

```
{
    "insurance":{
        "policyHolder":{
            "name":"David",
            "surname":"Shan",
            "mainOccupation":{
                "occupationId":"3",
                "employmentStatus":"6"
            },
            "claims":[
                {
                    "claimTypeId":2,
                    "dateOfClaim":"2012-02-02",
                    "noClaimsAffected":true
                }
            ]
        },
        "additionalDrivers":[
            {
                "name":"Paul",
                "surname":"Rik",
                "mainOccupation":{
                    "occupationId":"3",
                    "employmentStatus":"6"
                },
                "claims":[
                    {
                        "affectedNCD":true,
                        "claimType":2,
                        "incidentDate":"2012-02-02"
                    }
                ]
            }
        ]
    }
}

i want the output to be like 

{
    "persons":[
        {
            "details":{
                "firstName":"David",
                "surname":"Shan"
            },
            "driving":{
                "claims":[
                    {
                        "claimDate":"2012-02-02",
                        "claimTypeId":2,
                        "isNoClaimsAffected":true
                    }
                ]
            },
            "mainOccupation":{
                "occupation":3,
                "employmentStatusId":"6"
            }
        },
        {
            "details":{
                "firstName":"Paul",
                "surname":"Rik"
            },
            "driving":{
                "claims":[
                    {
                        "claimDate":"2012-02-02",
                        "claimTypeId":2,
                        "isNoClaimsAffected":true
                    }
                ]
            },
            "mainOccupation":{
                "occupation":3,
                "employmentStatusId":"6"
            }
        }
    ]
}

using the spc.. (i know it's wrong..

[
    {
        "operation":"shift",
        "spec":{
            "insurance":{
                "policyHolder":{
                    "name":"persons[0].details.firstName",
                    "surname":"persons[0].details.surname",
                    "mainOccupation":{
                        "occupation":"persons[0].mainOccupation.occupationId",
                        "employmentStatus":"persons[0].mainOccupation.employmentStatusId"
                    },
                    "claims":{
                        "*":{
                            "claimTypeId":"persons[0].driving.claims[&1].claimTypeId",
                            "dateOfClaim":"persons[0].driving.claims[&1].claimDate",
                            "noClaimsAffected":"persons[0].driving.claims[&1].isNoClaimsAffected"
                        }
                    }
                },
                "additionalDrivers":{
                    "*":{
                        "name":"persons[&1].details.firstName",
                        "surname":"persons[&1].details.surname",
                        "mainOccupation":{
                            "occupation":"persons[&1].mainOccupation.occupationId",
                            "employmentStatus":"persons[&1].mainOccupation.employmentStatusId"
                        },
                        "claims":{
                            "*":{
                                "claimTypeId":"persons[&1].driving.claims[&1].claimTypeId",
                                "dateOfClaim":"persons[&1].driving.claims[&1].claimDate",
                                "noClaimsAffected":"persons[&1].driving.claims[&1].isNoClaimsAffected"
                            }
                        }
                    }
                }
            }
        }
    }
]

gettin the output as..

{
  "persons" : [ {
    "details" : {
      "firstName" : [ "David", "Paul" ],
      "surname" : [ "Shan", "Rik" ]
    },
    "driving" : {
      "claims" : [ {
        "claimDate" : "2012-02-02",
        "claimTypeId" : 2,
        "isNoClaimsAffected" : true
      } ]
    },
    "mainOccupation" : {
      "employmentStatusId" : "6"
    }
  } ]
}
```

can you please advise me on this?

**Comment by kchandrashekar** [comment]
Is there a way using  Jolt to transform a Json structure to an anonymous array.
for example

input  

{"Data" : {"Contents" : "InvoiceHeader", "InvoiceNumber" : "8874943-1", "InvoiceCurrency" : "EUR", "InvoiceTotal" : "23260.35"}}

Output Needed
{
 [{ "InvoiceNumber" : "8874943-1", "InvoiceCurrency" : "EUR", "InvoiceTotal" : "23260.35"}]
}

Tried a spec 

[
  {
    "operation": "shift",
    "spec": {
      "Data": {
        "Contents":null,
        "*": "&"
      }
    }
  }
]

but this emits

{
  "InvoiceCurrency" : "EUR",
  "InvoiceNumber" : "8874943-1",
  "InvoiceTotal" : "23260.35"
}

**Comment by milosimpson** [comment]
Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "Data": "[]"
    }
  }
]
```

**Comment by kchandrashekar** [comment]
Thank you so much , the expression works as expected.
Kannan.c
________________________________

**Comment by PadminiGowda** [comment]
[issues facing .txt](https://github.com/bazaarvoice/jolt/files/963577/issues.facing.txt)

**Comment by PadminiGowda** [comment]
jolt spec required according to input and output data sample.

*input**

{
"summary":{  
      
      "start_date":"2015-12-01T08:44:29+00:00",
      "end_date":"2015-12-03T08:54:27+00:00",
     
      "params":{  
         
         "offset":0,
         "limit":200
      }
   
    }
}


**expected output**
{
"summary":
{
{"key":"start_date",
    "value":"2015-12-01T08:44:29+00:00"
	},

{"key":"end_date",
    "value":2015-12-03T08:54:27+00:00" 
	},
	
{"key":"params",
   "value":{
   
               {"key":"offset",
                "value":"0"},

              {"key":"limit",
               "value":200},
			   
			}


}
}


** but the output we are getting **

{"summary":[
{"key":"status","value":200},
{"key":"start_date","value":"2015-12-01T08:44:29+00:00"},
{"key":"end_date","value":"2015-12-03T08:54:27+00:00"},

{"key":"params",
"value":{"offset":0,"limit":200}

]}



please help me in solving this

**Comment by msoni9** [comment]
Hi Everyone, 
I have two perform one operation in which I have to change the key name of employee i.e.
f_name to firstname & l_name to lastname.

I have two objects in elements in Employee object in first element it is f_name & l_name but in the 2nd element it is expected as I wanted. 

INPUT JSON-

{
	"Employees": [
		{
			"userId": "rirani",
			"jobTitleName": "Developer",
			"f_Name": "Romin",      // this needs to be modified with firstname
			"l_Name": "Irani",          // this needs to be modified with lastname
			"preferredFullName": "Romin Irani",
			"employeeCode": "E1",
			"region": "CA",
			"phoneNumber": "408-1234567",
			"emailAddress": "romin.k.irani@gmail.com"
		},
		{
			"userId": "nirani",
			"jobTitleName": "Developer",
			"firstName": "Neil",
			"lastName": "Irani",
			"preferredFullName": "Neil Irani",
			"employeeCode": "E2",
			"region": "CA",
			"phoneNumber": "408-1111111",
			"emailAddress": "neilrirani@gmail.com"
		}
	]
}

Expected OUTPUT :
{
	"Employees": [
		{
			"userId": "rirani",
			"jobTitleName": "Developer",
			"firstname": "Romin",
			"lastname": "Irani",
			"preferredFullName": "Romin Irani",
			"employeeCode": "E1",
			"region": "CA",
			"phoneNumber": "408-1234567",
			"emailAddress": "romin.k.irani@gmail.com"
		},
		{
			"userId": "nirani",
			"jobTitleName": "Developer",
			"firstName": "Neil",
			"lastName": "Irani",
			"preferredFullName": "Neil Irani",
			"employeeCode": "E2",
			"region": "CA",
			"phoneNumber": "408-1111111",
			"emailAddress": "neilrirani@gmail.com"
		}
	]
}

Spec JSON 👍 
[
	{
		"operation": "shift",
		"spec": {
			"employees": {
				"*": {
					"userId": "rirani",
					"jobTitleName": "Developer",
					"f_Name": "employees[&1].firstName",
					"l_Name": "employees[&1].lastName",
					"preferredFullName": "Romin Irani",
					"employeeCode": "E1",
					"region": "CA",
					"phoneNumber": "408-1234567",
					"emailAddress": "romin.k.irani@gmail.com"
				},
				{
					"userId": "nirani",
					"jobTitleName": "Developer",
					"firstName": "Neil",
					"lastName": "Irani",
					"preferredFullName": "Neil Irani",
					"employeeCode": "E2",
					"region": "CA",
					"phoneNumber": "408-1111111",
					"emailAddress": "neilrirani@gmail.com"
				}
			}
		}
	]

Further leads would be appreciated.
