### ISSUE TITLE
Shift key and value based on condition 

### ISSUE THREAD

**Issue by bhupendrabjain** [bazaarvoice/jolt#136]
Given the following input 
```
{
  "$schema": "http://test.com/what/is/the/path#",
  "op": "update",
  "type": "episode",
  "vmid": "a5906c52-be25-4a43-9539-15755ffdf54d",
  "ref_lang": "en-latn-US",
  "titles": [
    {
      "title_type": "Default Title",
      "title_value": "Harvey Beaks #201",
      "lang": "en-latn-US"
    },
    {
      "title_type": "Long Title",
      "title_value": "Harvey Beaks #201 blah blah blah",
      "lang": "en-latn-US"
    }
  ]
}
```
I want the following output 
```
{
  "contentType": "episode",
  "pk_id": "a5906c52-be25-4a43-9539-15755ffdf54d",
  "vmid": "a5906c52-be25-4a43-9539-15755ffdf54d",
  "language": "en-latn-US",
  "title": "Harvey Beaks #201",
  "longTitle": "Harvey Beaks #201 blah blah blah"
}
```
I am not able to find a way to get the title and long title ?  If the "title_type": "Default Title" then add the value of "title_value" to the key title and if the  "title_type": "Long Title" then add the value of "title_value" to the key longTitle

Can someone please help me with this ?

**Comment by milosimpson** [comment]
I think this does what you want.

```
[
	{
		"operation": "shift",
		"spec": {
			"titles": {
				"*": {
					"title_type": {
						"Default Title": {
							"@(2,title_value)": "title"
						},
						"Long Title": {
							"@(2,title_value)": "titleLong"
						}
					}
				}
			}
		}
	}
]
```

Produces output : 
```
{
  "title" : "Harvey Beaks #201",
  "titleLong" : "Harvey Beaks #201 blah blah blah"
}
```

**Comment by bhupendrabjain** [comment]
This is exactly what I needed .. Thanks a lot .. Just one more question what does number 2 means in the above specs ? Does it mean the second element in the array ?

**Comment by milosimpson** [comment]
Q: Does it mean the second element in the array?  
A: No.   The Shift is logic is essentially a recursive parallel tree walk of the input data and the spec.   As recursive calls are made, and we "walk down" the tree, it stores references to the path it has walked.
Thus  "@(2,title_value)" means, "go up 3 levels in the path we have walked (0, 1, 2), then look for a key named "title_value".    Grab the 'value' at the 'key' "title_value", and put it in the output.

**Comment by bhupendrabjain** [comment]
So does that mean if the input was 
  {
      "title_type": "Default Title",
      "lang": "en-latn-US",
     "title_value": "Harvey Beaks #201"
    }

i.e if the position of title_value is changed , we have to do @(3,title_value) ? Is that right ? If I dont know the position of title_value then what to do ?

**Comment by bhupendrabjain** [comment]
If my input is "titles": [
    {
      "title_type": "Default Title",
      "title_value": "Harvey Beaks #201",
      "lang": "en-latn-US"
    },
    {
      "title_type": "Long Title",
      "title_value": "Harvey Beaks #201 blah blah blah",
      "lang": "en-latn-US"
    }
  ]

Then how can I get the ouput as 

title:{
 "Harvey Beaks #201",
"Harvey Beaks #201 blah blah blah"
}

I tried 
 "titles":{
            "*":{
            "title_value":"title"
            }
            }

but I get the ouput with square bracket instead of {}

**Comment by milosimpson** [comment]
Your desired output is not valid JSON.
```
title:{
 "Harvey Beaks #201",
 "Harvey Beaks #201 blah blah blah"
}
```

Do you mean?
```
title: [
 "Harvey Beaks #201",  "Harvey Beaks #201 blah blah blah"
]
```

If so, this spec will do that:
```
[
	{
		"operation": "shift",
		"spec": {
			"titles": {
				"*": {
					"title_type": {
						"Default Title": {
							"@(2,title_value)": "title[0]"
						},
						"Long Title": {
							"@(2,title_value)": "title[1]"
						}
					}
				}
			}
		}
	}
]
```

**Comment by bhupendrabjain** [comment]
Sorry typed it wrongly . Yes thats what I need .. This is a great library .. Thanks for all you help ..

**Comment by anupmallick** [comment]
Input
{
  "Name": "Test Name",
  "Description": "Test Description",
  "Pre Status": "New",
  "Status": "Open"
}

I need following output based on these criteria
1. If Pre Status = New & Status = Open, then 
Output:
{
  "Name": "Test Name",
  "Description": "Test Description",
  "Status": "In Progress"
}
2. If Pre Status = Open & Status = Fixed, then
Output:
{
  "Name": "Test Name",
  "Description": "Test Description",
  "Status": "Resolved"
}
