### ISSUE TITLE
Adding Prefix to the output value and adding new field not available in input to the output

### ISSUE THREAD

**Issue by bhupendrabjain** [bazaarvoice/jolt#139]
I need help with the below transformation

for a given input 
```
{
  "vmid": "a5906c52-be25-4a43-9539-15755ffdf54d"
}
```
I need the output to be 
```
{
  "vmid": "a5906c52-be25-4a43-9539-15755ffdf54d",
  "pm_vmid": "gcc_a5906c52-be25-4a43-9539-15755ffdf54d",
  "content":123
}
```

As you can see I need the same value to be copied to 2 different fields and in one of the fields I want to add my own prefix to the output value. Also i need to add one new field to the output which was not there in the input . Can someone help me with this ?

**Comment by milosimpson** [comment]
This spec produces the output, but not it is hard coded.   Aka, always adds "gcc_" as a prefix, and then always just add `"content":123` at the end.

Spec:
```
[
	{
		"operation": "shift",
		"spec": {
			"vmid": {
				"@": "vmid",
				"*": {
					"#willGetThrownAway": "pm_vmid.gcc_&1"
				}
			}
		}
	},
	{
		"operation": "shift",
		"spec": {
			"vmid": "vmid",
			"pm_vmid": {
				"*": {
					"$": "pm_vmid"
				}
			}
		}
	},
	{
		"operation": "default",
		"spec": {
			"content": 123
		}
	}
]
```
