### ISSUE TITLE
Add repeated values inside Array

### ISSUE THREAD

**Issue by manankapoor88** [bazaarvoice/jolt#141]
Hi,

I am trying to add "name" & "moduleType" inside array. As multiref  data is dynamic. it contains two objects or single , so in this scenario I want it to print twice in new node array. But i am not able to get desired output. Please see below details:

Input:

    {
	"moduleType": "asdf",
	"name": "asdf",
	"multiref": [
		{
			"title": "asdf",
			"tmsid": "1"
		},
		{
			"title": "asdf1",
			"tmsid": "2"
		}
	]
    }

Expected Output:

      {
    "node": [
        {
            "identity": {
                "name": "asdf",
                "moduleType": "asdf"
            },
            "dynamic": {
                "title": "asdf",
                "tmsid": "1"
            }
        },
        {
            "identity": {
                "name": "asdf",
                "moduleType": "asdf"
            },
            "dynamic": {
                "title": "asdf1",
                "tmsid": "2"
            }
        }
    ]
    }

spec:

    [
	{
		"operation": "shift",
		"spec": {
			"name": "node.identity.name",
			"moduleType": "node.identity.moduleType",
			"multiref": {
				"title": "node.dynamic.title",
				"tmsid": "node.dynamic.tmsid",
				"*": {
					"title": "node.[&1].dynamic.title",
					"tmsid": "node.[&1].dynamic.tmsid"
				}
			}
		}
	}
    ]

Wrong Output:

    {
      "node" : {
    "identity" : {
      "moduleType" : "asdf",
      "name" : "asdf"
    }
      }
         }

**Comment by milosimpson** [comment]
Spec
```
[
	{
		"operation": "shift",
		"spec": {
			"multiref": {
				"*": {
					"@(2,name)": "node[&1].identity.name",
					"@(2,moduleType)": "node[&1].identity.moduleType",
					"title": "node[&1].dynamic.title",
					"tmsid": "node[&1].dynamic.tmsid"
				}
			}
		}
	}
]
```

The key thing is using the "transpose" operator "@(2,name)" to grab the root level "name" field, for each element of the input multiref array.

**Comment by manankapoor88** [comment]
Thanks a lot for your response. I have tested this with array and it is working. 

Can we handle this scenario ?

Multiref is coming as single object or  array of two objects as seen below. When I added your spec, it is working for array alone and object alone. not in combination(using single spec). Can you please let me know way to handle this in combination using single spec. 

For ex- If multiref is array, it will show in array and if single object,  it will show in single object.

 Input:

    {
    "moduleType": "asdf",
    "name": "asdf",
    "multiref": [
        {
        "title": "asdf",
        "tmsid": "1"
    },
    {
        "title": "asdf1",
        "tmsid": "2"
    }
    ]
    }

or other input:

    {
     "moduleType": "asdf",
    "name": "asdf",
     "multiref": 
      {
        "title": "asdf1",
        "tmsid": "2"
     }
    }


To handle this I have added spec as seen below:

      [
        {
        "operation": "shift",
        "spec": {
            "multiref": {
                       "@(2,name)": "node.identity.name",
                    "@(2,moduleType)": "node.identity.moduleType",
                    "title": "node.dynamic.title",
                    "tmsid": "node.dynamic.tmsid"
                "*": {
                    "@(2,name)": "node[&1].identity.name",
                    "@(2,moduleType)": "node[&1].identity.moduleType",
                    "title": "node[&1].dynamic.title",
                    "tmsid": "node[&1].dynamic.tmsid"
                }
            }
        }
    }
    ]

**Comment by milosimpson** [comment]
This spec can handle multiref being an array or a single value.   As such it, in the output it generates "node" can either be an array or a map.
```
[
	{
		"operation": "shift",
		"spec": {
			"multiref": {
				"title": "node.dynamic.title",
				"tmsid": {
					"@": "node.dynamic.tmsid",
					"@(2,name)": "node.identity.name",
					"@(2,moduleType)": "node.identity.moduleType"
				},
				"*": {
					"@(2,name)": "node[&1].identity.name",
					"@(2,moduleType)": "node[&1].identity.moduleType",
					"title": "node[&1].dynamic.title",
					"tmsid": "node[&1].dynamic.tmsid"
				}
			}
		}
	}
]
```

Generally, I think it would be "better" / safer to always output the same thing, regardless of input.
This spec "fixes" the cardinality of the "multiref" input to always be a List, before the "shift" operation runs.   Thus, shift always sees the "multiref" as a list and always outputs "node" as a List.
```
[
	{
		"operation": "cardinality",
		"spec": {
			"multiref": "MANY"
		}
	},
	{
		"operation": "shift",
		"spec": {
			"multiref": {
				"*": {
					"@(2,name)": "node[&1].identity.name",
					"@(2,moduleType)": "node[&1].identity.moduleType",
					"title": "node[&1].dynamic.title",
					"tmsid": "node[&1].dynamic.tmsid"
				}
			}
		}
	}
]
```

**Comment by sreenivas123456** [comment]
@milosimpson
I have a JSON
{
  "name": "product_image",
  "type": "string"
}
I need to transform it as
{"fun":
	[
		{
			"name":"product_image",
			"type":"string"
		}
	]
}
my spec is 
[
  {
    "operation": "shift",
    "spec": {
      "*": {
        "@": "fun.[].&"
      }
    }
}
]
with above spec i am not able to get the correct output
can anyone help in this

**Comment by sreenivas123456** [comment]
i got it 
[
  {
    "operation": "shift",
    "spec": {
      "@1": "fun[]"
    }
}
]

**Comment by milosimpson** [comment]
That works.

This also works, and is a bit more explicit about the fun array having all the data in it's zeroth index.
```
[
  {
    "operation": "shift",
    "spec": {
      "*": "fun[0].&"
    }
  }
]
```

**Comment by zzdga** [comment]
Would appreciate some help, I've also got a JSON:

{
  "vendorName" : "name1",
  "beginTime" : "2020-01-21T10:00:00+08:00",
  "userLabel" : "label1",
  "sometype001" : {
    "sub_name01" : {
      "counter1" : "0",
      "counter2" : "0",
      "counter3" : "0"
    }
  },{
   "someType002" : {
    "sub_name002": {
      "counter8" : "0",
      "counter5" : "0",
      "counter3" : "0"
      }
    }
}
and would need something like:
{
  "vendorName" : "name1",
  "beginTime" : "2020-01-21T10:00:00+08:00",
  "userLabel" : "label1",
  "Types": [ {
           "type_name": "some_name1",
            "SubTypes": [ {
                  "sub_type_name": "sub_name01",
                  "Counters": [ {
                      "cnt_name": "counter1",
                     "cnt_value": "0" 
                    },{
                      "cnt_name": "counter2",
                      "cnt_value": "0",
                    },{
                      "cnt_name": "counter3",
                     "cnt_value": "0"
                    } ],
             },
             {
             "type_name": "someType002",
             "SubTypes": [ {
                     "sub_type_name": "sub_name002",
                     "Counters": [ {
                            "cnt_name": "counter8",
                            "cnt_value": "0"
                            },{
                              "cnt_name": "counter5"
                              "cnt_value": "0"
                             },{
                               "cnt_name": "counter3",
                              "cnt_value": "0"
                            } ]
                    }]
}

could someone give me a helping hand
