### ISSUE TITLE
How to get multiple array value out

### ISSUE THREAD

**Issue by manankapoor88** [bazaarvoice/jolt#144]
Hi

Can you please help me this transforamtion:

input:

     {
    "image": [
        "content1",
        "content2",
        "content3"
    ],
    "legal": [
        "legal1",
        "legal2",
        "legal3"
    ],
    "hyper": [
        "hyper1",
        "hyper2",
        "hyper3"
    ]
    }

output:

    [
    {
        "image": "content1",
        "legal": "legal1",
        "hyper": "hyper1"
    },
    {
        "image": "content1",
        "legal": "legal1",
        "hyper": "hyper1"
    },
    {
        "image": "content1",
        "legal": "legal1",
        "hyper": "hyper1"
    }
    ]

**Comment by milosimpson** [comment]
I think this is what you want
```
[
	{
		"operation": "shift",
		"spec": {
			"*": {
				"*": "[&0].&1"
			}
		}
	}
]
```

but this produces the output you specified
```
[
	{
		"operation": "shift",
		"spec": {
			"*": {
				"*": {
					"@(1,[0])": "[&1].&2"
				}
			}
		}
	}
]
```
