### ISSUE TITLE
Remove spec not removing items from objects within an array

### ISSUE THREAD

**Issue by dan-s1** [bazaarvoice/jolt#145]
I have a JSON document where I have a top level array of objects and I am trying to remove items from within the objects and its not working:
example document 
```
{
  "stooges"  : 
  [
          "manny :   {
                "height" : 200,
               "hair_color" : brown"
          }                                                                                                                                    
  ]
}
```

and my spec is
```
[
   {
            "operation" : "remove",
            "spec" :         
            {
                       "stooges" :
                       "*" :
                       { 
                                "*" :  
                               {
                                      "hair_color" : ""
                               }
                       }       
            }
   }
]
```

yet hair color is not removed. What is strange is for a shift spec I used the same type of structure and I am able to shift items at the same level of hair_color. Please advise. 

Also on a side note I tried running the above example on http://jolt-demo.appspot.com/ and I got the following error 
"Could not url-decode the inputs."

**Comment by dan-s1** [comment]
Looks like the spec did not come out. This is what it should look like:
```
           [
   {
            "operation" : "remove",
            "spec" :         
            {
                       "stooges" :
                       "*" :
                       { 
                                "*" :  
                               {
                                      "hair_color" : ""
                               }
                       }       
            }
   }
]
```

**Comment by milosimpson** [comment]
Yeah, "remove" currently does not handle Arrays.  It can't step down into the input array of "stooges".

There is code in the main trunk that let "remove" handle arrays, but it needs more QA and then a release.

Also with respect to "Could not url-decode the inputs."   Your input data and spec are not valid Json.

**Comment by milosimpson** [comment]
Fixed in  jolt-0.0.17.

**Comment by SUNYTYAGI** [comment]
Hi,

Input:
{
	"data": {
		"clientId": "",
		"Suny": "tyagi"
	}
}

I want to remove key "Suny" if key "clinetId" is empty(""). I tried below spec but it did not work.Could you please help me out?

[
  {
    "operation": "remove",
    "spec": {
      "data": {
        "clientId": {
          "": {
            "&(1,Suny)": ""
          }
        }
      }
    }
  }
]

**Comment by milosimpson** [comment]
Remove can not do any conditional logic.

What you want can be done via Shift, but it is kinda ugly.

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "data": {
        "clientId": {
          "@": "clientId",  // always pass clientId thru

          "": null, // If the value of clientId is "", then do nothing
                    // "do nothing" by matching and preventing the "*"
          					// logic below from matching

          "*": {    // For all other values of "clientId", go buack up the
                    //  the tree, and grab the value of Suny and write it 
                    //  to the output as Suny
            "@(2,Suny)": "Suny"
          }
        }
      }
    }
  }
]
```
