### ISSUE TITLE
Keep null value after transformation

### ISSUE THREAD

**Issue by qwelyt** [bazaarvoice/jolt#150]
Example input
```json
{
	"key": null
}
```
Example spec
```json
[
	{
		"operation": "shift",
		"spec": {
			"key": "key.value"
		}
	}
]
```

Is there a way to output the value even if it's null? The data can exist, but can also be null.
I still want the value because the format has to be correct.
So is there a way to, in the output, still get the structure even if the value happens to be null?

Wanted output:
```json
{
  "key" : {
    "value" : null
  }
}
```

**Comment by qwelyt** [comment]
I got the desired output by adding a `default` operation to the spec.
```json
[
    {
        "operation": "shift",
        "spec": {
            "key": "key.value"
        }
    },
    {
        "operation": "default",
        "spec": {
           "key": {
              "value": null
           }
        }
    }
]
```

But out of curiosity, is there another way to do this?

**Comment by milosimpson** [comment]
No there is a bug in Shiftr somewhere where it does not like to pass a null thru.
