### ISSUE TITLE
Unable to default data in array items

### ISSUE THREAD

**Issue by intuit-recruiting** [bazaarvoice/jolt#151]
I need help getting the "defaultr" to add new elements to array items.  Is this possible?

Input:
```
{
	"survey": {
		"ratings": [
			{
				"score": 1
			},
			{
				"score": 2
			}
		]
	}
}
```
Spec:
```
[
	{
		"operation": "shift",
		"spec": {
			"survey": {
				"ratings": {
					"*": {
						"score": "ShiftedSurvey.[&1].&"
					}
				}
			}
		}
	},
	{
		"operation": "default",
		"spec": {
			"Range": 5,
			"ShiftedSurvey": {
				"*": {
					"DefaultedItem": 5
				}
			}
		}
	}
]
```
Output:
```
{
  "ShiftedSurvey" : [ {
    "score" : 1
  }, {
    "score" : 2
  } ],
  "Range" : 5
}
```
Desired Output (Please help!, Thank you):
```
{
  "ShiftedSurvey" : [ {
    "score" : 1,
   "DefaultedItem": 5
  }, {
    "score" : 2,
   "DefaultedItem": 5
  } ],
  "Range" : 5
}
```

**Comment by milosimpson** [comment]
Spec :
```
[
	{
		"operation": "shift",
		"spec": {
			"survey": {
				"ratings": {
					"*": {
						"score": "ShiftedSurvey.[&1].&"
					}
				}
			}
		}
	},
	{
		"operation": "default",
		"spec": {
			"Range": 5,
			"ShiftedSurvey[]": {
				"*": {
					"DefaultedItem": 5
				}
			}
		}
	}
]
```

Each of the operations, default, shift, remove, etc have a unique but generally related syntax targeted at their particular job.

In this case "default" needs to know it is supposed to be operating on an array thus "ShiftedSurvey[]".

**Comment by pollaxman** [comment]
This helped me. How can we set the default value in array element based on specific condition.

**Comment by soumyadeep-saha** [comment]
Hi @milosimpson ,
I am having difficulties in an urgent production issue. Please help me
My Input(it can have data inside array or empty array, a single spec should handle both)
{
  "category": {
    "data": {
      "recordSetTotal": "0",
      "sectionTitle": "",
      "sortByDetails": [],
      "recordSetCount": "0",
      "productDetails": [],
      "breadcrumb": [],
      "facetDetails": []
    }
  }
}
My Spec:
[
  {
    "operation": "shift",
    "spec": {
      "category": {
        "data": {
          "recordSetTotal": "recordSetTotal",
          "recordSetCount": "recordSetCount",
          "sectionTitle": "sectionTitle",
          "breadcrumb": {
            "*": {
              "value": "breadcrumb.[&1].value",
              "label": "breadcrumb.[&1].label",
              "seoURL": "breadcrumb.[&1].seoURL"
            }
          },
          "sortByDetails": {
            "*": {
              "propertyName": "sortByInfo.[&1].name",
              "propertyId": "sortByInfo.[&1].id",
              "propertySelected": "sortByInfo.[&1].selectedProperty"
            }
          },
          "facetDetails": {
            "*": {
              "facetId": "facets.[&1].id",
              "facetCount": "facets.[&1].totalCount",
              "facetName": "facets.[&1].name",
              "facetExpanded": "facets.[&1].facetExpanded",
              "facetallowMultipleValueSelection": "facets.[&1].allowMultipleValueSelection",
              "facetdisplaySequence": "facets.[&1].displaySequence",
              "facetProperty": "facets.[&1].property",
              "values": {
                "*": {
                  "labelProperty": "facets.[&3].labels.[&1].property",
                  "labelSEOUrl": "facets.[&3].labels.[&1].seoUrl",
                  "labelName": "facets.[&3].labels.[&1].name",
                  "labelcount": "facets.[&3].labels.[&1].count",
                  "labelId": "facets.[&3].labels.[&1].id"
                }
              }
            }
          },
          "productDetails": {
            "*": {
              "name": "productinfo.[&1].name",
              "uniqueID": "productinfo.[&1].id",
              "shortDescription": "productinfo.[&1].shortDescription",
              "longDescription": "productinfo.[&1].longDescription",
              "buyable": "productinfo.[&1].sellable",
              "color_count": "productinfo.[&1].colorCount",
              "flavour_count": "productinfo.[&1].flavourCount",
              "team_count": "productinfo.[&1].teamCount",
              "patern_count": "productinfo.[&1].patternCount",
              "clr_flavour_count": "productinfo.[&1].clrFlavourCount",
              "clr_color_count": "productinfo.[&1].clrColorCount",
              "clr_team_count": "productinfo.[&1].clrTeamCount",
              "clr_patern_count": "productinfo.[&1].clrPatternCount",
              "aycolorimages": "productinfo.[&1].colorImages",
              "xitem_count": "productinfo.[&1].skuCount",
              "bv_rating": "productinfo.[&1].bvRating",
              "manufacturer": "productinfo.[&1].manufacturer",
              "rep_child_catid": "productinfo.[&1].defaultSku",
              "hasSingleSKU": "productinfo.[&1].isSingleSkuProduct",
              "bundletype": "productinfo.[&1].bundletype",
              "varianttype": "productinfo.[&1].varianttype",
              "partNumber": "productinfo.[&1].partNumber",
              "seo_token_ntk": "productinfo.[&1].seoURL",
              "fullImage": "productinfo.[&1].imageURL",
              "imageAltDesc": "productinfo.[&1].imageAltDescription",
              "gc_flag": "productinfo.[&1].isGiftCard",
              "price": {
                "offerPrice": "productinfo.[&2].defaultSkuPrice.salePrice",
                "priceMessage": "productinfo.[&2].defaultSkuPrice.priceMessage",
                "savings": "productinfo.[&2].defaultSkuPrice.savings",
                "regularPrice": "productinfo.[&2].defaultSkuPrice.listPrice",
                "priceRange": "productinfo.[&2].priceRange"
              },
              "description": "productinfo.[&1].promoMessage",
              "adbug": "productinfo.[&1].adBug",
              "shippingMessage": "productinfo.[&1].shippingMessage",
              "storeID": "productinfo.[&1].storeId",
              "defaultSkuInventory": {
                "*": {
                  "availableQuantity": "productinfo.[&3].defaultSkuInventory.[&1].availableQuantity",
                  "inventoryStatus": "productinfo.[&3].defaultSkuInventory.[&1].inventoryStatus"
                }
              },
              "defaultStoreInventory": {
                "*": {
                  "availableQuantity": "productinfo.[&3].defaultStoreInventory.[&1].availableQuantity",
                  "inventoryStatus": "productinfo.[&3].defaultStoreInventory.[&1].inventoryStatus"
                }
              },
              "sKUs": {
                "*": {
                  "partNumber": "productinfo.[&3].sKUs.[&1].skuId",
                  "uniqueID": "productinfo.[&3].sKUs.[&1].itemId",
                  "fullImage": "productinfo.[&3].sKUs.[&1].imageURL",
                  "price": {
                    "offerPrice": "productinfo.[&4].sKUs.[&2].price.salePrice",
                    "priceMessage": "productinfo.[&4].sKUs.[&2].price.priceMessage",
                    "savings": "productinfo.[&4].sKUs.[&2].price.savings",
                    "regularPrice": "productinfo.[&4].sKUs.[&2].price.listPrice",
                    "priceRange": "productinfo.[&4].sKUs.[&2].priceRange"
                  },
                  "adbug": "productinfo.[&3].sKUs.[&1].adBug",
                  "attributes": {
                    "*": {
                      "uniqueID": "productinfo.[&5].sKUs.[&3].attributes.[&1].uniqueID",
                      "name": "productinfo.[&5].sKUs.[&3].attributes.[&1].name",
                      "usage": "productinfo.[&5].sKUs.[&3].attributes.[&1].usage",
                      "values": {
                        "*": {
                          "value": "productinfo.[&7].sKUs.[&5].attributes.[&3].values.[&1].value"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
	},
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "productinfo": {
        "*": {
          "seoURL?": "=concat('/shop/pdp/',@(1,seoURL))"
        }
      },
      "breadcrumb": {
        "*": {
          "seoURL?": "=concat('/shop',@(1,seoURL))"
        }
      },
      "facets": {
        "*": {
          "labels": {
            "*": {
              "seoUrl?": "=concat('/shop',@(1,seoUrl))"
            }
          }
        }
      }
    }
	},
  {
    "operation": "default",
    "spec": {
      "sortByDetails[]": {},
      "productDetails[]": {},
      "breadcrumb[]": {},
      "facetDetails[]": {}
    }
  }
]

My Expected output in case of empty array and the same spec should handle for data with array also
{
    "recordSetTotal": "0",
    "recordSetCount": "0",
    "breadcrumb": [],
    "sortByInfo": [],
    "facets": [],
    "productinfo": []
}

Please help on how should I do it
