### ISSUE TITLE
single value in array

### ISSUE THREAD

**Issue by manankapoor88** [bazaarvoice/jolt#152]
Hi,

input type 1:

     {
       "a" : "test" 
     }

or
Inpy type 2:

    {
       "a": "[test1,test2]"
    }

Expected:
Input value is dynamic. 
I need output result as an array only. If input is not in form of array then I need it inside array. For ex , if I am getting  input as type 1, I need value in array. But if I am getting input as type 2 which is in array, I don't want to change it.

spec:

         [
	{
		"operation": "shift",
		"spec": {
			"a": {
				"*": "identity.vanityUrls[]"
			}
		}
	}
        ]

This spec is working fine for input type 2 but not for type 1. I need single spec which work for both inputs. Thanks

**Comment by milosimpson** [comment]
I don't understand the question.

**Comment by manankapoor88** [comment]
Sorry for inconvenience. I have updated the question again. Please check.

**Comment by milosimpson** [comment]
"If I am getting input as type 1, I need value in array. But if I am getting input as type 2 which is in array, I don't want to change it."

This does that; it is actually what the "cardinality" operation was created for.
Spec
```
[
	{
		"operation": "cardinality",
		"spec": {
			"a": "MANY"
		}
	}
]
```

**Comment by manankapoor88** [comment]
Thanks for you  quick response. it is working at my end.
