### ISSUE TITLE
List to List transformation : how to do it?

### ISSUE THREAD

**Issue by rishabhdhwaj** [bazaarvoice/jolt#154]
We are evaluating JOLT for JSON to JSON transformation in our service where the input is a generic template(as a JSON) and we need to construct specific jsons out of the generic template on the fly depending upon business use cases. 

However I am not able to do transformations from List of Maps to List of Maps with transformed keys
My input is a list. My output would also be a list with transformed keys:
For example 
Input : 
{
	"restaurantId": "ZZ4ORJDY3E",
	"chainId": "RLR932KI",
	"orderItems": [
		{
			"itemName": "Small Barqs",
			"quantity": 2
		},
		{
			"itemName": "Mozzz",
			"quantity": 1
		}
	]
}

Expected Output : 

{
  "invoice_item" : [ {
    "invoice_item_Name" : 2,
    "invoice_quantity" : "Small Barqs"
  }, {
    "invoice_item_Name" : 1,
    "invoice_quantity" : "Mozzz"
  } ],
  "retailer_id" : "RLR932KI",
  "store_id" : "ZZ4ORJDY3E"
}

Actual output I am getting 

{
  "invoice_item" : [ {
    "invoice_item_Name" : 2
  }, {
    "invoice_quantity" : "Small Barqs"
  }, {
    "invoice_item_Name" : 1
  }, {
    "invoice_quantity" : "Mozzz"
  } ],
  "retailer_id" : "RLR932KI",
  "store_id" : "ZZ4ORJDY3E"
}

Wrong JOLT spec I am using 

[
	{
		"operation": "shift",
		"spec": {
			"chainId": "retailer_id",
			"restaurantId": "store_id",
			"orderItems": {
				"*": {
					"quantity": "invoice_item.[].invoice_item_Name",
					"itemName": "invoice_item.[].invoice_quantity"
				}
			}
		}
	}
]

Can you please let me know what should be the correct JOLT spec

**Comment by rishabhdhwaj** [comment]
Thanks was able to solve by using the following JOLT Spec :)


[
	{
		"operation": "shift",
		"spec": {
			"chainId": "retailer_id",
			"restaurantId": "store_id",
			"orderItems": {
				"*": {
					"quantity": "invoice_item[&1].invoice_item_Name",
					"itemName": "invoice_item[&1].invoice_quantity"
				}
			}
		}
	}
]

**Comment by milosimpson** [comment]
Cool, nice job figuring it out on your own.
