### ISSUE TITLE
How to create a temporary variable in json spec

### ISSUE THREAD

**Issue by kvnmanohar** [bazaarvoice/jolt#157]
I want to copy a input value into a temporary variable for some time.I will use this variable after some time.How to do this in spec file?
For eg: When going through nested levels of input json, "$" wild card needs to be stored for some time, as @(3,$) like notations are wrong.I want to store that $ in temp and will use in deeper levels.

**Comment by milosimpson** [comment]
There isn't a notion of a variable.

I know of two ways to accomplish what you want.
# Use the Right Hand Side "@(3,a.b.c)" logic to continually reference a part of your document
# Use two Shifts
## Pass everything thru, but match and setup your "variable" as an easy to reference thing.

Can you provide an example?

**Comment by kvnmanohar** [comment]
Input:
"IDMap":{
	"classA":{
		"ids":{
			"id1":123,
			"id2":456
		}
	},
	"classA":{
		"ids":{
			"id1":453,
			"id2":323
		}
	}
}

Ouptut:

[
  {
    "id1": "123",
    "className": "ClassA"
  },
  {
    "id1": "456",
    "className": "ClassA"
  },
  {
    "id1": "453",
    "className": "ClassB"
  },
  {
    "id1": "323",
    "className": "ClassB"
  }
]

**Comment by milosimpson** [comment]
Use two shifts.

```
[
	{
		"operation": "shift",
		"spec": {
			"IDMap": {
				"class*": {
					"ids": {
						"*": "&2---&"
					}
				}
			}
		}
	},
	{
		"operation": "shift",
		"spec": {
			"*---*": {
				"$(0,1)": "[#2].className",
				"@": "[#2].&(1,2)"
			}
		}
	}
]
```
The first Shift "flattens" the data into 
```
{
  "classA---id1" : 123,
  "classA---id2" : 456,
  "classB---id1" : 453,
  "classB---id2" : 323
}
```

The second one can then take that and build the Array of Maps structure you want.

**Comment by kvnmanohar** [comment]
I gave a sample data.What if I want to travel input again after first shift operation.Several other output fields depends on input. If I use two shifts,there would be redundancy in spec as I have to pass all the input fields through shift.
Also, how to use '&' wild card in LHS. I cant' find any example.If I can use "&2" on LHS,it will be very helpful.

**Comment by milosimpson** [comment]
It is pretty easy to pass the whole input or large chunks of the input thru the first Shift.

This does the two Shifts, but keeps IDMap pass thru.  Its not an overly expensive operation, as it is not making a deep copy of the data.   
```
[
	{
		"operation": "shift",
		"spec": {
			"IDMap": {
				"@": "IDMap",
				"class*": {
					"ids": {
						"*": "flattend.&2---&"
					}
				}
			}
		}
	},
	{
		"operation": "shift",
		"spec": {
			"IDMap": "IDMap",
			"flattend": {
				"*---*": {
					"$(0,1)": "flattend.[#2].className",
					"@": "flattend.[#2].&(1,2)"
				}
			}
		}
	}
]
```

Be careful tho, about doing a blanket copy of the data to the output, then traversing the input and writing to itself.   IE. if you pass "IDMap" thru the first Shift, don't also send any other writes to it.

**Comment by milosimpson** [comment]
Example of LHS "&".  It allows you to match on a parent value.

Input
```
{
	"A": {
		"A": {
			"1": "a",
			"2": "a"
		},
		"B": {
			"1": "b",
			"2": "b"
		}
	}
}
```

Spec 
```
[
	{
		"operation": "shift",
		"spec": {
			"*": {
				"&": {
					"1": "parent_and_grandparent_matched"
				}
			}
		}
	}
]
```
Outputs "a".   If you change the top level field in the intput to "B", then the spec will output "b".

**Comment by kvnmanohar** [comment]
Thank you.Two shifts worked for me.
