### ISSUE TITLE
Is there a way to assign same constant value to different properties?

### ISSUE THREAD

**Issue by pollaxman** [bazaarvoice/jolt#161]
input:
```
{
	"survey": {
		"key": "value"
	}
}
```

Spec:
```
{
	"operation": "shift",
	"spec": {
		"survey": {
                         "key": "a.b.firstProperty"
                         "key": "a.b.secondProperty"
			"#Constant": "a.b.thirdProperty",
                       "#Constant": "a.b.fourthProperty"
		}
	}
}
```
Wanted :
```
{
	"a": {
		"b": {
			"firstProperty": "value",
			"secondProperty": "value",
			"thirdProperty": "Constant",
                         "fourthProperty": "Constant",
		}
	}
}
```

**Comment by milosimpson** [comment]
This Spec does what you want
```
[
	{
		"operation": "shift",
		"spec": {
			"survey": {
				"key": {
					"@": [ "a.b.firstProperty", "a.b.secondProperty" ],
					"#Constant": [ "a.b.thirdProperty",	"a.b.fourthProperty" ]
				}
			}
		}
	}
]
```

For the shift operation, if you want to write the same thing to multiple places, you use an array.

**Comment by pollaxman** [comment]
Thank you. Its helped me.
One more question how to append some constant value to existing value.
Ex:
input:
{
    "survey": {
        "key": "value1"
    }
}
expected:
{
    "a": {
        "b": {
            "firstproperty": "surveyConstant_value1",
            "secondProperty": "b_value1",
             "id":"b"
        }
    }
}
How to achieve this in spec.Please suggest me.

**Comment by milosimpson** [comment]
"How to append some constant value to existing value."
Jolt does not does not support this out of the box.

It can be bent / twisted into doing so, but it is really ugly.
Spec
```
[
	{
		"operation": "shift",
		"spec": {
			"survey": {
				"key": {
					"*": [
						"a.b.firstproperty.surveyConstant_&",
						"a.b.secondProperty.b_&"
					]
				}
			}
		}
	},
	{
		"operation": "shift",
		"spec": {
			"a": {
				"b": {
					"firstproperty": {
						"*": {
							"$": "a.b.firstproperty"
						}
					},
					"secondProperty": {
						"*": {
							"$": "a.b.secondProperty"
						}
					}
				}
			}
		}
	},
	{
		"operation": "default",
		"spec": {
			"a": {
				"b": {
					"id": "b"
				}
			}
		}
	}
]
```

Effectively you have to build the "surveyConstant_value1" as a key in a map, then do a 2nd Shift to make it be a value.

**Comment by pollaxman** [comment]
Thank you very much for your quick response.

**Comment by pollaxman** [comment]
Thank you .Closing the issue
