### ISSUE TITLE
How Can we update Array?

### ISSUE THREAD

**Issue by swarit15** [bazaarvoice/jolt#163]
"Employees": [
					{
						"id": "aaaaaa",
						"project": "any",
						"technology": "any"
					}
				]
I am having Employee Array as mentioned, From the input json I just want to replace/shift id.

I tried to use "_id": "Employees[#].id" in "operation": "shift", while  "project" and "technology" would be remain in "operation": "default" but this has created another Array with same name.

Kindly let me know what option I have to update only one field of an Array

**Comment by milosimpson** [comment]
Please give me an example of your input and then desired output.

**Comment by swarit15** [comment]
Hi, Thanks for response,

input :-
"Employees": [
                {
                    "id": "aaaaaa",
                    "project": "any",
                    "technology": "any"
                }
            ]

Output :-
"Employees": [
                {
                    "id": "bbbbb",
                    "project": "any",
                    "technology": "any"
                }
            ]

**Comment by milosimpson** [comment]
You desired Output is the same as the input.
