### ISSUE TITLE
One to Many Object

### ISSUE THREAD

**Issue by swarit15** [bazaarvoice/jolt#165]
Hi, Not sure if there is any possibility to create multiple object from one object.

For Example :-

*input*
"audiEngines":{
	"engine1" : "engine1",
	"engine2" : "engine2",
	"engine3" : "engine3"
}

*output*
repairAudi{
	"engine" : "engine2",
	"service" : "servicingDone"
}

repairAudi{
	"engine" : "engine3",
	"service" : "servicingDone"
}

In given example, service is default across all output object while engine is updating for each object.

**Comment by milosimpson** [comment]
Nope, there is no way to create multiple output JSON documents from a single input.

That said, we can make an output object that has an array of the output objects you want, and then you could manually extract that into multiple output JSON objects.

Spec
```
[
	{
		"operation": "shift",
		"spec": {
			"audiEngines": {
				"engine*": "outputs[#1].repairAudi.engine"
			}
		}
	},
	{
		"operation": "default",
		"spec": {
			"outputs[]": {
				"*": {
					"repairAudi": {
						"service": "servicingDone"
					}
				}
			}
		}
	}
]
```
Output
```
{
  "outputs" : [ {
    "repairAudi" : {
      "engine" : "engine1",
      "service" : "servicingDone"
    }
  }, {
    "repairAudi" : {
      "engine" : "engine2",
      "service" : "servicingDone"
    }
  }, {
    "repairAudi" : {
      "engine" : "engine3",
      "service" : "servicingDone"
    }
  } ]
}
```

**Comment by swarit15** [comment]
Thanks for reply.

Yeah this way could help me too, in between just curious to know meaning of *#1 in outputs[#1].*

**Comment by milosimpson** [comment]
Generally, it means "go up the tree, one level, and ask it how many of it's children have had a match.

In this case, it means "go up the tree to the 'audiEngines' level, as ask it how many times one of it's children (engine1, engine2, engine3) matched.

**Comment by swarit15** [comment]
Thanks again for all clarifications, Its really helped.
