### ISSUE TITLE
Is this possible to append Values

### ISSUE THREAD

**Issue by swarit15** [bazaarvoice/jolt#166]
*input*
{
"empId" : "1234",
"empName" : "test"
}

**expected output**
{
"employeeDetail" : 1234-test
}

I have tried to use create spec like 

*spec*
{
		"operation": "shift",
		"spec": {
				"empId | empName": "employeeDetail",
			}
	}

which is producing....
{
"employeeDetail" : [1234, test]
}

Kindly help to generate given **expected output**

**Comment by milosimpson** [comment]
Jolt does not really support that.   It can be done but its messy, and brittle.

See https://github.com/bazaarvoice/jolt/issues/161 where I do the same thing.   It requires 2 shifts.

**Comment by swarit15** [comment]
Thanks for comment. Yeah its little tricky, got a work around for now.
