### ISSUE TITLE
How to check empty and null value of a property using spec

### ISSUE THREAD

**Issue by pollaxman** [bazaarvoice/jolt#168]
sample input1:
{
"firstProperty":"",
}

expected output1:
{
}

sample input2:
{
"firstProperty":"ABCLife"
}

sample Output2:
{
firstPropertyValue:"ABCLife"
}

If property value is empty then that property should not come into the output json.
Can you help to provide a spec to check  Empty Condition. Thanks in Advance

**Comment by milosimpson** [comment]
Spec : 
```
[
	{
		"operation": "shift",
		"spec": {
			"firstProperty": {
				"ABCLife": {
					"$": "firstPropertyValue"
				},
				"*": "TRASH"
			}
		}
	},
	{
		"operation": "remove",
		"spec": {
			"TRASH": ""
		}
	}
]
```

**Comment by pollaxman** [comment]
How to check given property is array or single value? 
If it is single value then put into the array
If it is array then put as same(no conversion)

Example Input for single
{
"property":"493"
}
Expected:
{
"property":["493"]
}

Example Input for Array
{
"property":["493","594"]
}
Expected:
{
"property":["493","594"]
}

**Comment by milosimpson** [comment]
Use the "cardinality" operation.   It is what it is designed for.

See https://github.com/bazaarvoice/jolt/blob/master/jolt-core/src/test/resources/json/cardinality/manyLiteralTestData.json

Spec to try in the demo site
```
[
	{
		"operation": "cardinality",
		"spec": {
			"property": "MANY"
		}
	}
]
```

**Comment by anusha94** [comment]
The trick is to capture the input you want, and send the rest to some TRASH variable, that you can delete in a subsequent step.

For the above solution, we are explicitly checking for "ABCLife", but can we do something like except empty string "", match everything else?

Thanks!
