### ISSUE TITLE
Transformation of field having null value or type and value information

### ISSUE THREAD

**Issue by svvenkat** [bazaarvoice/jolt#193]
I have a field, say "Id", in my JSON that can have its value in two formats. One where the value is null. The other where the value has its type information and a value. Have given the corresponding JSON below. 

{"Id": null}   
{"Id" : {"sometype": "somevalue"} }

I want to write a single transformation that does  

{"Id": null} => {"Id": null}  // same as the input data
{"Id" : {"sometype": "somevalue"} } => {"Id": "somevalue"} // Removes the type information.

I am able to do this transformation if the value in the first format is a null string(  {"Id": "null"} ) using the below transformation.

```
[
     {
		"operation": "shift",
		"spec": {
			"*": {
				"sometype": "&1",
				"*": {
					"@1": "&2"
				}
			}
		}
	}
]
```

 But could not figure out a way to do it for my need. Is there a way to achieve this.

**Comment by milosimpson** [comment]
Not cleanly via a single shift.   

This does what you want, but uses a default step to apply "Id" : null, if no "Id" was written by the shift.
```
[
	{
		"operation": "shift",
		"spec": {
			"Id": {
				"sometype": "&1"
			}
		}
	},
	{
		"operation": "default",
		"spec": {
			"Id": null
		}
	}
]
```
