### ISSUE TITLE
Does Jolt consider any optimizations in case the input and output are the same?

### ISSUE THREAD

**Issue by jobinar** [bazaarvoice/jolt#194]
I want to use jolt in cases where the input and the output are currently the same, but I don't my implementation to fail in case the input JSON format changes, I'll just change the spec file, so I'll use jolt to transform to the pattern I expect in case the input changes.

In such cases, where the input & output and the same, does jolt have any optimizations in place?

**NB:** The JSON I get as input is actually a huge JSON array (with ~10k JSON objects), hence this concern.

**Comment by milosimpson** [comment]
No.  Jolt just takes input and produces ouput.   It doesn't have any way of "storing the previous output" to compare with new input, in order to be smart.

You would have to build that smart-ness outside / above Jolt.

**Comment by jobinar** [comment]
I think I have been misunderstood. What I meant was a use case of something like this:

1. Today I have an API which gives a JSON like this:

```
[
    {
        "key1": "value1",
        "key2": "value2",
        "key3": "value3",
    }
]

```
which I'll consume and perform some operations. However, if tomorrow the API gives me something like this:

```
[
    {
        "key1": "value1",
        "key2": {
                       "key4": "value2", 
                       "key5": "value3"
          }
     }
]

```
I'll just change the spec file and everything still works fine. So, in the first case, my spec file would do no transformation at all. I just want the input of jolt to be the ouptut as of today. Does jolt consider any optimizations in such cases. I hope I am clear now. Let me know if you need clarification.

**Comment by milosimpson** [comment]
Ah, ok.  You want the "identity" shift.   

https://github.com/bazaarvoice/jolt/blob/master/jolt-core/src/test/resources/json/shiftr/identity.json

**Comment by jobinar** [comment]
Awesome, this is most probably what we need. Do we have a documentation which will explain clearly and in detail how these operations work apart from the slide deck?

**Comment by milosimpson** [comment]
https://github.com/bazaarvoice/jolt/blob/master/jolt-core/src/main/java/com/bazaarvoice/jolt/Shiftr.java

https://github.com/bazaarvoice/jolt/tree/master/jolt-core/src/test/resources/json/shiftr
