### ISSUE TITLE
Array to Array Shift

### ISSUE THREAD

**Issue by jacob-ramsey** [bazaarvoice/jolt#198]
Input
`{
	"pre": [
		[{
			"key": 11
		}, {
			"key": 12
		}],
		[{
			"key": 15
		}, {
			"key": 16
		}]
	],
	"con": [
		[{
			"key": 17
		}, {
			"key": 18
		}],
		[{
			"key": 19
		}, {
			"key": 20
		}]
	]
}`

Output:
`{
	"types": [{
		"type": "PRE",
		"keys": [{
			"key": 11
		}, {
			"key": 12
		}]
	}, {
		"type": "PRE",
		"keys": [{
			"key": 15
		}, {
			"key": 16
		}]
	}, {
		"type": "CON",
		"keys": [{
			"key": 17
		}, {
			"key": 18
		}]
	}, {
		"type": "CON",
		"keys": [{
			"key": 19
		}, {
			"key": 20
		}]
	}]
}`

All elements in the pre level map to elements with the type element with value PRE, likewise all elements in the con level map to elements with the type element CON.

**Comment by milosimpson** [comment]
You have to do two shifts.

First one builds to parallel arrays, of the types and the keys.   The second then flattens into your desired "types" array.

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "*": { // type
        "*": { // arrayindex
          "@": "parrallelArrayOfKeys[]",
          "$1": "parrallelArrayOfTypes[]"
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      // flatten the parrallel arrays in to a single "types" array
      "parrallelArrayOfTypes": {
        "*": "types[&].type"
      },
      "parrallelArrayOfKeys": {
        "*": "types[&].keys"
      }
    }
  }
]
```

**Comment by jacob-ramsey** [comment]
It is not possible to do that with a match? Like the demo called "On a match, apply a string default"?

**Comment by milosimpson** [comment]
You can match exactly "pre" -> "PRE"   and "con" -> "CON".   But you can't match "*" and then uppercase the match.

See the following test for an example of how to "match exactly"
https://github.com/bazaarvoice/jolt/blob/master/jolt-core/src/test/resources/json/shiftr/hashDefault.json

**Comment by jacob-ramsey** [comment]
Ok, thanks, this gives me plenty of information to solve the problem.
