### ISSUE TITLE
Handle aggregation using json/jolt

### ISSUE THREAD

**Issue by KiranGitHubM** [bazaarvoice/jolt#199]
**Brief** We are evaluating a choice of moving some of our services from xml to json and we currently have good exposure to XML suite of technologies and our services currently have xml I/O but recently there is a push to expose some of our service outputs as json.

**Query** 
Inline with this we may end up having to handle various aggregations requirements with jolt (as a json transformation solution).  

One sample use-case will be to aggregate as per the attached data "xml-based-InputOutput.txt" (contains xml input and aggregated output) and the required xml translation was handled using the attached "xmltranslator.txt"

We are new to jolt so wanted to check if similar requirements can be handled with equal ease using jolt. As you  can see the xml translation using xslt was achieved with roughly 15 lines of xsl code.

I have also attached the equivalent Jsonbased input and expected Output in the attached "json-based-InputOutput.txt"

Any suggestions/help is much appreciated.

Thanks,
Kiran

[Json-based-InputOutput.txt](https://github.com/bazaarvoice/jolt/files/214923/Json-based-InputOutput.txt)
[xml-based-InputOutput.txt](https://github.com/bazaarvoice/jolt/files/214922/xml-based-InputOutput.txt)

[xmltranslator.txt](https://github.com/bazaarvoice/jolt/files/214924/xmltranslator.txt)

**Comment by milosimpson** [comment]
Yeah, in your xml transform it looks like you are doing a bunch of selecting things by id from multiple places, that is not easy in Jolt.

However, given your Json example of input and desired output, Jolt can do that.
Input
```
{
	"accessGroup": [
		{
			"id": "ci1",
			"group": "GROUP1"
		},
		{
			"id": "ci2",
			"group": "GROUP2"
		},
		{
			"id": "ci3",
			"group": "GROUP3"
		}
	],
	"deprole": [
		{
			"id": "ci1",
			"dept": "Dept1",
			"role": "DP1_LEAD"
		},
		{
			"id": "ci2",
			"dept": "Dept2",
			"role": "DP2_LEAD"
		},
		{
			"id": "ci3",
			"label": "Dept3",
			"target": "DP3_LEAD"
		}
	],
	"spRole": [
		{
			"id": "spId1",
			"dept": "Dept1",
			"role": "DP1_LEAD"
		},
		{
			"id": "spId2",
			"dept": "Dept2",
			"role": "DP2_LEAD"
		},
		{
			"id": "spId3",
			"label": "Dept3",
			"target": "DP3_LEAD"
		}
	]
}
```

Desired Output
```
[
	{
		"id": "ci1",
		"group": "GROUP1",
		"dept": "Dept1",
		"role": "DP1_LEAD",
		"id2": "spId1"
	},
	{
		"id": "ci2",
		"group": "GROUP2",
		"dept": "Dept2",
		"role": "DP2_LEAD",
		"id2": "spId2"
	},
	{
		"id": "ci3",
		"group": "GROUP3",
		"dept": "Dept3",
		"role": "DP3_LEAD",
		"id2": "spId3"
	}
]
```

Spec 
```
[
  {
    "operation": "shift",
    "spec": {
      "accessGroup": {
        "*": {
          "id": "[&1].id",
          "group": "[&1].group"
        }
      },
      "deprole": {
        "*": {
          "dept": "[&1].dept",
          "role": "[&1].role"
        }
      },
      "spRole": {
        "*": {
          "id": "[&1].id2"
        }
      }
    }
  }
]

```

**Comment by satyacha** [comment]
Is there a way to do joins based on the data, instead of relying on the matching / correlated indexes in the arrays? That'd be a really good addition to the library.
