### ISSUE TITLE
Translating un-named array

### ISSUE THREAD

**Issue by dmascord** [bazaarvoice/jolt#200]
Hi,

First of all, thanks for writing such a translation tool, it seems to do what I need it to do, but I can't wrap my brain around it.

I have written a spec:

{
  "latitude": "Features.geometry.coordinates",
  "longitude": "Features.geometry.coordinates"
}

To translate the fake-beacon.TXT into fake-geojson.TXT, but jolt fails due to "Chainr failed to process spec file.".

[fake-beacon.TXT](https://github.com/bazaarvoice/jolt/files/224994/fake-beacon.TXT)
[fake-geojson.TXT](https://github.com/bazaarvoice/jolt/files/224995/fake-geojson.TXT)

Obviously the spec is not complete, but I have tried to read the previously reported issues, including all of the JavaDoc, but can't see how to implement the spec to generate what I need.

Thanks,

Damien

**Comment by milosimpson** [comment]
Spec   
This moves handles the "name", "latitude", and "longitude".   For the rest of the stuff, I did not see it as part of the input data, so I assume it s a bunch of defaults, hence you should should add a "default" transform step to apply thing like "type": "FeatureCollection".
```
[
  {
    "operation": "shift",
    "spec": {
      "*": { // input data is top level array
        "name": "features[&1].properties.Name",
        "latitude": "features[&1].geometry.coordinates[0]",
        "longitude": "features[&1].geometry.coordinates[1]"
      }
    }
  }
]
```
