### ISSUE TITLE
Applying chain specification to a default transform results in a NullPointer exception

### ISSUE THREAD

**Issue by YolandaMDavis** [bazaarvoice/jolt#202]
I've been working with Jolt Libraries and during my testing I discovered an interesting bug. It was a negative test case however I was looking for the library to report the error in a consistent way.  

I attempted to pass a specification meant for a Chain transformation object to a Default transformation object. I was expecting a SpecException or a TransfomException (similar to the other transform objects that receive unsupported specifications) however a NullPointer exception occurred. For comparison passing the same specification to the Shift transformation object results in an expected SpecException (with the message "Shiftr expected a spec of Map type, got ArrayList").

Attached are the example of the specification used and example input (pulled from the Jolt Transform Demo http://jolt-demo.appspot.com/#inception)

[chainr_transform_spec_json.txt](https://github.com/bazaarvoice/jolt/files/230457/chainr_transform_spec_json.txt)
[example_input_json.txt](https://github.com/bazaarvoice/jolt/files/230458/example_input_json.txt)

Any help or insight with this would be greatly appreciated

**Comment by milosimpson** [comment]
Yeah, when the transform specifications are loaded, they are not typed, they are generic List<Object> and Map<String,Object> trees.

The exceptions you are seeing are from the Shift transform trying to process the "generic" given spec into its actual Spec objects, and it running into something invalid.

The reason the specs are generic is that I did not want to tie the core of the jolt library to a specific Json -> Java serializer (Jackson, Gson, etc).

**Comment by YolandaMDavis** [comment]
Thanks for responding! I'm working on incorporating JOLT into Apache NiFi.  Cited as a minor issue for our users, but if there is a potential fix in the future that would be awesome.

**Comment by juliofalbo** [comment]
Hi, what is the solution for it? @milosimpson
