### ISSUE TITLE
Help with JOLT transform

### ISSUE THREAD

**Issue by eklinger** [bazaarvoice/jolt#203]
Hello,
My use case is pretty simple but I can't figure out what my shift should look like. Essentially pulling the array up one level and camel casing the attributes. Also, is there a way to remove attributes with null value?

Thank you

Input:
```
{
	"Addresses": [
		{
			"AddressLine1": "VICTORIA SQUARE",
			"AddressLine2": "1",
			"AddressLine3": null,
			"AddressLine4": null,
			"City": "BELFAST",
			"State": "CO ANTRIM",
			"Country": null,
			"ZipCode": "BT1 4QG"
		},
		{
			"AddressLine1": "TEST",
			"AddressLine2": "1",
			"AddressLine3": null,
			"AddressLine4": null,
			"City": "IRVINE",
			"State": "CA",
			"Country": "USA",
			"ZipCode": "94201"
		}
	]
}
```
Desired output:
```
{
	[
			"addressLine1": "VICTORIA SQUARE",
			"addressLine2": "1",
			"addressLine3": null,
			"addressLine4": null,
			"city": "BELFAST",
			"state": "CO ANTRIM",
			"country": null,
			"zipCode": "BT1 4QG"
		},
		{
			"addressLine1": "TEST",
			"addressLine2": "1",
			"addressLine3": null,
			"addressLine4": null,
			"city": "IRVINE",
			"state": "CA",
			"country": "USA",
			"zipCode": "94201"
		}
	]
}
```

**Comment by eklinger** [comment]
This got me some of the way, but now I need to camel case the keys:

[
  // Test from Jolt Issue 98 : Question one from andrewkcarter
  // Summary : Bucket data from an Array, based on a leaf level value
  {
    "operation": "shift",
    "spec": {
      "Addresses": {
        // The "*" matches each Map pair of "type" and "data".
        // We then write the pair to a top level array whos name is the "type"
        // The "[]" means always write to an array, even when there is only one
        //  item written.
        "*": "[]"
      }
    }
  }


]

**Comment by eklinger** [comment]
Sorry that key should be STAR before the bracket

**Comment by milosimpson** [comment]
This does what you want 
```
[
  {
    "operation": "shift",
    "spec": {
      "Addresses": {
        "*": { // array index
          // match the AddressLine* keys
          "AddressLine*": "[&1].addressLine&(0,1)",
          // catch and pass thru all the rest
          "*": "[&1].&"
        }
      }
    }
  }
]
```

**Comment by eklinger** [comment]
Thank you but what about lower casing the remaining fields like city and
state and country? Will this also move the array of objects to the root of
the json output?
Thanks
Evan

**Comment by milosimpson** [comment]
You will need to just explicitly match each one (City -> city, etc).

```
[
  {
    "operation": "shift",
    "spec": {
      "Addresses": {
        "*": { // array index
          // match the AddressLine* keys
          // see http://jolt-demo.appspot.com/#prefixSoupToBuckets for explaination of "&(0,1)"
          "AddressLine*": "[&1].addressLine&(0,1)",
          // catch and pass thru all the rest
          "City": "[&1].city",
          "State": "[&1].state",
          "Country": "[&1].country",
          "ZipCode": "[&1].zipcode"
        }
      }
    }
  }
]
```

**Comment by eklinger** [comment]
Thank you that works perfectly!

**Comment by prasad0509** [comment]
Hi Milo Simpson,

Need your help to arrive at the JOLT spec to transform below. Kindly help.

INPUT
-------
{
	"empId": "123",
	"empName": "John",
	"addressList" : [
		{
			"streetName": "Wells Street",
			"city": "Chicago"
		},
		{
			"streetName": "Adams Street",
			"city": "Edison"
		}		
	]
}

OUTPUT
----------
{
    "metaDataList":[
		{
			"empId": "123",
	                "empName": "John",
			"streetName": "Wells Street",
			"city": "Chicago"
		},
		{
			"empId": "123",
	                "empName": "John",
			"streetName": "Adams Street",
			"city": "Edison"
		}
    ]
}

Thank you very much.

Regards,
Sai

**Comment by shureddy** [comment]
Hi @prasad0509 
use the below jolt will give you the desired output.
```
[
  {
    "operation": "shift",
    "spec": {
      "addressList": {
        "*": {
          "@(2,empId)": "metaDataList[&1].empId",
          "@(3,empName)": "metaDataList[&1].empName",
          "streetName": "metaDataList[&1].streetName",
          "city": "metaDataList[&1].city"
        }
      }
    }
  }
  ]
```
input:- 
```
{
  "empId": "123",
  "empName": "John",
  "addressList": [
    {
      "streetName": "Wells Street",
      "city": "Chicago"
    },
    {
      "streetName": "Adams Street",
      "city": "Edison"
    }
  ]
}
```
output:- 
```
{
  "metaDataList" : [ {
    "empId" : "123",
    "empName" : "John",
    "streetName" : "Wells Street",
    "city" : "Chicago"
  }, {
    "empId" : "123",
    "empName" : "John",
    "streetName" : "Adams Street",
    "city" : "Edison"
  } ]
}
```

**Comment by prasad0509** [comment]
Thank you
