### ISSUE TITLE
How to do the array to array shift

### ISSUE THREAD

**Issue by JeffSG** [bazaarvoice/jolt#206]
hi there,

Could anyone help to show me how to do an array to array shift?
For example, the input Json is
```
{
  "students": [
    {"id":"1", "score":"5"},
    {"id":"2", "score":null}
  ]
}
```
And the expected output Json is
```
{
  "level1": {
    "level2": [
      {"number":"1", "score":"5"},
      {"number":"2", "score":null}
    ]
  }
}
```
How to write the shiftr spec?

Furthermore, is it possible to output only array element of which "score" is not null?

Thanks in advance.

Regards,
Jeff

**Comment by milosimpson** [comment]
You have to do two shifts. 

First one, passes thru only the "students" with a non-null score.   The second one, then does the "id" -> "number" transform.

```
[
  {
    "operation": "shift",
    "spec": {
      "students": {
        "*": {
          "score": {
            "null": null,
            "*": {
              "@(2)": "level1.level2[]"
            }
          }
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "level1": {
        "level2": {
          "*": {
            "id": "level1.level2[&1].number",
            "score": "level1.level2[&1].score"
          }
        }
      }
    }
  }
]

```

**Comment by JeffSG** [comment]
hi milosimson, thanks for the reply.
About the first "filter" shift, still have one question.
This time the input is 
{
	"SolarSystem": {
		"Planet": [
			{
				"Satellite": {
					"PhysicalData": {
						"pd1": "pdv1",
						"pd2": "pdv2"
					},
					"ChemicalData": {
						"cd1": "cdv1",
						"cd2": "cdv2"
					}
				},
				"Name": "Earth"
			},
			{
				"Name": "Mercury",
				"Satellite": null
			}
		]
	}
}

And the expected output is 
[ {
  "Satellite" : {
    "PhysicalData" : {
      "pd1" : "pdv1",
      "pd2" : "pdv2"
    },
    "ChemicalData" : {
      "cd1" : "cdv1",
      "cd2" : "cdv2"
    }
  },
  "Name" : "Earth"
}]

Say, only keep the array element with non-null "Satellite"
I wrote the below spec
[
  {
    "operation": "shift",
    "spec": {
      "*": {
        "Planet": {
          "*": {
            "Satellite": {
              "null": null,
              "*": {
                "@(2)": "[]"
              }
            }
          }
        }
      }
    }
  }
]

The filter works. However, I got below output with duplicated elements (The repeating number is the key number under satellite). 
[ {
  "Satellite" : {
    "PhysicalData" : {
      "pd1" : "pdv1",
      "pd2" : "pdv2"
    },
    "ChemicalData" : {
      "cd1" : "cdv1",
      "cd2" : "cdv2"
    }
  },
  "Name" : "Earth"
}, {
  "Satellite" : {
    "PhysicalData" : {
      "pd1" : "pdv1",
      "pd2" : "pdv2"
    },
    "ChemicalData" : {
      "cd1" : "cdv1",
      "cd2" : "cdv2"
    }
  },
  "Name" : "Earth"
} ]

Could you please help point out what the issue is in my spec?
Thank you.

**Comment by milosimpson** [comment]
Huh, looks like you found a legit bug.   Usually, the filtering for "null" thing is either a null or a String, not a Map like Satellite.

**Comment by milosimpson** [comment]
Actually, no.  Its working as intended.   The problem is that when Satellite is not null, the "*" logic recurses down into the Satellite object, which has two entries "PhysicalData" and "ChemicalData" each of which trigger a copy.

The fix to change the first spec from looking for a "null", to looking for a Satellite that has a sub-object, like "PhysicalData".

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "Planet": {
        "*": {
          "Satellite": {
            "PhysicalData": {
              // @2 means look up the tree three levels (0, 1, 2), grab what is there (the whole planet object)
              // and then use that as the data to write to "PlanetsWithMoons"
              "@2": "PlanetsWithMoons"
            }
          }
        }
      }
    }
  }
]
```

**Comment by JeffSG** [comment]
Thank you very much Milo. It works now. Fantastic tool :)
