### ISSUE TITLE
SimpleTraversalTest.getTests / Auto expand array test - appears flawed

### ISSUE THREAD

**Issue by EdHowe** [bazaarvoice/jolt#210]
The test, which basically looks like this, will result in "null" being printed, as expected.
```
        SimpleTraversal<Object> simpleTraversal = SimpleTraversal.newTraversal( "a.[].b" );
        Object input = JsonUtils.jsonToMap( "{ \"a\" : [ { \"b\" : null } ] }" );
        Optional<Object> result = simpleTraversal.get(input);
        System.out.println(result.get());
```

However, *regardless* of the value of "b", it will print null.  For example,
```
        SimpleTraversal<Object> simpleTraversal = SimpleTraversal.newTraversal( "a.[].b" );
        Object input = JsonUtils.jsonToMap( "{ \"a\" : [ { \"b\" : \"c\" } ] }" );
        Optional<Object> result = simpleTraversal.get(input);
        System.out.println(result.get());
```
will print "null", but I would have thought it would have printed "c".  It seems like SimpleTraversal.get() always returns an Optional with a value of null whenever the path has "[]" in it.  Is this the intended behavior?

**Comment by milosimpson** [comment]
"Optional with a value of null whenever the path has "[]" in it. Is this the intended behavior?"  

Yes.   The Optional of null actually comes from the AutoExpandArrayTraversalStep.get method.

The "[]" as a Traversal step really only makes sense for writes / sets.
