### ISSUE TITLE
How can we replace Json value for a particular field with Jolt Spec

### ISSUE THREAD

**Issue by knaresh85** [bazaarvoice/jolt#211]
Hi,I am new to jolt and trying to replace the below shippingAddressState field with abbrevation as like o/p .Can you please provide the jolt specification for the same?
I/P:
```
{  
   "header":[  
      {  
         "lastName":"Saunders",
         "shippingAddressState":"TEXAS",
         "posDate":"05/19/2016 01:02:43 PM",
         "shippingAddressCity":"RICHARDSON"
       }
   ]
}
```
spec: Dynamically replace the shipping address state value with the abbrevation

O/P:
```
{  
   "header":[  
      {  
         "lastName":"Saunders",
         "shippingAddressState":"TX",
         "posDate":"05/19/2016 01:02:43 PM",
         "shippingAddressCity":"RICHARDSON"    
      }
   ]
}
```

**Comment by milosimpson** [comment]
Jolt is not good at dynamic modification of data.   It really is more about doing non-dynamic structural changes of a Json document.

That said, it can be done in Jolt Shiftr, it is just super ugly, and you should probably not use it.
```
[
  {
    "operation": "shift",
    "spec": {
      "header": {
        "*": {
          "lastName": "header[&1].lastName",
          "posDate": "header[&1].posDate",
          "shippingAddressCity": "header[&1].shippingAddressCity",
          "shippingAddressState": {
            "TEXAS": {
              "#TX": "header[&3].shippingAddressState"
            },
            "NEVADA": {
              "#NV": "header[&3].shippingAddressState"
            }
          }
        }
      }
    }
  }
]
```

**Comment by knaresh85** [comment]
Thank you very much for your help. Yes it works, as you said if i add all the 53 states then i spec would become too lengthy. I am finding some scenarios in my application which i need to create by using jolt spec.If i required help from you will post for the same.
