### ISSUE TITLE
Hi, I am new to Apache Camel and trying to create a jolt transformation i have a i/p, o/p and spec json files and how can i use it with the  route and how can i produce it as o/p in main class

### ISSUE THREAD

**Issue by knaresh85** [bazaarvoice/jolt#212]
Requirement is to read from input json and access the jolt spec json and put it in the o/p json file using apache camel.

**Comment by knaresh85** [comment]
In Mock test example i can see like the below code : public class JoltFirstSampleTest extends CamelTestSupport {
	
	

    @Test
    public void testFirstSampleJolt() throws Exception {
     
		
         getMockEndpoint("mock:result").expectedBodiesReceived(
       IOHelper.loadText(
                ResourceHelper.resolveMandatoryResourceAsInputStream(
                    context.getClassResolver() ,
                    "org/apache/camel/component/jolt/firstSample/output.json")
            ).trim() // Remove the last newline added by IOHelper.loadText()
        );
        
        sendBody("direct://start", 
                ResourceHelper.resolveMandatoryResourceAsInputStream(
                        context.getClassResolver(),
                        "org/apache/camel/component/jolt/firstSample/input.json"));
      
   
    }

    @Override
    protected RouteBuilder createRouteBuilder() throws Exception {
        return new RouteBuilder() {
            public void configure() {
                from("direct://start")
                    .to("jolt:org/apache/camel/component/jolt/firstSample/spec.json?inputType=JsonString&outputType=JsonString")
                    .to("mock:result");
            }
        };
    }
}

**Comment by milosimpson** [comment]
Sorry, I have no idea.   Someone else integrated Jolt with Apache Camel.   I have never used Camel.

**Comment by knaresh85** [comment]
It's Ok Simpson.. I walk through some examples and working on it. Thanks for your cooperation.
