### ISSUE TITLE
Changing value of array

### ISSUE THREAD

**Issue by vasdevdua** [bazaarvoice/jolt#213]
Hi,

I need to change value of array element, The input is:
```
{
	"classicData": {
		"CORE_DATA_BEAN": {
			"lastUpdated": "2016-05-31",
			"licassigned": [
				"Timekeeper_Employee",
				"Manager"
			],
			"prsnlastname": "abcd",
			"prsnfirstname": "abcd"
		}
	}
}

The desired output is
{
	"classicData": {
		"CORE_DATA_BEAN": {
			"lastUpdated": "2016-05-31",
			"licassigned": [
				"Timer1",
				"Manager"
			],
			"prsnlastname": "abcd",
			"prsnfirstname": "abcd"
		}
	}
}
```
Need to change the value of first element of "licassigned". How should i create the spec?

**Comment by milosimpson** [comment]
This can do it, but I don't recommend it, as Shift really isn't built for manipulating data (Timekeeper_Employee - > Timer1), it is really built to transforming the format of the data.

Spec 
```
[
  {
    "operation": "shift",
    "spec": {
      "classicData": {
        "CORE_DATA_BEAN": {
          "*": "classicData.CORE_DATA_BEAN.&",
          "licassigned": {
            "0": {
              "Timekeeper_Employee": {
                "#Timer1": "classicData.CORE_DATA_BEAN.licassigned[0]"
              }
            },
            "*": "classicData.CORE_DATA_BEAN.licassigned[&]"
          }
        }
      }
    }
  }
]
```

**Comment by vasdevdua** [comment]
Thanks a lot for the response. I have one more question. 

Is it possible we can customize the operators used in jolt, can we use any addition operator with Jolt?

**Comment by milosimpson** [comment]
Nope.   Jolt currently is about manipulating the format of the Json, not the data within it.
