### ISSUE TITLE
Removing Elements from array based on a condition

### ISSUE THREAD

**Issue by sandeepturvo** [bazaarvoice/jolt#214]
Hi,

I was looking into the functionalities for remove spec, and I have a requirement where I have to remove elements from json based on a condition

Example : 
**Input **
```
{
	"customer_orders": [
		{
			"customer_order_id": 5531,
			"customer": {
				"id": 16136
			}
		},
		{
			"customer_order_id": 5532,
			"customer": {
				"id": 16137
			}
		},
		{
			"customer_order_id": 5533,
			"customer": {
				"id": 16138
			}
		}
	]
}
```

**Expected Output :** 
```
{
	"customer_orders": [{
		"customer_order_id": 5531,
		"customer": {
			"id": 16136
		}
	}]
}
```

Scenario :  I would like to keep an element in the "customer_orders" array, only if "customer.id" matches with "16136", else remove it from the array.

**Comment by milosimpson** [comment]
Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "customer_orders": {
        "*": {
          "customer": {
            "id": {
              "16136": {
                "@3": "customer_orders[]"
              }
            }
          }
        }
      }
    }
  }
]
```

**Comment by sandeepturvo** [comment]
Thanks Simpson for your quick response. It worked 👍

**Comment by isidro-vasquez** [comment]
Hi, Quick question? How can I Do the opposite? I mean, if I only have only the id = 16136, I want to remove that and keep the others?

Expected Output :
{
    "customer_orders": [       
        {
            "customer_order_id": 5532,
            "customer": {
                "id": 16137
            }
        },
        {
            "customer_order_id": 5533,
            "customer": {
                "id": 16138
            }
        }
    ]
}

**Comment by milosimpson** [comment]
Yes.

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "customer_orders": {
        "*": {
          "customer": {
            "id": {
              // match 16136 but do nothing with it
              "16136": null,
              //everything else; pass thru
              "*": {
                "@3": "customer_orders[]"
              }
            }
          }
        }
      }
    }
  },
  {
    "operation": "default",
    "spec": {
      // probably want to apply a default that makes there be 
      //  a customer_orders array, on the off chance that nothing
      //  passes thru the shift. 
      "customer_orders": []
    }
  }
]
```

**Comment by isidro-vasquez** [comment]
Thanks dude you're the best, I started learning JOLT this week, Reading the documentation I thought this was a remove spec, Thanks

**Comment by yarabsyp** [comment]
{
"addressInfo": {
"legalAddress": {
"country": "US",
"attentionLinePrefix": "ATTN",
"attentionLineDetail": "detail",
"line1": "testmail@test.com",
"line2": "One Pershing Plz",
"line3": "Jersey City",
"city": "New Jersey",
"stateProvince": "AK"
},
"sameAsLegalAddress": [
"Y"
],
"mailingAddress": {
"country": "AL",
"attentionLinePrefix": "sdc",
"attentionLineDetail": "fd",
"line1": "",
"line2": "",
"line3": "",
"city": "",
"stateProvince": ""
},
"additionalAddress": []
}
}

if sameAsLegalAddress is Y then copy the legalAddress to mailingAddress..

outPut :
{
"addressInfo": {
"legalAddress": {
"country": "US",
"attentionLinePrefix": "ATTN",
"attentionLineDetail": "detail",
"line1": "testmail@test.com",
"line2": "One Pershing Plz",
"line3": "Jersey City",
"city": "New Jersey",
"stateProvince": "AK"
},
"sameAsLegalAddress": [
"Y"
],
"mailingAddress": {
"country": "US",
"attentionLinePrefix": "ATTN",
"attentionLineDetail": "detail",
"line1": "testmail@test.com",
"line2": "One Pershing Plz",
"line3": "Jersey City",
"city": "New Jersey",
"stateProvince": "AK"
},
"additionalAddress": []
}
}

what we tried here we using this spec

[
{
"operation": "shift",
"spec": {
"addressInfo": {
"sameAsLegalAddress": {
"": "&2.legalAddress.&1"
},
"": "&1.&"
}
}
},
{
"operation": "shift",
"spec": {
"addressInfo": {
"legalAddress": {
"sameAsLegalAddress": {
"Y": {
"@2": ["&4.legalAddress", "&4.mailingAddress"]
},
"": {
"@2": "&4.&3"
}
}
},
"*": "&1.&"
}
}
}

]

getting result is below .. plz help us to resovle this issue

{
"addressInfo" : {
"legalAddress" : {
"aType" : "2",
"country" : "US",
"attentionLinePrefix" : "ATTN",
"attentionLineDetail" : "detail",
"line1" : "testmail@test.com",
"line2" : "One Pershing Plz",
"line3" : "Jersey City",
"city" : "New Jersey",
"stateProvince" : "AK",
"sameAsLegalAddress" : "Y"
},
"mailingAddress" : [ {
"aType" : "2",
"country" : "US",
"attentionLinePrefix" : "ATTN",
"attentionLineDetail" : "detail",
"line1" : "testmail@test.com",
"line2" : "One Pershing Plz",
"line3" : "Jersey City",
"city" : "New Jersey",
"stateProvince" : "AK",
"sameAsLegalAddress" : "Y"
}, {
"aType" : "Y",
"country" : "AL",
"attentionLinePrefix" : "sdc",
"attentionLineDetail" : "fd",
"line1" : "",
"line2" : "",
"line3" : "",
"city" : "",
"stateProvince" : ""
} ],
"additionalAddress" : [ ]
}
}

**Comment by vslala** [comment]
How do we walk the tree? 
Like how to start counting up?
Does it behave differently from inside the array as compared to inside the object?
I hope I'm making sense 😄

**Comment by JalliBhargavi** [comment]
Hii, can anyone tell me how to( ""airline": {
                "name": "Longhao Airlines",
                "iata": "GI",
                "icao": "LHA"
            }" )this particular remove this content from
" {
    "pagination": {
        "limit": 10,
        "offset": 0,
        "count": 10,
        "total": 420263
    },
    "data": [
        {
            "flight_date": "2024-05-23",
            "flight_status": "scheduled",
            "departure": {
                "airport": "Shenzhen",
                "timezone": "Asia/Shanghai",
                "iata": "SZX",
                "icao": "ZGSZ",
                "terminal": null,
                "gate": null,
                "delay": null,
                "scheduled": "2024-05-23T02:05:00+00:00",
                "estimated": "2024-05-23T02:05:00+00:00",
                "actual": null,
                "estimated_runway": null,
                "actual_runway": null
            },
            "arrival": {
                "airport": "Suvarnabhumi International",
                "timezone": "Asia/Bangkok",
                "iata": "BKK",
                "icao": "VTBS",
                "terminal": null,
                "gate": null,
                "baggage": null,
                "delay": null,
                "scheduled": "2024-05-23T03:40:00+00:00",
                "estimated": "2024-05-23T03:40:00+00:00",
                "actual": null,
                "estimated_runway": null,
                "actual_runway": null
            },
            "airline": {
                "name": "Longhao Airlines",
                "iata": "GI",
                "icao": "LHA"
            },
            "flight": {
                "number": "4351",
                "iata": "GI4351",
                "icao": "LHA4351",
                "codeshared": null
            },
            "aircraft": null,
            "live": null
        },
        {
            "flight_date": "2024-05-23",
            "flight_status": "scheduled",
            "departure": {
                "airport": "Brisbane International",
                "timezone": "Australia/Brisbane",
                "iata": "BNE",
                "icao": "YBBN",
                "terminal": null,
                "gate": null,
                "delay": null,
                "scheduled": "2024-05-23T01:15:00+00:00",
                "estimated": "2024-05-23T01:15:00+00:00",
                "actual": null,
                "estimated_runway": null,
                "actual_runway": null
            },
            "arrival": {
                "airport": "Adelaide International Airport",
                "timezone": "Australia/Adelaide",
                "iata": "ADL",
                "icao": "YPAD",
                "terminal": null,
                "gate": null,
                "baggage": null,
                "delay": null,
                "scheduled": "2024-05-23T04:15:00+00:00",
                "estimated": "2024-05-23T04:15:00+00:00",
                "actual": null,
                "estimated_runway": null,
                "actual_runway": null
            },
            "airline": {
                "name": "Qantas",
                "iata": "QF",
                "icao": "QFA"
            },
            "flight": {
                "number": "7338",
                "iata": "QF7338",
                "icao": "QFA7338",
                "codeshared": null
            },
            "aircraft": null,
            "live": null
        },
        {
            "flight_date": "2024-05-23",
            "flight_status": "scheduled",
            "departure": {
                "airport": "Brisbane International",
                "timezone": "Australia/Brisbane",
                "iata": "BNE",
                "icao": "YBBN",
                "terminal": null,
                "gate": null,
                "delay": null,
                "scheduled": "2024-05-23T01:20:00+00:00",
                "estimated": "2024-05-23T01:20:00+00:00",
                "actual": null,
                "estimated_runway": null,
                "actual_runway": null
            },
            "arrival": {
                "airport": "Perth International",
                "timezone": "Australia/Perth",
                "iata": "PER",
                "icao": "YPPH",
                "terminal": null,
                "gate": null,
                "baggage": null,
                "delay": null,
                "scheduled": "2024-05-23T04:45:00+00:00",
                "estimated": "2024-05-23T04:45:00+00:00",
                "actual": null,
                "estimated_runway": null,
                "actual_runway": null
            },
            "airline": {
                "name": "Qantas",
                "iata": "QF",
                "icao": "QFA"
            },
            "flight": {
                "number": "7396",
                "iata": "QF7396",
                "icao": "QFA7396",
                "codeshared": null
            },
            "aircraft": null,
            "live": null
        },
        {
            "flight_date": "2024-05-23",
            "flight_status": "scheduled",
            "departure": {
                "airport": "Brisbane International",
                "timezone": "Australia/Brisbane",
                "iata": "BNE",
                "icao": "YBBN",
                "terminal": null,
                "gate": null,
                "delay": null,
                "scheduled": "2024-05-23T01:25:00+00:00",
                "estimated": "2024-05-23T01:25:00+00:00",
                "actual": null,
                "estimated_runway": null,
                "actual_runway": null
            },
            "arrival": {
                "airport": "Adelaide International Airport",
                "timezone": "Australia/Adelaide",
                "iata": "ADL",
                "icao": "YPAD",
                "terminal": null,
                "gate": null,
                "baggage": null,
                "delay": null,
                "scheduled": "2024-05-23T03:55:00+00:00",
                "estimated": "2024-05-23T03:55:00+00:00",
                "actual": null,
                "estimated_runway": null,
                "actual_runway": null
            },
            "airline": {
                "name": "Qantas",
                "iata": "QF",
                "icao": "QFA"
            },
            "flight": {
                "number": "7483",
                "iata": "QF7483",
                "icao": "QFA7483",
                "codeshared": null
            },
            "aircraft": null,
            "live": null
        },
        {
            "flight_date": "2024-05-23",
            "flight_status": "scheduled",
            "departure": {
                "airport": "Brisbane International",
                "timezone": "Australia/Brisbane",
                "iata": "BNE",
                "icao": "YBBN",
                "terminal": "I",
                "gate": null,
                "delay": null,
                "scheduled": "2024-05-23T01:55:00+00:00",
                "estimated": "2024-05-23T01:55:00+00:00",
                "actual": null,
                "estimated_runway": null,
                "actual_runway": null
            },
            "arrival": {
                "airport": "Dubai",
                "timezone": "Asia/Dubai",
                "iata": "DXB",
                "icao": "OMDB",
                "terminal": "3",
                "gate": null,
                "baggage": null,
                "delay": null,
                "scheduled": "2024-05-23T10:05:00+00:00",
                "estimated": "2024-05-23T10:05:00+00:00",
                "actual": null,
                "estimated_runway": null,
                "actual_runway": null
            },
            "airline": {
                "name": "Emirates",
                "iata": "EK",
                "icao": "UAE"
            },
            "flight": {
                "number": "431",
                "iata": "EK431",
                "icao": "UAE431",
                "codeshared": null
            },
            "aircraft": null,
            "live": null
        },
        {
            "flight_date": "2024-05-23",
            "flight_status": "scheduled",
            "departure": {
                "airport": "Brisbane International",
                "timezone": "Australia/Brisbane",
                "iata": "BNE",
                "icao": "YBBN",
                "terminal": null,
                "gate": null,
                "delay": null,
                "scheduled": "2024-05-23T01:55:00+00:00",
                "estimated": "2024-05-23T01:55:00+00:00",
                "actual": null,
                "estimated_runway": null,
                "actual_runway": null
            },
            "arrival": {
                "airport": "Adelaide International Airport",
                "timezone": "Australia/Adelaide",
                "iata": "ADL",
                "icao": "YPAD",
                "terminal": null,
                "gate": null,
                "baggage": null,
                "delay": null,
                "scheduled": "2024-05-23T04:19:00+00:00",
                "estimated": "2024-05-23T04:19:00+00:00",
                "actual": null,
                "estimated_runway": null,
                "actual_runway": null
            },
            "airline": {
                "name": "National Jet Express",
                "iata": "NC",
                "icao": "JTE"
            },
            "flight": {
                "number": "7483",
                "iata": "NC7483",
                "icao": "JTE7483",
                "codeshared": null
            },
            "aircraft": null,
            "live": null
        },
        {
            "flight_date": "2024-05-23",
            "flight_status": "scheduled",
            "departure": {
                "airport": "Soekarno-Hatta International",
                "timezone": "Asia/Jakarta",
                "iata": "CGK",
                "icao": "WIII",
                "terminal": "3",
                "gate": null,
                "delay": null,
                "scheduled": "2024-05-23T00:55:00+00:00",
                "estimated": "2024-05-23T00:55:00+00:00",
                "actual": null,
                "estimated_runway": null,
                "actual_runway": null
            },
            "arrival": {
                "airport": "Doha International",
                "timezone": "Asia/Qatar",
                "iata": "DOH",
                "icao": "OTHH",
                "terminal": null,
                "gate": null,
                "baggage": "4",
                "delay": null,
                "scheduled": "2024-05-23T05:25:00+00:00",
                "estimated": "2024-05-23T05:25:00+00:00",
                "actual": null,
                "estimated_runway": null,
                "actual_runway": null
            },
            "airline": {
                "name": "JetBlue Airways",
                "iata": "B6",
                "icao": "JBU"
            },
            "flight": {
                "number": "6534",
                "iata": "B66534",
                "icao": "JBU6534",
                "codeshared": {
                    "airline_name": "qatar airways",
                    "airline_iata": "qr",
                    "airline_icao": "qtr",
                    "flight_number": "955",
                    "flight_iata": "qr955",
                    "flight_icao": "qtr955"
                }
            },
            "aircraft": null,
            "live": null
        },
        {
            "flight_date": "2024-05-23",
            "flight_status": "scheduled",
            "departure": {
                "airport": "Melbourne - Tullamarine Airport",
                "timezone": "Australia/Melbourne",
                "iata": "MEL",
                "icao": "YMML",
                "terminal": null,
                "gate": null,
                "delay": null,
                "scheduled": "2024-05-23T02:50:00+00:00",
                "estimated": "2024-05-23T02:50:00+00:00",
                "actual": null,
                "estimated_runway": null,
                "actual_runway": null
            },
            "arrival": {
                "airport": "Adelaide International Airport",
                "timezone": "Australia/Adelaide",
                "iata": "ADL",
                "icao": "YPAD",
                "terminal": null,
                "gate": null,
                "baggage": null,
                "delay": null,
                "scheduled": "2024-05-23T03:50:00+00:00",
                "estimated": "2024-05-23T03:50:00+00:00",
                "actual": null,
                "estimated_runway": null,
                "actual_runway": null
            },
            "airline": {
                "name": "Qantas",
                "iata": "QF",
                "icao": "QFA"
            },
            "flight": {
                "number": "7458",
                "iata": "QF7458",
                "icao": "QFA7458",
                "codeshared": null
            },
            "aircraft": null,
            "live": null
        },
        {
            "flight_date": "2024-05-23",
            "flight_status": "scheduled",
            "departure": {
                "airport": "Da Nang",
                "timezone": "Asia/Ho_Chi_Minh",
                "iata": "DAD",
                "icao": "VVDN",
                "terminal": null,
                "gate": "6-8",
                "delay": null,
                "scheduled": "2024-05-23T01:00:00+00:00",
                "estimated": "2024-05-23T01:00:00+00:00",
                "actual": null,
                "estimated_runway": null,
                "actual_runway": null
            },
            "arrival": {
                "airport": "Gimhae",
                "timezone": "Asia/Seoul",
                "iata": "PUS",
                "icao": "RKPK",
                "terminal": "I",
                "gate": null,
                "baggage": null,
                "delay": null,
                "scheduled": "2024-05-23T07:30:00+00:00",
                "estimated": "2024-05-23T07:30:00+00:00",
                "actual": null,
                "estimated_runway": null,
                "actual_runway": null
            },
            "airline": {
                "name": "Air Busan",
                "iata": "BX",
                "icao": "ABL"
            },
            "flight": {
                "number": "774",
                "iata": "BX774",
                "icao": "ABL774",
                "codeshared": null
            },
            "aircraft": null,
            "live": null
        },
        {
            "flight_date": "2024-05-23",
            "flight_status": "scheduled",
            "departure": {
                "airport": "Da Nang",
                "timezone": "Asia/Ho_Chi_Minh",
                "iata": "DAD",
                "icao": "VVDN",
                "terminal": null,
                "gate": "6-8",
                "delay": null,
                "scheduled": "2024-05-23T01:00:00+00:00",
                "estimated": "2024-05-23T01:00:00+00:00",
                "actual": null,
                "estimated_runway": null,
                "actual_runway": null
            },
            "arrival": {
                "airport": "Gimhae",
                "timezone": "Asia/Seoul",
                "iata": "PUS",
                "icao": "RKPK",
                "terminal": "I",
                "gate": null,
                "baggage": null,
                "delay": null,
                "scheduled": "2024-05-23T07:30:00+00:00",
                "estimated": "2024-05-23T07:30:00+00:00",
                "actual": null,
                "estimated_runway": null,
                "actual_runway": null
            },
            "airline": {
                "name": "Asiana Airlines",
                "iata": "OZ",
                "icao": "AAR"
            },
            "flight": {
                "number": "9754",
                "iata": "OZ9754",
                "icao": "AAR9754",
                "codeshared": {
                    "airline_name": "air busan",
                    "airline_iata": "bx",
                    "airline_icao": "abl",
                    "flight_number": "774",
                    "flight_iata": "bx774",
                    "flight_icao": "abl774"
                }
            },
            "aircraft": null,
            "live": null
        }
    ]
}"
