### ISSUE TITLE
Possibility of removing all elements except one under a node

### ISSUE THREAD

**Issue by ratheeshpkumar** [bazaarvoice/jolt#216]
I would like to get help in writing a 'remove spec' to remove all elements except one under a particular node keeping all elements under all other nodes as is. 

In the below example, I want to remove all elements except primaryinfo under consumerinfo.personaldetails. I want to keep all the elements under all other nodes.
The names of all elements that I want to remove are not known. tThats why i want to define some thing like 'remove-everything-except'.

Example :
Input:
```
{
	"supplierid": "123",
	"status": "completed",
	"consumerinfo": {
		"personaldetails": {
			"primaryinfo": {
				"firstname": "abcd",
				"lastname": "defg"
			},
			"address": {
				"housenumber": "26728",
				"street": "street name"
			},
			"additionalinfo": "extrainformation"
		},
		"employmentinfo": {
			"name": "employer"
		}
	}
}
```
Expected output:
```
{
	"supplierid": "123",
	"status": "completed",
	"consumerinfo": {
		"personaldetails": {
			"primaryinfo": {
				"firstname": "abcd",
				"lastname": "defg"
			}
		},
		"employmentinfo": {
			"name": "employer"
		}
	}
}
```

**Comment by milosimpson** [comment]
Remover does not have that capability.

You can get kind of the same thing with Shiftr, it just is a bit more verbose, i.e. enumerate all the things you want to pass thru.

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "*": "&",
      "consumerinfo": {
        "personaldetails": {
          "primaryinfo": "consumerinfo.personaldetails.primaryinfo"
        },
        "*": "consumerinfo.&"
      }
    }
  }
]
```

**Comment by ratheeshpkumar** [comment]
:This is working fine. Thank you.
