### ISSUE TITLE
Jolt Transformation

### ISSUE THREAD

**Issue by Venkatesha7533** [bazaarvoice/jolt#223]
hello Team ,
i m trying to convert multiple arrays in side the another multiple arrays. i got error sometimes and null sometimes while converting in your online tool. please help me to solve this .
below is my Input Json
```
[
	{
		"list1": [
			{
				"id": "CPP1600000009846",
				"list2": [
					{
						"amount": {
							"formattedPrimeAmount": "0.00",
							"primeAmount": "0.00"
						},
						"code": "CONAMP"
					},
					{
						"amount": {
							"formattedPrimeAmount": "0.00",
							"primeAmount": "0.00"
						},
						"code": "PCCPRI"
					},
					{
						"amount": {
							"formattedPrimeAmount": "0.00",
							"primeAmount": "0.00"
						},
						"code": "PCCPCI"
					},
					{
						"amount": {
							"formattedPrimeAmount": "0.00",
							"primeAmount": "0.00"
						},
						"code": "PCCPII"
					}
				]
			},
			{
				"id": "CPP1600000009846",
				"list2": [
					{
						"amount": {
							"formattedPrimeAmount": "0.00",
							"primeAmount": "0.00"
						},
						"code": "CONEIT"
					},
					{
						"amount": {
							"formattedPrimeAmount": "0.00",
							"primeAmount": "0.00"
						},
						"code": "CONCRT"
					},
					{
						"amount": {
							"formattedPrimeAmount": "0.00",
							"primeAmount": "0.00"
						},
						"code": "CONNCT"
					}
				]
			}
		]
	}
]
```

i need it Dynamically instead of transforming using Index.

**Comment by milosimpson** [comment]
What are output are you looking for.

General strategy I would suggest is : flatten all the items into a single list, then iterate over the lists doing what ever processing you need to do.

This could be accomplished bya series of 3 shift operations.
1) Push things like ""id": "CPP1600000009846"" down into each item of nested list2 arrays.
2) Grab all the leaf level nodes and write them to a single big list
3) Process each items in the flattened big list, given that it has all the info it needs (aka you pushed Ids down in step 1).
