### ISSUE TITLE
Conditional Static Values

### ISSUE THREAD

**Issue by mhubbard** [bazaarvoice/jolt#224]
I need to add static/hardcoded values to my output based on my input, it seems like there is no conditions in defaultr and no static values in shiftr. For example if I have a section of input

```json
{
    "Order": {
        "Purpose": "New Business"
    }
}
```

Where "Purpose" can be "New Business", "Renewal", or null. And would like to transform that to numbers of significance to my system, for example; if new business then 560, if renewal then 204, otherwise 1. So I would like an output of.

```json
{
    "Order": {
        "purposeTypeId": 560
    }
}
```

Is this possible currently?

**Comment by milosimpson** [comment]
Well pull 222 merges, you will have to approaches.

Basically you effectively have a "map" of String to integer.  
New Business ->  560
Renewal -> 204

You can either ninja that into the input json as a Map, and then remove it later, or pass that Map as part of the "context", ala  https://github.com/bazaarvoice/jolt/blob/master/jolt-core/src/main/java/com/bazaarvoice/jolt/Chainr.java#L174

Thus your spec would be something like 
```
{
    "Order" : { 
        "purposeTypeId" : "^bizMapping.@0"
    }
}

where "^" means lookup from the context.
with Context
{ 
   "bizMapping: { 
      "New Business" : 560,
      "Renewal" :  204
   }
}
```

**Comment by mhubbard** [comment]
Perfect! The context solution should fit quite nicely with what I'm trying to do.

With your example spec, which operation would that be? Defaultr?

Also thank you for your very timely responses.

**Comment by milosimpson** [comment]
overwrite-beta, default-beta, or define-beta   they are all the same code and spec file, it is just that the different operations vary its behavior wrt overwriting data in the original document.

overwrite will stomp whatever is there
default will only stomp if the thing you want to write is null or the key/arrayindex does not exist
define will only work if the key/arrayindex does not exist

**Comment by hauseja3** [comment]
@mhubbard @milosimpson would you please show me the desired syntax for this mapping? Just simple example

**Comment by hauseja3** [comment]
@milosimpson is something similar possible in the last release? 

I need to map integer -> integer values.

**Comment by milosimpson** [comment]
@hauseja3 example syntax : see this unit test and his friends https://github.com/bazaarvoice/jolt/blob/c4c4942580abcd81522ea97f8b7c2a927f2ffa86/jolt-core/src/test/resources/json/templatr/simpleLookup.json

"is something similar possible in the last release".  No, this next release will be the first to feature a transform specifically written for modifying the json "data", instead of "reformatting" it (but generally leaving the "data" alone).
