### ISSUE TITLE
Need to Understand the Scenarios Support by JOLT Spec

### ISSUE THREAD

**Issue by knaresh85** [bazaarvoice/jolt#225]
Hi, I have a couple of questions on Jolt Spec,Could you please clarify me on the below Queries
1.Is Jolt can support Sequence Number Generation dynamically ?
```
Ex : <sequence> 1 </sequence>
```
2. Is Jolt can provide the reference i.e, parent and child. The parent attribute is in Header and the child attribute is in the below Json dynamically
To get the OrderType Details from the child object with referring the Parent attribute
Ex: 
```
{ 
"customerOrderNumber":"211221445722", 
   "orderType":"CREATE", 
   "Address": null, 
   "createdDate": null, 
{ },
{ },
{ },
Customer{
 "orderType":"CREATE", 
"orderId": 12,
"order name":CustomDet",
"OrderDesc":"Testing Simply"
} 
}
```

Could you please let me know the same.
Thanks in Advance.

**Comment by milosimpson** [comment]
A) Sequence Numbers, no
B) I don't understand the question.

**Comment by knaresh85** [comment]
Ok, thank you for your very timely responses.
for B i i will create a new issue with an clear example.
Thank you once again!
