### ISSUE TITLE
How can JOLT support to order the attributes from the two objects ?

### ISSUE THREAD

**Issue by knaresh85** [bazaarvoice/jolt#226]
Hi,
I have a doubt that how can i display an order of elements with the jolt spec as show in the sample i/p json.

```
{
	"Telephone": {
		"value": {
			"lob_type": "Telephone",
			"order_id": "7578050141"
		},
		"lineOfServiceGroups": {
			"A": {
				"status": "complete",
				"Items": [
					"1",
					"2"
				],
				"extraAttributes": {}
			},
			"B": {
				"status": "complete",
				"Items": [
					"3",
					"4"
				],
				"extraAttributes": {}
			}
		},
		"itemInf": {
			"1": {
				"itemType": "test",
				"itemId": "1",
				"Id": "7650320",
				"productId": "prod8330924"
			},
			"2": {
				"itemType": "rest",
				"itemId": "2",
				"Id": "7650321",
				"productId": "prod8330954"
			},
			"3": {
				"itemType": "best",
				"itemId": "3",
				"Id": "7650310",
				"productId": "prod833094"
			},
			"4": {
				"itemType": "dust",
				"itemId": "4",
				"Id": "7650510",
				"productId": "prod837094"
			}
		}
	},
	"Telegraph": {
		"value": {
			"lob_type": "Telegraph"
		},
		"lineOfServiceGroups": {
			"C": {
				"status": "complete",
				"Items": [
					"5"
				],
				"extraAttributes": {}
			},
			"itemInf": {
				"5": {
					"itemType": "device",
					"Id": " 3456244",
					"productId": "prod8210241"
				}
			}
		}
	}
}
```
				
In the above I/P Json i have Telephone and Telegraph object and  A,B & C lineOfServiceGroups are under the Objects, and 1,2,3,4 & 5 itemInf are present .I need to get the O/P as like below
O/P :
```
{  
   "groups":{  
      "groups":[  
         {  
            "loSGCharacteristics":{  
               "loSGReferenceId":"A",
               "loSGStatus":"complete"
            },
            "loSGCharacteristics":{  
               "loSGReferenceId":"B",
               "loSGStatus":"complete"
            },
            "loSGCharacteristics":{  
               "loSGReferenceId":"C",
               "loSGStatus":"complete"
            }
         ]
      }
   },
   "lineItems":[  
      {  
         "Id":"1",
         "PaymentArrangement":"POSTPAID"
      },
      {  
         "Id":"2",
         "PaymentArrangement":"POSTPAID"
      },
      {  
         "Id":"3",
         "PaymentArrangement":"POSTPAID"
      },
      {  
         "Id":"4",
         "PaymentArrangement":"POSTPAID"
      },
      {  
         "Id":"5",
         "PaymentArrangement":"POSTPAID"
      }
   ]
}
```
Could you please provide me a sample Jolt spec to place the elements in the order.I need to display all the lineOfServiceGroups inside the Groups and all the ID's inside the lineItems array. Please help me out to create the order spec.
Thanks in Advance.

**Comment by milosimpson** [comment]
Spec 
```
[
  {
    "operation": "shift",
    "spec": {
      "*": { // Telephone , Telegraph
        "lineOfServiceGroups": {
          "*": { // A,B,C
            "status": "lineOfServiceGroups[].&1"
          }
        },
        "itemInf": {
          "*": { // 1,2,3 
            "itemId": "lineItems[].Id"
          }
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "lineOfServiceGroups": {
        "*": { // index
          "*": { // A,B,C
            "@": "groups.group[&2].completeloSGCharacteristics.loSGStatus",
            "$": "groups.group[&2].completeloSGCharacteristics.loSGReferenceId"
          }
        }
      },
      "lineItems": "lineItems" // pass thru
    }
  },
  {
    "operation": "default",
    "spec": {
      "lineItems[]": {
        "*": {
          "PaymentArrangement": "POSTPAID"
        }
      }
    }
  }
]
```

Your input data was not valid Json, so I guessed on what it is supposed to be.

**Comment by surendrakongurootu** [comment]
Hi, 

Thanks for the spec.
If as well need to include any other elements e.g. Items under lineOfServiceGroups  into target JSON, will you pl suggest what changes to be done in spec.

"groups" : {
    "groups" : [ {
      "Type" : "LINE_OF_SERVICE",
      "additionalDetails" : [ ],
      "channelCode" : "estore",
      "groupCharacteristics" : {
        "loSGCharacteristics" : {
          "loSGReferenceId" : "dtv",
          "loSGStatus" : "complete" 
        }
      },
      "id" : "GROUP_01",
      "Items" : [ "1", "2"],
      "price" : null,
      "promotionRefs" : null,
      "sequence" : 1
    }

**Comment by milosimpson** [comment]
Need specific input and output.

**Comment by surendrakongurootu** [comment]
Hi, I am referring to the same input pasted at the start of this post. At present, spec you shared will help in getting the title e.g. A, B and "status" values into output JSON. Please suggest on what need to be updated in spec to get "items" and any thing under  "extraAttributes" as well into output JSON.

Thanks in advance.

input:

       "lineOfServiceGroups": {
            "A": {
                "status": "complete",
                "Items": [
                    "1",
                    "2"
                ],
                "extraAttributes": {
                     "extraData" : "123"
                   }
            },
            "B": {
                "status": "complete",
                "Items": [
                    "3",
                    "4"
                ],
                "extraAttributes": {
                    "extraData" : "567"
                }
            }
        }

output:

"groups" : {
"groups" : [ {
"Type" : "LINE_OF_SERVICE",
"extra" : "123",
"groupCharacteristics" : {
"loSGCharacteristics" : {
"loSGReferenceId" : "A",
"loSGStatus" : "complete" 
}
},
"id" : "GROUP_01",
"Items" : [ "1", "2"]
},
{
"Type" : "LINE_OF_SERVICE",
"extra" : "567",  
"groupCharacteristics" : {
"loSGCharacteristics" : {
"loSGReferenceId" : "B",
"loSGStatus" : "complete" 
}
},
"id" : "GROUP_02",
"Items" : [ "3", "4"]
}]}

**Comment by milosimpson** [comment]
I can not help you.
