### ISSUE TITLE
String functions in Shiftr

### ISSUE THREAD

**Issue by mhubbard** [bazaarvoice/jolt#229]
Hello,

I was wondering if the new functions, specifically concat is available during a shift operation. As an example of what I'm trying to do I have an input with an array of object with first and last names, 

```json
[
    {
        "FirstName": "Ted",
        "LastName": "Johnson"
    },
    {
        "FirstName": "John",
        "LastName": "Doe"
    }
]
```

Desired output:

```json
[
    {
        "FullName": "Ted Johnson"
    },
    {
        "FullName": "John Doe"
    }
]
```

I was hoping I could do something like this

```json
[
    {
        "operation": "shift",
        "spec": {
            "*": {
                "=concat(FirstName,' ',LastName)": "[&1].FullName"
            }
        }
    }
]
```

Is my syntax wrong or is this just not possible? I suppose I could shift the first and last names, then do a define or overwrite operation followed by a remove to remove the first and last names.

**Comment by milosimpson** [comment]
Interesting syntax, not what we are shooting for right now.

"I could shift the first and last names, then do a define or overwrite operation followed by a remove to remove the first and last names."   Yep, that is one way to do it.

If you need to do a shift anyways, maybe to do the overwrite first, and then do the shift, and just not pass thru the FirstName, LastName fields.

**Comment by mhubbard** [comment]
Overwrite -> Shift is working for me and is much more elegant than the Shift -> Overwrite -> Remove that I thought I had to do.

Thank you for the help
