### ISSUE TITLE
Globally remove all given keys

### ISSUE THREAD

**Issue by dfparker2002** [bazaarvoice/jolt#238]
Goal: 
remove a key/value pair globally in data. Spec yields an invalid removr spec RHS. Should be an empty string or map (tested @ online demo)

Is global remove possible?

**DESIRED OUTPUT**
```
[
  {
    "isActive": false,
  },
  {
     "isActive": true,
 }
]
```
-----

**SPEC**
```
[{
"operation":"remove",
"spec": {
"*": {
"foo:created" : "*",
"bar:registered": "*"
}
}
}]
```

-----
**IN-DATA**
```
[
  {
    "foo:created": "2016-07-10T02:02:32 +10:00",
    "isActive": false,
    "bar:registered": "2015-06-27T08:16:25 +10:00"
  },
  {
    "foo:created": "2014-04-05T05:04:53 +10:00",
    "barregistered": "2016-01-19T08:15:55 +10:00"
     "isActive": true,
 }
]
```

**Comment by milosimpson** [comment]
Spec
```
[{
  "operation": "remove",
  "spec": {
    "*": {
      "foo*": "",
      "bar*": ""
    }
  }
}]
```

**Comment by dfparker2002** [comment]
Remove the key:colon - got it!

This does work at the top level but not for nested data - thank you.

Is there a similar technique for n-level nested data?

**Comment by milosimpson** [comment]
Removing something from "n-level nested data?"   No, not by a spec.   We have found a use for it tho, and have a Util method that does this.

https://github.com/bazaarvoice/jolt/blob/dcf544eb873159ef26003541731638a81e182797/jolt-core/src/main/java/com/bazaarvoice/jolt/utils/JoltUtils.java#L38

That said, do you need n-level or like 3 or 4 levels?

Spec that should work for 3 levels
```
[{
  "operation": "remove",
  "spec": {
    "*": {
      "foo*": "",
      "bar*": "",
      "*": {
        "foo*": "",
        "bar*": "",
        "*": {
          "foo*": "",
          "bar*": ""
        }
      }
    }
  }
}]
```

**Comment by milosimpson** [comment]
Also "Remove the key:colon - got it!"   no.  It was not the key:colon stuff on the Left hand side, it was the "*" on the Right hand side.

This spec works
```
[{
  "operation": "remove",
  "spec": {
    "*": {
      "foo:created": "",
      "bar*": ""
    }
  }
}]
```
