### ISSUE TITLE
Apply a mask to json

### ISSUE THREAD

**Issue by jbjornson** [bazaarvoice/jolt#239]
I have a use case where I want to apply a mask/filter to my json.  I want to keep the original structure intact but only keep some of the nodes.  I currently do this with a "remove" spec, but it would me much nicer to define what to include, rather than defining what should be removed.  

If this is already supported, could you please point me in the right direction?  If not, is this functionality that you would consider adding in the future?

**Comment by mhubbard** [comment]
The shift function will do what you need, traverse your input on the lefthand side, then specify the same path on the righthand.

Example input:
```
{
  "Order": {
    "ID": "12345",
    "Type": "Purchase",
    "Value": 1234,
    "foo": "bar"
  }
}
```

Example Spec:
```
[
  {
    "operation": "shift",
    "spec": {
      "Order": {
        "ID": "Order.ID",
        "Value": "Order.Value"
      }
    }
  }
]
```

Output:
```
{
  "Order": {
    "ID": "12345", 
    "Value": 1234
  }
}
```

**Comment by milosimpson** [comment]
Yeah, what mhubbard said.    

Thing to be aware of is that Remove operates on the input Map/List objects, whereas Shift makes a new Map and selectively copies stuff across.

**Comment by jbjornson** [comment]
Ok, thanks for the info.  I was hoping that there was a way that I didn't have to specify the full target path in the spec.  We have a pretty deep model including arrays and the syntax for that looks a bit cumbersome.  I guess I'll just have to play with it a bit more.

I have implemented my mask/filter with a "remove" transformation and I've been extremely impressed with the speed of jolt!  I'll give it a try with the shift and see if it's easier to understand.
