### ISSUE TITLE
Array to Array conversion using Shift 

### ISSUE THREAD

**Issue by bhupendrabjain** [bazaarvoice/jolt#248]
Hi ,

Given this as input
```
{
  "Materials": [
    {
      "Text": "hi",
      "MaterialId": 123
    },
    {
      "Text": "Bye",
      "MaterialId": 234
    }
  ]
}
```
Expected Output
```
{
  "childDoc": [
    {
      "Text": "hi",
      "MaterialId": 123
    },
    {
      "Text": "Bye",
      "MaterialId": 234
    }
  ]
}
```
This looks really simple but not able to warp my head around it ? Any help will be highly appreciated

**Comment by milosimpson** [comment]
Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "Materials": "childDoc"
    }
  }
]
```

**Comment by bhupendrabjain** [comment]
Sorry I didnt put the expected output right . I need the following as expected output 

{
  "childDoc": [
    {
      "MaterialText": "hi",
      "id": 123
    },
    {
      "MaterialText": "Bye",
      "id": 234
    }
  ]
}

**Comment by milosimpson** [comment]
Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "Materials": {
        "*": {
          "Text": "childDoc[&1].MaterialText",
          "MaterialId": "childDoc[&1].id"
        }
      }
    }
  }
]
```

**Comment by bhupendrabjain** [comment]
Thanks a lot . It worked . Is it possible to get the following output 

{
  "MaterialText":["hi","bye"],
  "childDoc": [
    {
      "id": 123
    },
    {
      "id": 234
    }
  ]
}

**Comment by milosimpson** [comment]
Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "Materials": {
        "*": {
          "Text": "MaterialText[]",
          "MaterialId": "childDoc[&1].id"
        }
      }
    }
  }
]
```

Also, when pasting in Json wrap with with ``` and ``` so that it shows nicely.

**Comment by bhupendrabjain** [comment]
Sure .. Will keep that in that and thanks a lot for the help .
