### ISSUE TITLE
Adding a new Field in array elements

### ISSUE THREAD

**Issue by sandeepturvo** [bazaarvoice/jolt#249]
Hi,

We were struggling to copy and add a new element  in case of array,

Example : 
Input : 
```
{
	"customer": [
		{
			"locations": [
				{
                                        "name" : "Location1",
					"id": 1234
				},
				{
                                        "name" : "Location2",
					"id": 4567
				}
			]
		}
	]
}
```

Expected Output : 
```
{
	"customer": [
		{
			"locations": [
				{
                                        "name" : "Location1",
					"id": 1234,
                                       "customId" : 1234,
				},
				{
                                        "name" : "Location2",
					"id": 4567,
                                        "customId" : 4567   
				}
			]
		}
	]
}
```

Here "customId" is a field which is a copy of "id" field in the array elements.
We Tried the following spec:

```
[
  {
    "operation": "shift",
    "spec": {
      "customer": {
        "*": {
          "locations": {
            "*": {
              "id": "customer[&1].id",
              "name": "customer[&1].name",
              "id": "customer[&1].customId"
            }
          }
        }
      }
    }
  }
]
```

But couldn't achieve it. 
We were expecting not to touch other fields in spec(as the input json will be a very huge file) and achieve the final output only adding the info about the "customId" field in the spec.

Any help is very much appreciated.

**Comment by mhubbard** [comment]
There's a few issues with your spec, however the main one is that you have a json object that has duplicate keys of "id", when jackson tries to transform your spec into a java object to be fed into the jolt engine it writes the first id key with a value of "customer[&1].id" then overwrites it with "customer[&1].customId".

Luckily what you're trying to do can be done with a the default operation which will avoid the duplicate keys
```json
[
  {
    "operation": "modify-default-beta", 
    "spec": {
      "customer": {
        "*": {
          "locations": {
            "*": {
              "customId": "@(1,id)"
            }
          }
        }
      }
    }
  }
]
```

**Comment by milosimpson** [comment]
Yeah, given that the input data will be large, and you generally don't want to mess with it, I recommend the "modify-default-beta" approach.

For the record tho this can be done with Shift
```
[
  {
    "operation": "shift",
    "spec": {
      "customer": {
        "*": {
          "locations": {
            "*": {
              "id": ["customer[&3].locations[&1].id",
                      "customer[&3].locations[&1].customId"],
              "name": "customer[&3].locations[&1].name"
            }
          }
        }
      }
    }
  }
]
```

Shiftr can write a matched value to multiple places in the output by making the RHS of the spec be an Array.

**Comment by mhubbard** [comment]
Interesting, thanks for the info, I must have missed the mulitPlacement test case.

**Comment by sandeepturvo** [comment]
Thanks guys for the update, "modify-default-beta" approach would better suit for my requirements. Will go ahead with that 👍

**Comment by amolbc** [comment]
I just wasted about 10 mins only to realize that 
"customId": "@(1,id)" 
is totally different from 
"customId": "@(1, id)"
The extra space before id breaks it. Shouldn't white spaces be ignored?

**Comment by mhubbard** [comment]
I too have spent some time on errors like that, that request should probably go in it's own issue though.
It's not too hard to fix, just remove the whitespace before passing to the traversal builder in each *LeafSpec.java 

For instance line 62 in ShiftrLeafSpec.java becomes
```java
writers = Arrays.asList( TRAVERSAL_BUILDER.build( ((String)rhs).replaceAll("\\s+","") ) );
```

And lines 137 and 140 become the following
```java
return FunctionArg.forContext( TRAVERSAL_BUILDER.build( arg.substring( 1 ).replaceAll("\\s+","") ) );
```
```java
return FunctionArg.forSelf( TRAVERSAL_BUILDER.build( arg.replaceAll("\\s+","") ) );
```

This is just for the right hand side though, the keys/lhs requires similar changes to parent class of the *LeafSpec classes.
