### ISSUE TITLE
Shiftr : Transforming n level depth array to one level depth

### ISSUE THREAD

**Issue by abarnwal13** [bazaarvoice/jolt#250]
I am new to jolt and don't know is this question is already answered by someone earlier. I have to transform 2 level or may be more nested level arrays to one level array of objects. Please find input, output and jolt specs below.
Input : 
```
{
	"customers": [
		{
			"timestamp": "2016-07-29T00:20:11+0000",
			"attributes": [
				{
					"id": 3,
					"name": "Width",
					"values": [
						{
							"id": 12,
							"name": "REGULAR"
						},
						{
							"id": 13,
							"name": "WIDE"
						}
					]
				}
			],
			"dates": [
				{
					"id": 1234,
					"name": "Date of Birth",
					"value": "2000-03-13T15:00:00.000+0000"
				},
				{
					"id": 321,
					"name": "Start Date",
					"value": "2014-03-13T15:00:00.000+0000"
				}
			]
		},
		{
			"timestamp": "2015-07-29T00:20:11+0000",
			"attributes": [
				{
					"id": 102,
					"name": "Men",
					"values": [
						{
							"id": 2413,
							"name": "Shoes"
						},
						{
							"id": 2412,
							"name": "Tshirt"
						}
					]
				},
				{
					"id": 132,
					"name": "Hidden Collections - US",
					"values": [
						{
							"id": 2078,
							"name": "Mobile"
						},
						{
							"id": 319314,
							"name": "Corporate"
						}
					]
				}
			],
			"dates": [
				{
					"id": 123,
					"name": "End Date",
					"value": "2014-03-13T15:00:00.000+0000"
				}
			]
		}
	]
}
```

Output: 
```
{
  "customers" : [ {
    "attribute" : {
      "3" : [ "REGULAR","WIDE" ]
    },
    "timestamp" : "2016-07-29T00:20:11+0000",
    "dateOfBirth": "2000-03-13T15:00:00.000+0000",
    "startDate" : "2014-03-13T15:00:00.000+0000"
  }, {
    "attribute" : {
      "102" : [ "Shoes","Tshirt" ],
      "132" : [ "Mobile","Corporate" ]
    },
    "timestamp" : "2015-07-29T00:20:11+0000",
    "endDate" : "2014-03-13T15:00:00.000+0000"
  } ]
}
```

JOLT Specs:
```
[
  {
    "operation": "shift",
    "spec": {
      "customers": {
        "*": {
          "timestamp": "customers[&1].timestamp",
          "attributes": {
            "*": {
              "values": {
                "*": {
                  "name": "customers[&1].attribute.@(3,id)[]"
                }
              }
            }
          },
          "dates": {
            "*": {
              "id": {
                "1234": {
                  "@(2,value)": "customers[&1].dateOfBirth"
                },
                "321": {
                  "@(2,value)": "customers[&1].startDate"
                },
                "123": {
                  "@(2,value)": "customers[&1].endDate"
                }
              }
            }
          }
        }
      }
    }
  }
]
```

Please let me know where I am going wrong, any help will be appreciated. Thanks.

**Comment by abarnwal13** [comment]
@milosimpson : can you please provide the transform for above input and output ?

**Comment by milosimpson** [comment]
Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "customers": {
        "*": {
          "timestamp": "customers[&1].timestamp",
          "attributes": {
            "*": {
              "values": {
                "*": {
                  "name": "customers[&5].attribute.@(3,id)[]"
                }
              }
            }
          },
          "dates": {
            "*": {
              "id": {
                "1234": {
                  "@(2,value)": "customers[&5].dateOfBirth"
                },
                "321": {
                  "@(2,value)": "customers[&5].startDate"
                },
                "123": {
                  "@(2,value)": "customers[&5].endDate"
                }
              }
            }
          }
        }
      }
    }
  }
]
```

**Comment by abarnwal13** [comment]
@milosimpson : Thanks alot, it works. I was doing wrong in depth of customers array in target.

**Comment by rajimanu** [comment]
Input Json:

 {
 

 
 	"customers": [{
 			"timestamp": "2016-07-29T00:20:11+0000",
 			"attributes": [{

 					"categ": "Width",
 					"values": [{
 							"id": 12,
 							"name": {
 								"val1": "",
 								"val2": ""
 							}
 						},
 						{
 							"id": 14,
 							"name": {
 								"val1": "",
 								"val2": ""
 							}
 						}
 					]
 				},
 				{
 					"values": [{
 							"id": 18,
 							"name": {
 								"val1": "",
 								"val2": ""
 							}
 						},
 						{
 							"id": 17,
 							"name": {
 								"val1": "",
 								"val2": ""
 							}
 						}

 					],
 					"categ": "eee"
 				}
 			]
 		},
 		{
 			"timestamp": "2019-07-29T00:20:11+0000",
 			"attributes": [{

 				"name": "Width",
 				"values": [{
 					"id": 12,
 					"name": {
 						"val1": "",
 						"val2": ""
 					}
 				}]
 			}]
 		}
 	]
 }

Expected output:


 {



 	"customers": [{
 			"timestamp": "2016-07-29T00:20:11+0000",
 			"attributes": [{

 					"categ": "Width",
 					"values": [{
 							"id": 12,
 							"name": {
 								"val1": "",
 								"val2": ""
 							}
 						},
 						{
 							"id": 14,
 							"name": {
 								"val1": "",
 								"val2": ""
 							}
 						}
 					]
 				},
 				{
 					"categ": "eee",
 					"values": [

 						{
 							"id": "an",
 							"name": {
 								"code": [18, 17]

 							}
 						}

 					]

 				}
 			]
 		},
 		{
 			"timestamp": "2019-07-29T00:20:11+0000",
 			"attributes": [{

 				"name": "Width",
 				"values": [{
 					"id": 12,
 					"name": {
 						"val1": "",
 						"val2": ""
 					}
 				}]
 			}]
 		}
 	]
 }

I am new to jolt .Please help me with the transformation. I really appreciate the help

**Comment by wisthy** [comment]
@rajimanu please create a new issue instead of commenting on an old, closed one. If your issue is indeed related to this one, just add a link to it (adding # + issue number)

**Comment by meisam94** [comment]
I want to set  seed value from ai object to   new address  $.jobInput.ai.common.seed"
I write a operation but not work
can someone help me?

```
"ai":{
      "model_structure":{
            "backend":"tensorflow",
	    "seed":100,
             "model_type":"Deep"
   }
   
```
   




```
{
    "operation": "modify-overwrite-beta",
    "spec": {
      "jobInput": {
        "ai": {
          "common": {
            "seed": "ai[&5].model_structure.@(seed)"

          }
        }
      }
    }
  }
```
