### ISSUE TITLE
How to handle Camel Case Sensitivity or Case Change in Jolt 

### ISSUE THREAD

**Issue by mangalapalli** [bazaarvoice/jolt#251]
HI Team, 

How can we handle string case(Upper case to lower Case, vise versa) changes in Jolt . i would request suggest me the available options in Jolt for the above one.

**Comment by milosimpson** [comment]
camelCasing, no.   

toUpper and toLower, yes.   Need to use the latest release and the "beta" modify transforms. 
Read the release notes / doc here https://github.com/bazaarvoice/jolt/releases/tag/jolt-0.0.22
and example unit test https://github.com/bazaarvoice/jolt/blob/c7f3cec86e941ffbf151a3c965abe54e73462652/jolt-core/src/test/resources/json/modifier/functions/stringsTests.json

**Comment by mangalapalli** [comment]
Is it possible for ignore case in Jolt Spec?

**Comment by milosimpson** [comment]
No, since Jolt operates on Map<String,Object> and Map is case sensitive.

Sounds like a feature request, for a new wildcard, kinda like "rating-*".

**Comment by barbaros74** [comment]
Dear @mangalapalli ; there exists such a workaround currently on SO -> https://stackoverflow.com/a/75399297/5841306 , keep jolting !
