### ISSUE TITLE
Jolt transformation - id based matching output issues

### ISSUE THREAD

**Issue by santooshkhcl** [bazaarvoice/jolt#256]
Hello Team,

This is my first post on jolt transformation (Writing in issues Category)
Expected Output:  Each  Address will have parsed and unparsed address and it should generated be based on input address id match
If jolt spec found matching address id then it should add the respective address in output section
PFA spec and input, out json for reference

Output Strcture: 
Address {
Address_id
Parsed Address{}
Unparsed Address{}
}
Note: It should only populate parsed on unparsed based on matching id
Currently my logic only hold good if input having both address if not then it will keep appending with other address irrespective of ids

Thanks for your help
Santosh

[Details.zip](https://github.com/bazaarvoice/jolt/files/429713/Details.zip)

**Comment by santooshkhcl** [comment]
Spec:
[
  {
    "operation": "shift",
    "spec": {
      "check": {
        "address": {
          "value": {
            "addressInfo": {
              "Map": {
                "*": {
                  "$": "Addresses[].Address.Address_id",
                  "shippingAddressStreet1": "Addresses[#2].Address.UnparsedAddress.AddressLine1",
                  "shippingAddressStreet2": "Addresses[#2].Address.UnparsedAddress.AddressLine2",
                  "AddressLine3": "Addresses[#2].Address.UnparsedAddress.AddressLine3"
                }
              }
            },
            "additionalInfo": {
              "address*": {
                "AddressStreetLine": "Addresses[#2].Address.ParsedAddress.AddressStreetLine",
                "HouseNumberPrefix": "Addresses[#2].Address.ParsedAddress.HouseNumberPrefix",
                "HouseNumberSuffix": "Addresses[#2].Address.ParsedAddress.HouseNumberSuffix",
                "DirectionPrefix": "Addresses[#2].Address.ParsedAddress.DirectionPrefix",
                "Direction": "Addresses[#2].Address.ParsedAddress.Direction",
                "AssignedStreetNumber": "Addresses[#2].Address.ParsedAddress.AssignedStreetNumber"
              }
            }
          }
        }
      }
    }
   }
]

Input Json:
{
	"check": {
		"address": {
			"value": {
				"version": 1,
				"id": "checkout-address-1",
				"status": {
					"state": "complete"
				},
				"addressInfo": {
					"Map": {
						"address_id_1": {
							"shippingAddressStreet1": "1100 RD",
							"shippingAddressStreet2": "RD 2",
							"AddressLine3": "RD 3",
							"PostOfficeBox": "07302"
						},
						"address_id_2": {
							"shippingAddressStreet1": "1135 RD",
							"shippingAddressStreet2": "AD 2",
							"AddressLine3": "AD 3",
							"PostOfficeBox": "89568"
						},
						"address_id_3": {
							"shippingAddressStreet1": "1135 RD",
							"shippingAddressStreet2": "AD 2",
							"AddressLine3": "AD 3"
						}
					}
				},
				"additionalInfo": {
					"address_id_1": {
						"AddressStreetLine": "12 PKW",
						"HouseNumberPrefix": "PX11"
					},
					"address_id_2": {
						"AddressStreetLine": "13 PKW",
						"HouseNumberPrefix": "PX13"
					},
					"address_id_3": {
						"AddressStreetLine": "14 PKW",
						"HouseNumberPrefix": "PX14"
					}
				}
			}
		}
	}
}

**Comment by santooshkhcl** [comment]
[Input.txt](https://github.com/bazaarvoice/jolt/files/429761/Input.txt)
[Output.txt](https://github.com/bazaarvoice/jolt/files/429760/Output.txt)
[spec.txt](https://github.com/bazaarvoice/jolt/files/429759/spec.txt)
Added spec and input files for reference

**Comment by santooshkhcl** [comment]
![expectedoutput](https://cloud.githubusercontent.com/assets/21142096/17849902/83fa7886-6878-11e6-8540-194027b6d05d.jpg)

**Comment by milosimpson** [comment]
Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "check": {
        "address": {
          "value": {
            "addressInfo": {
              "Map": {
                "*": {
                  "$": "Addresses[].Address.Address_id",
                  "shippingAddressStreet1": "Addresses[#2].Address.UnparsedAddress.AddressLine1",
                  "shippingAddressStreet2": "Addresses[#2].Address.UnparsedAddress.AddressLine2",
                  "AddressLine3": "Addresses[#2].Address.UnparsedAddress.AddressLine3",
                  "@(3,additionalInfo.&)": {
                    "AddressStreetLine": "Addresses[#3].Address.ParsedAddress.AddressStreetLine",
                    "HouseNumberPrefix": "Addresses[#3].Address.ParsedAddress.HouseNumberPrefix",
                    "HouseNumberSuffix": "Addresses[#3].Address.ParsedAddress.HouseNumberSuffix",
                    "DirectionPrefix": "Addresses[#3].Address.ParsedAddress.DirectionPrefix",
                    "Direction": "Addresses[#3].Address.ParsedAddress.Direction",
                    "AssignedStreetNumber": "Addresses[#3].Address.ParsedAddress.AssignedStreetNumber"
                  }
                }
              }
            }
          }
        }
      }
    }
   }
]
```

With this modified input, it dos not return parsedAddress info for the missing one, "address_id_2"
Modified Input 
```
{
	"check": {
		"address": {
			"value": {
				"version": 1,
				"id": "checkout-address-1",
				"status": {
					"state": "complete"
				},
				"addressInfo": {
					"Map": {
						"address_id_1": {
							"shippingAddressStreet1": "1100 RD",
							"shippingAddressStreet2": "RD 2",
							"AddressLine3": "RD 3",
							"PostOfficeBox": "07302"
						},
						"address_id_2": {
							"shippingAddressStreet1": "1135 RD",
							"shippingAddressStreet2": "AD 2",
							"AddressLine3": "AD 3",
							"PostOfficeBox": "89568"
						},
						"address_id_3": {
							"shippingAddressStreet1": "1135 RD",
							"shippingAddressStreet2": "AD 2",
							"AddressLine3": "AD 3"
						}
					}
				},
				"additionalInfo": {
					"address_id_1": {
						"AddressStreetLine": "12 PKW",
						"HouseNumberPrefix": "PX11"
					},
					"address_id_3": {
						"AddressStreetLine": "14 PKW",
						"HouseNumberPrefix": "PX14"
					}
				}
			}
		}
	}
}
```

**Comment by santooshkhcl** [comment]
Thanks Milo for the update,
Above modified spec changes looks fine. Would like to know your input on below scenario
For any missing UnparsedAddress section, do not want to miss parsedAddress section for same address Id. Is it possible to check the address (parsed or unparsed ) based on address id. if respective match found then add to output. Please advise

Current spec output is ok. but if its do not found the section in unparsed address then its ignores same in parsed section. but we may need address from either section based on address id.

Kindly check and advise
Thanks for your help

**Comment by milosimpson** [comment]
Have to do 3 transforms
Spec 
```
[
  {
    "operation": "shift",
    "spec": {
      "check": {
        "address": {
          "value": {
            // send UnparsedAddress and ParsedAddress to a temp map
            // note Address_id might get duplicated as it can come from both
            "addressInfo": {
              "Map": {
                "*": {
                  "$": "temp.&1.Address.Address_id",
                  "shippingAddressStreet1": "temp.&1.Address.UnparsedAddress.AddressLine1",
                  "shippingAddressStreet2": "temp.&1.Address.UnparsedAddress.AddressLine2",
                  "AddressLine3": "temp.&1.Address.UnparsedAddress.AddressLine3"
                }
              }
            },
            "additionalInfo": {
              "*": {
                "$": "temp.&1.Address.Address_id",
                "AddressStreetLine": "temp.&1.Address.ParsedAddress.AddressStreetLine",
                "HouseNumberPrefix": "temp.&1.Address.ParsedAddress.HouseNumberPrefix",
                "HouseNumberSuffix": "temp.&1.Address.ParsedAddress.HouseNumberSuffix",
                "DirectionPrefix": "temp.&1.Address.ParsedAddress.DirectionPrefix",
                "Direction": "temp.&1.Address.ParsedAddress.Direction",
                "AssignedStreetNumber": "temp.&1.Address.ParsedAddress.AssignedStreetNumber"
              }
            }
          }
        }
      }
    }
  },
  {
    "operation": "cardinality",
    "spec": {
      "temp": {
        "*": {
          "Address": {
            // squash Address_id to a single field
            // if UnparsedAddress and ParsedAddress both exist then 
            // Address_id would be an array
            "Address_id": "ONE"
          }
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "temp": {
        // turn the map based on Address_ids into a list
        "*": "Addresses[#1]"
      }
    }
  }
]
```

This modified input
```
{
	"check": {
		"address": {
			"value": {
				"version": 1,
				"id": "checkout-address-1",
				"status": {
					"state": "complete"
				},
				"addressInfo": {
					"Map": {
						"address_id_1": {
							"shippingAddressStreet1": "1100 RD",
							"shippingAddressStreet2": "RD 2",
							"AddressLine3": "RD 3",
							"PostOfficeBox": "07302"
						},
						"address_id_2": {
							"shippingAddressStreet1": "1135 RD",
							"shippingAddressStreet2": "AD 2",
							"AddressLine3": "AD 3",
							"PostOfficeBox": "89568"
						}
					}
				},
				"additionalInfo": {
					"address_id_1": {
						"AddressStreetLine": "12 PKW",
						"HouseNumberPrefix": "PX11"
					},
					"address_id_3": {
						"AddressStreetLine": "14 PKW",
						"HouseNumberPrefix": "PX14"
					}
				}
			}
		}
	}
}
```

Produces 
```
{
  "Addresses" : [ {
    "Address" : {
      "Address_id" : "address_id_1",
      "UnparsedAddress" : {
        "AddressLine1" : "1100 RD",
        "AddressLine2" : "RD 2",
        "AddressLine3" : "RD 3"
      },
      "ParsedAddress" : {
        "AddressStreetLine" : "12 PKW",
        "HouseNumberPrefix" : "PX11"
      }
    }
  }, {
    "Address" : {
      "Address_id" : "address_id_2",
      "UnparsedAddress" : {
        "AddressLine1" : "1135 RD",
        "AddressLine2" : "AD 2",
        "AddressLine3" : "AD 3"
      }
    }
  }, {
    "Address" : {
      "Address_id" : "address_id_3",
      "ParsedAddress" : {
        "AddressStreetLine" : "14 PKW",
        "HouseNumberPrefix" : "PX14"
      }
    }
  } ]
}
```

**Comment by santooshkhcl** [comment]
Apologies for late update.
Thanks a lot Milo, above looks ok, however we do not  have much options to change input data, having said that, this transformation will help
