### ISSUE TITLE
Unable to find ChainrFactory in the JOLT library.

### ISSUE THREAD

**Issue by anupz** [bazaarvoice/jolt#260]
I am using jolt-core-0.0.22 and json-utils-0.0.22  in my project.  I am not able to create a Chainr instance using ChainrFactory. ChainrFactory is not in com.bazaarvoic.jolt package. Can you please let me know where is ChainrFactory class? Or there is another way to create Chainr instance.?

I am creating Chainr Object using below code : 
```
	String specFilename = "src\\main\\resources\\chainrSpec1.json";
		Chainr chainr = ChainrFactory.fromFile(new File(specFilename));
```

**Comment by milosimpson** [comment]
ChainrFactory is in the "jolt-complete" artifact, which pulls in Jackson.

See : https://mvnrepository.com/artifact/com.bazaarvoice.jolt for the list of Jolt artifacts available.

**Comment by anupz** [comment]
Thanks Mr Simpson this solves my issue. It was confusing for me to decide which jars to use.
