### ISSUE TITLE
Jolt transformation for list within list

### ISSUE THREAD

**Issue by swayamsnigdha** [bazaarvoice/jolt#261]
Hi Team,

I have a from json as below:

```
{
    "Identifier": {
        "obj": {
            "Code": "1",
            "Plan": "1"
        },
        "obj1": {
            "Code": "1",
            "Plan": "2"
        },
        "obj3": {
            "memberId": "12312312"
        }
    }
}
```

I need to covert it to the below format. Appreciate if anyone can suggest the spec for this. 

```
{
  "Identifier": [
    {
      "identifierGroup": "obj",
      "keyName": "Code",
      "keyValue": "1"
},
    {
      "identifierGroup": "obj",
      "keyName": "Plan",
      "keyValue": "1"
},
    {
      "identifierGroup": "obj1",
      "keyName": "Code",
      "keyValue": "1"
},
    {
      "identifierGroup": "obj1",
      "keyName": "Plan",
      "keyValue": "2"
},
    {
      "identifierGroup": "obj3",
      "keyName": "memberId",
      "keyValue": "12312312"
}

        ]
}
```

Can anyone help me on this?

**Comment by saivsn** [comment]
`[
  {
    "operation": "shift",
    "spec": {
      "Identifier": {
        "*": {
          "*": {
            "$1": "Identifier.identifierGroup",
            "$": "Identifier.keyName",
            "@": "Identifier.keyValue"
          }
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "Identifier": {
        "identifierGroup": {
          "*": {
            "@": "Identifier[&1].identifierGroup"
          }
        },
        "keyName": {
          "*": {
            "@": "Identifier[&1].keyName"
          }
        },
        "keyValue": {
          "*": {
            "@": "Identifier[&1].keyValue"
          }
        }
      }
    }
  }
]
`

**Comment by swayamsnigdha** [comment]
Thanks it worked!!
