### ISSUE TITLE
Start array index at one

### ISSUE THREAD

**Issue by aschuhl** [bazaarvoice/jolt#262]
Is it possible to index the array by 1 instead of by 0?
Input:

```
{
    "test": [
        {
            "this": "json"
        }
    ]
}
```

Current spec:

```
[
  {
    "operation": "shift",
    "spec": {
      "test": {
        "*": {
          "this": "&0_&1"
        }
      }
    }
  }
]
```

Desired output:

```
{
    "this_1":json
}
```

**Comment by milosimpson** [comment]
I can't think of a way to do it with the "out of the box tools".    

If you modify your Json first, by inserting an empty item in your array, then the Jolt transform would work.

**Comment by aschuhl** [comment]
That is what I figured. Thank you for the help.
