### ISSUE TITLE
Split the DOB  String 

### ISSUE THREAD

**Issue by mounikakatnapelli** [bazaarvoice/jolt#272]
i have the DOB as String like   dateOfBirth:"23-03-1983" i would like to convert that object to 

DOB{

"Month":03,
"Day":23,
"year":1983
}

**Comment by milosimpson** [comment]
Spec 

```
[
  {
    "operation": "shift",
    "spec": {
      "dateOfBirth": {
        "*-*-*": { // "23-03-1983"
          "$(0,1)": "DOB.Day",
          "$(0,2)": "DOB.Month",
          "$(0,3)": "DOB.Year"
        }
      }
    }
  }
]
```

**Comment by mounikakatnapelli** [comment]
Thanks it is helped for me alot to complete my task

**Comment by mounikakatnapelli** [comment]
REQUEST{
	"traits": [
		{
			"clientId": "12",
			"hidden": "hai"
		},
		{
			"clientId": "35",
			"hidden": "hello"
		}
	]
}

I want the out put if hidden is hai  i want the entire that object like this

{
  "clients" : {
 	"clientId": "12",
    "hidden" : "hai"
  }
}
Can you help I tried this 
[
  {
    "operation": "shift",
    "spec": {
      "traits": {
        "*": {
          "hidden": {
            "hai": {
              "#clientId": "clients.@(3,clientId)",
              "$(0,0)": "clients.hidden"
            }
          }
        }
      }
    }
  }
]

ou put is showing in reverse for client id value and tag

{
  "clients" : {
    "12" : "clientId",
    "hidden" : "hai"
  }
}
