### ISSUE TITLE
Space in Expressions Cause Problems

### ISSUE THREAD

**Issue by ghost** [bazaarvoice/jolt#281]
In for example `ismith.json` change
`"@(4,ref.True)"`
to
`"@(4, ref.True)"`
(note the space after `4,`)

that will break the test. It took me an hour or two to figure out what was cause test failures, spaces should not cause such issues I presume.

**Comment by milosimpson** [comment]
The issue is that you could technically have a JSON document with a key / left-hand-side value that starts with a space.
```
{
    " ref" : {
         "True" : "sushi" 
    }
}
```
So the "@" logic does not do a trim.    There would need to be additional thought and work done on the parser to be able to "escape" the spaces or something.

Sorry you ran into that.

**Comment by pete-experimenter** [comment]
Thanks for explaining. Would be interested to know how you do the parsing. Could you give a pointer to the code? Maybe I could have a look.

**Comment by milosimpson** [comment]
Would need to be addressed at least here : https://github.com/bazaarvoice/jolt/blob/557a9efccf1847498c056c7c122d860ec00aec93/jolt-core/src/main/java/com/bazaarvoice/jolt/common/pathelement/TransposePathElement.java#L80

But may also need to be in other places...

On the "thought" side, how would you explicitly say that you want the space char?

**Comment by pete-experimenter** [comment]
Thanks for the pointer. To be honest I don't fully understand the need to "say that you want the space char". Could you clarify? I was simply looking at the expression and thought, that spaces could be added as in java, where you are OK to have spaces.

**Comment by milosimpson** [comment]
In Json it is valid to have a Left Hand Side key with a space in it.   
If Jolt just did a "trim" on the spec, then it would not be able to match Json data with a space in it.

It's an odd and minor use case, but still doesn't seem worth breaking.
```
   " ref" : "sushi"   \\ where the "ref" has a space in front of it
```

**Comment by pete-experimenter** [comment]
Understood, thank you for explanation. Do agree spaces could not just be stripped out. It should be context dependent, as you have shown. I think expression parsing could be simplified if defined in EBNF form in a tool like javacc.

**Comment by pete-experimenter** [comment]
And thank you for the wonderful tool. Does magic for us.

**Comment by milosimpson** [comment]
"I think expression parsing could be simplified if defined in EBNF form in a tool like javacc. "   

I agree in theory.  But I have made 3 attempts at trying to use some kind of Parser thingy and have not been able to wrap my head around it / make it work.   2x attempts at ANTLR; 1x attempt at ParBoiled.

**Comment by pete-experimenter** [comment]
Right,  I did use AntLR before to be honest. Wrote quite a few grammars, looked simple to be honest. Can try to help if needed.
