### ISSUE TITLE
Array element as key and value from another element

### ISSUE THREAD

**Issue by Degola** [bazaarvoice/jolt#287]
Hey,

for our analytics event processing we need to change the following event:
```
{
	"type": [
		"user",
		"profile",
		"personalInfo",
		"firstName"
	],
	"value": "John",
	"_meta": {
		"appId": "xyz",
		"userId": "56c1614b677c35cc3f28fbd0"
	}
}
```
into the following structure:
```
{
  "firstName": "John",
  "appId": "xyz",
  "userId":"56c1614b677c35cc3f28fbd0"
}
```
My issue is to find a proper solution for using a specific array element as key, can anyone help here?

**Comment by milosimpson** [comment]
Your question does not use or reference any data from the "type" array...

This spec produces the output you described.
Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "value": "firstName",
      "_meta": {
        "appId": "appId",
        "userId": "userId"
      }
    }
  }
]
```

**Comment by Degola** [comment]
Sorry that I was not clear enough: i need the last element of the type array as key for the corresponding value. Based on your example I tried the following but it doesn't work:
`[
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "value": "=lastElement(@(1,type))",
      "_meta": {
        "appId": "appId",
        "playerId": "playerId"
      }
    }
  }
]
`

**Comment by milosimpson** [comment]
Use the modify to first extract the last element of the Type array, then do a shift, that references it.

Spec
```
[
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "lastElementOfType": "=lastElement(@(1,type))"
    }
  },
  {
    "operation": "shift",
    "spec": {
      "value": "@(1,lastElementOfType)",
      "_meta": {
        "appId": "appId",
        "userId": "userId"
      }
    }
  }
]
```

**Comment by Degola** [comment]
Great, thanks a lot. I'm starting to understand the syntax of Jolt :-).
