### ISSUE TITLE
Are calls to chainr.transform thread safe?

### ISSUE THREAD

**Issue by vivasur** [bazaarvoice/jolt#288]
Hi,

I will be Creating One Chainr Instance for each spec type. 
There will be multiple client requests in parallel, where I will be calling chainr.transform for each spec type. 
I wanted to know if the call to chainr.transform is thread safe or do I have to ensure thread safety?

Thanks,
Vivek

**Comment by milosimpson** [comment]
Chainr and the built in Transforms (shift, default, etc) are thread safe.

At BV we have different types of "content" (reviews, questions, answers, etc) and we have one Chainr instance for each type that gets used by multiple threads to do transforms.

**Comment by vivasur** [comment]
Thanks a lot.
