### ISSUE TITLE
Merging 2 arrays of same type into one array, using a key value

### ISSUE THREAD

**Issue by bortoffe** [bazaarvoice/jolt#291]
Hello,

I have 2 arrays, and I need to line up the objects in each using the "x" value. 

Input:

```
{
"first": [
      {
        "x": "1",
        "y": "value y1"
      },
      {
        "x": "2",
        "y": "value y2"
      }
    ],
    "sec": [
      {
        "x": "1",
        "z": "value z1"
      },
      {
        "x": "2",
        "z": "value z2"
      }
    ]
  }
```
Desired Output:
```
[
  {
    "x": "1",
    "y": "value y1",
    "z": "value z1"
  },
  {
    "x": "2",
    "y": "value y2",
    "z": "value z2"
  }
]
```

Thanks for any help you can provide.

**Comment by milosimpson** [comment]
So can almost do what you want.   Note that in your desired output x=1 is actually in the Zeroth array in the output.

Also, to truly drive the output array by the value of "x" should mutate the input so that you can't just key off the array index of "first" and "second".   Note if you can then a simpler transform can be done.

Adjusted Input
```
{
	"first": [
		{
			"x": "2",
			"y": "value y2"
		},
		{
			"x": "1",
			"y": "value y1"
		}
	],
	"sec": [
		{
			"x": "1",
			"z": "value z1"
		},
		{
			"x": "2",
			"z": "value z2"
		}
	]
}
```

Spec 
```
[
  {
    "operation": "shift",
    "spec": {
      "*": { // first or sec
        "*": { // array of first[] or sec[]
          "x": {
            "*": { // value of x, assumed to be number

              // go up two levels, and grab the value of y or z
              // and write it to [ <value of x> ].y or .z
              "@(2,y)": "[&1].y",
              "@(2,z)": "[&1].z",
              "$": "[&1].x" // write the x to the output
            }
          }
        }
      }
    }
  },
  {
    "operation": "cardinality",
    "spec": {
      "*": {
        // because both first[] and sec[] contained "x" keys
        // the output from above will have an array of x values.
        // They are the same, so pick one
        "x": "ONE"
      }
    }
  }
]
```

Close output
```
[
	null,
	{
		"x": "1",
		"y": "value y1",
		"z": "value z1"
	},
	{
		"x": "2",
		"y": "value y2",
		"z": "value z2"
	}
]
```

**Comment by bortoffe** [comment]
Thanks for your quick reply! Is there a way to do this when the key value is a string?

**Comment by milosimpson** [comment]
"when the key value is a string" ... what do you mean?   Your input is/are already strings, "x" : "1".

**Comment by bortoffe** [comment]
If the input was not a number in a string such as this: 
`{
	"first": [
		{
			"x": "value x1",
			"y": "value y2"
		},
		{
			"x": "value 2",
			"y": "value y1"
		}
	],
	"sec": [
		{
			"x": "value x1",
			"z": "value z1"
		},
		{
			"x": "value 2",
			"z": "value z2"
		}
	]
}`

**Comment by milosimpson** [comment]
So, extract the "1" from "value x1" and use that.
Should be possible

**Comment by milosimpson** [comment]
The input you gave did not have a consistent pattern for the right hand side of "x".   x="value x1" and x="value 1", made them be x="value x1"

Adjusted Input
```
{
	"first": [
		{
			"x": "value x1",
			"y": "value y2"
		},
		{
			"x": "value x2",
			"y": "value y1"
		}
	],
	"sec": [
		{
			"x": "value x1",
			"z": "value z1"
		},
		{
			"x": "value x2",
			"z": "value z2"
		}
	]
}
```

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "*": { // first or sec
        "*": { // array of first[] or sec[]
          "x": {
            "value x*": { // value of x, assumed to be pattern "value x<NUMBER>"
              // go up two levels, and grab the value of y or z
              // and write it to [ <value of the number part of the x> ].y or .z
              "@(2,y)": "[&(1,1)].y",
              "@(2,z)": "[&(1,1)].z",
              "$(0,1)": "[&(1,1)].x" // write the x to the output
            }
          }
        }
      }
    }
  },
  {
    "operation": "cardinality",
    "spec": {
      "*": {
        // because both first[] and sec[] contained "x" keys
        // the output from above will have an array of x values.
        // They are the same, so pick one
        "x": "ONE"
      }
    }
  }
]
```

**Comment by sujay1848** [comment]
Hi, I am facing something similar here, the only difference being that the field to join on has different names in the collections.

Input:
```
{
	"first": [
		{
			"x": "1",
			"y": "value y1"
		},
		{
			"x": "2",
			"y": "value y2"
		}
	],
	"sec": [
		{
			"x1": "1",
			"z": "value z1"
		},
		{
			"x1": "2",
			"z": "value z2"
		}
	]
}
```
Output:
```
{
	"output": [
		{
			"x": "1",
			"y": "value y1",
			"z": "value z1"
		},
		{
			"x": "2",
			"y": "value y2",
			"z": "value z2"
		}
	]
}
```

Any help would be greatly appreciated!

**Comment by Ribhu4** [comment]
> So can almost do what you want. Note that in your desired output x=1 is actually in the Zeroth array in the output.
> 
> Also, to truly drive the output array by the value of "x" should mutate the input so that you can't just key off the array index of "first" and "second". Note if you can then a simpler transform can be done.
> 
> Adjusted Input
> 
> ```
> {
> 	"first": [
> 		{
> 			"x": "2",
> 			"y": "value y2"
> 		},
> 		{
> 			"x": "1",
> 			"y": "value y1"
> 		}
> 	],
> 	"sec": [
> 		{
> 			"x": "1",
> 			"z": "value z1"
> 		},
> 		{
> 			"x": "2",
> 			"z": "value z2"
> 		}
> 	]
> }
> ```
> 
> Spec
> 
> ```
> [
>   {
>     "operation": "shift",
>     "spec": {
>       "*": { // first or sec
>         "*": { // array of first[] or sec[]
>           "x": {
>             "*": { // value of x, assumed to be number
> 
>               // go up two levels, and grab the value of y or z
>               // and write it to [ <value of x> ].y or .z
>               "@(2,y)": "[&1].y",
>               "@(2,z)": "[&1].z",
>               "$": "[&1].x" // write the x to the output
>             }
>           }
>         }
>       }
>     }
>   },
>   {
>     "operation": "cardinality",
>     "spec": {
>       "*": {
>         // because both first[] and sec[] contained "x" keys
>         // the output from above will have an array of x values.
>         // They are the same, so pick one
>         "x": "ONE"
>       }
>     }
>   }
> ]
> ```
> 
> Close output
> 
> ```
> [
> 	null,
> 	{
> 		"x": "1",
> 		"y": "value y1",
> 		"z": "value z1"
> 	},
> 	{
> 		"x": "2",
> 		"y": "value y2",
> 		"z": "value z2"
> 	}
> ]
> ```

Hi @milosimpson 

I am new to JOLT and find JOLT as an excellent framework for transformation. In the quoted reply, I am not able to remove null by providing any spec. My use case is similar but it has huge data , so lots of null come up. Can you please help?
