### ISSUE TITLE
Do you plan to work with Spark?

### ISSUE THREAD

**Issue by steve-drew-strong-bridge** [bazaarvoice/jolt#299]
Great app. I love how easy this is to manipulate JSON.

I'd like to use this against Spark files hosted on AWS S3.

Any plans to make it serializable?

**Comment by milosimpson** [comment]
There are developers at my company that use Jolt to transform Json for building parquet format files.

What do you mean by "serializable" and how would that help with Spark files in S3?

**Comment by steve-drew-strong-bridge** [comment]
My apologies.  I should lay out the issue, since my understanding of what is going on may be flawed. :-)

I didn't see any example code for Spark on your site, so I tried to hack it together from your javadocs.  This is the nut of what I'm doing with Jolt:
val source = scala.io.Source.fromFile("SPEC.txt")
val specjson = try source.mkString finally source.close()
val transformFunction = (line: String) => {
val chainrSpecJSON = JsonUtils.stringToType(specjson,classOf[java.util.List[Object]])
val chainr = Chainr.fromSpec( chainrSpecJSON )
val inputJSON = JsonUtils.stringToType(line,classOf[Object])
val transformedOutput = chainr.transform( inputJSON )
val result = JsonUtils.toJsonString( transformedOutput ).toString
}
val rdd = spark.sparkContext.textFile("s3 folder").map(transformFunction)

I've tried this as:
A) the transform function above
B) executing the code within the map
C) wrapping my code in a scala object extending Serializable 

In all three cases, I get a serialization debugger error that stops it from processing.
WARN SerializationDebugger: Exception in serialization debugger
java.io.IOException: Stream Closed
<snip>
org.apache.spark.SparkException: Task not serializable
<snip>
Caused by: java.io.NotSerializableException: scala.io.BufferedSource
<snip>
(I've attached the full output, in case it helps.)

I'm trying to track down what's failing here.  Also, the two test case JSON documents and the spec, just so you have context.  Any working spark samples to share?  Maybe I can figure out my mistake by seeing how someone else accomplished it. 

Thanks
[SPEC.txt](https://github.com/bazaarvoice/jolt/files/678867/SPEC.txt)
[test_case_android_2.txt](https://github.com/bazaarvoice/jolt/files/678868/test_case_android_2.txt)
[test_case_ios_1.txt](https://github.com/bazaarvoice/jolt/files/678869/test_case_ios_1.txt)
[io exception message.txt](https://github.com/bazaarvoice/jolt/files/678870/io.exception.message.txt)

**Comment by milosimpson** [comment]
So, have you seen / tried the code from here?   https://github.com/bazaarvoice/jolt/blob/master/gettingStarted.md

Basically "Chainr.fromSpec" and "chainr.transform" both take in fully hydrated Java objects that correspond to the input Json text, aka Map<String,Object> and or List<Object>.

**Comment by steve-drew-strong-bridge** [comment]
Yes, your sample code is where I started and converted to work with Scala until I had it working using your sample spec and input files.

Then, I had to convert to stringToType as my map object will return each line of the text file to the executors.

I'll try converting the RDD[String] to a List and see if that helps anything.  
I'm also attempting to load the spec on the executor (as a shot at which stream was closed.)
But, I'm basically just thumping around in the dark looking for the switch. :-) 

Thanks for your help.

**Comment by steve-drew-strong-bridge** [comment]
just further information... This code works until I use chainr.transform.  If I comment out that line, I get the correct inputJSON (essentially just passing back what I handed in).  But, as soon as I call chainr.transform I get 
java.io.NotSerializableException: com.bazaarvoice.jolt.Chainr
Serialization stack:
        - object not serializable (class: com.bazaarvoice.jolt.Chainr, value: com.bazaarvoice.jolt.Chainr@7d86b6cf)
        - field (class: $iw, name: chainr, type: class com.bazaarvoice.jolt.Chainr)

```
val transformFunction = (sourceJSON: String) => {  
import java.io.Serializable
import com.bazaarvoice.jolt.Chainr
import com.bazaarvoice.jolt.JsonUtils
import java.io.IOException
import java.util.List
import scala.collection.JavaConverters
val chainrSpecJSON = com.bazaarvoice.jolt.JsonUtils.stringToType(spec,classOf[java.util.List[Object]])
val chainr = com.bazaarvoice.jolt.Chainr.fromSpec( chainrSpecJSON )
val inputJSON = com.bazaarvoice.jolt.JsonUtils.stringToType(sourceJSON,classOf[Object])
//works to this point and returns the inputJSON as expected
val transformedOutput = chainr.transform( inputJSON )
//val result = com.bazaarvoice.jolt.JsonUtils.toJsonString( transformedOutput )

//return result
 inputJSON
}

```

**Comment by milosimpson** [comment]
Huh, so ... is it that Spark / Scala wants the Chainr instance to be serializable so that it can farm this transform job out across the network?

The problem is that Chainr is just a holder for a ton of other objects that make up your Spec, so theoretically a whole bunch of stuff would need to be hit with the serializeable annotation?

**Comment by steve-drew-strong-bridge** [comment]
It seems that way.  I may be going about this the wrong way.
Do any of the guys at your work that use Jolt and Spark have any similar code they'd be willing to share to help me out?  I'm happy to clean it up and maybe make a sample you can share with others on your 'get started' page if it helps.

They are doing exactly what I want to be doing, which is transforming the JSON and then streaming it to parquet and other JSON files for other users.

**Comment by charanthota** [comment]
You just need to make below classes Serializable. I was able to make it work with http://jolt-demo.appspot.com/#listKeys this example

jolt-core\src\main\java\com\bazaarvoice\jolt\Chainr.java 
jolt-core\src\main\java\com\bazaarvoice\jolt\common\pathelement\PathElement.java
jolt-core\src\main\java\com\bazaarvoice\jolt\common\PathEvaluatingTraversal.java
jolt-core\src\main\java\com\bazaarvoice\jolt\common\reference\PathReference.java
jolt-core\src\main\java\com\bazaarvoice\jolt\common\spec\BaseSpec.java
jolt-core\src\main\java\com\bazaarvoice\jolt\JoltTransform.java
jolt-core\src\main\java\com\bazaarvoice\jolt\traversr\traversal\TraversalStep.java
jolt-core\src\main\java\com\bazaarvoice\jolt\traversr\Traversr.java

**Comment by prabhathk14411** [comment]
You can also wrap the Jolt code inside a static class and use MeatLocker to make the function serializable to solve this issue.
public class TaskSerializationUtil {
  private TaskSerializationUtil() {

  } 
  public static Object joltTransform(String specJson, String input) {
    List chainrSpecJson = com.bazaarvoice.jolt.JsonUtils.stringToType(specJson, List.class);
    Chainr bchainr = Chainr.fromSpec(chainrSpecJson);
    return bchainr.transform(com.bazaarvoice.jolt.JsonUtils.stringToType(input, Object.class));
  } 

}

In spark job 

def genMapper[A, B , C ](f: (A, B) => C): (A, B) => C = {
        val locker = com.twitter.chill.MeatLocker(f)
        (x,y) => locker.get.apply(x,y)
  }

val transformFunction = genMapper(TaskSerializationUtil.joltTransform);

val mrdd = jsonRdd.map{x => transformFunction.apply(specjson,x)}
