### ISSUE TITLE
Having trouble transforming array of elements with no root

### ISSUE THREAD

**Issue by cah-jeffgraham** [bazaarvoice/jolt#302]
Great tool!  Its helped me a lot so far, although I'm having some learning pains with shift DSL.

I have the following input:
`[
{"task_name": "Full Load","table":"myTable","data":[{"proc":"xform"},{"name":"foo"}]},
{"task_name": "Part Load","table":"failTable","data":[{"proc":"baz"},{"name":"bar"}]}
]
`
would like like to transform to:
`[
{"proc":"xform","name":"foo"},
{"proc":"baz","name":"bar"}
]`

I had success in transforming a single element (using jolt-demo.appspot.com):

`{"task_name": "Full Load","table":"myTable","data":[{"proc":"xform"},{"name":"foo"}]}`

using this spec: 

`[
  {
    "operation": "shift",
    "spec": {
      "data": {
        "*": {
          "*": "&0"
        }
      }
    }
  }
]`

result:

`{"name" : "foo","proc" : "xform"}`

Attempted this spec:

`[
  {
    "operation": "shift",
    "spec": {
      "*": {
        "data": {
          "*": "&0"
        }
      }
    }
  }
]`

but returned:

`{
  "0" : [ {
    "proc" : "xform"
  }, {
    "proc" : "baz"
  } ],
  "1" : [ {
    "name" : "foo"
  }, {
    "name" : "bar"
  } ]
}`

Appreciate your help.

**Comment by milosimpson** [comment]
Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "*": { // top level array
        "data": {
          "*": { // data array (note we never reference this index)
            // here &3 references the index of the top level array
            "proc": "[&3].proc",
            "name": "[&3].name"
          }
        }
      }
    }
  }
]
```

**Comment by milosimpson** [comment]
Can be "simplified" if you know that you will only ever see "proc" and "name".
Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "*": { // top level array
        "data": {
          "*": { // data array (note we never reference this index)
            // here &3 references the index of the top level array
            "*": "[&3].&"
          }
        }
      }
    }
  }
]
```

**Comment by cah-jeffgraham** [comment]
Excellent!  The second example is exactly what I needed.  Thanks for the quick response.
