### ISSUE TITLE
Feature: =fromJson(<value>) to deserialize json string field to json type

### ISSUE THREAD

**Issue by nickcarenza** [bazaarvoice/jolt#303]
I have a field with serialized json that i want to hydrate.

Is there a way to currently do this with jolt? If so, how?
If not, would you consider it in scope to add it as a function? If so, would you be open to a contribution of that function?

**Comment by milosimpson** [comment]
Not so much Jolt needs to change, as how you read that stuff in and process it via Jackson.

I recommend doing whatever magic you need to do to de-serilaize the lines, and build in-memory hydrated Json (List<Object> and Map<String,Object>) and then hand it to Jolt to transform.

If you wanted to build a feature into modify-beta like "=deseralize( .. )" that is an interesting idea, but there are build / meta concerns.

Right now the "core" of jolt does not require / know / have any dependencies on Jackson, thus users are free to use what ever Json libraries they want of any version.

Given that a "=deseralize( .. )" function would most likely leverage one of those libraries, it would "need" to be an another "package" / jar and then how do you register it etc, etc.

So, right now safest / sanest thing to do is to "fix" your Json first...

**Comment by vamittal** [comment]
I am facing similar issue as some part of my JSON is serialised string.

Does JOLT now has functionality to deserialise as part of transformation spec?
