### ISSUE TITLE
How can I support jsonline (jsonl)

### ISSUE THREAD

**Issue by TroyLDay** [bazaarvoice/jolt#307]
I'd like to transform a json array of objects to a jsonline file for elasticsearch batch ingestion. Can this be supported? Will try to simplify the use case as much as possible:

input:
{
   "data": [
     {"id":1, ...},
     {"id":2 ,...}
   ]
}

desired output:

{"index": {"_id":1}}/lf
{"id":1, ...}/lf
{"index": {"_id":2}}/lf
{"id":2, ...}/lf

Note the linefeed utf8 character rather than commas and no parent {}

**Comment by milosimpson** [comment]
No.    Jolt really only deals with one "whole" json doc at a time.

**Comment by milosimpson** [comment]
Well, you could use jolt to move things around into a top level array, and then use jq or something else to strip the comma and add line breaks.

Input where I added some data to help see how it passes thru the transform
```
{
	"data": [
		{
			"id": 1,
			"a": "b"
		},
		{
			"id": 2,
			"number": 2
		}
	]
}
```

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "data": {
        "*": { // data array index
          "id": {
            "*": { // match all values of id
              //     [] means be an array, and each time we write to it append
              "$":  "[].index._id", // write the value of id
              "@2": "[]"   // got up 3 levels, (0,1,2), 
              						 // grab that whole object and write it to the output
            }
          }
        }
      }
    }
  }
]
```

Output
```
[
	{
		"index": {
			"_id": "1"
		}
	},
	{
		"id": 1,
		"a": "b"
	},
	{
		"index": {
			"_id": "2"
		}
	},
	{
		"id": 2,
		"number": 2
	}
]
```

**Comment by milosimpson** [comment]
The above output nicely formats to jsonl with the following jq 
```
cat output.json | jq -c ".[]"
```

**Comment by TroyLDay** [comment]
impressive - Thank you!
