### ISSUE TITLE
Nested functions with modify-overwrite operation

### ISSUE THREAD

**Issue by nickcarenza** [bazaarvoice/jolt#311]
Is it possible to nest functions with modify-overwrite? I have tried all the combinations I can think of and none seem to produce the desired result.

input:
```json
{
    "timestamp": 1484613919
}
```
spec:
```json
[{
	"operation": "modify-overwrite-beta",
	"spec": {
            "\\timestamp_ms": "=toLong(@(1,timestamp))"
	}
},{
	"operation": "modify-overwrite-beta",
	"spec": {
        "\\timestamp_ms": "=divide(@(1,&0),0.001)"
	}
},{
	"operation": "modify-overwrite-beta",
	"spec": {
        "\\timestamp_ms": "=toLong"
	}
}]
```
output
```json
{
    "timestamp_ms": 1484613919000
}
```
Or is there straight up a better way to do this. Sorry if I missed examples in code or docs.

**Comment by milosimpson** [comment]
"nest functions with modify-overwrite"  - Nope.

Your spec where you are repeated calling modify is close.

**Comment by nickcarenza** [comment]
It _does_ work, I was just hoping to be able to do something like:
```json
[{
	"operation": "modify-overwrite-beta",
	"spec": {
            "timestamp_ms": "=toLong(=divide(=toLong(@(1,timestamp)),0.001))"
	}
}]
```
or even this to make parsing simpler
```json
[{
	"operation": "modify-overwrite-beta",
	"spec": {
            "timestamp_ms": [["=toLong","@(1,timestamp)"], ["=divide", 0.001], "=toLong"]
	}
}]
```
And thank you, more examples on the demo page would be _very_ helpful. Any chance we could get a `=multiply` function as well?
