### ISSUE TITLE
Checking for Array and transforming object/primitive to array

### ISSUE THREAD

**Issue by rotemfogel** [bazaarvoice/jolt#312]
Hi @milosimpson ,
I need some help with checking if an object is an array and if not copying it to an array.
For example:
```
{  
   "id":"1",
   "imp":[  
      {  
         "id":"1",
         "banner":{  
            "w": 300,
            "h": 250,
            "btype":[ 1, 2, 3 ] // correct type - array
         }
      },
      {  
         "id":"2",
         "banner":{  
            "w": 600,
            "h": 800,
            "btype":"1" // wrong type primitive
         }
      },
      {  
         "id":"3",
         "banner":{  
            "w": 400,
            "h": 300,
            "btype":{  // wrong type object
            }
         }
      }
   ]
}
```
Expected Output:
```
{  
   "id":"1",
   "imp":[  
      {  
         "id":"1",
         "banner":{  
            "w": 300,
            "h": 250,
            "btype":[ 1, 2, 3 ]
         }
      },
      {  
         "id":"2",
         "banner":{  
            "w": 600,
            "h": 800,
            "btype": [1]
         }
      },
      {  
         "id":"3",
         "banner":{ 
            "w": 400,
            "h": 300
         }
      }
   ]
}
```

I need  way to:
1. Check if the btype is of type array
2. If an object, remove it
3. If a primitive construct an array of size 1
I know how to check if a node is present (?) and I know how to transform a primitive to an array.
How can I validate that the value is an array?
How can I remove elements based on their type?

Cheers,
Rotem.

**Comment by rotemfogel** [comment]
Hi @milosimpson,
Thank you for your response.
I have started writing my own transformer.
How do I write a spec for it?
What is the operation?

Thanks,
Rotem.

**Comment by milosimpson** [comment]
How do I write a spec for it?
 - Don't; at least initially.   Just implement https://github.com/bazaarvoice/jolt/blob/master/jolt-core/src/main/java/com/bazaarvoice/jolt/Transform.java   and make your Transform be specific to your data.

What is the operation?
- Whatever you class name is.
- Example : 
```
"operation" : "com.bazaarvoice.jolt.chainr.transforms.GoodTestTransform"
```
from 
https://github.com/bazaarvoice/jolt/blob/master/jolt-core/src/test/resources/json/chainr/transforms/loadsGoodTransform.json test

**Comment by rotemfogel** [comment]
Excellent. 
Thank you for your swift response.

**Comment by milosimpson** [comment]
To be clear the custom transform will by kind of ugly.

The very safe way.
```
        do {
            if ( ! (input instanceof Map ) ) {
                break;
            }

            Map<String,Object> inputMap = (Map<String,Object>) input;

            Object imp = inputMap.get("imp");

            if ( ! (imp instanceof List) ) {
                break;
            }

            List<Object> impList = (List<Object>) imp;

            // Loop thru each item of "imp[]", grab and fix "banner.btype"
            for ( Object a : impList ) {
                // todo
            }



        } while (false);

        return input;
```

**Comment by rotemfogel** [comment]
Actually, I have several of theses types.
I figured, I would have to traverse the object and validate/replace the actual values.

**Comment by milosimpson** [comment]
Slightly less bad, using JoltUtil.navigateSafe
```
        do {
            List<Object> impList = JoltUtils.navigateSafe( null, input, "imp" );

            if ( impList == null ) {
                break;
            }

            // Loop thru each item of "imp[]", grab and fix "banner.btype"
            for ( Object a : impList ) {
                // todo

            }

        } while (false);

        return input;
```
