### ISSUE TITLE
Adding the value of an existing field in a node to a new field in an Array

### ISSUE THREAD

**Issue by codequester** [bazaarvoice/jolt#313]
Hi , 

Given the below input json 
```
{
	"location": "chicago",
	"entries": [{
		"name": "aaa",
		"id": "001"
	}, {
		"name": "bbb",
		"id": "002"
	}]
}
```
Please let me know how to transform the above json as below
```
{
	"participants": [{
		"name": "aaa",
		"id": "001",
                "location": "chicago"
	}, {
		"name": "bbb",
		"id": "002",
                "location": "chicago"
	}]
}
```
Please note that the length of the entries are not known before. So if there are 100 entires the location from root should be copied over to all the 100 entries. I tried the below spec but its only adding the location to the 1st element
```
[
  {
    "operation": "shift",
    "spec": {
      "location": "participants[].location",
      "entries": {
        "*": {
          "name": "participants[&1].name",
          "id": "participants[&1].id"
        }
      }
    }
  }
]
```
Any help is very much appreciated.

Thanks

**Comment by milosimpson** [comment]
Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "entries": {
        "*": {
          "@(2,location)": "participants[&1].location",
          "name": "participants[&1].name",
          "id": "participants[&1].id"
        }
      }
    }
  }
]
```

You were close.    To get the location into each of the entries array, the way to do that is to go look it up, "@(2,location)", for each item in the entries array.

**Comment by codequester** [comment]
@milosimpson  Thanks so much! It worked like a charm  and thanks for JOLT, its such an awesome library!!!
