### ISSUE TITLE
Custom transform spec reference  

### ISSUE THREAD

**Issue by dcappieri** [bazaarvoice/jolt#315]
Hi,
Is it possible to not have my Custom Transform in my class path.
e.g.

```
[
  {
    "operation" : "/home/user/Development/joltFiles/CustomTransform.java",
    "spec" : {
                "a" : "b"
    }
   }
]
```

Currently I’m getting the error:

> "JOLT Chainr could not find transform class:/home/user/Development/joltFiles/CustomTransform.java at index:0.

**Comment by milosimpson** [comment]
Use the className (and make sure your class is in the classpath of the running system), not a file path.

Something like
```
"operation" : "joltFiles.CustomTransform",
```

**Comment by dcappieri** [comment]
Thanks for your reply. Is there a way to use a file path instead of class path?

**Comment by milosimpson** [comment]
No.    What is your usecase where you want to load from the filesystem?

Also if you did you would need to point at the compiled .class file instead of the .java source file.

**Comment by dcappieri** [comment]
So what I want to do is have my jolt task running and have a separate library of spec files. I use a different spec folder depending on what input I use.
Its all working fine except for the custom transformer which looks like it needs to be packaged with the jolt task and I would like it to be kept separate
