### ISSUE TITLE
Remove null value from list

### ISSUE THREAD

**Issue by KrishnaNagar** [bazaarvoice/jolt#317]
Hello, 
I jst want to remove all null values from list . Please help me to do so

INPUT : 
```
[
	{
		"key1": "value1",
		"Key2": "value2",
		"Key3": "value3"
	},{
		"key1": "value4",
		"Key2": "value5",
		"Key3": "value6"
	},
	null,
        {
		"key1": "value7",
		"Key2": "value8",
		"Key3": "value9"
	}
]
```
EXPECTED OUTPUT : 
```
[
	{
		"key1": "value1",
		"Key2": "value2",
		"Key3": "value3"
	},{
		"key1": "value4",
		"Key2": "value5",
		"Key3": "value6"
	},
       {
		"key1": "value7",
		"Key2": "value8",
		"Key3": "value9"
	}
] 
```
Thnks

**Comment by milosimpson** [comment]
There is not a clean and easy way to do that.

**Comment by KrishnaNagar** [comment]
Do it have provision to remove string "removeIt"? if null is replaced by any string?

[
	{
		"key1": "value1",
		"Key2": "value2",
		"Key3": "value3"
	},{
		"key1": "value4",
		"Key2": "value5",
		"Key3": "value6"
	},
	"removeIt",
        {
		"key1": "value7",
		"Key2": "value8",
		"Key3": "value9"
	}
]

or if null is replaced by map , 

[
	{
		"key1": "value1",
		"Key2": "value2",
		"Key3": "value3"
	},{
		"key1": "value4",
		"Key2": "value5",
		"Key3": "value6"
	},
	{
                "toBeRemoved":null
        },
        {
		"key1": "value7",
		"Key2": "value8",
		"Key3": "value9"
	}
]

want the same output mentioned above.
