### ISSUE TITLE
Remove quotes or convert types...

### ISSUE THREAD

**Issue by nishal** [bazaarvoice/jolt#318]
input (array of such items as below):
```
[{
  "number" : "60.00",
  "date" : "2012-01-17T12:00:00Z",
  "percentage" : "2.8",
  "price" : "4084"
}, {...}, {...}]
```
needed output:
```
[{
  "number" : 60,
  "date" : "2012-01-17T12:00:00Z",
  "percentage" : 2.8,
  "price" : 4084
}, {...}, {...}]
```
As the needed output shows, the numbers in quotes are replaced without quotes. Is this possible with JOLT? If YES, then show me the spec for it. I'm using http://jolt-demo.appspot.com/#inception to test, so prefer if solution is testable online. TIA

**Comment by milosimpson** [comment]
Play with http://jolt-demo.appspot.com/#modify-typeConversion
