### ISSUE TITLE
Unable to Convert array to comma separted String

### ISSUE THREAD

**Issue by sri33519** [bazaarvoice/jolt#321]
Hi Team,
 I need to convert array values to comma separated String. Input data, Expected Output, Tried Specification, Output getting is given below. I have tried Custom Transformation also, getting data object in the Custom Transformation class but unable to understand how to proceed further. Could you please help on this. Thanks in Advance.

Input data:
------------
```
{
  "p_err_code": "success",
  "all": {
    "count": 3,
    "data": [
      {
        "key1": "val1",
        "key2": "val2",
        "key3": "val3",
        "key4": [
          "val5",
          "val6",
          "val7",
          "val8"
        ],
        "key5": "val9",
        "key6": [
          "val10",
          "val11",
          "val12"
        ],
        "key7": "val13",
        "key8": [
          "val14",
          "val15"
        ]
      },
      {
        "key1": "val16",
        "key2": "val17",
        "key3": "val18",
        "key4": [
          "val19",
          "val20"
        ],
        "key5": "val21",
        "key6": [
          "val22",
          "val23",
          "val24",
          "val25"
        ],
        "key7": "val26",
        "key8": [
          "val27",
          "val28",
          "val29"
        ]
      },
      {
        "key1": "val30",
        "key2": "val31",
        "key3": "val32",
        "key4": [
          "val33",
          "val34",
          "val35",
          "val36",
          "val37"
        ],
        "key5": "val38",
        "key6": [
          "val39"
        ],
        "key7": "val40",
        "key8": [
          "val41",
          "val42"
        ]
      }
    ]
  },
  "totalcount": 3
}
```
Expected Output:
------------------
```
[
  {
    "Keyone": "val1",
    "Keytwo": "val2",
    "Keythree": "val3",
    "Keyfour": "val5, val6, val7, val8",
    "Keyfive": "val9",
    "Keysix": "val10, val11, val12",
    "Keyseven": "val13",
    "Keyeight": "val14, val15"
  },
  {
    "Keyone": "val16",
    "Keytwo": "val17",
    "Keythree": "val18",
    "Keyfour": "val19, val20",
    "Keyfive": "val21",
    "Keysix": "val22, val23, val24, val25",
    "Keyseven": "val26",
    "Keyeight": "val27, val28, val29"
  },
  {
    "Keyone": "val30",
    "Keytwo": "val31",
    "Keythree": "val32",
    "Keyfour": "val33, val34, val35, val36, val37",
    "Keyfive": "val38",
    "Keysix": "val39",
    "Keyseven": "val40",
    "Keyeight": "val41,val42"
  }
]
```
Tried Spec:
------------
[
  {
    "operation": "shift",
    "spec": {
      "all": {
        "data": {
          "*": {
            "key1": "[&1].Keyone",
            "key2": "[&1].Keytwo",
            "key3": "[&1].Keythree",
            "key4": {
              "*": "[&2].keyfour"
            },
            "key5": "[&1].keyfive",
            "key6": {
              "*": "[&2].keysix"
            },
            "key7": "[&1].keyseven",
            "key8": {
              "*": "[&2].keyeight"
            }
          }
        }
      }
    }
  }
]

Output for the above spec:
----------------------------
[
  {
    "Keyone": "val1",
    "Keytwo": "val2",
    "Keythree": "val3",
    "Keyfour": [
      "val5",
      "val6",
      "val7",
      "val8"
    ],
    "Keyfive": "val9",
    "Keysix": [
      "val10",
      "val11",
      "val12"
    ],
    "Keyseven": "val13",
    "Keyeight": [
      "val14",
      "val15"
    ]
  },
  {
    "Keyone": "val16",
    "Keytwo": "val17",
    "Keythree": "val18",
    "Keyfour": [
      "val19",
      "val20"
    ],
    "Keyfive": "val21",
    "Keysix": [
      "val22",
      "val23",
      "val24",
      "val25"
    ],
    "Keyseven": "val26",
    "Keyeight": [
      "val27",
      "val28",
      "val29"
    ]
  },
  {
    "Keyone": "val30",
    "Keytwo": "val31",
    "Keythree": "val32",
    "Keyfour": [
      "val33",
      "val34",
      "val35",
      "val36",
      "val37"
    ],
    "Keyfive": "val38",
    "Keysix": [
      "val39"
    ],
    "Keyseven": "val40",
    "Keyeight": [
      "val41",
      "val42"
    ]
  }
]

Tried Customclass:
--------------------

package com.mycompany.mavenroughwork;

import com.bazaarvoice.jolt.Transform;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

public class ArrayToStringJSONTransform implements Transform {

    @Override
    public Object transform( Object input ) {
        // Grab the time out of the incoming Json data / Map
        HashMap all =  (HashMap)((Map) input).get("all"); 
        ArrayList data =  (ArrayList)all.get("data");
        System.out.println("data :  "+data);
        
		String transformedData="Need to do";
        // Overwrite the old value with the new / fixed one.
       return ((Map) input).put("composition", transformedData); 
        
        
    }
}

**Comment by mhubbard** [comment]
This is about as close as I was able to get for you:

Spec: 
```json
[
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "all": {
        "data": {
          "*": {
            "key1": "=concat(@(1,key1))",
            "key2": "=concat(@(1,key2))",
            "key3": "=concat(@(1,key3))",
            "key4": "=concat(@(1,key4))",
            "key5": "=concat(@(1,key5))",
            "key6": "=concat(@(1,key6))",
            "key7": "=concat(@(1,key7))",
            "key8": "=concat(@(1,key8))"
          }
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "all": {
        "data": {
          "*": {
            "*": "[&1].&"
          }
        }
      }
    }
  }
]
```
Output:
```json
[ {
  "key1" : "val1",
  "key2" : "val2",
  "key3" : "val3",
  "key4" : "[val5, val6, val7, val8]",
  "key5" : "val9",
  "key6" : "[val10, val11, val12]",
  "key7" : "val13",
  "key8" : "[val14, val15]"
}, {
  "key1" : "val16",
  "key2" : "val17",
  "key3" : "val18",
  "key4" : "[val19, val20]",
  "key5" : "val21",
  "key6" : "[val22, val23, val24, val25]",
  "key7" : "val26",
  "key8" : "[val27, val28, val29]"
}, {
  "key1" : "val30",
  "key2" : "val31",
  "key3" : "val32",
  "key4" : "[val33, val34, val35, val36, val37]",
  "key5" : "val38",
  "key6" : "[val39]",
  "key7" : "val40",
  "key8" : "[val41, val42]"
} ]
```
