### ISSUE TITLE
convert string array into list of objects

### ISSUE THREAD

**Issue by gangakrishh** [bazaarvoice/jolt#323]
INPUT
---------
```
{
	"author": [
		"krish",
		"dev"
	]
}
```

Expected OUTPUT
```
{
     "author": {
          "firstName":"krish",
          "lastName":"dev"
     }
}
```

**Comment by houjincheng1992** [comment]
how about the following:

[
  {
    "operation": "shift",
    "spec": {
      "author": {
        "0": "author.firstName",
        "1": "author.lastName"
      }
    }
  }
]

**Comment by gangakrishh** [comment]
this is ok, can we split the string into array of String

`{ "author": "krish, dev"}`  = { "author": ["krish", "dev"]}

**Comment by milosimpson** [comment]
Yes, it is an odd usage, but works.

Input
```
{
	"author": "krish, dev"
}
```

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "author": {
        "*, *": {
          "$(0,1)": "author[0]",
          "$(0,2)": "author[1]"
        }
      }
    }
  }
]
```

Output
```
{
  "author" : [ "krish", "dev" ]
}
```

**Comment by mcandar** [comment]
Hey, isn't there any way to do this transformation dynamically?

{ "author": "word1,word2,word3,......"} = { "author": ["word1","word2","word3",....]}

Hardcoding does not provide a good generalization.
