### ISSUE TITLE
How to match "match" to data driven elements.

### ISSUE THREAD

**Issue by mhubbard** [bazaarvoice/jolt#325]
Hopefully this makes sense, I'm trying to loop through an array of objects, and if a value within that object is the same as a value outside of the array, I want to copy the object's contents. For example, with this input:
```json
{
	"clientActive": "AXE",
	"clients": [
		{
			"clientId": "Acme",
			"index": 1
		},
		{
			"clientId": "AXE",
			"index": 0
		}
	],
	"data": {
		"bookId": null,
		"bookName": "Enchiridion"
	}
}
```
I would like to loop through clients, and if clientId is the same as clientActive, I would like it's index. I'm trying spec
```json
[
  {
    "operation": "shift",
    "spec": {
      "clients": {
        "*": {
          "clientId": {
            "@(3,clientActive)": {
              "@(2,index)": "index"
            }
          }
        }
      }
    }
  }
]
```
But I'm getting the index of both clients, with the output being
```json
{
  "index" : [ 1, 0 ]
}
```
If I replace "@(3,clientActive)" with "AXE" I get my desired output. Is dynamic matching/if possible? or do I have to hardcode it?

**Comment by milosimpson** [comment]
Yes, can be done.   Have to do two shifts.

You can use "&" on the RHS of a shift to "match something already in the tree", so the first shift :

1) pivots the "clientActive" / "AXE" to be "above" the clients[]
2) shift can now match "AXE" in "both" places.

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "clients": "clientActive.@(1,clientActive)"
    }
  },
  {
    "operation": "shift",
    "spec": {
      "clientActive": {
        "*": { // AXE or whatever
          "*": { // index
            "clientId": {
              "&2": { // if the value of clientId matches
                // AXE which is 2 levels up
                "@(2,index)": "index"
              }
            }
          }
        }
      }
    }
  }
]
```

**Comment by mhubbard** [comment]
Thanks you for the help I forget to try doing things in multiple shifts. Just wondering why my original solution didn't work, does '@' not work with matching but '&' does? 

I do have one more issue I hope you can help me with, using the above scenario, I need to always store Acme's index in an element, as well as the active client's index in another. So using your spec it's
```json
[
  {
    "operation": "shift",
    "spec": {
      "clients": "clientActive.@(1,clientActive)"
    }
  },
  {
    "operation": "shift",
    "spec": {
      "clientActive": {
        "*": {
          "*": {
            "clientId": {
              "&2": {
                "@(2,index)": "activeClientIndex"
              },
              "Acme": {
                "@(2,index)": "acmeIndex"
              }
            }
          }
        }
      }
    }
  }
]
```

Which is working great when the active client is AXE, however when "clientActive" is Acme then I only get I only get "acmeIndex" in my output, and not "activeClientIndex".

Here's the example input 
```json
{
	"clientActive": "Acme",
	"clients": [
		{
			"clientId": "Acme",
			"index": 1
		},
		{
			"clientId": "AXE",
			"index": 0
		}
	],
	"data": {
		"bookId": null,
		"bookName": "Enchiridion"
	}
}```

**Comment by milosimpson** [comment]
Q: Just wondering why my original solution didn't work, does '@' not work with matching but '&' does?
A: Yes, & matches.   @ is always "fires" if the parent matched.

**Comment by milosimpson** [comment]
"Which is working great when the active client is AXE, however when "clientActive" is Acme then I only get I only get "acmeIndex" in my output, and not "activeClientIndex".  "

Yep, if "Acme" is also the "activeClient" then it will only match once.
```
            "clientId": {
              "&2": {
                "@(2,index)": "activeClientIndex"
              },
              "Acme": {
                "@(2,index)": "acmeIndex"
              }
            }
```
Because "&2" and "Acme" are the same thing only, once can match.

**Comment by milosimpson** [comment]
Ha, can do it in two.

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      // pass clientActive thru
      "clientActive": "clientActive",
      // build a clientNameToIndexMap
      "clients": {
        "*": {
          "index": "clientNameToIndexMap.@(1,clientId)"
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      // easily pull out acmeIndex from the clientNameToIndexMap
      "clientNameToIndexMap": {
        "Acme": "acmeIndex"
      },
      // match clientActive, and match it's value
      "clientActive": {
        "*": {
          // "re-parent" the tree up and over to clientNameToIndexMap
          "@(2,clientNameToIndexMap)": {
            // now use LHS & match to find the activeClientIndex
            "&1": "activeClientIndex"
          }
        }
      }
    }
  }
]
```
