### ISSUE TITLE
requre Jolt Demo code

### ISSUE THREAD

**Issue by KrishnaNagar** [bazaarvoice/jolt#328]
Hello, 

We are using http://jolt-demo.appspot.com/ for creating and testing jolt spects. But the problem occurs is that if jolt version is upgraded on the site then, older jolt spects do not run properly, or our tested jolts on the site do not run with our older version of jolt-core used in our project. This creates problem in our software and we have to put extra efforts for recreating that jolt spec again.  Please share code that is being used in latest version of demo site so that  we can just use that version and we do not get much problem with different jolt versions.

Thank you for your support.

**Comment by milosimpson** [comment]
Yeah, working on that.   The free hosting Google provides is not compatible with Java 8, which has been upgraded too.

**Comment by milosimpson** [comment]
Also, the code for the demo site is https://github.com/milosimpson/jolt-demo/   

Theoretically you can fork it, and run it locally.

**Comment by KrishnaNagar** [comment]
Thank you. It is working good.
