### ISSUE TITLE
Using Context for custom Transforms

### ISSUE THREAD

**Issue by dbgrey44** [bazaarvoice/jolt#330]
I checked out the code, expecting to see a Transform level mapping that can be leveraged across individual Transform as metadata. For e.g. : Transform x will have an entry in Context Map<String, Object> as "x"->(your object), so that at runtime the entire object is available to the corresponding transform.
But the code doesn't looks like that. Am I understanding the use of Context in a wrong manner?
Can you please explain with an example where it is being leveraged in the current set of Transformations?

The reason I am asking is that I am implementing some functions of my own and I was thinking to allow users to add runtime data to the new transformation. Can anyone guide me on how to achieve this with the current setup?

**Comment by milosimpson** [comment]
The "context" is to allow for "extra" information to be passed to the Transforms.

The "canonical" example/use-case at Bazaarvoice was for "photo urls".

We have a custom Java Photos transform, that needs to know if it needs to build "http" or "https" urls.   It looks for a "well know" key in the Context Map.

Code outside of Jolt populates the context map, and then you call the Chainr method that takes a Context map.

For a single "run" of Chainr, all transforms that implement "ContextualTransform" interface, are passed the Context.

**Comment by milosimpson** [comment]
For example Java code see this unit test : 
https://github.com/bazaarvoice/jolt/blob/master/jolt-core/src/test/java/com/bazaarvoice/jolt/ChainrContextTest.java
which uses test data
https://github.com/bazaarvoice/jolt/blob/master/jolt-core/src/test/resources/json/chainr/context/spec_with_context.json

**Comment by dbgrey44** [comment]
That is good, but the thing is there is no separation of context from one transform to the another. Assuming I am performing a lot of operations each with a separate set of metadata (and not just a simple json, each operation takes its own context object based on the need), for the current setup the same context will be used for all operations. For e.g. : Sorting operation might take a custom comparator logic.  But this is needed just by sorting operation. 
Allowing the same context for all the operations doesn't make sense. 

Let me know your suggestions.
