### ISSUE TITLE
default op and Arrays

### ISSUE THREAD

**Issue by mhardin18** [bazaarvoice/jolt#331]
I'm having trouble getting the default operation to insert a value into an object that is an array.

Input:
```
{
	"mickey": [{
			"bar": 1
		}, {
			"bar": 2
		}
	]
}
```
Expected Output:
```
{
	"mickey": [{
                        "foo": 3,
			"bar": 1
		}, {
                        "foo": 3,
			"bar": 2
		}
	]
}
```

Spec:
```
[{
		"operation": "default",
		"spec": {
			"mickey": {
				"*": {
					"foo": 3
				}
			}
		}
	}
]
```

Actual output:
```
{
  "mickey" : [ {
    "bar" : 1
  }, {
    "bar" : 2
  } ]
}
```

Any help would be appreciated.   Thanks for the tool and the time.

**Comment by milosimpson** [comment]
Spec
```
[
  {
    "operation": "default",
    "spec": {
      "mickey[]": {
        "*": {
          "foo": 3
        }
      }
    }
  }
]

```

Each "operation" has it's own syntax and DSL.   "default" and "modify" have to know that they are are supposed to operate on an array, thus "mickey[]" so that default know that mickey is supposed to be an array.
