### ISSUE TITLE
Grouping by key value

### ISSUE THREAD

**Issue by kruton** [bazaarvoice/jolt#333]
I'm trying to take the output of a JMH run in JSON format and put it into a plot.ly-style JSON data file. I've gotten it pared down to the data I need, but I need some way of grouping by the value of a key so that I can graph it with plot.ly.

I'm assuming I'm going to have to write my own Transform implementation for this, but I figured I'd post here first just to see if I'm missing some existing functionality.

input:
```json
[
{
  "data" : {
    "x" : "64 bytes",
    "y" : 48938,
    "yError" : 348
  },
  "name" : "benchmark1"
},
{
  "data" : {
    "x" : "128 bytes",
    "y" : 23942,
    "yError" : 123
  },
  "name" : "benchmark1"
},
{
  "data" : {
    "x" : "64 bytes",
    "y" : 15000,
    "yError" : 117
  },
  "name" : "benchmark2"
},
{
  "data" : {
    "x" : "128 bytes",
    "y" : 8001,
    "yError" : 91
  },
  "name" : "benchmark2"
},
{
  "data" : {
    "x" : "256 bytes",
    "y" : 3983,
    "yError" : 41
  },
  "name" : "benchmark2"
}
]
```

desired output:
```json
[
{
  "name": "benchmark1",
  "x": [ "64 bytes", "128 bytes", "256 bytes" ],
  "y": [ 48938, 23942 ],
  "yError": [ 348, 123 ]
},
{
  "name": "benchmark2",
  "x": [ "64 bytes", "128 bytes", "256 bytes" ],
  "y": [ 15000, 8001, 3983 ],
  "yError": [ 117, 91, 41 ]
}
]
```

**Comment by milosimpson** [comment]
Possible to do, requires 3 shifts.

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      // pivot the data by benchmark name
      "*": {
        "name": {
          "*": { // match any value of name
            // go up the tree 3 levels
            // grab the whole array element and 
            // write it to the output in an array
            // aka benchmark1[] or benchmark2[]
            "@(3,[&2])": "&.[]"
          }
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      // now group the x,y,yError data
      "*": { // benchmark 1 or 2
        "$": "&.name",
        "*": { // array of benchmark1 or 2
          "data": {
            "x|y|yError": "&3.&[]"
          }
        }
      }
    }
  },
  {
    // now convert from a map to a top level list
    "operation": "shift",
    "spec": {
      // benchmark1 or benchmark2
      "*": "[#1]"
    }
  }
]
```

I recommend looking at what each step does individually on the demo site.   http://jolt-demo.appspot.com/#inception

**Comment by kruton** [comment]
Ah, I wasn't aware of ablity the `@(3,[&2])`! Do you mind if I use this in an Apache 2 licensed project?

**Comment by milosimpson** [comment]
This project is Apache 2 license. 

https://github.com/bazaarvoice/jolt/blob/master/LICENSE

So, should be fine.   Would like to know which project.   I know that Jolt has been pulled into Apache Nifi.

**Comment by kruton** [comment]
It is going to be used to convert [JMH benchmark](http://openjdk.java.net/projects/code-tools/jmh/) results to an HTML page using [Plotly JSON chart schema](http://help.plot.ly/json-chart-schema/) for a crypto library called [Conscrypt](https://github.com/google/conscrypt/).
