### ISSUE TITLE
Query related to Exceptions for custom transform

### ISSUE THREAD

**Issue by dbgrey44** [bazaarvoice/jolt#334]
I'm creating my own custom transformation, but I am a bit confused as to what the best approach should be regarding throwing the RuntimeExceptions (JoltExceptions). 
Should in case of any exceptions, I should return the same json without any operation/transformation or return the runtime exceptions? 
It sounds silly at first and seems obvious to throw exceptions; but because it is a chain of of operations, any time any assumption that isn't met by the client might lead to breaking this entire chain. There can be a lot of instances where the spec is correct and the user input might lead to RuntimeExceptions and since these are not checked the client might not be able to properly handle them.

Can anyone provide some tips as to in which cases I shouldn't throw the exception, but instead do a no-op and in which cases exception must be thrown back to the client.

**Comment by milosimpson** [comment]
Jolt is for transforming data, not schema enforcement.   If you need schema enforcement, you should layer on another tool after Jolt to verify schema.

Throwing exceptions given "weird" / "bad input data" starts the slippery slope to schema enforcement / validation.

Thus, the philosophy of the OOTB Jolt Operations is to "try to" never throw a TransformException.  
Thus, Jolt leans toward "no-op"-ing.

SpecExeptions are for error in processing a spec at load time.
