### ISSUE TITLE
modify-defalut-beta fails when try to assign integer value with leading zero

### ISSUE THREAD

**Issue by SUNYTYAGI** [bazaarvoice/jolt#335]
```
Hi, Below specs not working because of leading zero in 01.Is it valid scenario? why?
[
  {
    "operation": "modify-default-beta",
    "spec": {
      "roll-number": 01 // if replace 01 with 1 it is working
    }
  }
]

```

**Comment by milosimpson** [comment]
Because '01' is not a String.   It gets read in as an Interger/Long, and thus comes out as '1'.

**Comment by SUNYTYAGI** [comment]
Agree. But it should not throw error.It should assign 1 (not 01) to roll-number.

**Comment by milosimpson** [comment]
It throws a stack trace?

**Comment by SUNYTYAGI** [comment]
No. But it says spec is not valid.

**Comment by milosimpson** [comment]
Given that there is no way for it to actually put '01' in the output, then it saying the spec is not valid is actually good thing, no?

What is worse.   Specifying '01' and getting '1', or being told '01' does not work?
