### ISSUE TITLE
Doing merge of two field values in the output json

### ISSUE THREAD

**Issue by prantan7** [bazaarvoice/jolt#336]
I have recently started using JOLT for json transformations and it seems that I need to write a custom
transformation for something like below;

Input
{
  "first_name" : "user",
  "last_name" : "test",
}

Output
{
  "name" : "user test"
}

I also see some stock functions like toLower,toUpper defined in the Modifier class. Could you please
provide reference how these could be used?

**Comment by milosimpson** [comment]
See and play with : http://jolt-demo.appspot.com/#modify-stringConcat

**Comment by prantan7** [comment]
Thanks the concatentation worked and now am able to merge the values of two fields into the new one.

I will write remove spec to remove the original values.

I was facing another issue while adding an object to an array using default
