### ISSUE TITLE
Adding custom functions

### ISSUE THREAD

**Issue by steveratay** [bazaarvoice/jolt#337]
Is there any documentation around adding custom functions to Jolt?  For example, it would be great to be able to support adding a regex replacement.  The spec might look something like this, to replace all digits with an "X".
```
{ "someString": "=regex(@(1,&0), '[0-9]', 'X')" }
```

**Comment by milosimpson** [comment]
No.   It is a thing I would like to get to, but the infrastructure to get there is not ready.

**Comment by steveratay** [comment]
OK, thanks Milo. We might have a look at what it would take to make that happen. From what I've seen in the code, the list of functions supported today is pretty much baked into the Jolt source code. I would imagine there could be some fairly straightforward ways we could make that a bit more dynamic.

I also saw that the Function code is marked deprecated. Can you provide any more commentary on the future of that code? Is there a plan to replace it? Just trying to gauge where, and if, it's worth having my team invest in this area.

**Comment by milosimpson** [comment]
Baking it in is ok.   A pull request with good unit tests would be good.

The tricky thing is allowing user to register a Function, in the same way that they can specify their own "operations".   There was alot of complexity in loading the custom classes and whatnot.

**Comment by milosimpson** [comment]
The Function interface is marked as @deprecated case as we weren't happy with it.  

The tricky thing there is making it easy for people to implement the Function interface.
* Does it need access to the "stack" / WalkedPath
* Does the interface just take Object, or can some machinery be built to narrow down to I want a list, map, scalar...  etc

**Comment by steveratay** [comment]
Thanks!

**Comment by Prasaddiwalkar** [comment]
> 

@milosimpson what is the alternative way to register custom functions

**Comment by Prasaddiwalkar** [comment]
> > 
> 
> @milosimpson what is the alternative way to register custom functions


I have followed https://github.com/bazaarvoice/jolt/issues/1091 but applySingle is not getting hit during transformation.
