### ISSUE TITLE
Using TransposePathElement with modifier

### ISSUE THREAD

**Issue by dbgrey44** [bazaarvoice/jolt#340]
I was trying to use @() syntax in lhs part of the spec for modifier operation. The syntax doesn't seem to be supported as of now.
Is there any specific reason for not using the syntax for making an upward tree traversal? Or is there any other approach provided by the operation?

The reason I am asking is I wanted to do a conditional modification where I want to modify the subtree only if the subtree has a specific property equal to a specific value. 

Any guidance or help will be greatly appreciated.

**Comment by milosimpson** [comment]
See https://github.com/bazaarvoice/jolt/issues/325

In that one, he only wants do do something if two values match in the document.
