### ISSUE TITLE
Remove and default operations based on conditions

### ISSUE THREAD

**Issue by prantan7** [bazaarvoice/jolt#344]
I am able to remove attributes from the input JSON using the remove operation but I need to check for a condition if it does not have any value then only remove the attribute else keep it.

Same is the case with default when input does not contain an attribute, then I want to populate the attribute with a value of "". If the input contains the attribute don't do anything

```
INPUT
{
	"data": {
		"id": "12345",
		"name": "sample",
		"components": [
			{
				"category": "custom",
				"fields": [
					{
						"id": "fld001",
						"label": "123"
					},
					{
						"id": "fld002",
						"label": ""
					}
				]
			}
		]
	}
}
```

```
OUTPUT

{
  "data" : {
    "components" : [ {
      "category" : "custom",
      "fields" : [ {
        "id" : "fld001"
         "label" : "123"
      }, {
        "id" : "fld002"
      } ]
    } ],
    "id" : "12345",
    "name" : "sample"
  }
}
```

```
Spec

[
  {
    "operation": "remove",
    "spec": {
      "data": {
        "components": {
          "*": {
            "fields": {
              "*": {
                "label": ""
              }
            }
          }
        }
      }
    }
   }
]
```

**Comment by milosimpson** [comment]
Q: I need to check for a condition if it does not have any value then only remove the attribute else keep it. 
A: Remove does not support conditional logic.

Q: default when input does not contain an attribute, then I want to populate the attribute with a value of "". If the input contains the attribute don't do anything
A: That is what the "default" operation does.

**Comment by prantan7** [comment]
Q: I need to check for a condition if it does not have any value then only remove the attribute else keep it.
A: Remove does not support conditional logic.

>>Is there any other way to do this by other operations or it can be done only by a custom transformer.

I could do the second part of adding an attibute if it does not exist, using the **modify-default-beta but not default operation.**

Below is the spec which does the job for me
```
[
  {
    "operation": "modify-default-beta",
    "spec": {
      "data": {
        "components": {
          "*": {
            "fields": {
              "*": {
                "label": ""
              }
            }
          }
        }
      }
    }
  }
]
```

**Comment by milosimpson** [comment]
Q: I really need conditional removal, and I really really don't want to write any code.
A: You can effectively do it with "shift", but that means shift-ing everything thru except the thing you don't want.   Done that before, but never tried to match empty string, "".

Seems to work

Input, where want to "remove" the b, case it RHS is ""
```
{
	"a": 1,
	"b": "", 
	"c": "c"
}
```

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "*": { // a, b, or c
        
        // match values of a/b/c
        "": null,
        "*": {
          "$": "&2"
        }
      }
    }
  }
]
```

I could do the second part of adding an attibute if it does not exist, using the modify-default-beta but not default operation.

Ok.
