### ISSUE TITLE
Extract/Remove substring value from input string

### ISSUE THREAD

**Issue by avish-3pg** [bazaarvoice/jolt#345]
Hello @milosimpson ,

I was wondering if it is possible to extract or remove a part of string value from the input. 

For example, if we can want to extract last part of the string for **"Values": "first_second_third"** into **"Values": "third"**. 

Also, if we can lets say remove double quotes ("") from a input string value like for example 
**"Values": "[{\\"first\\": \\"second\\"}]"** into **"Values": [{"first": "second"}]**; as we can see that not only removes the '\\' but also converts the string value into a JSON list.

Below is an actual example of my use case - 

**Input JSON -** 
```
{
"ID": "first_second_third",
"Values": 
"[{\"QuestionId\":\"R01\",\"Response\":null,\"NumberValue\":1},{\"QuestionId\":\"R02\",\"Response\":null,\"NumberValue\":2}]"
}
```

**Output JSON -** 
```
"ID": "third",
"Values": 
[
{"QuestionId":"R01","Response":null,"NumberValue":1},
{"QuestionId":"R02","Response":null,"NumberValue":2}
]
```

Please advice. Thank you.

**Comment by milosimpson** [comment]
You can break "ID": "first_second_third", apart because there is a unique delimiter, namely "_".
Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "ID": {
        "*_*_*": {
          "$(0,1)": "id_1",
          "$(0,2)": "id_2",
          "$(0,3)": "id_3"
        }
      }
    }
  }
]
```

This is no OOTB way to "de-Java escape" the Values string.   Can't even do the same trick as with "ID": "first_second_third", because there is no delimiter you can pick for the Values string.

**Comment by avish-3pg** [comment]
Thank you @milosimpson . I have a quick follow up question regarding selectively extracting values from a input json map. Below is an example - 

**Input JSON** - 
```
"results": [
		{
			"Id": "Id0001",
			"NumberValue": 1
		},
		{
			"Id": "Id0002",
			"TextValue": "JOLT is awesome"
		}
```

**JOLT Spec** - 
Check to see if the Id = Id0002, and filter out the output JSON based that as in below.

**Output JSON** - 
```
"results":[{
		{
			"Id": "Id0002",
			"TextValue": "JOLT is awesome"
		}
}]
```

**Comment by milosimpson** [comment]
Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "results": {
        "*": {
          "TextValue": {
            "JOLT is awesome": {
              // if we matched down all this way
              // then go backup the tree 3 levels, 
              // grab that whole object and copy it
              // across to "results[]"
              "@2": "results[]"
            }
          }
        }
      }
    }
  }
]
```

**Comment by avish-3pg** [comment]
Thank you @milosimpson , however what if I need to fetch only specific attributes from the array and transform it to a different name? Below is an example - 

```
{
	"results": [
		{
			"Id": "R001",
			"guid": "d93af5d9df7de9b2a8a34105894b09c5a76345c2",
			"value": 2
		},
		{
			"Id": "R002",
			"guid": "a21d9646d31cbaaf717c4abf5d337c20a294eaca",
			"value": 10
		},
		{
			"Id": "R003",
			"guid": "bb7f2acb1499cbe9129db5942f851e80b98221a7",
			"value": "JOLT is awesome"
		}
	]
}
```

**JOLT Spec** - 
```
[{
  "operation": "shift",
  "spec": {
    "results": {
      "*": {
        "Id": {
          "R000012": {
            "@2": {
              "NumberValue": "details[&1].id"
            }
          },
          "R003": {
            // if we matched down all this way
            // then go backup the tree 3 levels, 
            // grab that whole object and copy it
            // across to "results[]"
            "@2": {
              "Id": "OutputResults[&1].OutputId",
              "guid": "OutputResults[&1].OutputGuid"                       
              "value": "OutputResults[&1].OutputValue"                       
            }
          }
        }
      }
    }
  }
}]
```

**Output JSON** - 
```
{
	"OutputResults": [
		{
			"OutputId": "R003",
			"OutputGuid": "bb7f2acb1499cbe9129db5942f851e80b98221a7",
			"OutputValue": "JOLT is awesome"
		}
	]
}
```

**Comment by milosimpson** [comment]
"what if I need to fetch only specific attributes from the array and transform it to a different name"
Do it in two steps.

Step 1) match the large blocks that you want.
Step 2) transform each little block.

**Comment by milosimpson** [comment]
Spec 
```
[
  {
    "operation": "shift",
    "spec": {
      "results": {
        "*": {
          "Id": {
            "R000012": {
              "@2": {
                "NumberValue": "details[&1].id"
              }
            },
            "R003": {
              "@2": "temp[]"
            }
          }
        }
      }
    }
	},
  {
    "operation": "shift",
    "spec": {
      "temp": {
        "*": {
          "Id": "OutputResults[&1].OutputId",
          "guid": "OutputResults[&1].OutputGuid",
          "value": "OutputResults[&1].OutputValue"
        }
      }
    }
  }
]
```

**Comment by milosimpson** [comment]
The reason 
```
            }
          },
          "R003": {
            // if we matched down all this way
            // then go backup the tree 3 levels, 
            // grab that whole object and copy it
            // across to "results[]"
            "@2": {
              "Id": "OutputResults[&1].OutputId",
              "guid": "OutputResults[&1].OutputGuid"                       
              "value": "OutputResults[&1].OutputValue"                       
            }
          }
```

does not work is that, you need to don't want the array index of the input array, you just want to pass only certain blocks thru, and have them "accumulate" into a new array.

Then do a 2nd transform, where you can reference the "accumulated" array's indices.

**Comment by avish-3pg** [comment]
Thank you @milosimpson 

As always 'JOLT IS AWESOME'...:-)

**Comment by t06chandana** [comment]
Hi, milosimpson,

1. Can I do manipulations using JOLT? Ex: If(name==charles) then city:"Mclean" like this?

2. I have an input JSON as below. How to get the street from the address?

[ {
  "name" : charles,
  "city" : "BETHESDA",
  "state" : "MD",
  "zip" : "20817",
  "address" : {
    "street" : "TOWN GATE",
    "streetTypeSuffix" : "LN",
     "country" :"US"

}
}]

I tried using 

"operation": "shift",
  "spec": {
      "address": {
"*":{
    
    "street": "output.&1.value"}
}
    
  }

I see the output as null.

**Comment by pinky006** [comment]
Hi @milosimpson

Can I do manipulations using JOLT? Ex: If(name==charles) then city:"Mclean" like this?

I have an input JSON as below. How to get the street from the address?

[ {
"name" : charles,
"city" : "BETHESDA",
"state" : "MD",
"zip" : "20817",
"address" : {
"street" : "TOWN GATE",
"streetTypeSuffix" : "LN",
"country" :"US"

}
}]

I tried using

"operation": "shift",
"spec": {
"address": {
"*":{

"street": "output.&1.value"}
}

}

I see the output as null.

**Comment by shiiivam** [comment]
> "[{\"QuestionId\":\"R01\",\"Response\":null,\"NumberValue\":1},{\"QuestionId\":\"R02\",\"Response\":null,\"NumberValue\":2}]"

Hey @avish-3pg! any solution for -> "[{\"QuestionId\":\"R01\",\"Response\":null,\"NumberValue\":1},{\"QuestionId\":\"R02\",\"Response\":null,\"NumberValue\":2}]"
