### ISSUE TITLE
remove spec's work differently than shift spec. input needs to be wrapped in brackets ([...])

### ISSUE THREAD

**Issue by buildlackey** [bazaarvoice/jolt#350]
I can demonstrate this just using the online jolt demo  (http://jolt-demo.appspot.com/#inception)

First use the following for json input  &  jolt spec

```
json input  
    [ { "id": 1, "animal": 2 } ]

jolt spec
    [{ "operation": "remove", "spec": { "*": { "animal": "" } } }]

resulting output  (this is good): 
    [ { "id" : 1 } ] 
```
    

Now.. leave the brackets off of the json input and apply the same jolt spec as above:

```
json input  
     { "id": 1, "animal": 2 } 

with same jolt spec output results in failure to strip the 'animal' tag:
    { "animal" : 2, "id" : 1 }
```
    
Observation:   no brackets with 'remove' operation leads to incorrect results.

Note however that if I use a spec with 'shift' instead of remove the jolt online demo 
gives me opposite results 

encase the json input in brackets and transformation fails:

            json input  
                [ { "id": 1, "animal": 2 } ]

            jolt spec
                [{ "operation": "shift", "spec": { "animal": "newtag" } }]

            resulting output  (this is NOT good): 
                null
                

DO NOT encase the json input in brackets and transformation succeeds:

        json input  
            { "id": 1, "animal": 2 } 

        jolt spec
            [{ "operation": "shift", "spec": { "animal": "newtag" } }]

        resulting output  (this is good): 
            [ { "newtag" : 2 } ] 
            

Here is a java program that illustrates the same behavior.

    public class Transformer {

        private static Logger LOG = LoggerFactory.getLogger(Transformer.class);

        public LinkedHashMap<String, Object> convert(String json, String transformSpecJson) {

            LinkedHashMap<String, Object> parsedJson;
            Chainr chainr = null;
            LinkedHashMap<String, Object> transformedJson = null;
            List<Object> parsedTransformSpec = null;
            try {
                parsedJson = (LinkedHashMap<String, Object>) JsonUtils.jsonToMap(json);
                parsedTransformSpec = JsonUtils.jsonToList(transformSpecJson);
                chainr = Chainr.fromSpec(parsedTransformSpec);
                transformedJson = (LinkedHashMap<String, Object>) chainr.transform(parsedJson);
            } catch (Exception e) {
                LoggingThrower.logAndThrow("bad", e);
            }

            return transformedJson;
        }

        public static void main(String[] args) {
            String json =  "{ \"id\": 1278036, \"animal\": 1278036 }";
            String remove = "[ { \"operation\": \"remove\", \"spec\": { \"*\": { \"animal\": \"\" } } } ]";
            String shift = "[ { \"operation\": \"shift\", \"spec\": { \"animal\": \"newtag\" } } ]";

            System.out.println("remove:" + remove);
            System.out.println("shift:" + shift);
            System.out.println("json:" + json);

            Transformer t  = new Transformer();
            LinkedHashMap<String, Object> removed = t.convert(json, remove);
            System.out.println("removed:" + removed);

            LinkedHashMap<String, Object> shifted = t.convert(json, shift);
            System.out.println("shifted:" + shifted);
        }
    }

Output:

        remove:[ { "operation": "remove", "spec": { "*": { "animal": "" } } } ]
        shift:[ { "operation": "shift", "spec": { "animal": "newtag" } } ]
        json:{ "id": 1278036, "animal": 1278036 }
        removed:{id=1278036, animal=1278036}
        shifted:{newtag=1278036}

    Note that 'removed' is incorrect... the animal tag is still there
    just like what happened with the online demo.

    Note that 'shifted' is correct... 

Conclusion:  

'remove' spec needs json input in brackets
(which would be a json list), as opposed to no brackets, 
which results in input as json map, I am guessing.

'shift' spec requires the input NOT be in brackets.

**Comment by milosimpson** [comment]
Things look correct to me.   

**Remove only removes stuff that matches**

Given json input
```
{
	"id": 1,
	"animal": 2
}
```  
 Spec
```
[
	{
		"operation": "remove",
		"spec": {
			"*": {
				"animal": ""
			}
		}
	}
]
```
Remove is not going to do anything because, it does not match anything.   The "\*" in the remove spec matches "id" and "animal".   When "\*" matches animal, it recurses down and finds '2'.   '2' != "animal" from the remove spec.

The spec works, if the input is in an array, cause then the "\*" gets to match the array elements.

**Comment by milosimpson** [comment]
**Shift only "does stuff" it it matches**

        json input  
            [ { "id": 1, "animal": 2 } ]

        jolt spec
            [{ "operation": "shift", "spec": { "animal": "newtag" } }]


        resulting output  (this is NOT good): 
            null

In this case, shift tries to "index" the input array by "animal", which does not work, thus nothing is copied across from the input to the output.

In this case, where nothing is copied across from input to output, no output data is created, thus shift returns 'null'.   I guess to be nice it could return an empty map or an empty list, depending on the input...

If you remove the brackets from the intput, making the input to shift be a Map<String,Object> instead of a List<Map<String,Object>> then it can "index" the incoming map with "animal" from the spec, and get a match.

**Comment by buildlackey** [comment]
I think you are absolutely right !    sorry i misunderstood  ;^(
