### ISSUE TITLE
Min/Max/Avg of an array

### ISSUE THREAD

**Issue by dbgrey44** [bazaarvoice/jolt#351]
modify-overwrite-beta has functions but do they work for variable size array? 
The important thing here is that I don't have information about the number of elements. Can be a huge number as well.
For e.g.:
Input:

```json
{
"array":[2,3,1,0,9]
}
```

Output:

```json
{
"array":[2,3,0,1,9],
"min":0,
"max":9,
"avg":5
}
```

**Comment by milosimpson** [comment]
They should, try / test it.
