### ISSUE TITLE
How to set constant value of an empty string in shift operation

### ISSUE THREAD

**Issue by bortoffe** [bazaarvoice/jolt#361]
Hello! I am wondering if there is a way to set a default value of an empty string within the shift operation?
 `[
  {
    "operation": "shift",
    "spec": {
      "#": "output.fieldName"
    }
  }
]`

I know i can use # to set a constant value to the output field but it won't accept "#", it needs to contain some character as far as I can tell. I need the output to look like:

`{
  "output" : {
    "fieldName" : ""
  }
}`

Thank you for any help you can provide!

**Comment by milosimpson** [comment]
No can do from the shift operation.   

The "#" on the Left-Hand-Side were added to facilitate conversions from boolean to Strings.
