### ISSUE TITLE
Is it possible to add all the elements of the array and return the its outcome in output?

### ISSUE THREAD

**Issue by lelinolino** [bazaarvoice/jolt#362]
As in the title, I would like to add all the elements of an array and produce in output only the result.
Making an example, for this input:
`{
    values:[1,2,3]
}`

I would like to obtain this in output:
`{
value:6
}`

Is it possible?

**Comment by milosimpson** [comment]
Yes, but only on latest version of Jolt (that does not yet power the demo site).
```
[
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "sumOfScores": "=intSum(@(1,scores))"
    }
  }
]
```

See https://github.com/bazaarvoice/jolt/blob/8745c4c7b2649c0782e0811e7f1d83c4ef10007b/jolt-core/src/test/resources/json/modifier/functions/mathTests.json  for more.

The infrastructure that powers the Demo Site (Google App Engine) does not like Java 1.8, which I finally updated Jolt to.   So will need to figure out a different hosting provider.
