### ISSUE TITLE
Length of array

### ISSUE THREAD

**Issue by dgorkovets** [bazaarvoice/jolt#363]
Is it possible to get length of array?

Source:
```
{
    "key": ["A", "B", "C"]
}
```

Target:
```
{
    "keyLength": 3
}
````

**Comment by milosimpson** [comment]
Yes, but only on latest version of Jolt (that does not yet power the demo site).
```
[
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "keyLength": "=size(@(1,key))"
    }
  }
]
```

See
https://github.com/bazaarvoice/jolt/blob/8745c4c7b2649c0782e0811e7f1d83c4ef10007b/jolt-core/src/main/java/com/bazaarvoice/jolt/modifier/function/Objects.java#L205
and
https://github.com/bazaarvoice/jolt/blob/8745c4c7b2649c0782e0811e7f1d83c4ef10007b/jolt-core/src/main/java/com/bazaarvoice/jolt/Modifier.java#L63

The infrastructure that powers the Demo Site (Google App Engine) does not like Java 1.8, which I finally updated Jolt to.   So will need to figure out a different hosting provider.

**Comment by dgorkovets** [comment]
Thanks!

**Comment by Dinesh-Rajput** [comment]
Thanks! Very Helpful
