### ISSUE TITLE
Shifting  and Removing the Arraylist values based null check of the property

### ISSUE THREAD

**Issue by mounikakatnapelli** [bazaarvoice/jolt#364]

**Comment by milosimpson** [comment]
In both your examples, DNID is empty string ( "" ).

**Comment by mounikakatnapelli** [comment]
may i forgot one i have mentioned one request with empty and one is not not

**Comment by mounikakatnapelli** [comment]
i have mentioned two out puts request will be same alwasy one contains the dnid is null or without a tag and other contains dnid with value

**Comment by milosimpson** [comment]
Spec
```
[
  {
    "operation": "default",
    "spec": {
      "serviceInfo[]": {
        "0": {
          // shift can not "match" a non-existent DNID or 
          // even a null DNID, but default can.
          // So if DNID does not exist, or if it's value is 
          // null, then set it to empty string, so that 
          // shift can match on it.
          "DNID": ""
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "serviceInfo": {
        "0": {
          "name": "serviceInfo[0].name",
          "DNID": {
            "": { // DNID is empty string
              "@(2,dataSources.Catalog.servicecodes)": {
                "*": {
                  "ServiceCodeDescription": {
                    "RPT0037": {
                      // if the value of ServiceCodeDescription is RPT0037
                      // then go back up the tree two levelsn and grab the whole
                      // array entry and write it to servicecodes[0]
                      "@2": "serviceInfo[0].dataSources.Catalog.servicecodes[0]"
                    },
                    "*": {
                      "@2": "serviceInfo[0].dataSources.Catalog.subsequentservicecodes[]"
                    }
                  }
                }
              }
            },
            "*": { // DNID is any other non null value
              "@(2,dataSources.Catalog.servicecodes)": {
                "*": {
                  "ServiceCodeDescription": {
                    // match RPT0037 and do nothing with it
                    "RPT0037": null,
                    // pass all the rest of the values thru,
                    // has the "effect" of "removing the entry of ServiceCodeDescription with value RPT0037" 
                    "*": {
                      "@2": "serviceInfo[0].dataSources.Catalog.servicecodes[]"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
]
```

**Comment by mounikakatnapelli** [comment]
Thanks alot,  It is working,  one more condition need to be handled is when we don't see any RPT-0037 servicecodes  should be give it as  the same way without changing any thing

**Comment by mounikakatnapelli** [comment]
Actually I need some more help , my request is coming as  like this
{
	"serviceInfo": [
		{
			"name": "XYZ",
			"DNID": "",
			"dataSources": {
				"Catalog": {
					"servicecodes": [
						{
							"ServiceCodeDescription": "RPT0001"
						},
						{
							"ServiceCodeDescription": "RPT0003"
						},
						{
							"ServiceCodeDescription": "RPT0005"
						}
					]
				}
			}
		}
	]
} 

I am not getting service name and servicecode but we still populate in the same way , how to split  and populate those

**Comment by mounikakatnapelli** [comment]
or else Could   you please    help me to  transform this request  ,i can use two specs
INPUT 🥇 

{
"serviceInfo": [
{
"name": "XYZ",
"DNID": "",
"dataSources": {
"Catalog": {
"servicecodes": [
{
"ServiceCodeDescription": "RPT0001"
},
{
"ServiceCodeDescription": "RPT0003"
},
{
"ServiceCodeDescription": "RPT0005"
}
]
}
}
}
]
}

OUTPUT:

{
	"serviceInfo": [{
		"name": "XYZ",
		"DNID": "",
		"dataSources": {
			"Catalog": {
				"servicecodes": [{
						"serviceName": "RPT ",
						"ServiceCode": "0037",
						"ServiceCodeDescription": "RPT0037"
					},


					{
						"serviceName": "RPT",
						"ServiceCode": "0001",
						"ServiceCodeDescription": "RPT0001"
					},
					{
						"serviceName": "RPT",
						"ServiceCode": "0005",
						"ServiceCodeDescription": "RPT0005"
					}
				]
			}
		}
	}]
}

**Comment by mounikakatnapelli** [comment]
Can you please help for the above request
