### ISSUE TITLE
jolt spec required according to input and output data sample

### ISSUE THREAD

**Issue by PadminiGowda** [bazaarvoice/jolt#366]
input data:

{
"summary":{  

      "start_date":"2015-12-01T08:44:29+00:00",
      "end_date":"2015-12-03T08:54:27+00:00",

      "params":{  

         "offset":0,
         "limit":200
      }

    }
}
expected ouput

{
"summary":
{

{"key":"start_date",
    "value":"2015-12-01T08:44:29+00:00"
    },

{"key":"end_date",
    "value":2015-12-03T08:54:27+00:00" 
    },

{"key":"params",
   "value":{

               {"key":"offset",
                "value":"0"},

              {"key":"limit",
               "value":200},

            }

}
}

**Comment by milosimpson** [comment]
Please post valid input and output Json, per https://help.github.com/articles/creating-and-highlighting-code-blocks/
