### ISSUE TITLE
Use reference to value as key

### ISSUE THREAD

**Issue by gnicolae14** [bazaarvoice/jolt#368]
Hi, I am trying to create a transformation that uses the value of some key to further index another key and use its value. Do you have any suggestion for how my spec should look like?

input:
```
{
    "use": "some-category",
    "category": {
        "some-category": {
            "key1": "value1"
        },
        "some-other-category": {
            "key2": "value2"
        }
    }
}
```

spec:
```
{
    "operation": "shift",
    "spec": {
        "category": {
            "@(1,use)": ""
        }
    }
}
```
expected output:
```
{
    "key1": "value1"
}
```

actual output:
```
"some-category"
```

The following spec is working to this this transformation, but I need to use the value from "use" field instead of hard-coding "some-category" in spec:
```
spec:
{
    "operation": "shift",
    "spec": {
        "category": {
            "some-category": ""
        }
    }
}
```

Thanks,
Gabriel

**Comment by milosimpson** [comment]
It requires two shifts.

Spec
```
[
  // first shift, "nests" the category data
  // under the value from the "use"
  {
    "operation": "shift",
    "spec": {
      "category": "temp.@(1,use).category"
    }
  },
  {
    // now that the value of "use" is in 
    // the heirarchy / path, we can match
    // on it.
    "operation": "shift",
    "spec": {
      "temp": {
        "*": { // match whatever the value of "use" was
          "category": {
            // Match the sub item of "category" that 
            // was the value from 2 levels up the tree (0,1)
            "&1": ""
          }
        }
      }
    }
  }
]
```

Shift can match of values that it has already seen in it's "stack".   In your case you want to match on a value not along that path, so first you have to transform the data so that the value you want to match on is in the "path".

**Comment by gnicolae14** [comment]
Works great. Thank you!
I probably missed the part that you can only match against data seen in the stack.
