### ISSUE TITLE
Help please!!!

### ISSUE THREAD

**Issue by jlhernandezg7** [bazaarvoice/jolt#369]
Hi everyone,

I would like to transform  a object within an array with the ability to change the the key names.
The input json file is:
```
{
  "took": 4,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 79,
    "max_score": 12.385912,
    "hits": [
      {
        "_index": "pts_catalog",
        "_type": "asset",
        "_id": "41648cb8-fe0f-4d60-8dcb-ccf8589457e0",
        "_score": 11.957573,
        "_source": {
          "contentType": "episode",
          "vmid": "41648cb8-fe0f-4d60-8dcb-ccf8589457e0",
          "title": "Bellator MMA Live #150",
          "seriesVmid": "ebf10c4c-8740-4cfb-bfd1-c1708a78a0d7",
          "seriesTitle": "Bellator MMA Live",
          "seasonVmid": "17a50b56-6129-4b6b-8008-c6310e564afa",
          "seasonNumber": "13",
          "episodeNumber": "150",
          "country": "United States",
          "length": "01:00:00",
          "franchiseVmid": "c718a0ec-4848-4dfb-8bce-de44da5b2809",
          "franchiseTitle": "Bellator",
          "parentalGuideline": "NR ",
          "uSReleaseYear": "Jan ",
          "longDescription": "Bellator MMA is live from Wichita, Kansas with a heavyweight showdown between KO King Cheick Kongo and Brazilian slugger Vinicius Spartan. Plus David Rickels returns home to face dangerous Bobby Cooper in a Lightweight showdown.",
          "genres": [
            {
              "name": "Bellator"
            },
            {
              "name": "Martial Arts"
            }
          ]
        }
      },
      {
        "_index": "pts_catalog",
        "_type": "asset",
        "_id": "45e60e96-6b12-4cd9-ac0a-fba55f85c39d",
        "_score": 11.957573,
        "_source": {
          "contentType": "episode",
          "vmid": "45e60e96-6b12-4cd9-ac0a-fba55f85c39d",
          "title": "Bellator MMA Live #166",
          "seriesVmid": "ebf10c4c-8740-4cfb-bfd1-c1708a78a0d7",
          "seriesTitle": "Bellator MMA Live",
          "seasonVmid": "17a50b56-6129-4b6b-8008-c6310e564afa",
          "seasonNumber": "13",
          "episodeNumber": "166",
          "country": "United States",
          "length": "02:00:00",
          "franchiseVmid": "c718a0ec-4848-4dfb-8bce-de44da5b2809",
          "franchiseTitle": "Bellator",
          "parentalGuideline": "NR ",
          "uSReleaseYear": "Jan ",
          "longDescription": "Bellator comes to you live with part one of a two-night combat event from Thackerville as the baddest man on the planet, Joe Warren, looks to recapture the World Bantamweight Championship. ",
          "genres": [
            {
              "name": "Bellator"
            },
            {
              "name": "Martial Arts"
            }
          ]
        }
      },
      {
        "_index": "pts_catalog",
        "_type": "asset",
        "_id": "661a0a15-512b-4510-aae3-b9e83195eddd",
        "_score": 11.957573,
        "_source": {
          "contentType": "episode",
          "vmid": "661a0a15-512b-4510-aae3-b9e83195eddd",
          "title": "Bellator MMA Live #1004",
          "seriesVmid": "ebf10c4c-8740-4cfb-bfd1-c1708a78a0d7",
          "seriesTitle": "Bellator MMA Live",
          "seasonVmid": "7e55d3ad-614b-45f2-b873-ad2bb19024cc",
          "seasonNumber": "10",
          "episodeNumber": "1004",
          "country": "United States",
          "length": "01:00:00",
          "franchiseVmid": "c718a0ec-4848-4dfb-8bce-de44da5b2809",
          "franchiseTitle": "Bellator",
          "parentalGuideline": "NR ",
          "uSReleaseYear": "Jan ",
          "longDescription": "Bellator MMA is live from Mulvane, Kansas with the Light Heavyweight World Title on the line as Champ Attila Vegh and Interim Champ“The Hardcore Kid” Emanuel Newton meet to decide who the true Light Heavyweight Champion is! ",
          "genres": [
            {
              "name": "Bellator"
            },
            {
              "name": "Martial Arts"
            }
          ]
        }
      }
    ]
  }
}
```

I need to convert it to the following format: Very much appreciated if some one can suggest an spec for this.
Note: extract the _source object to items in the array with some key fields rename.
```
{
  "took": 4,
  "total_hits": 79,
  "episodes": [
      {
        "id": "41648cb8-fe0f-4d60-8dcb-ccf8589457e0",
        "content_Type": "episode",
        "vmid": "41648cb8-fe0f-4d60-8dcb-ccf8589457e0",
        "title": "Bellator MMA Live #150",
        "series_Vmid": "ebf10c4c-8740-4cfb-bfd1-c1708a78a0d7",
        "series_Title": "Bellator MMA Live",
        "season_Vmid": "17a50b56-6129-4b6b-8008-c6310e564afa",
        "season_Number": "13",
        "episode_Number": "150",
        "country": "United States",
        "length": "01:00:00",
        "franchise_Vmid": "c718a0ec-4848-4dfb-8bce-de44da5b2809",
        "franchise_Title": "Bellator",
        "parental_Guideline": "NR ",
        "uSRelease_Year": "Jan ",
        "long_Description": "Bellator MMA is live from Wichita, Kansas with a heavyweight showdown between KO King Cheick Kongo and Brazilian slugger Vinicius Spartan. Plus David Rickels returns home to face dangerous Bobby Cooper in a Lightweight showdown.",
        "genres": [
        {
            "name": "Bellator"
        },
        {
            "name": "Martial Arts"
        }
        ]
      },
      {
        "id": "45e60e96-6b12-4cd9-ac0a-fba55f85c39d",
        "content_Type": "episode",
        "vmid": "45e60e96-6b12-4cd9-ac0a-fba55f85c39d",
        "title": "Bellator MMA Live #166",
        "series_Vmid": "ebf10c4c-8740-4cfb-bfd1-c1708a78a0d7",
        "series_Title": "Bellator MMA Live",
        "season_Vmid": "17a50b56-6129-4b6b-8008-c6310e564afa",
        "season_Number": "13",
        "episode_Number": "166",
        "country": "United States",
        "length": "02:00:00",
        "franchise_Vmid": "c718a0ec-4848-4dfb-8bce-de44da5b2809",
        "franchise_Title": "Bellator",
        "parental_Guideline": "NR ",
        "uSRelease_Year": "Jan ",
        "long_Description": "Bellator comes to you live with part one of a two-night combat event from Thackerville as the baddest man on the planet, Joe Warren, looks to recapture the World Bantamweight Championship. ",
        "genres": [
        {
            "name": "Bellator"
        },
        {
            "name": "Martial Arts"
        }
        ]
      },
      {
        "id": "661a0a15-512b-4510-aae3-b9e83195eddd",
        "content_Type": "episode",
        "vmid": "661a0a15-512b-4510-aae3-b9e83195eddd",
        "title": "Bellator MMA Live #1004",
        "series_Vmid": "ebf10c4c-8740-4cfb-bfd1-c1708a78a0d7",
        "series_Title": "Bellator MMA Live",
        "season_Vmid": "7e55d3ad-614b-45f2-b873-ad2bb19024cc",
        "season_Number": "10",
        "episode_Number": "1004",
        "country": "United States",
        "length": "01:00:00",
        "franchise_Vmid": "c718a0ec-4848-4dfb-8bce-de44da5b2809",
        "franchise_Title": "Bellator",
        "parental_Guideline": "NR ",
        "uSRelease_Year": "Jan ",
        "long_Description": "Bellator MMA is live from Mulvane, Kansas with the Light Heavyweight World Title on the line as Champ Attila Vegh and Interim Champ“The Hardcore Kid” Emanuel Newton meet to decide who the true Light Heavyweight Champion is! ",
        "genres": [
        {
            "name": "Bellator"
        },
        {
            "name": "Martial Arts"
        }
        ]
      }
    ]
}
```
Thanks for any help.

**Comment by milosimpson** [comment]
This does most of it, you should be able to fill in the rest of the "key fields rename".

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "took": "took",
      "hits": {
        "total": "total_hits",
        "hits": {
          "*": {
            "_source": {
              "contentType": "episodes[&2].content_Type",
              "vmid": "episodes[&2].vmid",
              "title": "episodes[&2].title",
              "seriesVmid": "episodes[&2].series_Vmid"
            }
          }
        }
      }
    }
  }
]
```

**Comment by jlhernandezg7** [comment]
Excellent!!! Indeed you are the man!!! THANK YOU SO MUCH 🥇 🥇 🥇 🥇 🥇

**Comment by jlhernandezg7** [comment]
Hi Milo,

Thanks for your help provided yesterday...
I was able to follow your lead...

Regarding this same input data when adding the genres to the episodes output with this:
Spec
[
  {
    "operation": "shift",
    "spec": {
      "took": "took",
      "hits": {
        "total": "total_hits",
        "hits": {
          "*": {
            "_source": {
              "vmid": "episodes[&2].id",
              "contentType": "episodes[&2].content_type",
              "title": "episodes[&2].title",
              "seriesVmid": "episodes[&2].series_vmid",
              "seriesTitle": "episodes[&2].series_title",
              "seasonVmid": "episodes[&2].season_vmid",
              "seasonNumber": "episodes[&2].season_number",
              "episodeNumber": "episodes[&2].episode_number",
              "country": "episodes[&2].country",
              "length": "episodes[&2].length",
              "genres": {
                "*": {
                  "name": "episodes[&1].genre"
                }
              }
            }
          }
        }
      }
    }
  }
]


I get the following result:

{
  "episodes" : [ {
    "content_type" : "episode",
    "country" : "United States",
    "episode_number" : "150",
    "genre" : [ "Bellator", "Bellator", "Bellator" ],
    "id" : "41648cb8-fe0f-4d60-8dcb-ccf8589457e0",
    "length" : "01:00:00",
    "season_number" : "13",
    "season_vmid" : "17a50b56-6129-4b6b-8008-c6310e564afa",
    "series_title" : "Bellator MMA Live",
    "series_vmid" : "ebf10c4c-8740-4cfb-bfd1-c1708a78a0d7",
    "title" : "Bellator MMA Live #150"
  }, {
    "content_type" : "episode",
    "country" : "United States",
    "episode_number" : "166",
    "genre" : [ "Martial Arts", "Martial Arts", "Martial Arts" ],
    "id" : "45e60e96-6b12-4cd9-ac0a-fba55f85c39d",
    "length" : "02:00:00",
    "season_number" : "13",
    "season_vmid" : "17a50b56-6129-4b6b-8008-c6310e564afa",
    "series_title" : "Bellator MMA Live",
    "series_vmid" : "ebf10c4c-8740-4cfb-bfd1-c1708a78a0d7",
    "title" : "Bellator MMA Live #166"
  }, {
    "content_type" : "episode",
    "country" : "United States",
    "episode_number" : "1004",
    "id" : "661a0a15-512b-4510-aae3-b9e83195eddd",
    "length" : "01:00:00",
    "season_number" : "10",
    "season_vmid" : "7e55d3ad-614b-45f2-b873-ad2bb19024cc",
    "series_title" : "Bellator MMA Live",
    "series_vmid" : "ebf10c4c-8740-4cfb-bfd1-c1708a78a0d7",
    "title" : "Bellator MMA Live #1004"
  } ],
  "took" : 4,
  "total_hits" : 79
}

For some reason i get values for the first and second episode in the array and not only that it's like for the first takes the first index on the genres and subsequently and since there are only two genres within the array it will not display anything for the last episode..
For sure I'm doing something wrong, could you please help? Thanks in advance... also is there a documentation in order for me to read...

**Comment by jlhernandezg7** [comment]
disregard previous comment...I think i got it...
so, i was only looping within the genres but I need it to go up within the parent array...
interesting....any ways... this is very cool... LOVE IT!!!!!!

**Comment by jlhernandezg7** [comment]
Is there a way to say to include only distinct values within the subarray and if empty still include the field?
Thanks in advance!!!!

**Comment by milosimpson** [comment]
Is there a way to say to include only distinct values within the subarray and if empty still include the field? 

Probably not, but also, I don't understand the question.   Rephrase with a simple example.

**Comment by jlhernandezg7** [comment]
Sure...
INPUT:
{
	"took": 25,
	"timed_out": false,
	"_shards": {
		"total": 5,
		"successful": 5,
		"failed": 0
	},
	"hits": {
		"total": 79,
		"max_score": 12.385912,
		"hits": [
			{
				"_index": "pts_catalog",
				"_type": "asset",
				"_id": "5884c7ba-7595-44b1-920a-37553d63a3d8",
				"_score": 12.385912,
				"_source": {
					"contentType": "episode",
					"vmid": "5884c7ba-7595-44b1-920a-37553d63a3d8",
					"title": "Bellator MMA Live #910",
					"seriesVmid": "ebf10c4c-8740-4cfb-bfd1-c1708a78a0d7",
					"seriesTitle": "Bellator MMA Live",
					"seasonVmid": "3b7ee6f4-96d9-4747-a4fc-086084ce1c21",
					"seasonNumber": "9",
					"episodeNumber": "910",
					"country": "United States",
					"length": "01:00:00",
					"franchiseVmid": "c718a0ec-4848-4dfb-8bce-de44da5b2809",
					"franchiseTitle": "Bellator",
					"parentalGuideline": "NR ",
					"uSReleaseYear": "Jan ",
					"longDescription": "Bellator is in Atlantic City, New Jersey with Rampage Jackson making his Bellator debut against slugger Joey Beltran in a headlining feature fight. Champ Alexander Volcov takes on tournament winner Vitaly Minakov.",
					"genres": [
						{
							"name": "Bellator"
						},
						{
							"name": "Martial Arts"
						}
					],
					"channels": [
						{
							"name": "SpikeTV",
							"vmid": "cd79862c-c45a-4675-9843-0e959eb5d764"
						}
					],
					"versions": [
						{
							"code": "620486",
							"name": "Spike App/Online",
							"dsid": "HDBEL910N"
						},
						{
							"code": "554751",
							"name": "Cut Down Version ",
							"dsid": "HDBEL910B"
						},
						{
							"code": "554750",
							"name": "SD Version",
							"dsid": "HDBEL910A"
						},
						{
							"code": "554749",
							"name": "HD Version ",
							"dsid": "HDBEL910A"
						}
					]
				}
			},
			{
				"_index": "pts_catalog",
				"_type": "asset",
				"_id": "0d2679b7-657a-4568-a030-ada8bb4ab534",
				"_score": 11.957573,
				"_source": {
					"contentType": "episode",
					"vmid": "0d2679b7-657a-4568-a030-ada8bb4ab534",
					"title": "Bellator MMA Live #911",
					"seriesVmid": "ebf10c4c-8740-4cfb-bfd1-c1708a78a0d7",
					"seriesTitle": "Bellator MMA Live",
					"seasonVmid": "3b7ee6f4-96d9-4747-a4fc-086084ce1c21",
					"seasonNumber": "9",
					"episodeNumber": "911",
					"country": "United States",
					"length": "01:00:00",
					"franchiseVmid": "c718a0ec-4848-4dfb-8bce-de44da5b2809",
					"franchiseTitle": "Bellator",
					"parentalGuideline": "NR ",
					"uSReleaseYear": "Jan ",
					"longDescription": "Bellator is live from Bethlehem, PA with its season 9 finale as Middleweight Champ Alexander Shlemenko takes on Doug Marshall. Plus, the lightweight season tourney finals pit 12-1 Will Brooks against 25-1 Tiger Sarnavskiy. ",
					"genres": [
						{
							"name": "Bellator"
						},
						{
							"name": "Martial Arts"
						}
					],
					"channels": [
						{
							"name": "SpikeTV",
							"vmid": "cd79862c-c45a-4675-9843-0e959eb5d764"
						}
					],
					"versions": [
						{
							"code": "620487",
							"name": "Spike App/Online",
							"dsid": "HDBEL911N"
						},
						{
							"code": "554754",
							"name": "Cut Down Version ",
							"dsid": "HDBEL911B"
						},
						{
							"code": "554753",
							"name": "SD Version",
							"dsid": "HDBEL911A"
						},
						{
							"code": "554752",
							"name": "HD Version ",
							"dsid": "HDBEL911A"
						},
						{
							"code": "554755",
							"name": "SD Version",
							"dsid": "HDBEL911C"
						}
					]
				}
			},
			{
				"_index": "pts_catalog",
				"_type": "asset",
				"_id": "40538d30-a07e-4718-94e2-b0df2a26aead",
				"_score": 11.957573,
				"_source": {
					"contentType": "episode",
					"vmid": "40538d30-a07e-4718-94e2-b0df2a26aead",
					"title": "Bellator MMA Live #811",
					"seriesVmid": "ebf10c4c-8740-4cfb-bfd1-c1708a78a0d7",
					"seriesTitle": "Bellator MMA Live",
					"seasonVmid": "be9e0adf-4b44-402e-8075-750fc1f10070",
					"seasonNumber": "8",
					"episodeNumber": "811",
					"country": "United States",
					"length": "02:00:00",
					"franchiseVmid": "c718a0ec-4848-4dfb-8bce-de44da5b2809",
					"franchiseTitle": "Bellator",
					"parentalGuideline": "NR ",
					"uSReleaseYear": "Jan ",
					"longDescription": "From Atlantic City, NJ, Bellator presents Featherweight World Championship: Pat Curran vs. Shahbulat Shamhalaev; Middle & Featherweight Tournament Finals: Cooper vs. Marshall; Richman vs. Khasbulaev; Plus: Hawn vs. Parisyan",
					"genres": [
						{
							"name": "Bellator"
						},
						{
							"name": "Martial Arts"
						}
					],
					"channels": [
						{
							"name": "SpikeTV",
							"vmid": "cd79862c-c45a-4675-9843-0e959eb5d764"
						}
					],
					"versions": []
				}
			}
		]
	}
}

SPEC:

[
  {
    "operation": "shift",
    "spec": {
      "took": "took",
      "hits": {
        "total": "total_hits",
        "hits": {
          "*": {
            "_source": {
              "vmid": "episodes[&2].id",
              "contentType": "episodes[&2].content_type",
              "title": "episodes[&2].title",
              "seriesVmid": "episodes[&2].series_vmid",
              "seriesTitle": "episodes[&2].series_title",
              "seasonVmid": "episodes[&2].season_vmid",
              "seasonNumber": "episodes[&2].season_number",
              "episodeNumber": "episodes[&2].episode_number",
              "country": "episodes[&2].country",
              "length": "episodes[&2].length",
              "versions": {
                "*": {
                  "name": "episodes[&4].version"
                }
              },
              "genres": {
                "*": {
                  "name": "episodes[&4].genre"
                }
              }
            }
          }
        }
      }
    }
  }
]


OUTPUT:

{
  "episodes" : [ {
    "content_type" : "episode",
    "country" : "United States",
    "episode_number" : "910",
    "genre" : [ "Bellator", "Martial Arts" ],
    "id" : "5884c7ba-7595-44b1-920a-37553d63a3d8",
    "length" : "01:00:00",
    "season_number" : "9",
    "season_vmid" : "3b7ee6f4-96d9-4747-a4fc-086084ce1c21",
    "series_title" : "Bellator MMA Live",
    "series_vmid" : "ebf10c4c-8740-4cfb-bfd1-c1708a78a0d7",
    "title" : "Bellator MMA Live #910",
    "version" : [ "Spike App/Online", "Cut Down Version ", "SD Version", "HD Version " ]
  }, {
    "content_type" : "episode",
    "country" : "United States",
    "episode_number" : "911",
    "genre" : [ "Bellator", "Martial Arts" ],
    "id" : "0d2679b7-657a-4568-a030-ada8bb4ab534",
    "length" : "01:00:00",
    "season_number" : "9",
    "season_vmid" : "3b7ee6f4-96d9-4747-a4fc-086084ce1c21",
    "series_title" : "Bellator MMA Live",
    "series_vmid" : "ebf10c4c-8740-4cfb-bfd1-c1708a78a0d7",
    "title" : "Bellator MMA Live #911",
    "version" : [ "Spike App/Online", "Cut Down Version ", "SD Version", "HD Version ", "SD Version" ]
  }, {
    "content_type" : "episode",
    "country" : "United States",
    "episode_number" : "811",
    "genre" : [ "Bellator", "Martial Arts" ],
    "id" : "40538d30-a07e-4718-94e2-b0df2a26aead",
    "length" : "02:00:00",
    "season_number" : "8",
    "season_vmid" : "be9e0adf-4b44-402e-8075-750fc1f10070",
    "series_title" : "Bellator MMA Live",
    "series_vmid" : "ebf10c4c-8740-4cfb-bfd1-c1708a78a0d7",
    "title" : "Bellator MMA Live #811"
  } ],
  "took" : 25,
  "total_hits" : 79
}

Based on provided samples with 3 items as output shows 2 issues that I would like to fix:
1.- For item 2 (middle), shows duplicate "SD Version" in the array versions:
"version" : [ "Spike App/Online", "Cut Down Version ", "SD Version", "HD Version ", "SD Version" ]
How could I filter only unique values?

2.- For item 3 (last) there is no version field because the input array was empty, "versions": []
How could I provide a version empty array in the output instead of not including anything?

Thanks in advance for your help.

**Comment by jlhernandezg7** [comment]
Thanks
