### ISSUE TITLE
Modify/Split String which include special character and get  list of String

### ISSUE THREAD

**Issue by KrishnaNagar** [bazaarvoice/jolt#371]
Input :- 

```
{
  "key":"val1,val2,val3"
}
```

I want to convert values like val1,val2 in to the List. Simply split value of key with comma(,), and get list of String. Values can be multiple(more than 3 or any number)

Expected Output : - 
```
{
	"key": [
		"val1",
		"val2",
		"val3"
	]
}
```

**Comment by milosimpson** [comment]
Can not ... cleanly.

You can brute force it if you must.

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "key": {
        "*,*": {
          "$(0,1)": "key[0]",
          "$(0,2)": "key[1]"
        },
        "*,*,*": {
          "$(0,1)": "key[0]",
          "$(0,2)": "key[1]",
          "$(0,3)": "key[2]"
        },
        "*,*,*,*": {
          "$(0,1)": "key[0]",
          "$(0,2)": "key[1]",
          "$(0,3)": "key[2]",
          "$(0,4)": "key[3]"
        }
      }
    }
  }
]
```

Extend for how many comma delimted things you think you will get.

Also, more than three stars in a match, Jolt uses Java Regex which is really slow.
