### ISSUE TITLE
[MAY DAY MAY DAY] Need urgent help on JSON Transformation

### ISSUE THREAD

**Issue by avish-3pg** [bazaarvoice/jolt#374]
Hello @milosimpson 

I am in a tricky situation right now with below INPUT JSON with multiple ITEMS (array or not) incoming and it could be an array (Items[]) or separately (Items{}). The problem is that with the below JOLT SPEC I am able to manipulate the Item[] however if they come separate I need a way to SPEC out to map to each individual ITEM. Please advice if its feasible -

**INPUT JSON**
```
{
	"Ticket": {
		"TicketID": 601264,
		"Date": "2017-05-07T16:13:00",
		"StoreId": 98056,
		"Item": {
			"ItemId": 98056,
			"TicketID": 601264,
			"SeqNumber": 1,
			"ItemName": "ABC"
		},
		"Payment": {
			"StoreNo": 98056,
			"TicketID": 601264,
			"SeqNumber": 1,
			"PaymentType": "CASH",
			"Amount": 10.68
		},
		"Item": {
			"ItemId": 94738,
			"TicketID": 95639,
			"SeqNumber": 2,
			"ItemName": "DEF"
		}
	}
}
```

**JOLT SPEC**
```
[{
	"operation": "shift",
	"spec": {
		"Check": {
			"Date": "date",
			"CheckID": "id",
			"StoreId": "storeId",
			"Item": {
				"*": {
					"MenuItemID": "detail[&1].category",
					"ItemPrice": "detail[&1].cost",
					"ItemID": "detail[&1].id",
					"ItemName": "detail[&1].name"
				},
				"MenuItemID": "detail.category",
				"ItemPrice": "detail.cost",
				"ItemID": "detail.id",
				"ItemName": "detail.name"
			}
		}
	}
}]
```

**Current Output JSON** - 

```
{
	"date": "2017-05-07T16:13:00",
	"id": 601264,
	"storeId": 98056
}
```

**Expected Output JSON** - 

```
{
	"date": "2017-05-07T16:13:00",
	"id": 601264,
	"storeId": 98056
	"detail": [{
		"id": 98056,
		"name": "ABC"
	}, {
		"id": 94738,
		"name": "DEF"
	}]
}
```

**Comment by milosimpson** [comment]
Your input data is not valid JSON.

Can not have to "keys" in map that are the same.    
```
Not valid JSON
{
	"Ticket": {
		...
		"Item": {
			"ItemId": 98056,
			"TicketID": 601264,
			"SeqNumber": 1,
			"ItemName": "ABC"
		},
		...
		"Item": {
			"ItemId": 94738,
			"TicketID": 95639,
			"SeqNumber": 2,
			"ItemName": "DEF"
		}
	}
}
```

**Comment by milosimpson** [comment]
Also, seems like the cardinality operation may be useful for you.

Small Example
```
input 
{
	"a": "b"
}

spec
[
  {
    "operation": "cardinality",
    "spec": {
      "a": "MANY"
    }
  }
]

output
{
  "a" : [ "b" ]
}
```

See unit tests for more
https://github.com/bazaarvoice/jolt/tree/master/jolt-core/src/test/resources/json/cardinality

**Comment by avish-3pg** [comment]
Correct I agree, however is there a way out to combine those in creating an array since that is the input JSON I get in JoltTransform in NiFi?

I am currently ingesting in NiFi which is like --> SplitXML --> TransformXML --> JoltTransform.

So essentially the original problem is with the XML i.e. <Item> and <Payment> in random order, rather than all the <Item> first followed by <Payment>. However, if the <Item> are in order followed by <Payment> we get the Item[] array and JOLT does the transformation just fine.

**Comment by milosimpson** [comment]
Jolt never sees the two "Item" keys.   When Jackson serializes the JSON in to Java code, it turns it into a Map, which means that only only one of the Items will "survive" / be passed to Jolt.
