### ISSUE TITLE
Transform some values in input and keep the remaining same

### ISSUE THREAD

**Issue by hina1234** [bazaarvoice/jolt#377]
Hi,

Is there a way to keep the remaining values of input , that are not specified in spec, same in output?
As per what I understand,if we do not specify any key of input in spec,it removes the remaining.

In my use case, I am applying two shift operations,where second shift is on the temp array created from first, where the temp array has to reside somewhere in nested array objects.So when I apply second shift ,my first shift results get overridden

**Comment by milosimpson** [comment]
Shift copies data from it's input into a new output map/list.

You have to explicitly pass things you want to keep across when doing multiple shifts.
