### ISSUE TITLE
Convert top level Map to a list

### ISSUE THREAD

**Issue by anshulbhargava** [bazaarvoice/jolt#383]
Hi JoltMasters :)

I am trying to do the following JSON conversion

Input spec -

{
	"rating": {
		"primary": {
			"value": 3
		},
		"quality": {
			"value": 3
		}
	}
}

Output spec -

[{
	"rating": {
		"primary": {
			"value": 3
		},
		"quality": {
			"value": 3
		}
	}
}]

I tried cardinality transform here but could not figure out how to use that on the root element. Can anyone please help me out with this? It's a blocker for me and I have been struggling on this for a long time.

**Comment by SUNYTYAGI** [comment]
[
  {
    "operation": "shift",
    "spec": {
      "@": "[]"
    }
  }
]


Send me chocolate now :)

**Comment by anshulbhargava** [comment]
Thanks @SUNYTYAGI  :) Come to my place and take chocolate :)

**Comment by vishalbahedia** [comment]
@SUNYTYAGI : How to perform this as optional like cardinality? If root element is already an list then dont do anything, if not then convert it to list?
