### ISSUE TITLE
solved

### ISSUE THREAD

**Issue by yixuanya** [bazaarvoice/jolt#388]
INPUT
{
"key1":"value1",
"key2":"value2",
"data":[[0,3],[1,4],[2,5]]
}

OUTPUT

   "data":[{"label":3,
                         "value1": {"value2": 1}},
                         {"label": 4,
                         "value1": {"value2": 2}},
                         {"label": 5,
                         "value1": {"value2": 3}}]
           }

**Comment by milosimpson** [comment]
Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "key3": {
        "*": { // key3 array
          // the Zeroth item of the sub array, i.e. "a"
          "0": "data[&1].@(4,key1).@(4,key2)",
          // the First itme of the sub array, i.e. "A"
          "1": "data[&1].label"
        }
      }
    }
  }
]
```

**Comment by yixuanya** [comment]
Thank you so much! You are the person to ask!
Do you mind if I ask one more tricky conversion? Really appreciate your help!

INPUT
{
        “key1”: value1,
        “key2”: value2,
        "data": [
                {
                        “key3”: value3,
                        “A”: {
                                “part1”: 1,
                                “part2”: 4
                        },
                        "B": {
                                "part1": 2,
                                “part2": 5
                        },
                        “C”: {
                                "part1": 3,
                                “part2”: 6
                        }
                }
        ]
}

OUTPUT
{
	“key1”: value1,
	“key2”: value2,
	"data": [{
			“name”: “name.A”,
			 “key3”: value3,
			"value": 4,
			“info”: {
				“newName”: “value2”(from int to str conversion),
				“part”: “part2"
			}
		},
		{
			“name”: “name.B”,
			 “key3”: value3,
			"value": 5,
			“info”: {
				"newName": “value2”(from int to str conversion),
				“part”: “part2"
			}
		},
		{
			“name”: “name.C”,
			 “key3”: value3,
			"value": 6,
			“info”: {
				"newName": “value2”(from int to str conversion),
				“part”: "part2"
			}
		}
	]
}

**Comment by milosimpson** [comment]
Also, pls put the input back so that ppl can potentially reference it in the future.

**Comment by yixuanya** [comment]
Already did!

**Comment by saisamineni** [comment]
Hi Milo,
     In the above Spec, How did you use @(4,key1). I am trying to understand @ wildcard but a bit confused with the level parameter. How should we select the level (i.e 4 in the above case) with the @ wildcard. The documentation says levels in the tree, but which one is the tree here.

Thanks,
