### ISSUE TITLE
Do you mind helping with this tricky conversion?

### ISSUE THREAD

**Issue by yixuanya** [bazaarvoice/jolt#389]
INPUT
{
        "key1": "value1",
        "key2": "value2",
        "data": [
                {
                        "key3": "value3",
                        "A": {
                                "part1": 1,
                                "part2": 4
                        },
                        "B": {
                                "part1": 2,
                                "part2": 5
                        },
                        "C": {
                                "part1": 3,
                                "part2": 6
                        }
                }
        ]
}

OUTPUT
{ 
  "key1": "value1",
  "key2": "value2",
  "data": [{
      "name": "name.A",
      "key3": "value3",
      "value": 4,
      "info": {
        "newName": "value2", // (from int to str conversion),
        "part": "part2"
      }
},  
    { 
      "name": "name.B",
      "key3": "value3",
      "value": 5,
      "info": {
        "newName": "value2", // (from int to str conversion),
        "part": "part2"
      }
},  
    { 
      "name": "name.C",
      "key3": "value3",
      "value": 6,
      "info": {
        "newName": "value2", // (from int to str conversion),
        "part": "part2"
      }
}
]
}

**Comment by milosimpson** [comment]
Please post valid Json.   Aka use real double quotes.   It looks like this was copied pasted out of Word where it has annoying open and close quotes.

Also, there were thing that needed quotes.

**Comment by yixuanya** [comment]
Thanks for formatting. This conversion has haunted me for 24 hours... Appreciate your help

**Comment by milosimpson** [comment]
Complicated.   You should break it down to one transform step at a time using the demo site.
http://jolt-demo.appspot.com/#inception

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "key1": "key1",
      "key2": "key2",
      "data": {
        "0": {
          "key3": "key3", // move key3 to the top
          "*": {
            // make a new temp object and push A,B,C down as "name"
            // so we can operate on it in the next step
            "$": "temp.&.tempName",
            "part*": "temp.&1.&"
          }
        }
      }
    }
  },
  {
    "operation": "modify-default-beta",
    "spec": {
      "temp": {
        "*": { // A,B,C
          // build the "name" : "name.A" thingy
          "name": "=concat(name.,@(1,tempName))",
          // copy the "key3" value down
          "key3": "@(4,key3)",
          // default in an "info" section that always seemt to be the same
          "info": {
            "newName": "value2",
            "part": "part2"
          }
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      // pass key1 and 2 thru but not key3
      "key1": "key1",
      "key2": "key2",
      "temp": {
        "*": {
          // pass thru specific fields 
          // to a new data array
          "part2": "data[#2].value",
          "name": "data[#2].name",
          "key3": "data[#2].key3",
          "info": "data[#2].info"
        }
      }
    }
  }
]
```

**Comment by milosimpson** [comment]
Pls put the input back, so that this can potentially be a useful example for people in the future.

**Comment by yixuanya** [comment]
No problem. I've already put them back. 
I'm wondering if I want to do a vertical expansion, i.e. if the new input is an array of the old input, then it seems adding one more layer of "*" is not gonna work. Do you have any suggestions? Thanks!

**Comment by milosimpson** [comment]
Correct this spec assumes that the incoming "data" array has only one element.  

I suggest coming up with a test case with two items in the input "data" array, and then step by step modifying the spec to add an extra layer of array processing.

**Comment by yixuanya** [comment]
Hi, thanks for your reply. Could you please give an example? I can't figure out how to assign the name of the dataset to be data_index. Also I'm constantly confused about if I should use "0" or "*" to loop over a data structure. Thanks for your help.
