### ISSUE TITLE
No examples of truly custom transforms?

### ISSUE THREAD

**Issue by davidmichaelkarr** [bazaarvoice/jolt#390]
Looking through the docs, and then through all of the tests and examples, I can't find an example of doing a true "custom transform".  I was particularly intrigued by the statement of "where the "input" is "hydrated" Java version of your JSON Data" in the description for "SpecDriven".  The existing provided transform capabilities are pretty powerful, but I can see situations where I'd just like to operate on plain POJO properties, getting a "business-logic" input object and producing a "business-logic" output object.  It appears that "operation" can be a FQCN, but I see no examples of that.

**Comment by milosimpson** [comment]
Yeah, we have some large "true custom java transforms" in private projects that leverage Jolt.

In Jolt proper, I have some smaller "custom transforms" that mainly exist to test Chainr's ability to load classes and run custom java transforms.   See https://github.com/bazaarvoice/jolt/tree/master/jolt-core/src/test/java/com/bazaarvoice/jolt/chainr/transforms

Also see this spec file and ones near it in the directory structure : https://github.com/bazaarvoice/jolt/blob/master/jolt-core/src/test/resources/json/chainr/transforms/loadsGoodTransform.json

Wrt "business-logic" input object, none of the OOTB transforms/operations will work with them; they all expect plain vanilla Map<String,Object> and List<Object>.

**Comment by Rishikeshctonne** [comment]
I cant autowire in the custom class? 
Can you help me with it.
