### ISSUE TITLE
Regex Java Like in Specification

### ISSUE THREAD

**Issue by fkoner** [bazaarvoice/jolt#392]
Hi I´m Trying to convert the following input:

**input**
````
{
 "tipo": "L",
  "1": {
    "precio": 100,
    "idMoneda": 1,
    "margen": 0.5
  },
  "2": {
    "precio": 200,
    "idMoneda": 1,
    "margen": 0.5
  },
  "236": {
    "precio": 1000,
    "idMoneda": 1,
    "margen": 0.75
  }
}
````

And have the following spec:

**spec**
`````
[
  {
    "operation": "shift",
    "spec": {
      "tipo": "tipo",
      "*": {
        "@.precio": "lstPrecios[#2].precio",
        "@.idMoneda": "lstPrecios[#2].idMoneda",
        "@.margen": "lstPrecios[#2].margen",
        "$": "lstPrecios[#2].idArticulo"
      }
    }
  },
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "lstPrecios": {
        "*": {
          "idArticulo": [
            "=toInteger",
            0
          ]
        }
      }
    }
  },
  {
    "operation": "default",
    "spec": {
      "tipoComando": "actualiza.inserta.precios"
    }
  }
]
`````
I need to reproduce the next output:

**expected output**
`````
{
  "tipo": "L",
  "lstPrecios": [
    {
      "idArticulo": 1,
      "idMoneda": 1,
      "margen": 0.5,
      "precio": 100
    },
    {
      "idArticulo": 2,
      "idMoneda": 1,
      "margen": 0.5,
      "precio": 200
    },
    {
      "idArticulo": 236,
      "idMoneda": 1,
      "margen": 0.75,
      "precio": 1000
    }
  ],
  "tipoComando": "actualiza.inserta.precios"
}
`````
I tested on [jolt-demo.appspot](http://jolt-demo.appspot.com/) and the expected output is fine, but when i implemented it in java code I got the following output:

**actual output**
`````
{
  "tipo" : "L",
  "lstPrecios" : [ {
    "idArticulo" : 0
  }, {
    "precio" : 100,
    "idMoneda" : 1,
    "margen" : 0.5,
    "idArticulo" : 1
  }, {
    "precio" : 200,
    "idMoneda" : 1,
    "margen" : 0.5,
    "idArticulo" : 2
  }, {
    "precio" : 1000,
    "idMoneda" : 1,
    "margen" : 0.75,
    "idArticulo" : 236
  } ],
  "tipoComando" : "actualiza.inserta.precios"
}
`````
The previous output is because [jolt-demo.appspot](http://jolt-demo.appspot.com/) orders the json input.

Is there a way to create java regex patterns based on digits or another regex pattern support like 
[Java 8 Pattern](https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html) for example:

**java 8 regex pattern spec**
`````
[
  {
    "operation": "shift",
    "spec": {
      "tipo": "tipo",
      "\d{1,15}": {
        "@.precio": "lstPrecios[#2].precio",
        "@.idMoneda": "lstPrecios[#2].idMoneda",
        "@.margen": "lstPrecios[#2].margen",
        "$": "lstPrecios[#2].idArticulo"
      }
    }
  },
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "lstPrecios": {
        "*": {
          "idArticulo": [
            "=toInteger",
            0
          ]
        }
      }
    }
  },
  {
    "operation": "default",
    "spec": {
      "tipoComando": "actualiza.inserta.precios"
    }
  }
]
`````
Investigate the project documentation, google, but I can not find a solution for this case. Is there support planned for this feature? Or, there is a specification that meets the requirement. Beforehand thank you very much.
@milosimpson I will appreciate your support.

**Comment by milosimpson** [comment]
So, there are two problems.   

1) On the demo site, the JavaScript based validation of the Json input, does as a side effect of validating and formatting the data apply a sort to the input data.
2) The '#' logic in Shiftr doesn't actually do what you want it to do in this case.  
"lstPrecios[#2].precio"    I.e. The '[#]' logic only works when there isn't anything else in the data like our friend "tipo".

To trigger the problem you see when running "real" code, if you replace the input "tipo" with a "0" then the output on the demo site will match what you are seeing in the real code.

intput that shows the problem
```
{
	"0": "L",
	"1": {
		"precio": 100,
		"idMoneda": 1,
		"margen": 0.5
	},
	"2": {
		"precio": 200,
		"idMoneda": 1,
		"margen": 0.5
	},
	"236": {
		"precio": 1000,
		"idMoneda": 1,
		"margen": 0.75
	}
}
```

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "0": "tipo",
      "*": {
        "@.precio": "lstPrecios[#2].precio",
        "@.idMoneda": "lstPrecios[#2].idMoneda",
        "@.margen": "lstPrecios[#2].margen",
        "$": "lstPrecios[#2].idArticulo"
      }
    }
  }
]
```

**Comment by milosimpson** [comment]
This spec, which is based on yours should correctly handle the top level "tipo" causing problems.

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "tipo": "tipo",
      // move all the other things to a temp key, so that
      // we can use the "[#]" logic in a 2nd step
      "*": "temp.&"
    }
  },
  {
    "operation": "shift",
    "spec": {
      "tipo": "tipo",
      "temp": {
        // now that all the things under temp are going to be 
        // in an array, the [#2] logic will now work
        "*": {
          "$": "lstPrecios[#2].idArticulo",
          // match idMoneda, margen, precio and pass then thru
          "*": "lstPrecios[#2].&"
        }
      }
    }
  },
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "lstPrecios": {
        "*": {
          "idArticulo": ["=toInteger", 0]
        }
      }
    }
  },
  {
    "operation": "default",
    "spec": {
      "tipoComando": "actualiza.inserta.precios"
    }
  }
]
```

**Comment by fkoner** [comment]
@milosimpson 
Thank you very much for your support.

In fact, with this new specification, the requirement is supported.

From the theme of java type regular expressions. Is there any interest in supporting this feature? Or, in your experience Do you consider that with current operations these and other types of scenarios are supported?

The reason is optimization of steps, the solution you propose requires a previous step. I do not know if supporting regular expressions can achieve the same task, and even new scenarios.

**Comment by milosimpson** [comment]
From the theme of java type regular expressions. Is there any interest in supporting this feature? Or, in your experience Do you consider that with current operations these and other types of scenarios are supported?

Java Regex is slow.  The single biggest / best performance improvement I made to Jolt/Shift was to remove as much Regex as possible.

The real issue is to fix the '[#]' logic, so that it "does the right thing".
