### ISSUE TITLE
Need help to arrive at a JOLT spec

### ISSUE THREAD

**Issue by prasad0509** [bazaarvoice/jolt#393]
Hi,

Can some one please help to arrive at the right JOLT spec to transform below. Kindly help.

INPUT
-------
{
"empId": "123",
"empName": "John",
"addressList" : [
{
"streetName": "Wells Street",
"city": "Chicago"
},
{
"streetName": "Adams Street",
"city": "Edison"
}
]
}

OUTPUT
---------
{
"metaDataList":[
{
"empId": "123",
"empName": "John",
"streetName": "Wells Street",
"city": "Chicago"
},
{
"empId": "123",
"empName": "John",
"streetName": "Adams Street",
"city": "Edison"
}
]
}

Thank you very much.
Regards...

**Comment by nagarajasr** [comment]
try this:
```
[
  {
    "operation": "shift",
    "spec": {
      "addressList": {
        "*": {
          "streetName": "metadataList[#2].streetName",
          "city": "metadataList[#2].city",
          "@(2,empId)": "metadataList[#2].empId",
          "@(2,empName)": "metadataList[#2].empName"
        }
      }
    }
  }
]
```

**Comment by prasad0509** [comment]
Thank you very much Nagaraj. It works as required.
This is really a very very great help.

Best Regards,
Prasad

**Comment by prasad0509** [comment]
Thanks
