### ISSUE TITLE
Conversion from String value to Long

### ISSUE THREAD

**Issue by pankajbharambe** [bazaarvoice/jolt#394]
First thank you for such good utility. I am using it and I am sure that there will be a some solution of my problem.

I want to convert String value to Long. Below is my Specs and input. I have use **modify-overwrite-beta** but no luck.

Specs -  

```
[  
  {
    "operation": "modify-overwrite-beta",
    "spec": {
       "timestamp": "=toLong(@(1,time))"
    }
  },
  {
    "operation": "shift",
    "spec": {
      "key1": "outputText1",
      "key2": "outputText2",
      "key3": "outputText3",
      "time": "timestamp"     
   }
 }
]
```

Input Json

```
{
   "key1": "test1",
   "time": "1499967627",
   "key2": "test2",
   "key3": "test3",
}
```

So in above input json how I can convert time value to Long

Expected Json :

```
{
   "outputText1": "test1",
   "timestamp": 1499967627,
   "outputText2": "test2",
   "outputText3": "test3",
}
```

**Comment by milosimpson** [comment]
Spec
```
[
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "timestamp": "=toLong(@(1,time))"
    }
  },
  {
    "operation": "shift",
    "spec": {
      "key1": "outputText1",
      "key2": "outputText2",
      "key3": "outputText3",
      // pass timestamp thru
      "timestamp": "timestamp"
    }
 }
]
```

In the first operation (modify) it was making "timestamp" be a long.   But then in the 2nd operation, you were copying the String value from "time" to timestamp, instead of passing timestamp thru.
