### ISSUE TITLE
JSON records to JSON Array

### ISSUE THREAD

**Issue by jonmer85** [bazaarvoice/jolt#396]
Hello,
Is it possible to convert newline-delimited JSON objects to an array of those objects?

For example, I want to convert:
{"key1":"value1"}
{"key2":"value2"}
{"key3":"value3"}

to:
[{"key1":"value1"},{"key2":"value2"},{"key3":"value3"}]

**Comment by milosimpson** [comment]
No, Jolt requires "valid" Json as input.

jq can probably do what you want.

**Comment by jonmer85** [comment]
Thanks for the tip and prompt response @milosimpson
