### ISSUE TITLE
Map Key to a Value

### ISSUE THREAD

**Issue by kfeuerman** [bazaarvoice/jolt#397]
I'm looking for the inverse of https://stackoverflow.com/questions/42840917/map-value-to-a-key-using-jolt-spec.  For example:

Input:
```
{
  "age": {
    "type": "integer",
    "description": "some description",
    ... // arbitrary other properties and values
  }
}
```

Output:
```
{
  "name": "age",
  "type": "integer", 
  "description": "some description",
  ... // arbitrary other properties and values
}
```
More generally, I'd like to collect a whole object's worth of such properties into an array:

Input:
```
{
  "properties": {
    "age": {
      "type": "integer",
      ....
      }
    "firstname": {
      "type": "string",
      ...
      }
    ...
}
```
Output: 
```
{
  "fields": [
    {
      "name": "age",
      "type": "integer",
      ...
    },
    {
      "name": "firstname",
      "type": "string",
      ...
    },
    ...
  ]
}
```

What would the JOLT spec look like for this?  Thanks!

**Comment by milosimpson** [comment]
Sample input
```
{
	"properties": {
		"age": {
			"type": "integer"
		},
		"firstname": {
			"type": "string"
		},
		"lastname": {
			"type": "string"
		},
		"birthday": {
			"type": "date"
		}
	}
}
```

Spec
```
[
  {
    // create two parallel arrays, one of types
    // and one of property names, than in the second
    // step we can merge into a fields array
    "operation": "shift",
    "spec": {
      "properties": {
        "*": { // match : age, firstname, etc
          "type": {
            "*": {
              "$": "types[]",
              "$2": "propNames[]"
            }
          }
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      // because propNames and types are the same length
      // we can use the index of their array to merge the 
      // data into a fields array 
      "propNames": {
        "*": "fields[&].name"
      },
      "types": {
        "*": "fields[&].type"
      }
    }
  }
]
```

**Comment by milosimpson** [comment]
Now the question is your "..."s in your sample input.   If you have extra properties you want to pass thru this process, this approach will work as long as the new properties are one-to-one with propNames and types.

If they aren't then you will need to do a more complicated "lookup" using the "transpose" operator example "@(1,foo)"  see http://jolt-demo.appspot.com/#ritwickgupta

Ie, we know that propnames is he the driver, and so you can use it's values to do a lookup of the non one to one data.

**Comment by kfeuerman** [comment]
@milosimpson Thanks so much for the response!  Definitely helpful to see your approach.

In the case I have in mind, I'd have to go with the more complicated "lookup" approach that you referenced.  I think I see from your example how that could work, essentially by producing a propNames array in a first transformation, and then looping through it in a second transformation as in the #ritwickgupta example.  But for me (admittedly a noobie to this), it raises two questions:

1. How do I simply add a propNames array to the original input?  I'm assuming that the output from the first transformation consists of the original JSON input plus the propNames array, which therefore gives you the driver along with the data to lookup from.
2. In the second transformation, must I know _a priori_ what all of the possible properties in my "..."'s are?  I believe I can know that, but it might be rather tedious and verbose to list them all out in a transformation spec.

**Comment by milosimpson** [comment]
Sorry, this can be simpler.   This assumes that every sub entry on "property" just get accumulated into an output "fields" array, and the only thing you want to do is push "name" down.

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "properties": {
        "*": {
          // Copy the whole "age" block thru 
          //  where [#2] is ask the "properties" level 
          //  the current count of matches on the "*" below it
          "@": "fields[#2]",
          // write "age" to key name in the output
          "$": "fields[#2].name"
        }
      }
    }
  }
]
```

**Comment by rajpatta** [comment]
```
Input JSON: 
{
"request_details": {
    "key1":"value1",
    "key2":"value2",
    "key3":"value3",
    "key4":"value4",
    "expense_items": [
      {
        "item_no": "sequence of item number starting with 1",
        "description": "Description of purchase item",
        "short_description": "Short description of the purchase item",
        "transaction_date": "date of transaction",
        "vendor": "Name of vendor/supplier/merchant"
      }
    ]
  }
}

Expected output :  
"data": [{
          "key": "field1",
          "label": "key1",
          "value": "value1",
          "order": 1
        },
        {
          "key": "field2",
          "label": "key2",
          "value": "value2",
          "order": 2
        },
        {
          "key": "field3",
          "label": "key3",
          "value": "value3",
          "order": 3
        }
      ],
```
Is it possible to map some of the key names in the object to the values in other obj.
