### ISSUE TITLE
Custom transformation to "clean" data

### ISSUE THREAD

**Issue by poa3123** [bazaarvoice/jolt#401]
I'm having trouble creating a custom transformation to clean data.

I want to:
* Remove white spaces on keys -- `key with space` -> `keywithspace`
* Prepend keys starting with digits -- `2abc -> `_2abc`
* Remove dash characters -- `this-has-dashes Example` -> `thisHasDashesExample`

Example input:

```
"People": {
        "John Smith": {
             "Their Name": "John Smith",
             "Age": "1990-01-01",
             "10Rating": "8"
       },
        "Jill Smith": {
             "Their Name": "Jill Smith",
             "Age": "1992-01-01",
             "10Rating": "9"
       }
}
```

Expected output: 

```
"People": {
        "JohnSmith": {
             "TheirName": "John Smith",
             "Age": "19900101",
             "_10Rating": "8"
       },
        "JillSmith": {
             "TheirName": "Jill Smith",
             "Age": "19920101",
             "_10Rating": "9"
       }
}
```

**Comment by milosimpson** [comment]
OOTB Jolt does not support that.   It's primary use-case is to change the JSON structure of your data, not the actual data itself.

Given the specificity of your changes, you will need to implement that some non-Jolt way.

**Comment by poa3123** [comment]
@milosimpson Thanks for your reply.

My data's structure is consistent and so the spaces, dashes, and starting digits are in expected positions, so I was hoping to write a short spec iterating through all the expected keys and values that need changing. Is there still no way to do this with a custom transform?

**Comment by milosimpson** [comment]
To be clear, the Out of The Box operations won't be able to squash spaces, and prefix only keys that start with numbers with "_".   You will either have to write Java code, or use some other tooling to do that.

A "custom transform" is a Java Class that you create that implements Jolt's Transform interface, which you can then call as one operation mixed in with the Out Of The Box jolt operations (shift, default, remove, etc).

The transform interface is really simple / stupid / not super helpful in ht at It just takes in a Map or data, and returns a Map of data.

So, the logic you implement, you can make it be a Jolt Transform, but it is not necessary.

We internally use Custom Java transforms at BV, but I do not have a good example of one that is publicly visible.

**Comment by poa3123** [comment]
Thanks again - last question before I close this. 

I am working off the sort operation and trying to create a Custom Java transform but I am a bit confused on how the JSON data is represented when writing a Custom Java transformation. 

I see that 'sort' only works with 'Map<String,Object>' and 'List<String>'.

How would this be represented in the 'Map<String,Object>' format:

```
"People": {
        "John Smith": { 
             "Their Name": "John Smith",
             "Age": "1990-01-01",
             "10Rating": "8"
       },
        "Jill Smith": {
             "Their Name": "Jill Smith",
             "Age": "1992-01-01",
             "10Rating": "9"
       }
}

```

And what does the JSON data look like when it represents just a 'List<String>'? Also, what would JSON arrays translate to when writing the Java transforms?

**Comment by milosimpson** [comment]
Q: How would this be represented in the 'Map<String,Object>' format?
A: The input object would be of type Map.   
You would need to "instance of" check it, then cast it to a Map, say 'a'.
Now you have a Map, that you can call 'a.get("People")' on and it will return an Object.
You now 'instance of' check that Object to see what it is.
It is a Map.  You cast it to another Map, say 'b'.
The Map 'b' has two entries, "John Smith" and "Jill Smith".   etc.

Q: Also, what would JSON arrays translate to when writing the Java transforms?
A: Json Arrays turn into java.util.List
