### ISSUE TITLE
how to extract substring?

### ISSUE THREAD

**Issue by sravanmummadi** [bazaarvoice/jolt#407]
I am trying to extract first 6 characters of a string. No delimiters in the string.

 Can some one please help in writing spec for this. Thanks

Input:
```
 {
  "data": {
    "comment": "joltisawesome"
  }
}
```
output:
```
{
  "data": {
    "comment": "joltis"
  }
}
```

**Comment by sravanmummadi** [comment]
> converting

ing

**Comment by milosimpson** [comment]
There currently is not a way to do that.   

Sounds like a good "function" / feature request for modify; "=subString( str, start, end )"

**Comment by bhargavs84** [comment]
Is Substring function Implemented now?
