### ISSUE TITLE
Generic Flattener Jolt Transformer?

### ISSUE THREAD

**Issue by rjdthegreat** [bazaarvoice/jolt#411]
I want to transform the following input:
```
{ "parent1":
      {"child1": "value1"},
      {"child2": "value2"},
      {"child3": 
         { "grandChild1": "value3" }
      }
}
```

into 

> `{ "parent1_child1": "value1",
>      "parent1_child2": "value2",
>      "parent1_child3_grandChild1": "value3"
>  }`

Only there are 100 parent and 100 childs (there is only 3 level of nesting), so I need it to be generic.

is this possible?

**Comment by milosimpson** [comment]
No.   

There isn't a way for "shift" to determine / tell the difference between a full grandChild and just a scalar value of a child.

The best it can do is squash the first and 2nd levels.

Input
```
{
  "parent1": {
    "child1": "value1",
    "child2": "value2",
    "child3": {
      "grandChild1": "value3"
    }
  }
}
```

Spec
```
[
  {
    // squash down levels 1 and 2
    "operation": "shift",
    "spec": {
      // match any parent
      "*": {
        // match any child, and write the value of the child
        // to the concatenation of the parent and the child
        "*": "&1_&"
      }
    }
  }
]
```

Output
```
{
  "parent1_child1" : "value1",
  "parent1_child2" : "value2",
  "parent1_child3" : {
    "grandChild1" : "value3"
  }
}
```
