### ISSUE TITLE
Whats spec for this requirement ?

### ISSUE THREAD

**Issue by santooudnur** [bazaarvoice/jolt#412]
Need help on best possible ways of transformation of JSON for below JSON

Input JSON
[Test.JSON.zip](https://github.com/bazaarvoice/jolt/files/1248190/Test.JSON.zip)

Expected result : We need to merge all main-text -> text fields and  tables->data-> arrays of arrays   to string , with removing null fields new field document,.

{    "document": "This Agreement governs your acquisitionand use of XYZZ Cloud Services. You may select Cloud Services either on -line or through an Order DocumentXYZZ providesor they will be set forth in a Statement of Work (SOW) sig ned by both parties. The Order Document you submit to XYZZ, if applicable,will specify the Cloud Services and quantities selected, XYZZ chargesand other details of your order. The Order Document(if any), the ServiceDescription(s) for the selected Clou d Service(s), the SOW,and this Agreementwill constitute the completeagreement for the Cloud Servicesand will supersede any prior discussions or representations regarding the Cloud Services . ServicePerformance and Commitments When XYZZ accepts your Order Document or SOW for a Cloud Service, XYZZ will provide you theauthorizations specified in the Order Documentor SOW. You may access theCloud Service from any locationvia an internet connectionprovided by you. Cloud Services are designed to be availa ble 24/7 subject to maintenance.You will be notifiedof scheduled maintenance. Service Level commitments , if applicable,are specified inthe Service Description . In addition, some Cloud Services include entitlement to use enabling software on your machines. If applicable, descriptions and details of the software and permitted use granted by XYZZ or third parties will be included in the Service Description. You may access and use each Cloud Service that you order only to the extent ofAuthorizations acquired by you. You are responsible for useof Cloud Servicesby any majority owned subsidiary, yourusers and any authorized third partyrecipient who accesses the Service with your account credentials. XYZZ does not authorize use ofany Cloud Service for any unlawfulor inappropriatepurposes, such as gambling, obscenity, pornography, violence, misappropriation, unauthorized accessor interference, virusesor harmful code, harassment,unsolicitedor deceptivemessages, or evading filters. All such use is prohibited. Unless expressly provided in this Agreement, you are not authorized to use the Cloud Services to provide hosting or timesharing services to any third party. Integration, Configurationand Custom Services XYZZ may offer additional standardcustomization and configuration Services. Such Services are detailed in a n additional Service Description andmay be ordered pursuant to the Order Documentor SOW. At your request, XYZZmay perform additional custom services, as specified in a mutually agreed SOW. Confidentiality and Data Protection Each Cloud Service is designed to protect the proprietary content that you input into the Cloud Service and to provide for access and use of suchcontent only in accordance with the provision of theCloud Service. Except as otherwise specified in a Service Des cription, Cloud Services limit access and use ofyourproprietarycontent to XYZZ employees and contractors as needed to deliver the Cloud Service. XYZZ will not disclose your proprietary cont ent, and will return or destroy your content upon the expiration or cancellation of the Cloud Service, or earlier upon your request. XYZZ reserves the right to charge for certain activities performed at your request or direction(such as delivering content in a specific format) . The Service Description for each Cloud Service describes the security functionsand featuresapplicable to the Cloud Service.XYZZ Cloud Services areEU Safe Harbor certified, unless otherwise specified in the Service Description. Agreed to:  Agreed to:  Blackboard Inc.  XYZZ Corporation 2300 Dulles Station Blvd "
}

**Comment by milosimpson** [comment]
This is literally doing your work for you, so not doing it.
