### ISSUE TITLE
Whats JSON spec for this input JSON

### ISSUE THREAD

**Issue by santooudnur** [bazaarvoice/jolt#418]
My input JSON is as mentioned below.
```
{
  "title" : "XYYYY",
  "filename" : "b16091aa.o9j.pdf",
  "text" : "third party",
  "data0" : "STORRR ",
  "data1" : "Story 2",
  "data2" : "Story 3",
  "data3" : "Story"
}
```
data* key can appear 1 to n like the ways data0 to data3 as above.
Now I have take all data* values concatenate to **text** key vaues separated by comma or space. 
In this case final output JSON  after transformation is 

```
{
  "title" : "XYYYY",
  "filename" : "b16091aa.o9j.pdf",
  "text" : "third party STORRR Story 2 Story 3 Story"
 }
```

Whats the JSON transformation spec for achieving same. Please let me know if any further details required.

Waiting for your quick response.

**Comment by milosimpson** [comment]
So there are issues.  

Will the "dataNUM" elements be "in order" in the input?   
Will there ever be more than ten data elements? 

Worst case scenario, there can be more than ten elements, and they can be presented in the input in any order.

In that case, you would need to extract the number, convert it from a string to an it, and sort it and and maintain the link to the value.  And then concatenate.

Which Jolt can't do.

**Comment by santooudnur** [comment]
"data0" to dataNum elements are in order, in worst case scenario more than ten or more elements and are sorted,typically be in order 1 to n.

**Comment by santooudnur** [comment]
Actual JSON is 
[sa-sample.json.txt](https://github.com/bazaarvoice/jolt/files/1310437/sa-sample.json.txt)

it is transformed to following JSON
{
  "title" : "XYYYY",
  "filename" : "b16091aa.o9j.pdf",
  "text" : "third party",
  "data0" : "STORRR ",
  "data1" : "Story 2",
  "data2" : "Story 3",
  "data3" : "Story"
}

by applying following transformations spec 
[json-transform-spec.json.txt](https://github.com/bazaarvoice/jolt/files/1310442/json-transform-spec.json.txt) .I need to concatenate **data*** values to **text** field , order of concatenation of **data*** values to text filed does not matter. 

The challenge was to merge array of array values to single value , handle null, empty values in tables*/data tag in input filed sa-sample.json.txt. Now its requested dataNUM fields to be concatenated to **text** field.

Now we can handle concatenating data* fields outside of JOLT transformations but not recommended.

Please have look at input JSON , transformation spec , suggest solution with Transformation spec. 

Thanks

**Comment by milosimpson** [comment]
Spec
```
[
  {
    "operation": "shift",
    "spec": {
      // pass title and filename thru
      "title": "title",
      "filename": "filename",
      
			// accumulate input text and data* into 
      //  a text array in the output
      "text": "text[]",
      "data*": "text[]"
    }
  },
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      // overwrite text with the string join of the input text array
      "text": "=join(' ',@(1,text))"
    }
  }
]
```
