### ISSUE TITLE
What is the JSON spec for this transformation

### ISSUE THREAD

**Issue by sekaisan** [bazaarvoice/jolt#424]
Hi, I am new to JOLT, could you take a look at this requirement?

input : { 
    "dataMap": {
      "DSN": "123",
      "DEVICE_TYPE": "1234",
      "UPDATETIME": "12345",
      "CREATION_DATE": "123124534",
      "CREATED_BY": "admin"
    }
}

desired output : {
    "primaryKey" : "123",
    "secondaryKey: : "1234",
    "payload":  {
           "DSN": "123",
           "DEVICE_TYPE": "1234",
           "UPDATETIME": "12345",
   }
}

Thank you!

**Comment by milosimpson** [comment]
Partial Spec to give you the idea.   Run it at http://jolt-demo.appspot.com/ with your input.

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "dataMap": {
        "DSN": "primaryKey",
        "UPDATETIME": "payload.UPDATETIME"
      }
    }
  }
]
```

**Comment by sekaisan** [comment]
the output is this:
{
  "primaryKey" : "123",
  "payload" : {
    "UPDATETIME" : "12345"
  }
}
I understand this part. But I don't know how to achieve this:
output:
{
  "primaryKey" : "123",
  "payload" : {
    "DSN" : "123",
    "UPDATETIME" : "12345"
  }
}
I want the DSN value from the input to be copied to "primaryKey" and "payload.DSN", I tried several ways, but none of them work.

**Comment by milosimpson** [comment]
Ah.   Use an array, to copy a value to multiple places in the output.

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "dataMap": {
        "DSN": ["primaryKey", "payload.DSN"],
        "UPDATETIME": "payload.UPDATETIME"
      }
    }
  }
]
```

**Comment by sekaisan** [comment]
Thanks alot! Problem solved.
