### ISSUE TITLE
How to remove a key that matches a value in a array

### ISSUE THREAD

**Issue by santasudan** [bazaarvoice/jolt#425]
Hi,

I am new to jolt and looking out if jolt can do the below transformation. 

Input JSON

{
  "TRASHKEYLIST" : [ "lastname", "firstname" ],
  "lastname" : "TRASH",
  "firstname" : "TRASH",
  "age" : "25",
  "company":"ABC"
  "name": "John"
}

Output JSON

{
  "age" : "25",
  "company":"ABC"
  "name": "John"
}

Thanks.

**Comment by milosimpson** [comment]
Nope.   If you know the Right Hand Side value of "TRASH" you can match that and not pass they key / value thru. 

However, there is not a way to "filter out" keys based upon a list.
