### ISSUE TITLE
Wildcard not matching ""

### ISSUE THREAD

**Issue by aheys** [bazaarvoice/jolt#428]
Hi, I am not sure if this is by design or a bug, but using the wildcard with a key does not match the key itself. See below:

Input:
```json
{
  "rating": {
    "primary": {
      "value": 3
    },
    "primary2": {
      "value": 4
    }
  }
}
```
Spec:
```json
[
  {
    "operation": "shift",
    "spec": {
      "rating": {
        "primary*": {
          "value": "SecondaryRatings.&1.Value",
          "$": "SecondaryRatings.&1.Id"
        }
      }
    }
  }
]
```
Expected Result:
```json
{
  "SecondaryRatings" : {
    "primary" : {
      "Id" : "primary",
      "Value" : 3
    },
    "primary2" : {
      "Id" : "primary2",
      "Value" : 4
    }
  }
}
```
Actual Result:
```json
{
  "SecondaryRatings" : {
    "primary2" : {
      "Id" : "primary2",
      "Value" : 4
    }
  }
}
```

**Comment by milosimpson** [comment]
That is expected behavior.

**Comment by aheys** [comment]
Is there any desire to change the behavior to match the standard [glob](https://en.wikipedia.org/wiki/Glob_(programming)) pattern for wildcards?

**Comment by milosimpson** [comment]
Maybe.   The original goal was to be able to distinguish things like "rating" and "rating*", but now that I think about it, I think the implementation will do that, even if "*" was allowed to match "nothing".
