### ISSUE TITLE
Is it possible to add another level of nesting with jolt

### ISSUE THREAD

**Issue by fojcikr** [bazaarvoice/jolt#443]
Hi,
I've got an input JSON that looks like below

```
{
  "attributes": {
    "type": "someType",
    "url": "some/example/url"
  },
  "Id": "0063D000002mfBmQAI",
  "IsDeleted": false
}
```
I'm using the following spec to flatten out the input and get only Id and IsDeleted

```
[
  {
    "operation": "shift",
    "spec": {
      "attributes": {
        "@1": {
          "Id": "Id",
          "IsDeleted": "IsDeleted"
        }
      }
    }
  }
]
```

The output is like follows
```
{
  "Id" : "0063D000002mfBmQAI",
  "IsDeleted" : false
}
```
So that's pretty simple and it's working. Now I would like to add another level to the output. I know how to add custom fields with the default opperation, but I always end up with new fields inside the current branch, I can't figure out how to add a top level to the structure, so it would look something like below and I'd like to use the **type** value for that

```
{
  "someType" : {
    "Id" : "0063D000007HaogQAC",
    "IsDeleted" : false
  }
}
```
Is there a way to do that?

**Comment by milosimpson** [comment]
Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "Id": "someType.Id",
      "IsDeleted": "someType.IsDeleted"
    }
  }
]
```

You can just directly match on on Id and IsDeleted, I don't see why you were matching into "attributes" and then going back up and then down the tree, to just grab Id and IsDeleted.

**Comment by fojcikr** [comment]
@milosimpson 
You're right, I overdid it, now I can see that. Anyway.. thank you for your help, it's working fine :)

**Comment by akaHige91** [comment]
Hi @milosimpson 
I was looking at this issue and there's a question I have to ask. If you hardcode "Id": "someType.Id" then the output will be always
```
{
  "someType" : {
    "Id" : "0063D000002mfBmQAI",
    "IsDeleted" : false
  }
}
```
even if you change type to anotherType.
How can I use the value of type dynamically, so I don't have to bother what's the value. I wouldn't want to have it hadrcoded like that.

**Comment by milosimpson** [comment]
That is more meta than the tool is trying to support.   The typical usecase is we have documents of type A, B, & C, and then we have one Jolt transform for each type.

Thus being "hardcoded" in the Jolt Spec is fine.

We don't try to make one uber / master transform that can handle all of the types of JSON data that we run into.
