### ISSUE TITLE
Remove empty & blank field from the json.

### ISSUE THREAD

**Issue by piyushramani** [bazaarvoice/jolt#445]
I want to remove the empty field from the json

	"info": {
                    "name": [
                        {
                            "identifier": "current",
                            "firstName": "PINYT",
                            "lastName": "TEST",
                            "middleName": "",
                            "suffix": "",
                            "prefix": ""
                        }
                    ],
                    "cid": "777",
                    "sid": "666726178",
                    "gender": "M",
                    "dob": "1941-01-10",
                    "age": 76,
					"phoneNumber":[]
                    "addresses": [
                        {
                            "identifier": "CURRENT",
                            "streetName": "8613 BXJRKLRJEX DR",
                            "houseNumber": 305,
                            "city": "Baton Rouge",
                            "state": "LA",
                            "zip": ,
                            "country": "US",
                            "lengthAtAddress": 0
                        }
                    ],
                    "device": {
                        "ipAddress": "locahost",
                        "deviceFingerprint": ""
                    }
                }

**Comment by piyushramani** [comment]
Please help me out solve this problem

**Comment by milosimpson** [comment]
Jolt has a "remove" operation, but it does not do conditional removals.
