### ISSUE TITLE
JOLT: Conditions in nested JSON

### ISSUE THREAD

**Issue by 145995g** [bazaarvoice/jolt#447]
I have been struggling to find a solution to the below. Request your guidance on the same.
Input JSON-1:
{
 "Employee": "Mark Simpson"
}

Input JSON-2:
{
"Employee":{
 "content":"Mark Simpson"
}
}

Output JSON:
{
"emp_name": "Mark Simpson"
}

At runtime, I might receive either of the InputJSON1 or Input JSON2 but the output should be the same.

**Comment by pooya-az** [comment]
I think this spec help you

```
[
  {
    "operation": "shift",
    "spec": {
      "Employee": {
        "@(0,content)": "temp",
        "@": "temp"
      }
    }
  },
  {
    "operation": "cardinality",
    "spec": {
      "temp": "ONE"
    }
  }
]
