### ISSUE TITLE
@ wildcard level issue

### ISSUE THREAD

**Issue by saisamineni** [bazaarvoice/jolt#451]
Hi,

INPUT
```
{
  "data": {
    "1234": {
      "clientId": "12",
      "hidden": true
    },
    "1235": {
      "clientId": "35",
      "hidden": false
    }
  }
}
```
SPEC
```
[
  {
    "operation": "shift",
    "spec": {
      "data": {
        "*": {
          "hidden": "@clientId"
        }
      }
    }
  }
]
```

The above transformation does not seem to work. Replacing "@clientId" with "@(1,clientId)" works. Can someone help me understand why. It would be great if some one could explain how the level parameter works with the @ wildcard and which tree should be considered while calculating the level to use with @ wildcard

Thanks,

**Comment by milosimpson** [comment]
See https://stackoverflow.com/questions/47070256/jolt-modify-default-beta-what-does-the-first-argument-do

Describes the internal "stack" that the Jolt operations use.
