### ISSUE TITLE
Removing wrapper in Json-Output

### ISSUE THREAD

**Issue by SirNudel** [bazaarvoice/jolt#453]
INPUT
```
{
    "label": "sampleID",
    "details": "sampleURL",
    "content": {
        "localeId": {
            "content": "sampleLocaleID"
        },
        "locale": {
            "content": "sampleLocale"
        },
        "languageId": {
            "content": "sampleLanguageID",
            "label": "sampleLabel",
            "details": "sampleURL",
            "selector": "sampleURL"
        }
    }
}
```

OUTPUT
```
{
    "label": "sampleID",
    "details": "sampleURL",
    "content": {
        "localeId":  "sampleLocaleID"  
        "locale":  "sampleLocale"
        "languageId": {
            "content": "sampleLanguageID",
            "label": "sampleLabel",
            "details": "sampleURL",
            "selector": "sampleURL"
        }
    }
}
```
The essence of my issue is that i want to remove the content wrapper, when there is just one value in the Attribute.

**Comment by milosimpson** [comment]
I don't understand the "The essence of my issue is that i want to remove the content wrapper, when there is just one value in the Attribute.",   but this spec transforms the input->output as listed above.

Spec

    [
      {
        "operation": "shift",
        "spec": {
          // pass thru
          "label|details": "&",
          "content": {
            // pass languageId map across
            "languageId": "content.languageId",
            // match either localeId or locale
            "localeId|locale": {
              // match the sub "content" field
              //  and send it's value to 
              // "content.&1" in the output
              "content": "content.&1"
            }
          }
        }
      }
    ]
