### ISSUE TITLE
Need help with Jolt Spec

### ISSUE THREAD

**Issue by sekaisan** [bazaarvoice/jolt#454]
Hi, 

I have trouble with a jolt spec transformation. 

This is the input:
```
payload: {
  DEVICE_TYPE: "device_type",
  DSN: "dsn",
  ENROLLMENT_STATUS_ID: 1.
}
```
desired output: 
```
payload: {
  DEVICE_TYPE: "device_type",
  DSN: "dsn",
  ENROLLMENT_STATUS_ID: "ENROLLED"
}
```
The value of ENROLLMENT_STATUS_ID is a decimal : 1.  not int 1; not string "1."
I tried to play it out using http://jolt-demo.appspot.com/#inception; but I found 1. is not even allowed on the right hand side. 
What I want is to have a mapping for ENROLLMENT_STATUS_ID like this:
"mapping": {
        1. : "ENROLLED",
        2. : "UNENROLLED",
        3. : "ENROLLMENT_PENDING",
        4. : "UNENROLLMENT_PENDING"
      }
But I found that 1. is not allowed on either side of mapping. 

I really need help with dealing with the 1. decimal value. Thank you in advance!

**Comment by milosimpson** [comment]
The 1. is not valid Json.   Does not pass https://jsonlint.com/  either.

**Comment by milosimpson** [comment]
If you can fix you input to not have the ".", then this is the way way to do the mapping.

Spec : 

    [
      {
        "operation": "default",
        "spec": {
          // Add your mapping to the Json data
          "mapping": {
            "1": "ENROLLED",
            "2": "UNENROLLED",
            "3": "ENROLLMENT_PENDING",
            "4": "UNENROLLMENT_PENDING"
          }
        }
      },
      {
        "operation": "shift",
        "spec": {
          "payload": {
            // pass thru
            "DEVICE_TYPE|DSN": "&",
            "ENROLLMENT_STATUS_ID": {
              // match any value of ENROLLMENT_STATUS_ID
              "*": {
                // use the "mapping" that was added to the
                //  root of the document
                "@(3,mapping.&)": "ENROLLMENT_STATUS_ID"
              }
            }
          }
        }
      }
    ]
