### ISSUE TITLE
More than one input json

### ISSUE THREAD

**Issue by arunkjn** [bazaarvoice/jolt#456]
Hi,

I have a requirement where I want to transform one or more input jsons to one output json by picking and transforming keys from the input jsons. Would that be possible through jolt?

**Comment by milosimpson** [comment]
No.  You will need to "join" your various Json inputs into a single Json document before Jolt.

We do this at Bazaarvoice, were we get two different Json documents from backend microservices, and then "glue" them together in Java code before handing it off to Jolt.

**Comment by arunkjn** [comment]
Thats very creative. Thanks @milosimpson
