### ISSUE TITLE
Need help on Jolt transformation to include default for array

### ISSUE THREAD

**Issue by hariharan-cn** [bazaarvoice/jolt#466]
Hello, I need a help on jolt transformation to include default value to array fields based certain condition,

My Json input,
```
{
  "commits": [
    {
      "added": [
        "sample.txt",
        "abc.sh"
      ],
      "removed": [
        "del.shs"
      ],
      "modified": [
        "readme.md",
        "test.txt"
      ]
    }
  ]
}
```
Jolt spec - I tried,
```
[
  {
    "operation": "shift",
    "spec": {
      "commits": {
        "*": {
          "added": {
            "*": {
              "#added": "changes[].action",
              "@": "changes[].path"
            }
          },
          "modified": {
            "*": {
              "#modified": "changes[].action",
              "@": "changes[].path"
            }
          },
          "removed": {
            "*": {
              "#removed": "changes[].action",
              "@": "changes[].path"
            }
          }
        }
      }
    }
   }
]
```
Expected output should be,
```
{  
   "changes":[  
      {  
         "action":"added",
         "path":"sample.txt"
      },
      {  
         "action":"added",
         "path":"abc.sh"
      },
      {  
         "action":"modified",
         "path":"readme.md"
      },
      {  
         "action":"modified",
         "path":"test.txt"
      },
      {  
         "action":"removed",
         "path":"delete.sh"
      }
   ]
}
```
Please make sure that the json input added,removed and modified are not in order they may change dynamically. suppose if we include files to added,removed,modified json input then it should reflect in json output with changes.action and path. Please help me out on this to transform jolt. I trieed multiple ways but noting worked out.
Thanks

**Comment by milosimpson** [comment]
Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "commits": {
        "*": { // array
          "*": { // added/removed/mod
            // accumulate all the things into a 
            //  top level array
            "*": "[].&1"
          }
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "*": { // top level array
        "*": { // added/removed/etc
          // break the key value pairs into 
          //  "path" and "action"
          "@": "changes[&2].path",
          "$": "changes[&2].action"
        }
      }
    }
  }
]
```

**Comment by hariharan-cn** [comment]
Hi @milosimpson ,
This is my actual input,
{
  "ref": "refs/heads/master",
  "before": "fb6c2ca4688e039c07f8f6dab5f4bfbf67a23456",
  "after": "3fe85b380032ed055734e01f5d8704da607f8f6a7",
  "created": false,
  "deleted": false,
  "forced": false,
  "commits": [
    {
      "id": "3fe85b380032ed055734e01f5d8704da607f8f6a7",
      "tree_id": "fb6c2ca4688e039c07f8f6dab5f4bfbf67a23456",
      "distinct": true,
      "message": "updated few files\n\nChange-Id: I83234233344c3ea278d9d1b51f33f767d5a1c871382\n",
      "timestamp": "2017-12-05T19:55:52+05:30",
      "url": "http://sample.net/ctf/code/git/projects.test/scm.notifyrepo/commits?treeId=3fe85b380032ed055734e01f5d8704da6bf3aaa7",
      "author": {
        "name": "Administrator",
        "email": "root@sample.net",
        "username": "admin"
      },
      "committer": {
        "name": "Administrator",
        "email": "root@sample.net",
        "username": "admin"
      },
      "added": [
        "sample.txt",
        "abc.sh"
      ],
      "removed": [
        "del.sh",
        "deleted.sh"
      ],
      "modified": [
        "readme.md",
        "test.txt"
      ]
    }
  ],
  "head_commit": {
    "id": "3fe85b380032ed055734e01f5d8704da6bf3aaa7",
    "tree_id": "4517af54e303193e70a552a36bf992ec2497c52a",
    "distinct": true,
    "message": "updated few files\n\nChange-Id: I8323e34c3ea278d9d1b51f33f767d5a1c871382\n",
    "timestamp": "2017-12-05T19:55:52+05:30",
    "url": "http://sample.net/ctf/code/git/projects.test/scm.notifyrepo/commits?treeId=3fe85b380032ed055734e01f5d8704da6bf3aaa7",
    "author": {
      "name": "Administrator",
      "email": "root@sample.net",
      "username": "admin"
    },
    "committer": {
      "name": "Administrator",
      "email": "root@sample.net",
      "username": "admin"
    },
    "added": [],
    "removed": [],
    "modified": [
      "readme.md",
      "test.txt"
    ]
  },
  "pusher": {
    "name": "Administrator",
    "email": "root@sample.net",
    "username": "admin"
  },
  "event_type": "ref-updated",
  "event_created_on": "2017-12-05T14:27:38+00:00",
  "repository": {
    "id": "reps1009",
    "name": "notifyrepo",
    "full_name": "notifyrepo",
    "description": "| Repo Category: optional_review, History Protection: On",
    "url": "http://sample.net/ctf/code/git/projects.test/scm.notifyrepo/tree"
  },
  "project": {
    "id": "proj1010",
    "url": "http://sample.net/sf/projects/test"
  }
}

and my output should be like this,
{
  "repo_id" : "reps1009",
  "branch_name" : "notifyrepo",
  "item_id" : "3fe85b380032ed055734e01f5d8704da6bf3aaa7",
  "message" : "updated few files\n\nChange-Id: I83033344c3ea278d9d1b51f33f767d5a1c871382\n",
  "event_time" : "2017-12-05T19:55:52+05:30",
  "created_by" : "Administrator",
  "type" : "post_commit"
  "changes" : [ {
    "path" : "sample.txt",
    "action" : "added"
  }, {
    "path" : "abc.sh",
    "action" : "added"
  }, {
    "path" : "del.sh",
    "action" : "removed"
  }, {
    "path" : "deleted.sh",
    "action" : "removed"
  }, {
    "path" : "readme.md",
    "action" : "modified"
  }, {
    "path" : "test.txt",
    "action" : "modified"
  } ]
}

I tried to modify the spec you provided but it didn't workout. Please help me on this,
[
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "repository": {
        "id": "=toString"
      }
    }
        },
  {
    "operation": "shift",
    "spec": {
      "repository": {
        "id": "repo_id",
        "full_name": "branch_name"
      },
      "commits": {
        "*": {
          "id": "item_id",
          "message": "message",
          "timestamp": "event_time"
        }
      },
      "pusher": {
        "name": "created_by"
      }
    }
        },
  {
    "operation": "default",
    "spec": {
      "type": "post_commit"
    }
}
]
