### ISSUE TITLE
Handling Null values and having different mappings based on a field value

### ISSUE THREAD

**Issue by bethcox93** [bazaarvoice/jolt#467]
Hi, 
I have a couple of questions while using Jolt. The first is how to handle nulls. So, I have input Json of the form:
```
{
   "level1": {
           "key1":"value1"
   }
}
```

and I want it to be:
```
{
    "newlevel1":{
             "newkey1":"value1"
    }
}
```

But if value1 is null I want to put a string, like, 'NOTFOUND' as the value. Is there a way I can do this?

The second, is the potential of having a different mappings depending on the value of a field on the incoming JSON. If the field is equal to VALUE1 or VALUE2 then the first mapping needs to be followed, otherwise the second mapping is followed. Is this possible to do in Jolt or should I do a check using Java prior to calling Jolt.

**Comment by milosimpson** [comment]
First question : About them nulls...

Best thing to do is to use "default" or the newer "modify-default-beta" to fill in a default value for any nulls that many come in.

Example
Input
```
{
  "level1": {
    "key1": null
  }
}
```

Spec
```
[
  {
    "operation": "default",
    "spec": {
      "level1": {
        "key1": "NOTFOUND"
      }
    }
  }
]
```

Will "replace" the null with NOTFOUND, but if the input had a non-null value, let it thru.


2nd question : Do a different "transform" based upon a field.

At Bazaarvoice we have documents of type : "review", "question", "answer" etc.   They have a "type" field in them.   So for these we use "outside of Jolt" mechanisms to figure out the type, and then map that to a single Jolt transform spec.
