### ISSUE TITLE
Transformation Help - Arbitrary data to single value field

### ISSUE THREAD

**Issue by b-long** [bazaarvoice/jolt#472]
Hi @milosimpson , thanks for all your work on this project.

I have a simple transform I'm trying to achieve, for arbitrary input.  The output desired is that all data (keys and value or just value) are available in the output JSON.  Null can be omitted or kept (as a string).   For instance, consider these input:

Example input 1:
```json
{
  "entities": [
    {
      "type": "alpha",
      "data": "foo"
    },
    {
      "type": "beta",
      "data": "bar"
    },
    {
      "type": "alpha",
      "data": "zoo"
    }
  ]
}
```

Example input 2:
```json
{
  "x": [ 3, 2, 1, "go"],
  "small": "small",
  "BIG": "BIG",

  "people": [
    {
      "firstName": "Bob",
      "lastName": "Smith",
      "address": {
        "state": null
      }
    },
    {
      "firstName": "Sterling",
      "lastName": "Archer"
    }
  ]
}
```

The desired output, is something like this (input keys can be included or not).  Preferably not.

Output produced by input 1:
```
{
  "output_data": "alpha foo beta bar alpha zoo"
}
```

Output produced by input 2:
```
{
  "output_data": "3 2 1 go small BIG Bob Smith null Sterling Archer"
}
```
Any help would be greatly appreciated!

**Comment by b-long** [comment]
Here's the closest I've come so far.  Using the following spec, will result in the output below.

Spec:
```
[
  {
    "operation": "modify-default-beta",
    "spec": {
      "output_data": "=concat(@(2),' ')"
    }
  },
  {
    "operation": "shift",
    "spec": {
      "output_data": "output_data"
    }
  }
]
```

Output produced for input 1 above (not yet the desired state)
```
{
  "output_data" : "{entities=[{type=alpha, data=foo}, {type=beta, data=bar}, {type=alpha, data=zoo}]} "
}
```
Output produced for input 2 above (not yet the desired state)
```
{
  "output_data" : "{x=[3, 2, 1, go], small=small, BIG=BIG, people=[{firstName=Bob, lastName=Smith, address={state=null}}, {firstName=Sterling, lastName=Archer}]} "
}
```

**Comment by milosimpson** [comment]
There is no easy way to get Jolt to handle "arbitrary input".   The fundamental problem is that there is know way to "know" / "condition" on "if this thing is a leaf".

If you can generally know the shape of your data, then you can have a spec that will do what you want.   

Example spec given your Input 1
```
[
  {
    "operation": "shift",
    "spec": {
      "*": {
        "*": {
          "*": "accum[]"
        }
      }
    }
  },
  {
    "operation": "modify-default-beta",
    "spec": {
      "stringAccum": "=join(' ',@(1,accum))"
    }
  }
]
```

However, if you run that on the 2nd input, it doesn't "do the right thing" because it is only matching things 3 levels down.

This is the spec for your Input 2
```
[
  {
    "operation": "shift",
    "spec": {
      "x": {
        "*": "accum[]"
      },
      "people": {
        "*": { // array index
          "*": "accum[]",
          "address": {
            "*": "accum[]"
          }
        }
      },
      "*": "accum[]" // catch small, BIG
    }
  },
  {
    "operation": "modify-default-beta",
    "spec": {
      "stringAccum": "=join(' ',@(1,accum))"
    }
  }
]
```
