### ISSUE TITLE
Remove if the more than two strings which may be null or whose value is ""

### ISSUE THREAD

**Issue by Ramuksk** [bazaarvoice/jolt#474]
I am using the below url to remove the null or whose value is "" https://github.com/bazaarvoice/jolt/issues/130.
But in my case is 
**Input:**
```
[
  {
    "id1": "5941",
    "id2": ""
  },
  {
    "id1": "5942",
    "id2": ""
  }
]
````

Output :
```
{
"id1":["5941","5942"]
}
```

**Need Output is:**
```
{
"id1":["5941","5942"],
"id2":[]
}
```
let us know any possible way to get need output from input.

**Comment by milosimpson** [comment]
Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "*": { // arrays
        "*": { // id1-id2
          // match the empty string copy value at that location
          //  which is null to the output.
          "": "&1",
          "*": {
            "$": "&2[]"
          }
        }
      }
    }
  },
  {
    "operation": "default",
    "spec": {
      // for every top level item, if the value is null,
      //  make it an empty string
      "*": []
    }
  }
]
```

**Comment by Ramuksk** [comment]
Hi milosimpson <https://github.com/milosimpson>,

Its working. thank you.

**Comment by Ramuksk** [comment]
Hi @milosimpson 

we tested with in below json and expected output not generated.

**Input:**
[
  {
    "ids1": "5945",
    "ids2": ""
  },
  {
    "ids1": "",
    "ids2": "6119"
  },
  {
    "ids1": "",
    "ids2": "6305"
  },
  {
    "ids1": "",
    "ids2": "5947"
  },
  {
    "ids1": "",
    "ids2": "4752"
  }
]
 
Out come result is

{
  "ids1" : [ "5945", null, null, null, null ],
  "ids2" : [ "6119", "6305", "5947", "4752" ]
}

**Expected** is 

{
  "ids1" : [ "5945"],
  "ids2" : [ "6119", "6305", "5947", "4752" ]
}
