### ISSUE TITLE
Need to remove negative values from array

### ISSUE THREAD

**Issue by bhargavs84** [bazaarvoice/jolt#476]
Hi,

 Is there a way where I can remove -ve values from a specific array, or perform numeric operations on float values

**Comment by milosimpson** [comment]
"I can remove -ve values from a specific array"  - I don't know what that means.

"perform numeric operations on float values"   - the math functions that Jolt supports are listed / demoed here http://jolt-demo.appspot.com/#modify-mathFunctions

**Comment by bhargavs84** [comment]
I have an array of objects I want to remove objects   which have amount field (double) less than a specific amount.

**Comment by milosimpson** [comment]
Nope.

**Comment by bhargavs84** [comment]
Thanks for the response. Any alternate solution in jolt API.

**Comment by milosimpson** [comment]
Not w/out writing Java code.   You could write a class that implements Transform (where you have to deal with the raw Json data), and then reference that from your spec.
