### ISSUE TITLE
Keys from one Array to Value fro other Array transformation

### ISSUE THREAD

**Issue by rlneeraja** [bazaarvoice/jolt#478]
```
{
  "ids": [
    1,
    2
  ],
  "message": [
    "Hello",
    "dsf"
  ]
}
```
output { {"1": "Hello"}, {"2":"dsf"}}, Can someone help me with spec, Thanks

**Comment by milosimpson** [comment]
I am assuming you actually want :
```
{
  "1" : "Hello",
  "2" : "dsf"
}
```

This spec does that :
```
[
  {
    "operation": "shift",
    "spec": {
      "message": {
        // write the value at each index location of the message
        //  array, to ... @(2,ids[&0])
        // This means go back up the tree 3 levels (0,1,2)
        //  come match the "ids" field, which is an array
        //  index that array by the index value of the messages
        //   array we are currently processing
        "*": "@(2,ids[&0])"
      }
    }
  }
]
```

**Comment by rlneeraja** [comment]
Thanks , that worked , what is  [&0], can you please explain,

**Comment by milosimpson** [comment]
See the slide deck 
https://docs.google.com/presentation/d/1sAiuiFC4Lzz4-064sg1p8EQt2ev0o442MfEbvrpD1ls/edit#slide=id.g99aac474_481

and the JavaDoc for shift
https://github.com/bazaarvoice/jolt/blob/master/jolt-core/src/main/java/com/bazaarvoice/jolt/Shiftr.java#L184
