### ISSUE TITLE
Using JsonNode to transform

### ISSUE THREAD

**Issue by vinaygoureddy** [bazaarvoice/jolt#482]
We have JsonNode available for transformation but we cannot use JsonNode to transform first we have to convert it to Object and the transformed object is also returned as Object again we have to convert it to JsonNode, which is adding time for transformation. 

So can we add method that transforms using JsonNode and returns JsonNode?

**Comment by milosimpson** [comment]
## Context

Jolt, "the project", emits several different Jar files.
* core
* json-utils
* guice-integration
* command line

The "core" of jolt has the Transforms (shift, remove, etc) and **explicitly** does not pull in Jackson (JsonNode) as a dependency, and **explicitly** operates on "standard Java objects".

There are lots of JSON -> Java Pojo tools of which Jackson is one, but the core of Jolt should be agnostic about that.    Things that are useful to BV (Jackson, Jolt, Guice) but which might not be used at other places are in separate optional jars.

## Answer the Question

So, if you want to use Jolt, and you have JsonNode as input and output, you will need to take the hit of converting the data.   

"So can we add method that transforms using JsonNode and returns JsonNode?"  I take this to mean, hey can the stock transforms just "work" with JsonNode?  No.

Converting the core Transform logic of Jolt to be JsonNode based, would basically be a rewrite of the code.    And would not be as simple as adding a method.   AFAIK
