### ISSUE TITLE
Adding a number to a value

### ISSUE THREAD

**Issue by haxway** [bazaarvoice/jolt#485]
So my input json is here
```{
"arrayname": [
    {
      "myvalue": 1515647175384
    },
    {
      "myvalue": "10213424"
    }]
}
```

And my spec is here
```
[
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "arrayname": {
        "*": {
          "NewField": "=intSum(19080000,@(1,myvalue))"
        }
      }
    }
  }
]
```

**The sum I obtain isn't right for the longer value**

Here's the output
```
{
  "checkIns" : [ {
    "myvalue" : 1515647175384,
    "NewField" : -457200104 //Whats with this value?
  }, {
    "myvalue" : "10213424",
    "NewField" : 29293424 //This value is correct
  }
```
Can you help? Thank you.

**Comment by milosimpson** [comment]
The number 1515647175384 is too big for "intSum"

* 1515647175384 the number you specified
* 2147483647 the maximum value represent-able as a 32 bit int in Java
* 10213424 the other number you specified, which is ok.
 
I suspect the negative value is coming in when Java tries to read in the "too big" number, and it ends up flipping around to negative.

Try "longSum", the max value of a long (64 bits) is 9223372036854775807

**Comment by haxway** [comment]
Thanks. Just one more question how do subtract? Do you pass a negative value? or is there another method?

**Comment by haxway** [comment]
Thanks.
