### ISSUE TITLE
Supporting wildcards in transpose

### ISSUE THREAD

**Issue by StephenWithPH** [bazaarvoice/jolt#491]
Given an input:
```
{
  "outerA": "foo",
  "outerB": "bar",
  "items": [
    {
      "name": "aaa",
      "id": "001"
    },
    {
      "name": "bbb",
      "id": "002"
    }
  ]
}
```

and a spec:
```
[
  {
    "operation": "shift",
    "spec": {
      "items": {
        "*": {
          "@(2,outerA)": "items[&1].outerA",
          "*": "items[&1].&"
        }
      }
    }
  }
]

```

... it is easy to arrive at a "flattened" json where a field from the outer has been projected into each object within the inner array. Furthermore, one doesn't have to hand-code the fields from the inner objects:
```
{
  "items" : [ {
    "outerA" : "foo",
    "name" : "aaa",
    "id" : "001"
  }, {
    "outerA" : "foo",
    "name" : "bbb",
    "id" : "002"
  } ]
}
```
(HT to https://github.com/bazaarvoice/jolt/issues/313#issuecomment-274114190 for this structure)

*However*, I don't believe it's possible to wildcard _all_ the fields from outer object. Using the same input as above with the filter:

```
[
  {
    "operation": "shift",
    "spec": {
      "items": {
        "*": {
          "@(2,*)": "items[&1].&",
          "*": "items[&1].&"
        }
      }
    }
  }
]
```

results in:

> 'Transpose Input' can not contain expansion wildcards (* and []).  Offending key : @(2,*)

(https://github.com/bazaarvoice/jolt/blob/master/jolt-core/src/main/java/com/bazaarvoice/jolt/common/pathelement/TransposePathElement.java#L95-L97)

_Is_ there a compelling reason not to support wildcards here? It would be nice to say "I know I have an object which contains a known field _foo_; _foo_ is an array of objects. I would like to push everything else from my object into each object within _foo_, and I don't want to have to specify all the fields... I just want to specify _foo_ as my known field which contains the array of objects."

I suspect there's a deep magic way to achieve the same result today; a wildcard-all-the-things approach would just make this sort of use case easier to approach.

Regardless... thank you for an excellent library that solves annoying problems with ease.

**Comment by StephenWithPH** [comment]
Regarding a non-wildcard way to achieve this, it's doable! I suspect there may be a cleaner way, but this works. Regardless, the original idea of allowing wildcards still seems interesting to me.

Let me know what you think.


input:
```
{
  "outerA": "foo",
  "outerB": "bar",
  "items": [
    {
      "name": "aaa",
      "id": "001"
    },
    {
      "name": "bbb",
      "id": "002"
    }
  ]
}
```

filter:
```
[
  {
    "operation": "shift",
    "spec": {
      "items": "items",
      "*": "outer.&"
    }
  },
  {
    "operation": "shift",
    "spec": {
      "items": {
        "*": {
          "*": "items[&1].&",
          "@(2,outer)": "items[&1].outer"
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "items": {
        "*": {
          "outer": {
            "*": "items[&2].&"
          },
          "*": "items[&1].&"
        }
      }
    }
  }
]

```

output:
```
{
  "items" : [ {
    "outerA" : "foo",
    "outerB" : "bar",
    "name" : "aaa",
    "id" : "001"
  }, {
    "outerA" : "foo",
    "outerB" : "bar",
    "name" : "bbb",
    "id" : "002"
  } ]
}
```

**Comment by milosimpson** [comment]
Q:   "Is there a compelling reason not to support wildcards here? It would be nice to say "I know I have an object which contains a known field foo; foo is an array of objects. I would like to push everything else from my object into each object within foo, and I don't want to have to specify all the fields... I just want to specify foo as my known field which contains the array of objects."

A:  The reason that "*" or  "[]" is not supported in the "@(Number,String)" transpose operator, is rooted in the code.    

From the "left hand side" operator "@(Number,String)", the "String" logic *reuses* the Json tree navigation code from the "right hand side" of the Shift transform.

Example
```
  {
    "operation": "shift",
    "spec": {
      "rating": {
        "*": {
          "max":   "SecondaryRatings.&1.Range",
          "@(2,rating.primary.max)" : "SecondaryRatings.&1.PrimaryRange"
        }
      }
    }
  }
]
```

To perform the "write" to "SecondaryRatings.&1.Range" it requires navigating the output Json in memory tree structure.

That write logic can also do reads, and that logic is reused in the "@(x,y)" logic, as such the "y" component can't have "*" or "[]" because those don't lead to a "concrete" path thru the Json tree.

**Comment by milosimpson** [comment]
Your 3 step transform makes sense.

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "items": "items",
      // grab everything other than "items" at the top level,
      //  and make them nest under an "outer" key
      "*": "outer.&"
    }
  },
  {
    "operation": "shift",
    "spec": {
      "items": {
        "*": {
          "*": "items[&1].&",
          // "embed" the contents of outer into each item
          "@(2,outer)": "items[&1].outer"
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "items": {
        "*": {
          // flatten outer into the items
          "outer": {
            "*": "items[&2].&"
          },
          "*": "items[&1].&"
        }
      }
    }
  }
]
```

**Comment by StephenWithPH** [comment]
Thanks for the explanation... makes sense. And thank you for open-sourcing this; it makes life much easier.
