### ISSUE TITLE
String format (Currency Conversion)

### ISSUE THREAD

**Issue by troastarrr** [bazaarvoice/jolt#497]
Hi,

I just started yesterday using this framework to our project.  I have some question regarding transforming string numbers to formatted string.
Request:
`{
  "SourceString": "13333"
}` 

I want something like this.
Response:
`{
  "DestString": "$13,333.00"
}`

I'm trying to use =concat method but no luck.  Thanks in advance for your help :)
Also, do you have some documentations that's listed the whole transforming method.

**Comment by troastarrr** [comment]
Hi, It is possible also to transform this
Request:
`{
  "Nested": {
    "List": {
      "SourceListString": [
        "first",
        "second",
        "third"
      ],
      "SourceListMap": [
        {
          "Key": "Value"
        }
      ],
      "SourceListInteger": [
        2,
        3,
        5,
        7,
        11,
        13
      ],
      "SourceListDouble": [
        44.2,
        22.4,
        55.1
      ],
      "SourceListDecimal": [
        321.21,
        432,
        99.2
      ]
    },
    "SourceNone": "Free for all",
    "SourceString": "Hello world",
    "SourceMultiSelect": "Text",
    "SourceJson": "{\"Key\": \"Value\"}",
    "SourceInteger": 998877,
    "SourceDouble": 543.21,
    "SourceCurrency": 12345.67,
    "SourceBoolean": true
  }
}`
Response:
`{
  "DestString": "Hello world",
  "DestNone": "Free for all",
  "DestMultiSelect": "Text",
  "DestJson": "\"{\\\"Key\\\": \\\"Value\\\"}\"",
  "DestInteger": 998877,
  "DestDouble": 543.21,
  "DestCurrency": "$12,345.67",
  "DestBoolean": true,
  "DestListDecimal": [
    321.21,
    432,
    99.2
  ],
  "DestListDouble": [
    44.2,
    22.4,
    55.1
  ],
  "DestListInteger": [
    2,
    3,
    5,
    7,
    11,
    13
  ],
  "DestListString": [
    "first",
    "second",
    "third"
  ],
  "DestListMap": [
    {
      "Key": "Value"
    }
  ]
}`

I have some spec like this..

`
[{
    "operation": "shift",
    "spec": {
      "Nested.List.SourceListInteger": "DestListInteger",
      "Nested:List:SourceListMap": "DestListMap"
       // etc.... 
    }
}
]
`

Thanks in advance.

**Comment by milosimpson** [comment]
The spec is not flat, it is not "Nested.List.SourceListInteger" is is "Nested" : { "List" : { "SourceListInteger" : .. } } }

```
[
  {
    "operation": "shift",
    "spec": {
      "Nested": {
        "List": {
          "SourceListInteger": "DestListInteger",
          "SourceListMap": "DestListMap"
        }
      }
    }
  }
]
```

**Comment by bnrs2006** [comment]
@milosimpson @troastarrr 

Hi Can you please share how can I do the currency formatting? 

I have the data coming in the json as a floating point value like below

"totalAmount": 25.92  - I want this to be written as $25.92
"totalAmount":39 - $39.00
"totalAmount":13456 = $13,456.00

Any help or idea for the conversion is appreciated. Thanks in Advance.

**Comment by wisthy** [comment]
adding $ in front is easy. For the rest, as far as I know, it's not currently supported by Jolt.
