### ISSUE TITLE
Transforming based on value 

### ISSUE THREAD

**Issue by binitbhaskar** [bazaarvoice/jolt#498]
Hi,
I am trying to transform the following input json 

~~~json 
{
  "root" : {
    "myObject": [
        {
          "type": "0",
          "timeStamp": "2016-08-30"
        },
        {
          "type": "1",
          "timeStamp": "2016-07-30"
        },
        {
          "type": "2",
          "timeStamp": "2016-06-30"
        }
      ]
  }
}
~~~

To 

~~~json
{
	"convertted" : {
    "time" : "2016-08-30"
  }
}
~~~

The "$.converted.time" should get the value (is not fixed) from the timestamp present in the "root.myObject[]" array whose "type=0". 
I am not sure how to apply filter for "type=0" and get the value from the "timestamp".
Can you please let me know if this is possible in Jolt and how the spec will look like ?
Thanks.

**Comment by milosimpson** [comment]
See https://github.com/bazaarvoice/jolt/issues/489

Basically match down to "type" : { "0" : { ...} } then use the "@" logic to grab the timeStamp field.

**Comment by binitbhaskar** [comment]
Thanks I got the spec

[
  {
    "operation": "shift",
    "spec": {
      "root": {
        "myObject": {
          "*": { // state array index
            "type": {
              // match the value of mailingAddressSame as either "yes" or "no"
              // depending on the match map the data differently.
              "0": {
                // @2 means go back up the tree 3 levels (0,1,2) 
                //  basically resetting the match to "contactdetail" level
                "@2": {
                  // now do all the "yes" logic
                  //  aka send the value of physicaladdress1 to both physicaladdress and correspondanceaddress
                  "timeStamp": "convertted.time"
                    //
                    // you can do the rest
                }
              }
            }
          }
        }
      }
    }
  }
]

**Comment by binitbhaskar** [comment]
Hi I also wanted to map all the myObject[]. to map to converted.myAr[] plus type 0 matching

e.g.
Expected output 

~~~json
{
  "converted" : {
    "myAr" : [ {
      "type": "0",
      "timestamp" : "2016-08-30"
    }, {
      "type": "1",
      "timestamp" : "2016-07-30"
    }, {
      "type": "2",
      "timestamp" : "2016-06-30"
    } ],
    "time" : "2016-08-30"
  }
}

~~~
I am trying the following spec, but its not working
~~~json
[
  {
    "operation": "shift",
    "spec": {
      "root": {
        "myObject": {
          "*": { // state array index
            "timeStamp": "converted.myAr[&1].timestamp",
            "type": {
              "*": "converted.myAr[&1].type",
              "0": {
                // @2 means go back up the tree 3 levels (0,1,2) 
                "@2": {
                  "timeStamp": "converted.time"
                }
              }
            }
          }
        }
      }
    }
  }
]

~~~

I am getting the following output (type is missing)

~~~json
{
  "converted" : {
    "myAr" : [ {
      "timestamp" : "2016-08-30"
    }, {
      "timestamp" : "2016-07-30"
    }, {
      "timestamp" : "2016-06-30"
    } ],
    "time" : "2016-08-30"
  }
}

~~~

**Comment by milosimpson** [comment]
Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "root": {
        "myObject": {
          "*": { // state array index
            // copy the whole type/timestamp map across 
            "@": "converted.myAr[&1]",
            // additionally match down on type : 0 and grab that timestamp field
            //  as it is special
            "type": {
              "0": {
                // @2 means go back up the tree 3 levels (0,1,2) 
                "@2": {
                  "timeStamp": "converted.time"
                }
              }
            }
          }
        }
      }
    }
  }
]
```
