### ISSUE TITLE
Is it possible to take an input array and unshift a new element to the front?

### ISSUE THREAD

**Issue by tombburnell** [bazaarvoice/jolt#502]
so from { list: [ 1,2,3 ] } => { list: [ 0,1,2,3] }

in my case 1,2,3 are actually objects.

Thanks, Tom

**Comment by milosimpson** [comment]
Ish.  Ugly.   Basically you have to add your new "0" item to the data, then in a second operation write the new "0" info to the output array first, and then accumulate the rest of the input list elements into that new output array.

See https://github.com/bazaarvoice/jolt/issues/494

**Comment by leojh** [comment]
I am looking to do the same but cannot seem to find the sample transformation anywhere to what should be a pretty common operation.

**Comment by milosimpson** [comment]
Input
```
{
  "list": [
    { "b": "b" },
    { "c": "c" },
    { "d": "d" }
  ]
}
```

Desired output
```
{
  "list": [
    { "a": "a" },
    { "b": "b" },
    { "c": "c" },
    { "d": "d" }
  ]
}
```

Spec
```
[
  {
    // default into the document the new "first" value
    "operation": "default",
    "spec": {
      "first": {
        "a": "a"
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "list": {
        "*": "list[]"
      },
      //
      // Rely upon implementation detail of Shift in that :
      // "@" logic is processed before other things in the spec
      //   so this will happen / write/append to the output list first
      //   even tho it is specifed after the processing of the input list
      // 
      "@first": "list[]"
    }
  }
]
```

**Comment by leojh** [comment]
Thank you for your help. I meant to close this way back when. :)
