### ISSUE TITLE
Specific statement about whether asterisk wildcard can match an empty string as prefix or suffix?

### ISSUE THREAD

**Issue by davidmichaelkarr** [bazaarvoice/jolt#508]
I've been told that the asterisk wildcard, when combined with a non-empty prefix or suffix, cannot match a string consisting of only the prefix or suffix.  For instance, if the expression is "*FOO", it will not match "FOO", but it would match "AFOO".  Is this true?  I can't find a clear statement about this in the documentation.

**Comment by milosimpson** [comment]
Yes.  Technically the "*" in Jolt is "actually" "+" in regex meaning.

It dates back the the very beginning of Jolt, where we wanted to handle "rating" and "rating*" as different things.
