### ISSUE TITLE
compare key to with value in the and array element and get the out put 

### ISSUE THREAD

**Issue by raghavendraprasadgudipalli** [bazaarvoice/jolt#513]
input json 
{
  "Result": {
    "owner": {
      "name": "test  user"
    },
    "Components": [
      {
        **"id": "123-456-789"**
      }
    ],
    **"123-456-789":** {
      "temp": {
        "emip": "abc",
        "teto": "123"
      }
    }
  }
}
and out put required is 
 "123-456-789": {
      "temp": {
        "emip": "abc",
        "teto": "123"
      }

compare Components --> id should match with key

**Comment by raghavendraprasadgudipalli** [comment]
could you please help me I am new to JOLT

**Comment by milosimpson** [comment]
Answered on StackOverflow.
