### ISSUE TITLE
Jolt Spec required for this below input (unable to change name inside list)

### ISSUE THREAD

**Issue by yarabsyp** [bazaarvoice/jolt#515]
Hello Team,

input below

"addressDetails": {
		"legalAddress": {
			"aType": "L",
			"city": "test 1",
			"stateProvince": "test 1",
			"zipCodeInfo": "test 1"
		},
		"mailingAddress": {
			"aType": "M",
			"city": "test 2",
			"stateProvince": "test 2",
			"zipCodeInfo": "test 2"
		}
	}

want to change zipCodeInfo into zipNameChagne and make all as list of map. Please help us to solve 
this issue 

used this sepc not working out 

"addressDetails": {
				"legalAddress" : 
				{
				"zipCodeInfo": "&2.address[].zipCode1"
				
				},
				
				"mailingAddress": {
				"zipCodeInfo": "&2.address[].zipCode1"
				
				},
				"*": "&"
			},

output:

{
  "addressDetails": {
    "address": [
      {
        "aType": "L",
        "city": "test 1",
        "stateProvince": "test 1",
        "zipNameChagne": "test 1"
      },
      {
        "aType": "M",
        "city": "test 2",
        "stateProvince": "test 2",
        "zipNameChagne": "test 2"
      }
    ]
  }
}

**Comment by milosimpson** [comment]
Cleanup your question :  https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by yarabsyp** [comment]
Done
