### ISSUE TITLE
Json to Json with Jolt Transformation 

### ISSUE THREAD

**Issue by chaimoumaCJ** [bazaarvoice/jolt#520]
Hello everyone !
I'm new in Jolt
can anyone help me please !
I have a complex Json files to flatten , I wanna All the objects in the same level
How can I shift recursively the Json file I have !
[https://drive.google.com/open?id=1PohwRYpOK1_-e9kknqY9pA5gsBtz1fmE](url)
@milosimpson 
please Sir Can you help me !

**Comment by milosimpson** [comment]
Post an input and desired output.  Using these guidelines https://help.github.com/articles/creating-and-highlighting-code-blocks/
