### ISSUE TITLE
Does JOLT support splitting Strings

### ISSUE THREAD

**Issue by coriedai** [bazaarvoice/jolt#522]
Hi,

Is there a way to split a String into several fields, based on certain delimiters? I need to parse the following String into a map, but I'm not sure how we can achieve this with JOLT.

Input:
`
{
   "metadata":"key1:value1, key2:value2, key3:value3"
}
`

Expected output:
`
{
   "metadata": {"key1":"value1", "key1":"value2", "key3":"value3"}
}
`

Thank you!

**Comment by milosimpson** [comment]
Not in a generic way.

If you know your metadata always has 3 "things" in it, then you can do it via a hardcoded spec.

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "metadata": {
        // match exactly three sets of key value pairs
        "*, *, *": {
          // pull each one off and accumulate them into a temp array
          "$(0,1)": "temp[]",
          "$(0,2)": "temp[]",
          "$(0,3)": "temp[]"
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "temp": {
        "*": {
          // match each item by ":" into two captures
          "*:*": {
            "$(0,2)": "metadata.&(1,1)"
          }
        }
      }
    }
  }
]
```

**Comment by coriedai** [comment]
@milosimpson 
What if the exact number of key value pairs in the String is unknown, but I do know the max number (let's say 10)? 

Is it okay if I do "*, *, *, *, *, *, *, *, *, *" even though I might only have 3 key value pairs? Would JOLT through an exception?

Thank you!!

**Comment by milosimpson** [comment]
Try it.  http://jolt-demo.appspot.com

I think it would fail to match.

**Comment by coriedai** [comment]
@milosimpson 
I see. So it looks like the wildcard spec needs to match the original String exactly.

If I can somehow make the input to be "key1:value1, key2:value2, key3:value3,,,,,,," where the later * matches to empty Strings, will there be a workaround..?
