### ISSUE TITLE
Compare and add elements of two arrays in another

### ISSUE THREAD

**Issue by AyyubQW** [bazaarvoice/jolt#533]
Hey i have the following input array

`[
  {
    "brandsToBeDetailed": [
      "abc",
      "pqr",
      "lmn"
    ]
  },
  {
    "brandsDetailed": [
      "abc",
      "pqr",
      "xyz"
    ]
  }
]`

I want to compare the brandDetailed array with brandsToBeDetailed so that i can get the following output below

`[
  {
    "brandsSkipped": [
      "lmn"
    ],
    "otherBrands": [
      "xyz"
    ]
  }
]
`

**Comment by milosimpson** [comment]
No can do with OOTB transforms.

**Comment by AyyubQW** [comment]
Ok thanks milosimpson. Appreciate it
