### ISSUE TITLE
how to handle the json null

### ISSUE THREAD

**Issue by Cheakk** [bazaarvoice/jolt#534]

**Comment by Cheakk** [comment]
input:
{
  "id1" : "ceshi",
  "id2" : "SH17",
  "id3" : null,
  "id4" : "2018/2/1 8:50",
  "id5" : "进",
  "id6" : "POS",
  "id7" : "刷卡",
  "id8" : "01SCO"
}

spec:
[
  {
    "operation": "default",
    "spec": {
      "*": {
        "id5": "1"
      }
    }
  }
]

out:
{
	"id1": "ceshi",
	"id2": "SH17",
	"id3": {
		"id5": "1"
	},
	"id4": "2018/2/1 8:50",
	"id5": "进",
	"id6": "POS",
	"id7": "刷卡",
	"id8": "01SCO"
}

can i change the out like：
{
	"id1": "ceshi",
	"id2": "SH17",
	"id3": 1，
	"id4": "2018/2/1 8:50",
	"id5": "进",
	"id6": "POS",
	"id7": "刷卡",
	"id8": "01SCO"
}

thank you

**Comment by milosimpson** [comment]
Spec
```
[
  {
    "operation": "default",
    "spec": {
      "id3": "1"
    }
  }
]
```

**Comment by Cheakk** [comment]
thanks
