### ISSUE TITLE
Creating a map from string to list

### ISSUE THREAD

**Issue by coriedai** [bazaarvoice/jolt#536]
Hi,

I created an issue two weeks back (https://github.com/bazaarvoice/jolt/issues/522) and I have some additional questions on top of that.

More specifically, I want to construct a map from string to list. 

Input:
```
{
  "metadata": "k1:v1#k2:v2#k2:v2"
}
```

Current spec:
```
[
  {
    "operation": "shift",
    "spec": {
      "metadata": {
        "*#*#*": {
          "$(0,1)": "temp[]",
          "$(0,2)": "temp[]",
          "$(0,3)": "temp[]"
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "temp": {
        "*": {
          "*:*": {
            "$(0,2)": "metadata.&(1,1)"
          }
        }
      }
    }
  }
]
```

Current output:
```{
  "metadata" : {
    "k1" : "v1",
    "k2" : [ "v2", "v2" ]
  }
}
```

Expected output:
```
{
  "metadata" : {
    "k1" : ["v1"],
    "k2" : [ "v2", "v2" ]
  }
}
```

Since I want to construct a map from string to list, I need to create a list even if there is only one element in that list. Would it be possible to achieve with JOLT?

(Sorry I don't know how to properly format the spec code.... You can take a look at the spec you provided in the linked issue as an example.)

Thanks!

**Comment by coriedai** [comment]
Sorry I don't know how to properly format the spec code.... You can take a look at the spec you provided in the linked issue as an example.

**Comment by milosimpson** [comment]
Spec line to change
```
"$(0,2)": "metadata.&(1,1)[]"
```

**Comment by zenloop** [comment]
How can I convert a string like "one,two,three" to an array with Jolt ["one", "two", "three"]?  The length of the comma separated list is unknown. Any help is appreciated.
