### ISSUE TITLE
Constructing an array of structs. 

### ISSUE THREAD

**Issue by coriedai** [bazaarvoice/jolt#537]
Hi,

I'd like to know how I can construct a list of structs in my case.

Input:
```
{
  "metadata": "k1:v1#k2:v2#k2:v2#dummy"
}
```

Current spec:
```
[
  {
    "operation": "shift",
    "spec": {
      "metadata": {
        "*#*#*#*": {
          "$(0,1)": "temp[]",
          "$(0,2)": "temp[]",
          "$(0,3)": "temp[]",
          "$(0,4)": "temp[]"
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "temp": {
        "*": {
          "*:*": {
            "$(0,1)": "metadata[].key",
            "$(0,2)": "metadata[].value"
          }
        }
      }
    }
  }
]
```

Current output:
```
{
  "metadata" : [ {
    "key" : "k1"
  }, {
    "value" : "v1"
  }, {
    "key" : "k2"
  }, {
    "value" : "v2"
  }, {
    "key" : "k2"
  }, {
    "value" : "v2"
  } ]
}
```

Expected output:
```
{
  "metadata" : [
    {
      "key" : "k1",
      "value": "v1"
    },
    {
      "key" : "k2",
      "value": "v2"
    },
    {
      "key" : "k2",
      "value": "v2"
    }
  ]
}
```

With the current spec, I think I should add an array location inside  "[ ]", but I'm not sure how I can get the appropriate index. Also, I don't want to add a null entry for the "dummy" at the end.

Thank you!

**Comment by milosimpson** [comment]
Spec change
```
            // lookup the index of the temp array using "&2"
            "$(0,1)": "metadata[&2].key",
            "$(0,2)": "metadata[&2].value"
```

**Comment by coriedai** [comment]
It worked! Thank you very much! 

I did consider using "&2", but according to the JOLT documentation, " &: dereference against a "path" to get a value and use that value as if were a literal key". Why doesn't the "&2" here get the actual value of * (for example k1:v1)?  

Would this approach still work if the value "dummy" can show up in the middle?

**Comment by milosimpson** [comment]
JSon is a "tree" based structure.   The "shift" spec is also a "tree" based structure.   

Jolt "shift" is basically doing a parallel tree walk, of the input data and the spec, and when there is a "leaf" level "match" it copies data to the output.

While it is doing it's parallel tree walk, "shift" maintains a "stack" data structure, of the all the parent nodes visited.     The "&" logic allows you to "lookup" values from that stack.
