### ISSUE TITLE
Not able to convert string to boolean.

### ISSUE THREAD

**Issue by parkash-bansal** [bazaarvoice/jolt#538]
Hi team,

I am trying to convert string type json field with possible values of "Y" or "N" into true and false respectively but I am unable to do that.

Input JSON:

```
{
  "type": "1234",
  "data": {
    "booleanFlag": "Y"    
  }
}
```

Desired output JSON
```
{
  "client": {
    "values": {
      "1234": {
        "booleanFlag": "true"
      }
    }
  }
}
```

Following is the JOLT spec that I have created to convert this but transformer is giving null as output.

```
[
  {
    "operation": "shift",
    "spec": {
      "@data.booleanFlag": {
        "N": { "#false": "client.values.@type.booleanFlag" },
        "Y": { "#true": "client.values.@type.booleanFlag" }
      }
    }
  }
]
```

Please let me know what am I doing wrong here. The caveat here is I want to use the value of one of the input field in output json hierarchy which in this case is the value of field "type".
Thanks & Regards,
Parkash

**Comment by milosimpson** [comment]
Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "data": {
        "booleanFlag": {
          "N": {
            "#false": "client.values.@(4,type).booleanFlag"
          },
          "Y": {
            "#true": "client.values.@(4,type).booleanFlag"
          }
        }
      }
    }
  }
]
```

Changes
"@data.booleanFlag"  -> doesn't match anything.   Instead break it down.
"client.values.@type.booleanFlag" -> the "@type" value you want is from 5 levels up the tree, so use @(5,type)"

**Comment by parkash-bansal** [comment]
Hey @milosimpson, Thanks for the quick reply. Yes, this works.

But I am getting the converted value for booleanFlag as String. 
"booleanFlag": "true"
Is there any way to get it as boolean ?, I mean true or false without quotes as below

"booleanFlag": true

**Comment by milosimpson** [comment]
http://jolt-demo.appspot.com/#modify-typeConversion

see usage of "=toBoolean"

**Comment by parkash-bansal** [comment]
Yes, I am able to work it out.

Thanks a lot !
