### ISSUE TITLE
How Extract List into Flattened Map in JOLT

### ISSUE THREAD

**Issue by yarabsyp** [bazaarvoice/jolt#539]
Hello guys,
I have a input below format
```
{
   "additionalList" : ["a","b","c"],
   "mapAdditionalListofMap" : [{"key1":"value1","key2":"value2"},{"key1":"value3","key2":"value4"}]
}
```

I need to extract all list field into the flattened format. 
Note List may come more values  
["a","b","c".......etc] [{"key1":"value1","key2":"value2"},{"key1":"value3","key2":"value4"}.... etc]

Could you please help us to provide a spec for this item 

output
```
{
additionalList1":"a",
additionalList2":"b",
additionalList3":"c",
mapAdditionalListofMap1_key1" : "value1",
mapAdditionalListofMap1_key2":"value2",
"mapAdditionalListofMap2_key1" :"value3",
"mapAdditionalListofMap2_key2":"value4"
}
```

**Comment by milosimpson** [comment]
Easy-ish, as long as you are ok with the numbers starting from "zero".

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "additionalList": {
        "*": "additionalList&"
      },
      "mapAdditionalListofMap": {
        "*": {
          "key*": "mapAdditionalListofMap&1_&"
        }
      }
    }
  }
]
```

Produces Output
```
{
  "additionalList0" : "a",
  "additionalList1" : "b",
  "additionalList2" : "c",
  "mapAdditionalListofMap0_key1" : "value1",
  "mapAdditionalListofMap0_key2" : "value2",
  "mapAdditionalListofMap1_key1" : "value3",
  "mapAdditionalListofMap1_key2" : "value4"
}
```

If "additionalList0" does not work for you then I suggest.
1) Before jolt, prepend a null to the "additionalList" and "mapAdditionalListofMap"  
2) run jolt
3) use Jolt's remove operation to specifically remove the bogus "additionalList0"  and  "mapAdditionalListofMap0_key1"

**Comment by yarabsyp** [comment]
Awesome great I really appreciat your timeline help
