### ISSUE TITLE
Please please please help

### ISSUE THREAD

**Issue by alfj12** [bazaarvoice/jolt#542]
I need help figuring this out what the jolt transformation should be and am desperate for help.  if anyone can lend a helping hand that'd be great!!!

**This is my input:**

[ {
  "ID" : "3400000",
  "SubID" : [ "787878", "343434" ],
  "Name" : "Length",
  "Value" : "25"
}, {
  "ID" : "3400000",
  "SubID" : [ "787878", "343434" ],
  "Name" : "Angle",
  "Value" : "Acute"
}]

**This is what i need my output to be**

[ {
  "ID" : "3400000",
  "SubID" : "787878",
  "Name" : "Length",
  "Value" : "25"
}, 
{
  "ID" : "3400000",
  "SubID" : "343434",
  "Name" : "Length",
  "Value" : "25"
},
{
  "ID" : "3400000",
  "SubID" : "787878"
  "Name" : "Angle",
  "Value" : "Obtuse"
}, 
{
  "ID" : "3400000",
  "SubID" : "343434" 
  "Name" : "Angle",
  "Value" : "Obtuse"
}]

**Comment by criztovyl** [comment]
Something like this?

```json
[
    {
        "operation": "shift",
        "spec": {
            "*": {
                "SubID": {
                    "*": {
                        "@2": "&-&3.old",
                        "@": "&-&3.new.&2"
                    }
                }
            }
        }
    },
    {
        "operation": "remove",
        "spec": {
            "*": {
                "old": {
                    "SubID": ""
                }
            }
        }
    },
    {
        "operation": "shift",
        "spec": {
            "*": {
                "*": {
                    "*": "&2.&"
                }
            }
        }
    },
    {
        "operation": "shift",
        "spec": {
            "*": "[]"
        }
    }
]
```

Also, maybe try to use the following for highlighting JSON on GitHub, [also see here](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

    ```json
    {
        "key": "value"
    }
    ```

**Comment by alfj12** [comment]
Thank you!!! That solves my problem!!!  I really appreciate it!!!

**Comment by milosimpson** [comment]
This is a bit more straightfoward.

Spec

    [
      {
        "operation": "shift",
        "spec": {
          "*": { // input array
            "SubID": {
              "*": {
                // keep the two doubly nested arrays
                // where we can leverage the existing array indices
                // but now we can pull the "id" down
                "@": "[&3].subidArray[&1].SubID",
                "@(2,ID)": "[&3].subidArray[&1].ID",
                "@(2,Name)": "[&3].subidArray[&1].Name",
                "@(2,Value)": "[&3].subidArray[&1].Value"
              }
            }
          }
        }
      },
      {
        // walk the double nested lists, and accumulate the inner
        //  items into a top level output array.
        "operation": "shift",
        "spec": {
          "*": { // input array
            "subidArray": {
              "*": "[]"
            }
          }
        }
      }
    ]

**Comment by alfj12** [comment]
hi @milosimpson, if the array subid array had only one element instead of two, will the transformation create multiple json messages of the same info?

ie.
[ {
"ID" : "3400000",
"SubID" : [ "787878" ],
"Name" : "Length",
"Value" : "25"
}, {
"ID" : "3400000",
"SubID" : [ "787878"],
"Name" : "Angle",
"Value" : "Acute"
}]

**Comment by milosimpson** [comment]
Try it on the demo site.   http://jolt-demo.appspot.com/#inception
