### ISSUE TITLE
Replacing values

### ISSUE THREAD

**Issue by criztovyl** [bazaarvoice/jolt#543]
Hello,

while looking into #542, I naively tried the follwing spec to transform the data.
But Jolt does not produce any output any time soon, it seems like it hangs in an endless loop.

Data
```json
[
    {
        "id": "One",
        "subid": ["1.1", "1.2"]
    },
    {
        "id": "Two",
        "subid": ["2.1", "2.2"]
    }
]
```

Spec
```json
[
    {
        "operation": "shift",
        "spec": {
            "*": {
                "subid": {
                    "*": {
                        "@2": "&-&3",
                        "@0": "&-&3.&2"
                    }
                }
            }
        }
    },
    {
        "operation": "shift",
        "spec": {
            "*": "[]"
        }
    }
]
```
Expected Output
```json
[ {
  "id" : "One",
  "subid" : "1.1"
}, {
  "id" : "One",
  "subid" : "1.2"
}, {
  "id" : "Two",
  "subid" : "2.1"
}, {
  "id" : "Two",
  "subid" : "2.2"
} ]
```

**Comment by milosimpson** [comment]
"it seems like it hangs in an endless loop."  -> yes, this can happen.

If you switch the ordering of the "@"s the transform will complete.   It's not right, but it completes.

```
            "@0": "&-&3.&2",
            "@2": "&-&3"
```

**Comment by milosimpson** [comment]
At the "start" of the"shift" operation, a new Hashmap is created to be the "output".   When "shift" copies a "value" from the input to the output, it is a shallow copy.    The vast majority of the time this is ok, as it is typically "scalar" values that are being shallow copied from input to output : Strings, numbers, etc.

However, you can also have shift copy a whole "chunk" of the input map, across.

In this case when the "@2" was first in the spec, it was copying the "entire" input (which is a list) across to the output.
Then, when "@0" was processed it was inserting something into the shallow-copied input list.  Thus causing the infinite loop.

**Comment by milosimpson** [comment]
FYI Spec that does the transform

    [
      {
        "operation": "shift",
        "spec": {
          "*": { // input array
            "subid": {
              "*": {
                // keep the two doubly nested arrays
                // where we can leverage the existing array indices
                // but now we can pull the "id" down
                "@": "[&3].subidArray[&1].subid",
                "@(2,id)": "[&3].subidArray[&1].id"
              }
            }
          }
        }
      },
      {
        // walk the double nested lists, and accumulate the inner
        //  items into a top level output array.
        "operation": "shift",
        "spec": {
          "*": { // input array
            "subidArray": {
              "*": "[]"
            }
          }
        }
      }
    ]

**Comment by criztovyl** [comment]
So it's a bug? ^^

Maybe I should also have mentioned that I don't want to specify each key of the object.
In example if there are many keys, there is so much "code" duplication I would like to prevent.

But I currently don't have JSON I want to transform, I only would really like to have such a possibility.
So a way to request a deep copy somehow (or intelligently finding out if it's required, if that's possible) would be nice.

I have not yet understood the sources, but If I find time, I could try to implement something like that, if this would be something you want. (If you could point me to some portions in the code that relate to this, that would speed that up, hopefully :D)

Thank you.

**Comment by milosimpson** [comment]
It is a bug, that the only way to fix would require making copies of data, which for the vast majority of cases, I don't want to do.
