### ISSUE TITLE
Need help on shift operation

### ISSUE THREAD

**Issue by parkash-bansal** [bazaarvoice/jolt#544]
Hi Team,

I want to shift the data from one json to another.

Here is my input.

`{
  "type": "length",
  "event_time": "20170906",
  "data": {
    "unit": "m",
    "value": "56"
  }
}`

and here is the required output

`{
  "client" : {
    "length" : {
      "date": "20170906",
      "unit" : "m",
      "value" : "56"
    }
  }
}
`

Basically **client** is my root key and then it will have the value of **type** in input json as it child and the value of the type will be object containing all the elements of **data** object plus value of event_time as date element in the type value object.

Please help me how can I do that.

**Comment by milosimpson** [comment]
Spec

```
[
  {
    "operation": "shift",
    "spec": {
      "event_time": "client.@(2,type).date",
      "data": {
        "unit": "client.@(3,type).unit",
        "value": "client.@(3,type).value"
      }
    }
  }
]
```

**Comment by parkash-bansal** [comment]
@milosimpson As per my requirement, the fields of the data object are dynamic and are unknown. I need an operation where we shift the whole **data** object under the value of type field without actually knowing the field names of the data object.


**Example 1**
Here is my input.

`{
  "type": "length",
  "event_time": "20170906",
  "data": {
    "unit": "m",
    "value": "56"
  }
}`


and here is the required output

`{
  "client" : {
    "length" : {
      "date": "20170906",
      "unit" : "m",
      "value" : "56"
    }
  }
}
`

Another example could be.
**Example 2**
Here is my input.

`{ "type": "measurement", "event_time": "20170906", "data": { "booleanFlag": true, "measuredValue": "12" } }`
 and following should be output.

`{ "client" : { "measurement" : { "date": "20170906", "booleanFlag" : true, "measuredValue" : "12" } } }`

**Comment by milosimpson** [comment]
Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "event_time": "client.@(2,type).date",
      "data": {
        "*": "client.@(3,type).&"
      }
    }
  }
]
```

**Comment by parkash-bansal** [comment]
This is exactly what I needed. Thanks a lot @milosimpson !
