### ISSUE TITLE
Can You Have a Conditional Check in a Jolt Transform Check for Nulls & Blanks?

### ISSUE THREAD

**Issue by jag959** [bazaarvoice/jolt#546]
Hello!

With the Jolt transformation below, I would like to not have a specific step in the transformation occur if a field is blank or null for the specific field it's applying to.  I am trying to create unique keys by concatenating fields in the JSON document, but this does not work well if the fields are not populated (I'd assume not having a key for such a record in that case.)

Thanks in advance for help on this awesome library.
```
[
  {
    "operation": "default",
    "spec": {
      "InvoiceRecords[]": {
        "*": {
          "InvoiceRecordHeaderDetails[]": {
            "*": {
              "CompanyName": "%message{CompanyName}",
              "LastUpdated": "%message{LastUpdatedTimestamp}"
            }
          },
          "InvoiceRecordSplitDetails[]": {
            "*": {
              "CompanyName": "%message{CompanyName}",
              "LastUpdated": "%message{LastUpdatedTimestamp}"
            }
          },
          "InvoiceRecordLineItemDetails[]": {
            "*": {
              "CompanyName": "%message{CompanyName}",
              "LastUpdated": "%message{LastUpdatedTimestamp}"
            }
          },
          "InvoiceTaxCodeDetails[]": {
            "*": {
              "CompanyName": "%message{CompanyName}",
              "LastUpdated": "%message{LastUpdatedTimestamp}"
            }
          }
        }
      }
    }
  },
  {
    "operation": "modify-default-beta",
    "spec": {
      "InvoiceRecords": {
        "*": {
          "InvoiceRecordHeaderDetails": {
            "*": {
              "AgilityInvoiceLinkID": "=concat(@(1,CompanyName),@(1,Location),@(1,InvNum))"
            }
          },
          "InvoiceRecordSplitDetails": {
            "*": {
              "AgilityInvoiceLinkID": "=concat(@(1,CompanyName),@(1,Location),@(1,InvNum))"
            }
          },
          "InvoiceRecordLineItemDetails": {
            "*": {
              "AgilityInvoiceLinkID": "=concat(@(1,CompanyName),@(1,Location),@(1,InvNum))"
            }
          },
          "InvoiceTaxCodeDetails": {
            "*": {
              "AgilityInvoiceLinkID": "=concat(@(1,CompanyName),@(1,Location),@(1,InvNum))"
            }
          }
        }
      }
    }
  }
]
``
```

**Comment by milosimpson** [comment]
"if a field is blank or null for the specific field it's applying to."  Jolt really doesn't do "if" statements.  The only "if" you can kind of get at is "if this matches", but that doesn't really help here.

I think the best you can do is make sure there are default values for "CompanyName", "Location", and "InvNum", or do post processing on "AgilityInvoiceLinkID"

Idea being make "AgilityInvoiceLinkID" have dashes between the values
```
"=concat(@(1,CompanyName),'-',@(1,Location),'-',@(1,InvNum))"
```

That we it is easy to tell in your post processing if you see "---" or a string that contains "--" then you know you it is bad / remove it?

**Comment by jag959** [comment]
Thanks for you quick response and the suggestion.  I may take that route as it seems like a viable workaround.

- Regards.
