### ISSUE TITLE
Convert map to array of maps

### ISSUE THREAD

**Issue by darkpssngr** [bazaarvoice/jolt#555]
Hi is it possible to achieve something like this
<pre>
input
{
  "rating": {
    "primary": {
      "value": 3
    },
    "quality": [
      {
      "value": 3
    	},{
      "value" : 2
    	}
    ]
  }
}
</pre>
into 
<pre>
[{
  "rating": {
    "primary": {
      "value": 3
    },
    "quality":{
      "value" : 2
    	}
  }
},
{
  "rating": {
    "primary": {
      "value": 3
    },
    "quality":  {
      "value": 3
    	}
  }
}
]
</pre>

**Comment by darkpssngr** [comment]
I tried something like this
<pre>
[
  {
    "operation": "shift",
    "spec": {
      "rating": {
        "quality": {
          "*": {
            "@3": ""
          }
        }
      }
    }
  },
  {
    "operation": "remove",
    "spec": {
      "*": {
        "rating": {
          "quality": {
            "0": ""
          }
        }
      }
    }
  }
]
</pre>
need help on how to only select the first values.

**Comment by milosimpson** [comment]
Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "rating": {
        "quality": {
          "*": {
            "value": "[&1].quality.value",
            "@(2,primary.value)": "[&1].rating.primary.value"
          }
        }
      }
    }
  }
]
```

**Comment by darkpssngr** [comment]
This only works if I the payload structure is constant right? if the object inside quality has different keys which I can't control, can I make it work? something like 

<pre>
{
  "rating": {
    "primary": {
      "value": 3
    },
    "quality": [
      {
      "value": 3,
      "test": 54 
    	},{
      "value" : 2,
      "key": "user"
    	}
    ]
  }
}
</pre>

is there a way to tell the shiftr spec to capture the array index and use the value at the index?

**Comment by milosimpson** [comment]
Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "rating": {
        "quality": {
          "*": {
            "*": "[&1].quality.&",
            "@(2,primary.value)": "[&1].rating.primary.value"
          }
        }
      }
    }
  }
]
```

**Comment by darkpssngr** [comment]
Thanks !!!
