### ISSUE TITLE
Remove element based on subelements

### ISSUE THREAD

**Issue by pvve** [bazaarvoice/jolt#557]
Input:

`{
	"elements": {
		"1": {
			"var1": "A",
			"var2": "1"
		},
		"2": {
			"var1": "A",
			"var2": "2"
		},
		"3": {
			"var1": "B",
			"var2": "1"
		}
	}
}`

I want to remove all elements where var1 = A and var2 = 1.
Expected output:

`{
	"elements": {
		"2": {
			"var1": "A",
			"var2": "2"
		},
		"3": {
			"var1": "B",
			"var2": "1"
		}
	}
}`

Is this something that can be done using JOLT?

**Comment by milosimpson** [comment]
Can do, it is not so much "remove" as it is, only match and copy to the output things that aren't "var1 : A" and "var2 : 1"

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "elements": {
        "*": {
          "var1": {
            "A": {
              // if we match this far down it means
              //  var1 is A, in this case
              //  "reset" the tree traversal back up 3 levles
              //   (0,1,2), and then match var2 = 1
              "@2": {
                "var2": {
                  "1": null,
                  // if var 2 is not 1, then copy the element 
                  //  to the output
                  "*": {
                    "@5": "elements.&6"
                  }
                }
              }
            },
            // match all other values of var1
            //  and copy the element to the output.
            "*": {
              "@2": "elements.&3"
            }
          }
        }
      }
    }
  }
]
```

**Comment by pvve** [comment]
Thanks a lot for your very quick response. This worked perfectly for me!
