### ISSUE TITLE
Is it possible to perform subtraction operation in Jolt? 

### ISSUE THREAD

**Issue by Aman3006** [bazaarvoice/jolt#558]
Input:
[
  {
    event:{
                 "mat":60,
                 "dat":25
              }
  }
]

Expected output:

[
    "difference" : 35
]

**Comment by milosimpson** [comment]
No.

**Comment by Aman3006** [comment]
- So if we add a intSub() function in 
jolt\jolt-core\src\main\java\com\bazaarvoice\jolt\modifier\function\math.java 


```
// Adding Subtraction function
	 public static Optional<Integer> intSub(List<Object> args) {
        Integer diff = 0;
        for(Object arg: args) {
            Optional<? extends Integer> numberOptional = Objects.toInteger(arg);
            if(numberOptional.isPresent()) {
                diff = -(diff + numberOptional.get());
            }
        }
        return Optional.of(diff);
    }

    
	
	// Adding Subtraction Warning Suppress Function
	   @SuppressWarnings( "unchecked" )
    public static final class intSub extends Function.ListFunction {
        @Override
        protected Optional<Object> applyList( final List<Object> argIntList ) {
            return (Optional) intSub(argIntList);
        }
    }

 
```


- For test I added one case at
jolt\jolt-core\src\test\java\com\bazaarvoice\jolt\modifier\function\mathTest.java


```
Function INT_SUB_OF = new Math.intSub();

//Test "Subtraction
testCases.add( new Object[] { "intsub-combo-string-array",    INT_SUB_OF,  Arrays.asList(1, 2.0, "random", 0), Optional.of(3)});
testCases.add( new Object[] { "intsub-single-value",          INT_SUB_OF,  2,                                  Optional.empty()});
testCases.add( new Object[] { "intsub-combo-intstring-array", INT_SUB_OF,  Arrays.asList(1L, 2, "-3.0", 0), Optional.of(0)});
```

Is this approach acceptable. I can raise a pull request.

**Comment by milosimpson** [comment]
Feature has just been merged in.

**Comment by saketsaurabh91** [comment]
@milosimpson  Is it incorporated in the jolt demo site? Is the function name intSub()?

**Comment by milosimpson** [comment]
Demo site - not yet.   "intSubtract" 

I've started to use it and it is works but it IMHO it is overly strict (in only works if both values are actually Integers).   I will be relaxing it in the next release.

FYI what as added in 0.1.1
https://github.com/bazaarvoice/jolt/releases/tag/jolt-0.1.1
