### ISSUE TITLE
is it possible to add elements to an array based on a condition.

### ISSUE THREAD

**Issue by shreyasns** [bazaarvoice/jolt#559]
I have the following input
<pre>
{
  "rating": {
    "primary": {
      "value": 3
    },
    "action": "update",
    "type": "object"
}
</pre>

is it possible to generate a output like this
<pre>
{
  "rating": {
    "primary": {
      "value": 3
    },
    "action": ["update", "object_update"] 
    "type": "object"
}
</pre>

**Comment by milosimpson** [comment]
Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "rating": {
        "primary": {
          "value": "rating.primary.value"
        },
        "action": "action[0]",
        "type": "type"
      }
    }
  },
  {
    "operation": "default",
    "spec": {
      "action[]": {
        "1": "object_update"
      }
    }
  }
]

```

**Comment by shreyasns** [comment]
Sorry. The payload was wrong. I've updated it now. I want check if type exists and add $type_$action to the action array.

**Comment by shreyasns** [comment]
Thanks. but is it possible to do the operation only if a parameter exists? The filter option only exists in the shiftr spec right? is it possible to combine concat and the filter?

**Comment by milosimpson** [comment]
Not really.   Jolt isn't trying to do everything.

Check for you parameter existence up front yourself, and then have two Jolt transforms one that works when the parameter exists, and one that works when it doesn't.

**Comment by shreyasns** [comment]
ok thanks :). I'm closing this then
