### ISSUE TITLE
Add a new item in JSON file using JOLT

### ISSUE THREAD

**Issue by arun74039** [bazaarvoice/jolt#560]
@Hi, milosimpson ... I am new to Jolt.  I am struggling to add a new item on top of existing one and merge one or more items in an array. For example,

I have many JSON files(incoming) with the same unique id and with different Address. All I have to do is merge the address into an array and create a single JSON with respect to a unique ID.

Can anyone suggest the spec to do so?

If the incoming JSON file is like, 

{
  "unique_cid": "41f55b3a-30e6-11e8-8f62-cb4291fae189",
  "customer_id": "1051",
  "customer_name": "XXXXX, AAAA                 ",
  "address_type": "PRI",
  "telephone_number": "999999999",
  "dob": "630402",
  "dob_new": "1963-04-02",
  "sex": null,
  "email_address": "xyz@abc.com                                ",
  "cass_addressline1": "3911 aaaaaa Dr N",
  "cass_addressline2": null,
  "cass_city": "Gibson",
  "cass_confidence": "97",
  "cass_couldnotvalidate": null,
  "cass_country": "United States Of America",
  "cass_dpv": "Y",
  "cass_dpvfootnote": "AABB",
  "cass_matchscore": "0",
  "cass_postalcode": "27896-8639",
  "cass_postalcode_addon": "8639",
  "cass_stateprovince": "NC",
  "cass_status": null,
  "cass_status_code": null,
  "cass_status_description": null,
  "cass_postalcode_base": "27896",
  "cass_uscarrierroutecode": "R009",
  "cass_uscountyname": "Gibsonibson",
  "insert_date": "2018-03-29",
  "insert_time": "2018-03-29 05:49:17.635",
  "is_cassed": "Y"
}

Filter the required items and required output JSON should be like,

{
  "unique_cid" : "41f55b3a-30e6-11e8-8f62-cb4291fae189",
  "customer_id" : "1051",
  "customer_name" : "XXXXX, AAAA                 ",
  "address" : [ {
    "address_type" : "PRI",
    "addressline1" : "3911 aaaaaa Dr N",
    "addressline2" : null,
    "city" : "Gibson",
    "state" : "NC",
    "zipcode" : "27896-8639"
          } 
{
     "address_type" : "PRI",
      "addressline1" : "3911 aaaaaa Dr N",
      "addressline2" : null,
      "city" : "Gibson",
      "state" : "NC",
      "zipcode" : "27896-8639"
  } 
{
     "address_type" : "PRI",
    "addressline1" : "3911 aaaaaa Dr N",
    "addressline2" : null,
    "city" : "Gibson",
    "state" : "NC",
    "zipcode" : "27896-8639"
}
  "dob" : "630402",
  "email_address" : "xyz@abc.com                                ",
  "sex" : null,
  "telephone_number" : [ {
    "primary_number" : "999999999",
    "sec_number" : "999999999"
  } ],
  "dob_new" : "1963-04-02",
  "insert_date" : "2018-03-29",
  "insert_time" : "2018-03-29 05:49:17.635",
  "is_cassed" : "Y"
}

I have somehow managed to get the file in with Jolt spec.

[
  {
    "operation": "shift",
    "spec": {
      "unique_cid": "unique_cid",
      "customer_id": "customer_id",
      "customer_name": "customer_name",
      "address_type": "address.[#2].address_type",
      "cass_addressline1": "address.[#2].addressline1",
      "cass_addressline2": "address.[#2].addressline2",
      "cass_city": "address.[#2].city",
      "cass_stateprovince": "address.[#2].state",
      "cass_postalcode": "address.[#2].zipcode",
      "dob": "dob",
      "email_address": "email_address",
      "sex": "sex",
      "telephone_number": "telephone_number.[#2].telephone_number",
      "dob_new": "dob_new",
      "insert_date": "insert_date",
      "insert_time": "insert_time",
      "is_cassed": "is_cassed"
    }
    }
]

The output JSON is like,

{
  "unique_cid" : "41f55b3a-30e6-11e8-8f62-cb4291fae189",
  "customer_id" : "1051",
  "customer_name" : "XXXXX, AAAA                 ",
  "address" : [ {
    "address_type" : "PRI",
    "addressline1" : "3911 aaaaaa Dr N",
    "addressline2" : null,
    "city" : "Gibson",
    "state" : "NC",
    "zipcode" : "27896-8639"
  } ],
  "dob" : "630402",
  "email_address" : "xyz@abc.com                                ",
  "sex" : null,
  "telephone_number" : [ {
    "telephone_number" : "999999999"
  } ],
  "dob_new" : "1963-04-02",
  "insert_date" : "2018-03-29",
  "insert_time" : "2018-03-29 05:49:17.635",
  "is_cassed" : "Y"
}

Can anyone suggest the spec to do so?

**Comment by milosimpson** [comment]
You output doesn't make sense to me.   You want 3 copies of the same address info into an array?

If you want to duplicate input via "shift", use an array on the right hand side.

Ala
```
      "address_type": ["address.[0].address_type", "address.[1].address_type", "address.[2].address_type"],
      "cass_addressline1": ["address.[0].addressline1", "address.[1].addressline1", "address.[2].addressline1"],
```

Means explicitly copy "address_type" to three "different" places in the output.
