### ISSUE TITLE
Transform Java Object to desired Json based on the spec

### ISSUE THREAD

**Issue by rachalla** [bazaarvoice/jolt#569]
Jolt transforms an input json to output json based on the spec.
Is it possible to take input an existing java object and transform to ouput json based on the spec. This will avoid an extra step of using jackson to generate the input json and then use jolt to transform.

**Comment by milosimpson** [comment]
"existing java object and transform to ouput json based on the spec" no.

Jolt specifically only knows how to process Map, List, String, and Numbers.   If you feed it your domain specific Java Objects, it will not know what to do.

If you want to use Jolt, you have to transform your data from custom Pojos, into base/generic Java classes (Map, List, String, and Numbers).
