### ISSUE TITLE
Null value filtering in spec

### ISSUE THREAD

**Issue by nagabsss** [bazaarvoice/jolt#573]
Below is the JSON that has been generated by running other Jolt spec. I need to create a spec which does validation on values of orderKey, orderLineKey and statusKey. If the value is not empty then this JSON needs to be copied as it is else it should emit null indicating validation has failed. 
```
{
  "documentType": "0001",
  "enterpriseCode": "DEFAULT",
  "entryType": "CallCenter",
  "orderCreatedDate": "2018-04-10T10:45:35",
  "orderKey": "Order-11",
  "status": "Created",
  "orderNo": "Order-11",
  "line": {
    "orderKey": "Order-11",
    "orderLineKey": "20180410155838114013",
    "deliveryMethod": "SHP",
    "orderedQuantity": "11.0",
    "requestedDeliveryDate": "2018-04-10T10:45:35",
    "requestedShipDate": "2018-04-10T10:45:35",
    "itemId": "Item12",
    "itemDescription": " ",
    "unitOfMeasure": "EACH",
    "productClass": " ",
    "status": "Created",
    "linestatus": {
      "orderLineKey": "20180410155838114013",
      "statusKey": "2018041015145839114023",
      "status": "1100",
      "statusDate": "2018-04-10T15:58:39",
      "statusQuantity": "11.0",
      "statusDescription": "1100",
      "movedQuantity": "0.0",
      "shipNode": "",
      "releaseNo": ""
    }
  }
}
```

**Comment by milosimpson** [comment]
"does validation on values of orderKey, orderLineKey and statusKey. If the value is not empty then this JSON needs to be copied as it is else it should emit null indicating validation has failed."

Jolt is specifically not trying to solve that problem.  I recommend looking into some kind of JSON Schema tool, that can enforce "validation".
