### ISSUE TITLE
char delimited strings to array 

### ISSUE THREAD

**Issue by sapientcloud** [bazaarvoice/jolt#574]
Input jsons.
{   "rating": "a;bb;KK;ddd;r"   }
{   "rating": "12;ddssd;aDG"   }
{   "rating": ""   }
{   "rating": null   }

Expected output jsons
{   "rating":  [ "a", "bb", "KK", "ddd", "r"]   }
{   "rating": [ "12", "ddssd", "aDG" ]  }
{   "rating": [ "" ]  }
{   "rating": [  ]  }

Last two rows (empty value and null) are optional in final answer. If it works with that too it is much better.

**Comment by milosimpson** [comment]
Will be in the next release of Jolt.   "=split" function for the modify operations.    https://github.com/bazaarvoice/jolt/pull/499
