### ISSUE TITLE
Question regarding nested mapping

### ISSUE THREAD

**Issue by anboss** [bazaarvoice/jolt#575]
Hi  @milosimpson ,

I am trying to map a flat structure to a hierarchical structure using Jolt http://jolt-demo.appspot.com/#andrewkcarter2:

My input is a flat structure containing customer details: Below is my JSON Input:

    [
      {
        "customerId": "100",
        "customerName": "Ken",
        "accountId": "1001",
        "accountType": "SAV",
        "transactionAmount": "100.00",
        "homeaddress": "800 W Trade St",
        "businessaddress": "440 S Church St"
      },
      {
        "customerId": "100",
        "customerName": "Ken",
        "accountId": "1001",
        "accountType": "SAV",
        "transactionAmount": "15.00",
        "homeaddress": "800 W Trade St",
        "businessaddress": "440 S Church St"
      },
      {
        "customerId": "100",
        "customerName": "Ken",
        "accountId": "1002",
        "accountType": "CHK",
        "transactionAmount": "200.00",
        "homeaddress": "900 E 4th St",
        "businessaddress": "500 N Church St"
      },
      {
        "customerId": "100",
        "customerName": "Ken",
        "accountId": "1002",
        "accountType": "CHK",
        "transactionAmount": "116.00",
        "homeaddress": "900 E th St",
        "businessaddress": "500 N Church St"
      }
    ]

Here is my JOLT Spec:

    [
      {
        "operation": "shift",
        "spec": {
        "*": {
        "customerId": {
          "*": {
            "@2": "temp.&1[]"
              }
            }
          }
        }
      },
      {
        "operation": "shift",
        "spec": {
        "temp": {
        "*": {
          "0": {
            "customerId": "[#3].customerId",
            "customerName": "[#3].customerName",
            "accountId": "[#3].accounts[0].accountId",
            "accountType": "[#3].accounts[0].accountType",
            "transactionAmount": " 
             [#3].accounts[0].transactions[0].transactionAmount",
            "homeaddress": "[#3].addresses[0].homeaddress",
            "businessaddress": "[#3].addresses[0].businessaddres"
          },
          "*": {
            "accountId": "[#3].accounts[&1].accountId",
            "accountType": "[#3].accounts[&1].accountType",
            "transactionAmount": "[#3].accounts[&1].transactions[&1].&",
            "homeaddress": "[#3].addresses[&1].homeaddress",
            "businessaddress": "[#3].addresses[&1].businessaddress"
           }
          }
        }
       }
     }
    ]

The result which i am getting is:

    [ {
      "customerId" : "100",
      "customerName" : "Ken",
      "accounts" : [ {
          "accountId" : "1001",
          "accountType" : "SAV",
          "transactions" : [ {
          "transactionAmount" : "100.00"
        } ]
      }, {
          "accountId" : "1001",
          "accountType" : "SAV",
          "transactions" : [ null, {
          "transactionAmount" : "15.00"
        } ]
      }, {
          "accountId" : "1002",
          "accountType" : "CHK",
          "transactions" : [ null, null, {
          "transactionAmount" : "200.00"
        } ]
       }, {
          "accountId" : "1002",
          "accountType" : "CHK",
          "transactions" : [ null, null, null, {
          "transactionAmount" : "116.00"
          } ]
      } ],
      "addresses" : [ {
         "homeaddress" : "800 W Trade St",
         "businessaddres" : "440 S Church St"
        }, {
         "homeaddress" : "800 W Trade St",
         "businessaddress" : "440 S Church St"
        }, {
         "homeaddress" : "900 E 4th St",
         "businessaddress" : "500 N Church St"
        }, {
         "homeaddress" : "900 E th St",
         "businessaddress" : "500 N Church St"
      } ]
    } ]

In the above output, we see that accounts 1001 and 1002 are repeating so many number of times as the transactions. I dont want that to happen and I want the transactions to be grouped under the respective accounts. 

So, my desired output should be: 

    [ {
      "customerId" : "100",
      "customerName" : "Ken",
      "accounts" : [ {
        "accountId" : "1001",
        "accountType" : "SAV",
            "transactions" : [ {
                  "transactionAmount" : "100.00"
               },
               {
                  "transactionAmount" : "15.00"
            } ]
          }, {
        "accountId" : "1002",
        "accountType" : "CHK",
        "transactions" : [ null, null, {
                   "transactionAmount" : "200.00"
                   },{
                  "transactionAmount" : "116.00"
            } ]
          },
         "addresses" : [ {
        "homeaddress" : "800 W Trade St",
        "businessaddres" : "440 S Church St"
      }, {
        "homeaddress" : "900 E th St",
        "businessaddress" : "500 N Church St"
      } ]
    } ]

Similarly unique addresses only should come in the result.

Is there a way to group the transactions under the respective accounts. Could help with this?

**Comment by milosimpson** [comment]
It is possible, but messy and probably brittle.   I honestly don't recommend it.

You have to doubly pivot the data in the first shift.

After that it is using "cardinality" to "squash" the duplicate customerIds and customerName (this assumes that customerId 100 always has the same name).

Then more cleanup of the accounts array, and build the transactions array.

The last step is to convert from nested map structure into the list of list structure you want.

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "*": { // outer array index
        "customerId": {
          "*": { // custId number
            "@2": { // reset back up the tree
              "accountId": {
                "*": { // match accountId
                  "@5": "custId.&4.accountId.&1.[]",
                  "@(5,customerId)": "custId.&4.customerId",
                  "@(5,customerName)": "custId.&4.customerName"
                }
              }
            }
          }
        }
      }
    }
  },
  {
    "operation": "cardinality",
    "spec": {
      "custId": {
        "*": {
          "customerId": "ONE",
          "customerName": "ONE"
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "custId": {
        "*": { // custId
          "customerId|customerName": "custId.&1.&",
          "accountId": {
            "*": { // accountId
              "*": { // accountId array
                "accountId": "custId.&4.accountId.&2.accountId",
                "accountType": "custId.&4.accountId.&2.accountType",
                "homeaddress": "custId.&4.accountId.&2.homeaddress",
                "businessaddress": "custId.&4.accountId.&2.businessaddress",
                "transactionAmount": "custId.&4.accountId.&2.transactions[&1].transactionAmount"
              }
            }
          }
        }
      }
    }
  },
  {
    "operation": "cardinality",
    "spec": {
      "custId": {
        "*": {
          "accountId": {
            "*": {
              "accountId": "ONE",
              "accountType": "ONE",
              "homeaddress": "ONE",
              "businessaddress": "ONE"
            }
          }
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "custId": {
        "*": { // custId
          "customerId|customerName": "[#2].&",
          "accountId": {
            "*": { // accountId
              "accountId": "[#4].accounts[#2].accountId",
              "accountType": "[#4].accounts[#2].accountType",
              "homeaddress": "[#4].addresses[#2].homeaddress",
              "businessaddress": "[#4].addresses[#2].businessaddress",
              "transactions": "[#4].accounts[#2].transactions"
            }
          }
        }
      }
    }
  }
]
```

**Comment by anboss** [comment]
Thanks @milosimpson ... Appreciate your help.

**Comment by hykavitha** [comment]
Hi Miliosimpson, 

I have a question on the similar lines: I'm very new to jolt, This is my input


{
"id": "LIKKI MOSORU",
"aff_id": "WOOD",
"aff_name": "WOOD-LOVE",
"aff_desc": "WOOD INC.",
"aff_corrltn_name": "MARVEL MEMBERSHIP",		 
"aff_corrltn_id": "8999938",
"affil_trans_id": "222222",
"misc_aff_dtl_name": "MBR-FIRST-NAME",
"misc_aff_dtl_value" :"KKKKKLYYYY",
"oper_id": "AP",
"create_timestamp":"2018-10-16-04:00",
"update_timestamp": "2018-10-17-04:00",
"active_rcrd": "Y"
}

This is my expected output : 

{
    "rewards_id": "Jeannine Rosario",
		"aff": [
			{		 
				"aff_id": "WOOD",
				"aff_name": "WOOD-LOVE",
				"aff_desc": "WOOD INC.",
				"aff_corrltn": [
					{		 
						"aff_corrltn_name": "MARVEL MEMBERSHIP",		 
						"aff_corrltn_id": "8999938",
						"affil_trans_id": "222222",
						"misc_aff_dtl": [		 
							{  
								"name":"MBR-FIRST-NAME",
								"value":"DANJALKSA"
							}
				        ]	
					}			
			],
		 "oper_id": "AP",
		 "create_timestamp":"2018-10-16-04:00",
		 "update_timestamp": "2018-10-17-04:00",
		 "active_rcrd": "Y"
		 }
		 ]
}


I have worked and got the intermideate json : 
{
  "rewards_id" : "Jeannine Rosario",
  "affiliate" : [ {
    "rewards_id" : "Jeannine Rosario",
    "oper_id" : "AP",
    "create_timestamp" : "2018-10-16-04:00",
    "update_timestamp" : "2018-10-17-04:00",
    "active_rcrd" : "Y",
    "affiliate" : {
      "affiliate_id" : "STARWOOD",
      "affiliate_name" : "STARWOOD",
      "affiliate_desc" : "STARWOOD INC."
    },
    "affiliate_corrltn" : {
      "affiliate_corrltn_name" : "SPG-MEMBERSHIP",
      "affiliate_corrltn_id" : "828238"
    },
    "misc_affilate_dtl" : {
      "name" : "MBR-FIRST-NAME",
      "value" : "DANJALKSA"
    }
  } ]
}

using this jolt spec:
[
  {
    "operation": "shift",
    "spec": {
      "misc_affiliate_dtl_*": "misc_affiliate_dtl.&(0,1)",
      "affiliate_corrltn_*": "affiliate_corrltn.&(0,0)",
      "affiliate_*": "affiliate.&(0,0)",
      "rewards_id": "rewards_id",
      "oper_id": "oper_id",
      "create_timestamp": "create_timestamp",
      "update_timestamp": "update_timestamp",
      "active_rcrd": "active_rcrd"
    }
}

]

Any help is appreciated
