### ISSUE TITLE
Transpose key,value into array

### ISSUE THREAD

**Issue by zoolook001** [bazaarvoice/jolt#579]
Hello,

With JOLT, is there a way to do the following
Input
> [
>   {
>     "key1": "value1",
>     "key2": "value2"
>   },
>   {
>     "key1": "value3",
>     "key2": "value4"
>   }  
> ]

Expected outcome

> [
> 	{
> 		"key": "key1",
> 		"value": "value1"
> 	},
> 	{
> 		"key": "key2",
> 		"value": "value2"
> 	},
> 	{
> 		"key": "key1",
> 		"value": "value3"
> 	},
> 	{
> 		"key": "key2",
> 		"value": "value4"
> 	}
> ]

Thanks for your help

**Comment by milosimpson** [comment]
Spec
```
[
  {
    // unwrap the keys and values into literal
    // "key" : "A", "value" : "b",
    //  but maintain the initial outer list 
    //  structure.
    "operation": "shift",
    "spec": {
      "*": { // outer array index
        "key*": {
          "$": "[&2].&1.key",
          "@": "[&2].&1.value"
        }
      }
    }
  },
  {
		// Now that the data has been pivoted
    //  accumulate each "completed" item
    //  into the ouput being a top level array
    "operation": "shift",
    "spec": {
      "*": { // outer array index
        "key*": "[]"
      }
    }
  }
]
```

**Comment by zoolook001** [comment]
Hi milosimpson,

Thanks! I've got the 2 steps required for the full transformation

Regards
