### ISSUE TITLE
Filter empty map 

### ISSUE THREAD

**Issue by yarabsyp** [bazaarvoice/jolt#583]
Hello @milosimpson , Hope you doing well.

Could you please find input
```
{
"id": "id",
"studentList": [
{},
{},
{},
{},
{}
],
"EmpList": [
{
"Empid": "123",
"name": "milo"
},
{},
null,
{},
{}
]
}
```
I want to remove null/empty item from the list in the json(atlease empty map need to remove null value can restrict by adding a list) .
see the studentList all value is empty so we need to remove entire studentlist , but sometimes student list will come with value so by the time we should not remove(but check if the value is empty or null we should remove)
the trick is literally checking if all value is empty we should remove otherwise we have to remove only empty and keep other value
Could you plz advise i have tried multiple way i couldnt figure out .. plz help us to resolve this requirement

expected output

{
"id": "id",
"EmpList": [
{
"Empid": "123",
"name": "milo"
}
]
}

**Comment by milosimpson** [comment]
The trick is to match down to something "real", and only if you get there, copy the block across.

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "id": "id",
      "EmpList": {
        "*": {
          "Empid": {
            // we were able to match an 
            //  Empid in in the EmpList
            // then copy the whole item across to
            //  the output, and bulid a new "EmpList"
            "@1": "EmpList[]"
          }
        }
      },
      "studentList": {
        "*": {
          // TODO : change "Empid" this to something
          //  that should exist in the 
          "Empid": {
            "@1": "studentList[]"
          }
        }
      }
    }
  }
]
```
