### ISSUE TITLE
Flatten Complex JSON Object to Simple Array of Objects

### ISSUE THREAD

**Issue by mcwarman** [bazaarvoice/jolt#584]
I have a "Complex" JSON Object which i'm trying to flatten, repeating the objects by `n` number of `MoreDataIDs` objects:

I have the following input:
```json
[
  {
    "ID": 1,
    "Name": "Fred",
    "SomeDataID": {
      "ID": 180,
      "Value": 123
    },
    "MoreDataIDs": [
      {
        "ID": 220,
        "Value": 445
      },
      {
        "ID": 240,
        "Value": 78
      }
    ],
    "AnotherValue": true
  },
  {
    "ID": 2,
    "Name": "John",
    "SomeDataID": {
      "ID": 180,
      "Value": 41
    },
    "MoreDataIDs": [
      {
        "ID": 220,
        "Value": 123
      },
      {
        "ID": 240,
        "Value": 23
      }
    ],
    "AnotherValue": true
  },
  {
    "ID": 3,
    "Name": "Dave",
    "SomeDataID": {
      "ID": 180,
      "Value": 16
    },
    "MoreDataIDs": [
      {
        "ID": 250,
        "Value": 123
      }
    ],
    "AnotherValue": true
  }
]
```

Desired Output
```json
[
  {
    "ID": 1,
    "Name": "Fred",
    "SomeDataID_ID": 180,
    "SomeDataID_Value": 123,
    "MoreDataID_ID": 220,
    "MoreDataID_Value": 445,
    "AnotherValue": true
  },
  {
    "ID": 1,
    "Name": "Fred",
    "SomeDataID_ID": 180,
    "SomeDataID_Value": 123,
    "MoreDataID_ID": 240,
    "MoreDataID_Value": 78,
    "AnotherValue": true
  },
  {
    "ID": 2,
    "Name": "John",
    "SomeDataID_ID": 180,
    "SomeDataID_Value": 41,
    "MoreDataID_ID": 220,
    "MoreDataID_Value": 123,
    "AnotherValue": true
  },
  {
    "ID": 2,
    "Name": "John",
    "SomeDataID_ID": 180,
    "SomeDataID_Value": 41,
    "MoreDataID_ID": 240,
    "MoreDataID_Value": 23,
    "AnotherValue": true
  },
  {
    "ID": 3,
    "Name": "Dave",
    "SomeDataID_ID": 180,
    "SomeDataID_Value": 16,
    "MoreDataID_ID": 250,
    "MoreDataID_Value": 123,
    "AnotherValue": true
  }
]
```

jolt so far:
```json
[
  {
    "operation": "shift",
    "spec": {
      "*": {
        "MoreDataIDs": {
          "*": {
            "@(2,ID)": "[&3].[&1].ID",
            "@(2,Name)": "[&3].[&1].Name",
            "@(2,AnotherValue)": "[&3].[&1].AnotherValue",
            "@(2,SomeDataID.ID)": "[&3].[&1].SomeDataID_ID",
            "@(2,SomeDataID.Value)": "[&3].[&1].SomeDataID_Value",
            "ID": "[&3].[&1].MoreDataID_ID",
            "Value": "[&3].[&1].MoreDataID_Value"
          }
        }
      }
    }
  }
]
```

Current "incorrect" output:
```json
[ 
  [ 
    {
      "ID" : 1,
      "Name" : "Fred",
      "AnotherValue" : true,
      "SomeDataID_ID" : 180,
      "SomeDataID_Value" : 123,
      "MoreDataID_ID" : 220,
      "MoreDataID_Value" : 445
    }, 
    {
      "ID" : 1,
      "Name" : "Fred",
      "AnotherValue" : true,
      "SomeDataID_ID" : 180,
      "SomeDataID_Value" : 123,
      "MoreDataID_ID" : 240,
      "MoreDataID_Value" : 78
    } 
  ], 
  [ 
    {
      "ID" : 2,
      "Name" : "John",
      "AnotherValue" : true,
      "SomeDataID_ID" : 180,
      "SomeDataID_Value" : 41,
      "MoreDataID_ID" : 220,
      "MoreDataID_Value" : 123
    },
    {
      "ID" : 2,
      "Name" : "John",
      "AnotherValue" : true,
      "SomeDataID_ID" : 180,
      "SomeDataID_Value" : 41,
      "MoreDataID_ID" : 240,
      "MoreDataID_Value" : 23
    } 
  ], 
  [ 
    {
      "ID" : 3,
      "Name" : "Dave",
      "AnotherValue" : true,
      "SomeDataID_ID" : 180,
      "SomeDataID_Value" : 16,
      "MoreDataID_ID" : 250,
      "MoreDataID_Value" : 123
    } 
  ]
]
```

**Comment by milosimpson** [comment]
You can't do it in one shift.   The problem is that your top level input json array has 3 items in it, and you desired output has more than that.

Hence there is no array index  for "shift" to use.

Thus, you need to do two shifts.
1) Maintain the same nested list structure of you input, and copy information "down" into MoreDataIDs array, and make each item of MoreDataIDs array be the "finished" product.
2) Then, use shift to "accumulate" all the now finished elements of the "MoreDataIDs" arrays into your final output.

**Comment by milosimpson** [comment]
You effectively did step 1.

Add this as step 2
Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "*": {
        "*": "[]"
      }
    }
  }
]
```

**Comment by mcwarman** [comment]
Thanks, thats working as expected.

**Comment by msoni9** [comment]
Hello,

I have to perform jolt transformation to street object in HomeAddress. 
I have to rename street into streetdetails. Here problem is we have street object in OfficeAdress as well but we don't want to change in it.

**INPUT JSON**
[
  {
    "id": 123,
    "name": "Pankaj Kumar",
    "permanent": true,
    "homeAddress": {
      "street": "El Camino Real",
      "city": "San Jose",
      "zipcode": 95014
    },
    "officeAddress": {
      "street": "El Camino Real",
      "city": "San Jose",
      "zipcode": 95014
    },
    "phoneNumbers": [
      9988664422,
      1234567890
    ],
    "role": "Developer"
  },
  {
    "id": 123,
    "name": "Pankaj Kumar",
    "permanent": true,
    "homeAddress": {
      "street": "El Camino Real",
      "city": "San Jose",
      "zipcode": 95014
    },
    "officeAddress": {
      "street": "El Camino Real",
      "city": "San Jose",
      "zipcode": 95014
    },
    "phoneNumbers": [
      9988664422,
      1234567890
    ],
    "role": "Developer"
  }
]

**SPEC JSON :** 

[
  {
    "operation": "remove",
    "spec": {
      "*": {
        "homeAddress": {
          "street": ""
        }
      }
    }
   },
  {
    "operation": "default",
    "spec": {
      "*": {
        "homeAddress": {
          "streetdetails": {}
        }
      }
    }
   },
  {
    "operation": "shift",
    "spec": {
      "*": {
        "id": "[&1].id",
        "name": "[&1].firstname",
        "permanent": "[&1].permanent",
        "homeAddress": "[&1].homeAddress",
        "officeAddress": "[&1].officeAddress",
        "phoneNumbers": "[&1].phoneNumbers",
        "role": "[&1].role"
      }
    }
   }
]

**OUTPUT JSON :**
[ {
  "id" : 123,
  "firstname" : "Pankaj Kumar",
  "permanent" : true,
  "homeAddress" : {
    "city" : "San Jose",
    "zipcode" : 95014,
    "streetdetails" : { }
  },
  "officeAddress" : {
    "street" : "El Camino Real",
    "city" : "San Jose",
    "zipcode" : 95014
  },
  "phoneNumbers" : [ 9988664422, 1234567890 ],
  "role" : "Developer"
}, {
  "id" : 123,
  "firstname" : "Pankaj Kumar",
  "permanent" : true,
  "homeAddress" : {
    "city" : "San Jose",
    "zipcode" : 95014,
    "streetdetails" : { }
  },
  "officeAddress" : {
    "street" : "El Camino Real",
    "city" : "San Jose",
    "zipcode" : 95014
  },
  "phoneNumbers" : [ 9988664422, 1234567890 ],
  "role" : "Developer"
} ]

Your further help will be appreicated.
Thank in advance.
