### ISSUE TITLE
Jolt Spec Builder UI

### ISSUE THREAD

**Issue by compugeek25** [bazaarvoice/jolt#588]
Hi @milosimpson ,

I'm looking for building out an UI for end user who would get to see a JSON model on left and JSON model on right. I want to facilitate the UI for the user where he can select/drag-drop from left side model to right side model. Behind the scene I want to generate the JOLT Specification based on user input of (visual layman transformation logic) . Any tools or libraries that you may suggest that can be leveraged for this kind of situation? Or please advice what would be a best solution approach to this kind of problem using JOLT. Appreciate your response for my last query...

Thanks a lot!.

**Comment by milosimpson** [comment]
I don't know.

The drag and drop feature I think would work for basic / easy transforms.

I don't know how you would be able to incorporate the wildcards of "shift", which is what makes it powerful.

**Comment by compugeek25** [comment]
Hi @milosimpson ,

Thanks for the clarification. 
Please guide me if i'm looking to transform any (left) to any(right) json using jolt, is there a pattern that i can derive which will be able to generate the jolt spec based on the metadata of both side models.?

Am I heading in the wrong direction with Jolt?

Thanks
Rajat.

**Comment by AbbassFaytaroony** [comment]
Hello, 
This feature is very important. Providing the ability to use jolt from a UI as described by @compugeek25 will be huge. @compugeek25 did you find any solution for your use case?

**Comment by krunalpala** [comment]
Any updates on this one, do we have any UI for this spec builder?
