### ISSUE TITLE
How to change position of json attribute while converting hierarchial json to flat json

### ISSUE THREAD

**Issue by ShridharMHegde** [bazaarvoice/jolt#592]
I need to change a json like this 
```
{
  "key1": "value1",
  "key2": "value2",
  "line": {
    "key3": "value3",
    "key4": "value4"
  }
}
```
To
```
{
"key1":"value1",
"key3":"value3",
"key2":"value2",
"key4":"value4"
}
```

If i create a spec like 
```
 "operation": "shift",
        "spec": {
          "key1":"key1",
          "line":{
                "key3":"key3"
           },
          "key2":"key2",
            "line":{
                "key4":"key"
           },
```                  
It is not working as the only last entry of "line":{} is considered and key3 is omitted out . How to achieve the order that i am looking for . Should i use two shift operations one to flatten out the message first and then one more to change the order ? If so will not impact the performance

**Comment by milosimpson** [comment]
"How to achieve the order that i am looking for."    

With Json data Map data, you shouldn't be concerned with the order.

Generally Jolt tries to maintain input order to the output order, as a way of being "nice" to the humans that use it.    But, it has no specific means of doing a "custom order" on a map.

There is the Jolt "sort" operation, but again that is supposed to just be for human readability of Json data.

**Comment by ShridharMHegde** [comment]
Hi,

We will be converting these json messages to files where the order of
column matter that's the reason order is important to us.so from what I
understand using single shift operation I will not be able to achieve what
I am trying to do.


On 4 May 2018 4:04 pm, "Milo Simpson" <notifications@github.com> wrote:

"How to achieve the order that i am looking for."

With Json data Map data, you shouldn't be concerned with the order.

Generally Jolt tries to maintain input order to the output order, as a way
of being "nice" to the humans that use it. But, it has no specific means of
doing a "custom order" on a map.

There is the Jolt "sort" operation, but again that is supposed to just be
for human readability of Json data.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bazaarvoice/jolt/issues/592#issuecomment-386562948>,
or mute
the thread

**Comment by milosimpson** [comment]
Herm.   Well maybe something like this

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "key1": "[0]",
      "key2": "[2]",
      "line": {
        "key3": "[1]",
        "key4": "[3]"
      }
    }
  }
]
```

Produces, an array with the values in the order you want.   
It is just a very hard-coded spec
```
[ "value1", "value3", "value2", "value4" ]
```
