### ISSUE TITLE
Function to flatten structures

### ISSUE THREAD

**Issue by TuomasKiviaho** [bazaarvoice/jolt#596]
I've got a key/value lookup scenario that is not a simple as the below example but it'll give you the idea.

Flattening can of course be done with the help of shiftf as in the the user case below but I'd like to be able to do it also in modifier operation to reduce clutter in one go .

<details>
  <summary>Use Case</summary>

 ``` json
{
	"input": {
		"entries": [
			{
				"entry": "foo",
				"properties": [
					"key1",
					"key2"
				]
			},
			{
				"entry": "foo",
				"properties": [
					"key2"
				]
			}
		],
		"properties": {
			"key1": {
				"property1": "value1"
			},
			"key2": {
				"property1": "value1",
				"property2": "value2"
			}
		}
	},
	"spec": [
		{
			"comment": "Turn array to objects)",
			"operation": "shift",
			"spec": {
				"entries": {
					"*": {
						"properties": {
							"*": "entries[&2].properties.@0"
						},
						"*": "entries[&1].&"
					}
				},
				"*": "&"
			}
		},
		{
			"comment": "Lookup values",
			"operation": "modify-overwrite-beta",
			"spec": {
				"entries": {
					"*": {
						"properties": {
							"*": "@(4,properties.&)"
						}
					}
				},
				"properties": null
			}
		},
		{
			"comment": "Flatten properties",
			"operation": "shift",
			"spec": {
				"entries": {
					"*": {
						"properties": {
							"*": {
								"*": "entries.[&3].properties.&"
							}
						},
						"*": "entries.[&1].&"
					}
				}
			}
		}
	],
	"expected": {
		"entries": [
			{
				"entry": "foo",
				"properties": {
					"property1": [
						"value1",
						"value1"
					],
					"property2": "value2"
				}
			},
			{
				"entry": "foo",
				"properties": {
					"property1": "value1",
					"property2": "value2"
				}
			}
		]
	}
}
```

</details>

My with is to  get rid of the lookup keys in modifier operation with help of a unction the would flatten the object tree up to certain levels. Negative levels could indicate that counting should be started from leafs. If modifier is not capable of performing structural changes then the functionality could be applied only to the first encounter on each level. In my case the unwrap flattening clause would be something like `=flatten(1,@(4,properties.&))`. Indexing can start from 0 by all means.

PS. The array to objects an possible vice versa would also be nice if it could be done with a modifier function. I might be able to squeeze the whole flattening process into one operation.

**Comment by milosimpson** [comment]
Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "entries": {
        "*": { // entries array
          "entry": "entries[&1].entry",
          "properties": {
            "*": { // props array 0,1
              "*": { // props array value key1, key2
                //
                // reset over to properties.key1 / properties.key2
                "@(5,properties.&)": { 
                  // "property1": "value1"
                  "*": "entries[&5].properties.&"
                }
              }
            }
          }
        }
      }
    }
  }
]
```

**Comment by TuomasKiviaho** [comment]
Thanks for the quick response (and sorry for this to turn out to be yet another question)

```
"@(5,properties.&)": { 
                  // "property1": "value1"
                  "*": "entries[&5].properties.&"
```

There seems to be still some hidden aspects left for me to discover after all :-) I somehow thought that this is not allowed but I may have tried to use nested at/dollar signs and this is definitely so trivial that I should have tested it.

FYI: Jolt mentions not to support streaming thus the latency can become quite high when chaining multiple operations. Jackson can finally produce JsonNodes in non blocking way and JsonSurfer already utilizes this.  I was wondering about opening an issue about this, but this would have so big of an impact on the current chainr approach that I wonder if it's worth it.
