### ISSUE TITLE
Repeatable mapping convention

### ISSUE THREAD

**Issue by ewgenijkkg** [bazaarvoice/jolt#598]
Is it possible to create repeatable mapping conventions - kind of subclasses? I am thinking of the following JSON
```javascript
{
    "person": {
        "name": "John Smith",
        "address": {
            "city": "New York",
            "street": "abcde",
            "house": 2
        }
    },
    "company": {
        "title": "Fantasy company",
        "address": {
            "city": "New York",
            "street": "Xyz",
            "house": 5
        }
    }
}
```
I do not want to write how to map the child "address" tag 2 times for this parent structure if it is mapped on the same counterpart address structure in both cases. Is it possible just to "say" JOLT the way of mapping an address, so it can map it this way each time it encounters the address tag somewhere in my JSON? Would be similar to the way Dozer or Mapstruct map classes in Java where you define how to map different classes and do not care about how they are nested in a particular case.

**Comment by milosimpson** [comment]
No, there is not a way to define "transform" an address this way once, and then reference it in two / multiple places.
