### ISSUE TITLE
Bug in wildcard matching hierarchy

### ISSUE THREAD

**Issue by ewgenijkkg** [bazaarvoice/jolt#600]
I think I found a bug in dealing with the matching hierarchy. I have the following input:

```javascript
{
  "document": {
    "section1": {
      "section2": {
        "element": {
          "part1": {
            "value1": {
              "v": "02"
            },
            "subsection1": {
              "subsection2": {
                "value2": {
                  "a": "avalue",
                  "b": "bvalue"
                }
              }
            }
          },
          "part2": {
            "value3": {
              "value": "01"
            }
          }
        }
      }
    }
  }
}
```

And the following spec:

```javascript
[{
    "operation": "shift",
    "spec": {
      "document": {
        "section1": {
          "section2": {
            "*": {
              "part1": {
                "value1": "elements[#1].value1",
                "subsection1": {
                  "subsection2": {
                    "value2": "elements[#4].value2"
                  }
                }
              },
              "part2": {
                "value3": "elements[#1].value3"
              }
            }
          }
        }
      }
    }
}
]
```

Then I get the following result:

```javascript
{
  "elements" : [ {
    "value1" : {
      "v" : "02"
    },
    "value2" : {
      "a" : "avalue",
      "b" : "bvalue"
    },
    "value3" : {
      "value" : "01"
    }
  } ]
}
```

But there are two things:

1. Actually, the index of value1 should be `[#2]` and not `[#1]`, because we start with the current level and index 0.
2. If I change index of value1 to `[#2]`, it will yield the same result output. How can that be?
3. If I change the index of value3 (which is on the same level related to * as value1) to `[#2]`, I will get a different output:
```javascript
{
  "elements" : [ {
    "value1" : {
      "v" : "02"
    },
    "value2" : {
      "a" : "avalue",
      "b" : "bvalue"
    }
  }, {
    "value3" : {
      "value" : "01"
    }
  } ]
}
```
where value3 is nested outside the first element of the elements array.

So, something is wrong here, isn't it?

P.S. I used [http://jolt-demo.appspot.com](url) for all my tests

**Comment by milosimpson** [comment]
Yes, the implementation of "[#1]", "[#2]" is weird / not what you expect / wrong.

It was written to convert a simple map, into a simple array.   Also this usecase : http://jolt-demo.appspot.com/#mapToList 

In your spec example
```
[{
    "operation": "shift",
    "spec": {
      "document": {
        "section1": {
          "section2": {
            "*": {
```
"section2" being the parent of a "*" is the only thing that elements below should reference with the "#X" logic.

Internally, shift is maintaining a stack data structure as it is traversing the input Json data tree.
Every time, it recurses down it increments a counter on the stack.

Hence, every time the "*" child of "section2" matches, a counter associated with "section2" get incremented. 

If you ask the "*" how many times it's children have matched, it changes, with every new matched value of the star.
