### ISSUE TITLE
Windows path name separators not accepted

### ISSUE THREAD

**Issue by ewgenijkkg** [bazaarvoice/jolt#603]
`JsonUtils.classpathToList(pathString) `does not accept windows style name separators. So, if I develop on Windows and provide `"\testdata\json\myjson.json"`, I get an Exception that the file is not found. I digged into the code and found out that you use `java.lang.Class#getResourceAsStream`, which uses `java.lang.Class#resolveName`, which looks for `"/"` only. But suppose I get the path out of the `java.nio.file.Path` object using `pathObject.toString()`. Then I get the path with `"\"` separators on Windows.

So, is it a bug?

**Comment by criztovyl** [comment]
Either use `/` instead of `\` or use `\\`.

It's because `\` in a string starts an escape sequence, like `\n` for a newline.

Note that, IIRC, you access resources always using "/", unlike files, where you can use both.

**Comment by ewgenijkkg** [comment]
Hi, it's clear to me that there are workarounds :-) What I'm doing now is replacement of all occurrences of '\' with '/' using String.replace. As I already wrote, I use the Java standard Path interface as method parameters, so I can't influence how it transforms a path to a string on a particular environment. But as I said, that's not the real problem, I can adjust the result path string to jolt requirements after that. I'm just wondering why Jolt does not accept the Windows standard for file path transcription.

**Comment by ewgenijkkg** [comment]
Ah, indeed... I researched and you are right, I did not get the concept of "java resource" correctly :-) Thank you for clarification!
