### ISSUE TITLE
Split is not working

### ISSUE THREAD

**Issue by selvanponraj** [bazaarvoice/jolt#609]
Here is the input, output and spec.
Input:

{
  "SPLIT": "new.old",
  "BIG": "BIG"
}

Expected output is

{
  "OUTPUT": "new",
  "BIG": "BIG"
}

Spec:
"OUTPUT": "=firstElement(1,split('.',@(1,SPLIT))",

Any help on this would be great

**Comment by milosimpson** [comment]
The 'split' in Jolt is just a straight pass thru to Java's String.split method, which takes a regex.

https://docs.oracle.com/javase/9/docs/api/java/lang/String.html#split-java.lang.String-

In regex "." means "anything", so try escaping the ".".

"OUTPUT": "=firstElement(1,split('\\.',@(1,SPLIT))",

**Comment by selvanponraj** [comment]
Many Thanks
