### ISSUE TITLE
Creating a one-element array with both default values and values from the source document

### ISSUE THREAD

**Issue by jakekugel** [bazaarvoice/jolt#613]
I'm having a bit of trouble creating a transform that will create a one-element array in the output JSON with both default values (the "num" property in output) and values from the input JSON (the "body" property in output).

Input:
```
{
  "body": "lorem ipsum.",
  "docnum": "12345",
  "field1": "value1",
  "field2": "value2"
}
```

Desired output:
```
{
  "page" : [ {
    "body" : "lorem ipsum.",
    "num" : "1000"
  } ],
  "header" : {
    "docnum" : "12345"
  },
  "field1" : "value1",
  "field2" : "value2"
}
```

My spec:
```
[
  {
    "operation": "default",
    "spec": {
      "page": [{ "num": "1000" }]
    }
  },
  {
    "operation": "shift",
    "spec": {
      "body": "page[0].body",
      "docnum": "header.&(0,0)",
      "*": {
        "@": "&"
      }
    }
  }
]
```

Any idea what might be causing the difference between the output I am aiming for and what my spec actually produces?

Thanks,
Jake

**Comment by milosimpson** [comment]
Generally it is best to shift first, and then add / apply defaults.   Also, for the "default" operation, you need to tell it that page is an array.

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "body": "page[0].body",
      "docnum": "header.&",
      "*": "&"
    }
  },
  {
    "operation": "default",
    "spec": {
      "page[]": {
        "0": {
          "num": "1000"
        }
      }
    }
  }
]
```

**Comment by jakekugel** [comment]
Thanks very much, thanks for the improvements to the shift operation too.
