### ISSUE TITLE
How to validate the structure of the input json using jolt

### ISSUE THREAD

**Issue by sowmyaumesh** [bazaarvoice/jolt#614]
If the spec has x,y,z attributes, they should be mandatory attributes in the input otherwise raise exception for missing mandatory attributes

**Comment by milosimpson** [comment]
That is not what Jolt is meant for.   For "verifying" Json data, there are other tools like Json Schema that you should use.

**Comment by sowmyaumesh** [comment]
okay, wanted to check if we can achieve it using jolt.
Thanks
