### ISSUE TITLE
Output bare types?

### ISSUE THREAD

**Issue by vectro** [bazaarvoice/jolt#621]
Hi folks,

Is it possible for Jolt to output bare types (such as a string or int) rather than a collection (such as an object or array)? I see an example in the tests that generates a null, but all the other examples output an object or an array.

Here's an example of what I'm thinking:
```
{
  "input": {
    "q": 1.2
  },

  "expected": 1.2
}
```

I can see how to do this in jsonpath but I'd prefer to use Jolt.

**Comment by 6d77** [comment]
That's simple. Just use an empty string on the RHS of your spec, i.e.:

```json
{
  "input": {
    "q": ""
  },
}
```

This will translate your input document into a bare number value. You can test that at 

http://www.jolt-demo.appspot.com/#inception

**Comment by vectro** [comment]
Neato, thanks.
