### ISSUE TITLE
Can we make the spec template changes dynamic in nature?

### ISSUE THREAD

**Issue by sharmmoh1983** [bazaarvoice/jolt#627]
Lets say I make a change in spec and I want my code to dynamically pick up the mapping change without re building the code and starting the application 

Is this possible?

**Comment by milosimpson** [comment]
Well, the pattern we use is we have a of "Document type" (review, comment, question, answer, etc) to an instance of a Chainr, that was built from a Spec file.

Chainr doesn't have any "reloading" capability, so if we wanted to change the "transform" on the fly, we would load a new Chainr from a spec, and then swap it in on the lookup map.

Short Version : No Jolt doesn't have any magic reloading capability, but you should be able to build that on top of Jolt.

**Comment by milosimpson** [comment]
Do you have any working sample for the same?  --> No.

Some quick googling:   http://codepumpkin.com/hashtable-vs-synchronizedmap-vs-concurrenthashmap/

I would go with the Collections.SynchronizedMap approach.

**Comment by sharmmoh1983** [comment]
No . I am not asking for the current issue . This is related to transforms t but for specific business logic, you will need to implement your own "Transform"

I am not able use the Custom Transformer for getting and putting the value

`class JoltTimeTransform implements Transform {

    @Override
    public Object transform( Object input ) {
        // Grab the time out of the incoming Json data / Map
        String secondsString = ((Map) input).get("newCustomTime"); 

        // Todo
        String fixedTime = null; // Your custom date manipulation logic.

        // Overwrite the old value with the new / fixed one.
        ((Map) input).put("newCustomTime", fixedTime); 
    }
}`

**Comment by milosimpson** [comment]
See 
* https://github.com/bazaarvoice/jolt/blob/master/jolt-core/src/test/java/com/bazaarvoice/jolt/chainr/transforms/GoodContextDrivenTransform.java  and where it is used
* https://github.com/bazaarvoice/jolt/blob/master/jolt-core/src/test/resources/json/chainr/context/spec_with_context.json#L18

Example of a Custom transform and how to call it from the spec file.

Also, for "getting around" inside the data, look at the "navigate" functions. 
* https://github.com/bazaarvoice/jolt/blob/master/jolt-core/src/test/java/com/bazaarvoice/jolt/utils/JoltUtilsNavigateTest.java

**Comment by sharmmoh1983** [comment]
I used the classes mentioned above but I am getting  context as null object 

Also when I am implementing Transform  , there is no transformation happening even though value is getting updated in java transformer code:

Input:

```
{
"instantseconds": 1429720551,
"clientInfo": {
    "ip": "111.111.111.111",
    "userAgent": {
        "type": "COMPUTER"
            }
     }
}
```


`[
    {
    "operation": "shift",
    "spec": {
        "instantseconds": "newCustomTime",
        "id": "newid",
        "_clientInfo": {
            "ip": "client_ip"
        }
    }
    },
    {
       "operation" : "au.com.boral.api.order.ValueTransform"
    }
]`

Output:
1429720551

**Comment by sharmmoh1983** [comment]
@milosimpson 
It seems the Transformer functionality is not working as per the requirement?

**Comment by milosimpson** [comment]
Just implement 
```
public Object transform( Object input );
```
and ignore the Context.  That is an extra thing that can be done.   It is just that, that it he only public example that exists.

**Comment by sharmmoh1983** [comment]
@milosimpson 

As per the above comments I have implemented the function but I am getting just the originalvalue 

`Input:

{
"instantseconds": 1429720551,
"clientInfo": {
    "ip": "111.111.111.111",
    "userAgent": {
        "type": "COMPUTER"
            }
     }
}

`public class ValueTransform implements Transform{

 public static final String CONTEXT_KEY = "newCustomTime";

    private static final String STATIC_KEY = "c";

	@Override
	public Object transform(Object input) {
		  // Grab the time out of the incoming Json data / Map
        Integer secondsString = (Integer) ((Map) input).get("newCustomTime"); 

        // Todo
        String fixedTime = null; // Your custom date manipulation logic.

        // Overwrite the old value with the new / fixed one.
        return ((Map) input).put("newCustomTime", 123); 
	}

  /*  @Override
    public Object transform( Object input, Map<String, Object> context ) {

        String contextValue = (String) context.get(CONTEXT_KEY);

        ((Map) input).put( STATIC_KEY, contextValue );

        return input;
}*/

}
`

[ { "operation": "shift", "spec": { "instantseconds": "newCustomTime", "id": "newid", "_clientInfo": { "ip": "client_ip" } } }, { "operation" : "au.com.api.order.ValueTransform" } ]

Output:
1429720551`

**Comment by sharmmoh1983** [comment]
@milosimpson 
 Any comment on this.. I am really stuck with the issue of value not getting updated

**Comment by sharmmoh1983** [comment]
@milosimpson 
I got the issue resolved.. I had to create a new object to make it work

Thanks for your support
