### ISSUE TITLE
How to Pass Variable value from code to spec?

### ISSUE THREAD

**Issue by sharmmoh1983** [bazaarvoice/jolt#629]
My requirement is to pass variable value to be used in mapping in spec? How to achieve it?

I am also not  able to find the solution by using custom transformer by passing the value in the constructor

**Comment by sharmmoh1983** [comment]
There is variable in my application called organization name to be used in mapping for JSON. How we ca achieve it?

**Comment by sharmmoh1983** [comment]
Got the implementation..closing the issue

**Comment by sharmmoh1983** [comment]
I am just passing the required variable in context object and accessing it in the espec

**Comment by keshavhsk** [comment]
@sharmmoh1983 Could you pls let me know how you achieved this? may be an example?
