### ISSUE TITLE
Comments in transformation spec

### ISSUE THREAD

**Issue by vectro** [bazaarvoice/jolt#630]
Hi folks,

One thing I'm noticing as I develop JOLT transformations is that I wish there were a way to put comments in. Sometimes it may not be immediately obvious why a spec was designed in a certain way. Unfortunately JSON does not allow comments.

JSON Schema gets around this with a "$comment" key, which is ignored everywhere in a schema document and can therefore be used to store comments. The value can even be an array in order to break comments across lines.

The "$" symbol is already taken in JOLT, but what about "//"? JOLT could have a rule to ignore all keys starting with "//" anywhere in the spec, unless escaped, which could then be used for comments.

**Comment by milosimpson** [comment]
If you use the JsonUtils helper from Jolt, it leverages and configures Jackson to allow for standard // comments in the Json spec files.

So does the demo site (at least or the spec, but not the input).

**Comment by vectro** [comment]
That's fair, but the way I see it one of the main advantages of JOLT's approach is that the specs are themselves JSON files, so that they can be stored and processed using existing JSON tools. Adding // comments breaks that, going down the path of making a special-purpose language.

**Comment by milosimpson** [comment]
Before I figured out how to get Jackson to be cool with C style comments, I would something like 
```
{
  "comment" : "this is here for x, y z",
  "data: { 
     ...
  }
} 
```

The problem is if your comment is more than one line.   Then you have to start "numbering" your comments.
```
{
  "comment1" : "this is here for x, y z",
  "comment2" : "this data was copied from X"
  "comment3" : "As of 2016, this is now the 'old format', but we still support it"
  "data: { 
     ...
  }
} 
```

That looks ok, but has usability problems.
1) your "comments" can now "break" your file if you accidentally have two "comment2" entries.   Ie. the Json is no longer valid / won't load.
2) You can't have / copy-paste double quotes in your comment data / right hand side w/out manually fixing them  --> "old format" --> 'old format'

This bad in that it gives the "comments" the ability to break your "code".   Hence why I now go with the Jackson Json Parsing flag.

**Comment by vectro** [comment]
It's not quite so bad because you can put the comments in an array, like so:

```
{
  "comment": [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "Sed ac nibh fringilla, rutrum ipsum quis, elementum est.",
    "Sed non ante vel arcu tempus elementum."
  ]
}
```

Breaking lines this way is annoying, but as I said it comes with the advantages of being able to use the full suite of JSON tools (for example, JSON Schema, CouchDB/PostgreSQL, jsonpath, etc.).

My suggestion is to reserve a keyword (such as //) for comments, in case there is actually a key called "comment" that needs to be transformed.

**Comment by singhsaroj** [comment]
Input JSON
=============
{
  "type": "message",
  "id": "AdEYQOuS9BKAhImuuzVjap-6|0000010",
  "timestamp": "2019-02-26T12:51:34.166-05:00",
  "localTimestamp": "2019-02-26T12:51:33.768-05:00",
  "channelId": "directline",
  "from": {
    "id": "ava_dev",
    "name": "Ava (dev)"
  },
  "conversation": {
    "id": "AdEYQOuS9BKAhImuuzVjap-6"
  },
  "attachmentLayout": "list",
  "membersAdded": [],
  "membersRemoved": [],
  "text": "",
  "inputHint": "expectingInput",
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.hero",
      "content": {
        "text": "I'm happy to help. Please let me know what type of question you have, or ask a question directly in the chat window.",
        "buttons": [
          {
            "type": "imBack",
            "title": "Help with documentation",
            "value": "Help with documentation"
          },
          {
            "type": "imBack",
            "title": "Questions about policies",
            "value": "Questions about policies"
          },
          {
            "type": "imBack",
            "title": "Questions about accounts",
            "value": "Questions about accounts"
          },
          {
            "type": "imBack",
            "title": "Questions about something else",
            "value": "Questions about something else"
          }
        ]
      }
    }
  ],
  "entities": [],
  "replyToId": "AdEYQOuS9BKAhImuuzVjap-6|0000009"
}

Expected Output JSON
==================
{ 
    "type": "Structured",
    "contentType": "generic",
 
    "messageType": "text",
    "text": "",
 
    "content": [
 
        {
            "id": "987a6c84-ada0-468f-86e1-e9ea715b8c32",
            "title": "",
            "desc": "I\u0027m happy to help. Please let me know what type of question you have, or ask a question directly in the chat window.",
 
            "image": "http://www.samplesite.com/flights/img/norway_promo.jpg",
            "video": "",
 
            "actions": {
 
                "url": "http://www.samplesite.com/flights/norway",
                "urlTarget": "__BLANK"
            },
 
            "components": [
 
                {
                    "id": "0",
                    "type": "button",
                    "text": "View Details",
                    "title": "View Details",
                    "actions": {
 
                        "url": "http://www.samplesite.com/flights/norway",
                        "urlTarget": "__BLANK"
                    }
                },
 
                {
                    "id": "1",
                    "type": "button",
                    "text": "Book Now",
                    "title": "Book Now",
                    "actions": {
 
                        "url": "http://www.samplesite.com/flights/norway/book",
                        "urlTarget": "__BLANK"
                    }
                }
            ]
        }
    ]
}

Can anyone help me to deriving to specification , m new to this and i m getting jolted now.
