### ISSUE TITLE
Data loss in Java Jolt Transform

### ISSUE THREAD

**Issue by volo-schristie** [bazaarvoice/jolt#633]
Hello,

I have a spec which works perfectly in the web demo but when i reuse it in Java, i'm finding a field is not being shifted across. The following Input, Spec and Output is what I'm using in the demo:

**Input**
```
{
  "webHookContext": {
    "clientID": "3702"
  },
  "payload": {
    "products": [
      {
        "stockNumber": "API599350851",
        "available": 10,
        "unavailable": 0,
        "onOrder": 0,
        "committed": 0,
        "toShip": 0
      },
      {
        "stockNumber": "API599350823",
        "available": 5,
        "unavailable": 0,
        "onOrder": 0,
        "committed": 0,
        "toShip": 0
      }
    ]
  }
}
```

**Spec**
```
[
   {
      "operation":"shift",
      "spec":{
         "payload":{
            "products":{
               "*":{
                  "@(3,webHookContext)":{
                     "clientID":"[&1].seller.volo_tenant_id"
                  },
                  "@(stockNumber)":"[&1].sku",
                  "@(available)":"[&1].inventory.listed_quantity"
               }
            }
         }
      }
   }
]
```

**Output**
```
[ {
  "cust" : {
    "tenant_id" : "3702"
  },
  "sku" : "API599350851",
  "inventory" : {
    "listed_quantity" : 10
  }
}, {
  "cust" : {
    "tenant_id" : "3702"
  },
  "sku" : "API599350823",
  "inventory" : {
    "listed_quantity" : 5
  }
} ]
```

As said above, this is working as intended. However, when using the same input and spec in Java, the cust.tenant_id field is not appearing in the output. Here is the code in use:
```
private Object joltifyTheData(JsonNode specFile, JsonNode input) {

        LOGGER.info("spec  = {}", JsonUtils.jsonToObject(specFile.toString()));

        Chainr chainr = Chainr.fromSpec(JsonUtils.jsonToObject(specFile.toString()));

        Object inputJSON = JsonUtils.jsonToObject(input.toString());

        Object transformedOutput = chainr.transform(inputJSON);

        transformedOutput = JsonUtils.toJsonString(transformedOutput);
        LOGGER.info("Transformed Output = {}", transformedOutput);
        return transformedOutput;

}
```

I can see that the transform is functional as the sku and inventory fields are appearing in output where i'd expect.

Any help to get this functional would be great as I'd really like to make more use of Jolt in the future!

Thanks,
Steve

**Comment by milosimpson** [comment]
Herm.

First, try this simpler version of the spec.
```
[
  {
    "operation": "shift",
    "spec": {
      "payload": {
        "products": {
          "*": {
            "@(3,webHookContext.clientID)": "[&1].seller.volo_tenant_id",
            "stockNumber": "[&1].sku",
            "available": "[&1].inventory.listed_quantity"
          }
        }
      }
    }
  }
]

```
1) stockNumber and available don't need tha "@" operator, they can just be directly matched.
2) when using the "@" to look back up the tree, you can walk down more than one level.

Second, be aware that the "shift" operation is really just doing a "shallow copy".     I.e. in your input data there is only one "clientID", and it has a value of "3702".

In the Java code after the transform, a single String of "3702" will be a value in two maps.


Lastly, (grasping at straws), make sure your JsonNode toString is doing what you expect...

**Comment by volo-schristie** [comment]
Thanks for the info, looks to have done the trick using that spec.

Regards,
Steve
