### ISSUE TITLE
Shifting array of objects to another array of objects with a different key.

### ISSUE THREAD

**Issue by danielamaya** [bazaarvoice/jolt#635]
Assuming I have the following input:

**input.json**
```
"experience": [
	{
		"title": "Software Engineer",
		"company": [{
			"name": "Microsoft"
		}]
	},
	{
		"title": "Developer",
		"company": [{
			"name": "Oracle"
		}]
	},
]
```

And I'd like to create the following output:

**desired_output.json**
```
"exp": [
	{
		"title": "Software Engineer",
		"org": {
			"n": "Microsoft"
		}
	},
	{
		"title": "Developer",
		"org": {
			"n": "Oracle"
		}
	},
]
```

I'm trying to figure out what Shifts I would make here.

**spec.json**

```
[
  {
    "operation": "shift",
    "spec": {
      "_source": {
        "experience": {
          "*": {
            "title": "exp.[&1].title",
            "company": {
              "0": {
                "name": "exp.[&1].org.n"
              }
            }
          }
        }
      }
    }
  }
]
```

**actual_output.json**

```
{
  "exp" : [ {
    "title" : "Software Engineer",
    "org" : {
      "n" : [ "Microsoft", "Oracle" ]
    }
  }, {
    "title" : "Developer"
  } ]
}
```

**Comment by danielamaya** [comment]
I've answered my own question with the following spec:

```
"experience": {
          "*": {
            "title": "exp.[&1].title",
            "organization": {
              "0": {
                "name": "exp.[&3].org.n"
              }
            }
          }
        }
```

What I'm trying to figure out now is what the `[&1]` and `[&3]` notations actually do. I've been reading the docs, just wondering if there are any tutorials, wiki pages or anything else anyone can recommend.

**Comment by milosimpson** [comment]
https://github.com/bazaarvoice/jolt/blob/master/jolt-core/src/main/java/com/bazaarvoice/jolt/Shiftr.java#L184

**Comment by danielamaya** [comment]
@milosimpson I understand what it means on the LHS (input), but I'm having a hard time understanding what it means on the RHS (output).

Assuming I have the following spec:

**spec.json**

```
[
  {
    "operation": "shift",
    "spec": {
      "experience": {
        "*": {
          "title": "exp.[&1].title",
          "org": {
            "0": {
              "n": "exp.[&3].company.name"
            }
          }
        }
      }
    }
  }
]
```

And the following input:

**input.json**

```
{
  "experience": [
    {
      "title": "foo",
      "org": [
        {
          "n": "bar"
        }
      ]
    }
  ]
}
```



Then I would assume `n = &0, org = &1, exp = &2, and { = &3`? So what does it mean then to say `exp.[&3].org.n`? I'm trying to figure out on the RHS what that `[&3]` actually does, and what different the `[]` around it make (I'm assuming it's to do with arrays, but not sure). Looking at the javadoc you linked, I actually don't see any mention of `[&#]` notation.

**Comment by milosimpson** [comment]
From the "line" where you write the "&3" it will look up the tree that many levels and grab the matched value at that level.

I.e. in your "exp.[&3].company.name"   the &3 evaluates to the "current array index of the input experience array".     The "[]" tell shift to make an array, and put your data at an array index, as opposed to the converting the array index int into a String to be a "key".

I.e. run "exp.&3.company.name" and see what the output looks like.

**Comment by RamuYannam** [comment]
Input is:
---------
{
    "list": {
        "fruits": [
            {
                "name": "Orange",
                "price": "100",
                "priceUnit": "Per KG",
                "Currency": "INR"
            },
            {
                "name": "Banana",
                "price": "60",
                "priceUnit": "Per Dozen",
                "Currency": "INR"
            },
            {
                "name": "Apple",
                "price": "150",
                "priceUnit": "Per KG",
                "Currency": "INR"
            }
        ],
        "vegetables": [
            {
                "name": "Potato",
                "price": "20",
                "priceUnit": "Per KG",
                "Currency": "INR"
            }
        ]
    }
}

Expected output is:
{
    "order": {
        "creationDate": "17-09-2020",
        "channel": "App",
        "itemList": {
            "foodItems": [
                {
                    "itemName": "Orange",
                    "type": "Fruit",
                    "Unit Price": "100 Per KG"
                },
                {
                    "itemName": "Banana",
                    "type": "Fruit",
                    "Unit Price": "60 Per Dozen"
                },
                {
                    "itemName": "Apple",
                    "type": "Fruit",
                    "Unit Price": "100 Per KG"
                },
                {
                    "itemName": "Potato",
                    "type": "Vegetable",
                    "Unit Price": "20 Per KG"
                }
            ],
            "others":[
                {
                    "itemName": "Bag Big",
                    "type": "Packaging Material",
                    "Unit Price": "10 per Bag"
                }
            ]
        }
    }
}

Can some body let me know the **JOLT** spec for this please
