### ISSUE TITLE
Jolt Help with simple spec to transform key:value(s) to concatenated comma delim value

### ISSUE THREAD

**Issue by andrew-greiner** [bazaarvoice/jolt#637]
Good evening,
       First of all, amazing job. I absolutely love the concept and implementation. We're getting big into NIFI and the fact that there's a Jolt Transform (with custom transforms) is a perfect marriage. I'm just coming up to speed and thought I'd run a very simple one by you.

Input
```
{
   "locationAddress": {
        "addressLine": "CORSO ARNALDO LUCCI METROPARK",
        "postCode": "80144",
        "city": "NAPLES",
        "state": "ITALY",
        "countryCode": "it",
        "latitude": 40.85076412919103,
        "longitude": 14.27274501107081
   }
}
```

Expected Output
```
{
   "formattedAddress": {
         "NAPLES, 80144, ITALY"
   }
}
```

Products of the following from the input locationAddress:
"postCode": "80144",
"city": "NAPLES",
"state": "ITALY"

Thanks in advance

**Comment by milosimpson** [comment]
See http://jolt-demo.appspot.com/#modify-stringFunctions

**Comment by milosimpson** [comment]
Spec
```
[
  {
    "operation": "modify-default-beta",
    "spec": {
      "formattedAddress": "=concat(@(1,locationAddress.city),', ',@(1,locationAddress.postCode),', ',@(1,locationAddress.state))"
    }
  },
  {
    "operation": "remove",
    "spec": {
      "locationAddress": ""
    }
  }
]
```

**Comment by andrew-greiner** [comment]
Yep, sorry Milo. Pulling snippets of Json out on the fly and masking. Amazed at the speed at which you replied though. Top notch. 

Thanks again
