### ISSUE TITLE
Converting a  JSON to tree structure type jSON. Need help regarding json spec

### ISSUE THREAD

**Issue by adikac** [bazaarvoice/jolt#639]
I am trying to transform json response to another format. Need help regarding JSON spec
**Input JSON:** 
{
  "realCustomerNo": "34566",
  "structureCode": "VMXX",
  "structureDesc": "VMXXXX",
  "virtualMain": "VMX00001",
  "realNo": "12211212",
  "realBrn": "000",
  "interestCalcRequired": "N",
  "AccountMapDetailDTO": [
    {
      "id": "ID14",
      "MapMasterId": "5bfd3ab4-19ec-45d9-9c33-beb684e27586",
      "virtualMain": "VMX00001",
      "virtualParent": "VMX00002",
      "virtualChild": "VMX00005"
    },
    {
      "id": "ID13",
      "MapMasterId": "5bfd3ab4-19ec-45d9-9c33-beb684e27586",
      "virtualMain": "VMX00001",
      "virtualParent": "VMX00002",
      "virtualChild": "VMX00004"
    },
    {
      "id": "ID12",
      "MapMasterId": "5bfd3ab4-19ec-45d9-9c33-beb684e27586",
      "virtualMain": "VMX00001",
      "virtualParent": "VMX00001",
      "virtualChild": "VMX00003"
    },
    {
      "id": "ID11",
      "MapMasterId": "5bfd3ab4-19ec-45d9-9c33-beb684e27586",
      "virtualMain": "VMX00001",
      "virtualParent": "VMX00001",
      "virtualChild": "VMX00002"
    }
  ]
}

**Desired Output :** 
{
	"realCustomerNo": "34566",
	"structureCode": "VMXX",
	"structureDesc": "VMXXXX",
	"virtualMain": "VMX00001",
	"realNo": "000234349229",
	"realBrn": "000",
	"interestCalcRequired": "N",
	"virtualParent": {
		"virtualAcc": "VMX00001",
		"virtualChildren": [{
				"id": "ID11",
				"MapMasterId": "5bfd3ab4-19ec-45d9-9c33-beb684e27586",
				"virtualAcc": "VMX00002",
				"virtualChildren": [{
						"id": "ID14",
						"accMapMasterId": "5bfd3ab4-19ec-45d9-9c33-beb684e27586",
						"virtualAcc": "VMX00005"
					},
					{
						"id": "ID13",
						"accMapMasterId": "5bfd3ab4-19ec-45d9-9c33-beb684e27586",
						"virtualAcc": "VMX00004"
					}
				]

			},
			{
				"id": "ID12",
				"MapMasterId": "5bfd3ab4-19ec-45d9-9c33-beb684e27586",
				"virtualAcc": "VMX00003"
			}
		]

	}
}
Any help will be grateful...Thanks

**Comment by adikac** [comment]
@milosimpson  can u help

**Comment by milosimpson** [comment]
Yeah, It looks like you are trying to group by multiple items, which really isn't what Jolt should be used for.
