### ISSUE TITLE
Json spec for splitting input value to multiple output tags

### ISSUE THREAD

**Issue by vishhs** [bazaarvoice/jolt#644]
Hi,

Not sure how to get the spec built for the below requirement. Any help is greatly appreciated. 

Input:

{"params":"sn=GH6747246T4JLR6AZ&c=QUERY_RECORD&p=test_station_name&p=station_id&p=result&p=mac_addresss"}

Output:

{ "queryType": "scan", "dataSource": "xyz", "resultFormat": "list", "columns":["test_station_name","station_id","result","mac_address"], "intervals": [ "2018-01-01/2018-02-09" ],"filter": { "type": "selector", "dimension": "sn", "value":"GH6747246T4JLR6AZ" } }

Except for the content inside Columns and dimension and value attributes inside filter tag rest of the fields are hardcoded.

Thanks in advance.
Vish

**Comment by milosimpson** [comment]
Nope.   Not a thing that Jolt does out of the box.

**Comment by jashgala** [comment]
Would it help to extend the existing stock function modifiers to support string splitting and the like?
 
It wouldn't be hard to implement and it would enable resolving cases like this one.
