### ISSUE TITLE
Adding a numeric constant

### ISSUE THREAD

**Issue by Udith** [bazaarvoice/jolt#647]
I need to add a numeric constant value to a field in my output json. But when I used the following spec, the output is always generated as a string value. Is there a way to specify this as a numeric value?

**Sample Spec**
```json
{
    "operation": "shift",
    "spec": {
        "#2": "myField"
    }
}
```
**Actual Output**
```json
{
    "myField": "2"
}
```
**Expected Output**
```json
{
    "myField": 2
}
```

**Comment by milosimpson** [comment]
Use "default" or the newer "modify-default-beta".
