### ISSUE TITLE
How to append string to each item of array?

### ISSUE THREAD

**Issue by justinvincelette** [bazaarvoice/jolt#652]
Input:
` {  "ids": [ 1, 2, 3, 4, 5] } `
Output:
` { "newIds": [ "id-1", "id-2", "id-3", "id-4", "id-5" ] } `

Thanks in advance, and thanks for a great project!

**Comment by milosimpson** [comment]
This will do the string concatenation.   Then do a shift to move the ids array to be a newIds array.

Spec
```
[
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "ids": {
        "*": "=concat('id-',@(2,ids[&]))"
      }
    }
  }
]
```
