### ISSUE TITLE
Matching multiple values from inner array results in duplicate matches in output

### ISSUE THREAD

**Issue by rvertigo** [bazaarvoice/jolt#653]
I am attempting to match values in an inner array to filter the outer element. In the below structure, I want to select the _settings.options_ based on the contents of the _settings.options.filters_

When matching multiple values of the inner _settings.options.filters_ array, we end up selecting multiple matches of _settings.options_ as multiple duplicated elements. (Meaning, the "good" type is selected twice because of two matches in the inner _settings.options.filters_ array). I couldn't find how to match one single array value without traversing the entire array. I also couldn't find any way to have the `|` operator short circuit or otherwise match any one element of an array. Is there a way to match any one element of an array to multiple options or de-duplicate the returned indexes?

**input** 
<pre>
{
  "config": {
    "id_1": "one",
    "inner_config": {
      "id_2": "two"
    },
    "settings": {
      "options": [{
        "type": "good",
        "filters": ["find", "this", "entry"],
        "addresses": ["test1@test.com", "test2@test.com"]
      }, {
        "type": "more",
        "filters": ["also", "this", "one"],
        "addresses": ["test3@test.com", "test4@test.com"]
      }, {
        "type": "bad",
        "filters": ["not", "here"],
        "addresses": ["test5@test.com", "test6@test.com"]
      }]
    }
  }
}
</pre>

**spec**
<pre>
[{
  "operation": "shift",
  "spec": {
    "config": {
      "id_1": "id1",
      "inner_config": {
        "id_2": "id2"
      },
      "settings": {
        "options": {
          "*": {
            "filters": {
              "*": {
                "find|only|this|value": {
                  "@3": "matched[]"
                }
              }
            }
          }
        }
      }
    }
  }
}]
</pre>

**Expected**
<pre>
{
  "id1": "one",
  "id2": "two",
  "matched": [{
    "type": "good",
    "filters": ["find", "this", "entry"],
    "addresses": ["test1@test.com", "test2@test.com"]
  }, {
    "type": "other",
    "filters": ["also", "this", "one"],
    "addresses": ["test3@test.com", "test4@test.com"]
  }]
}
</pre>

**Actual**
<pre>
{
  "id1": "one",
  "id2": "two",
  "matched": [{
    "type": "good",
    "filters": ["find", "this", "entry"],
    "addresses": ["test1@test.com", "test2@test.com"]
  }, {
    "type": "good",
    "filters": ["find", "this", "entry"],
    "addresses": ["test1@test.com", "test2@test.com"]
  }, {
    "type": "other",
    "filters": ["also", "this", "one"],
    "addresses": ["test3@test.com", "test4@test.com"]
  }]
}
</pre>

**Comment by milosimpson** [comment]
Thank you for the well formed, reasonably sized question.

Answer, use a 2nd shift.

Spec
```
[{
    "operation": "shift",
    "spec": {
      "config": {
        "id_1": "id1",
        "inner_config": {
          "id_2": "id2"
        },
        "settings": {
          "options": {
            "*": {
              "filters": {
                "*": {
                  "find|only|this|value": {
                    // There can be multiple matches
                    //  and there is no way around that.
                    // So instead of accumulating them into 
                    //  as single "matched" list.
                    // Build a goodOptions list that can have
                    //  the same number of elements as the
                    //  input "options" array.
                    // And then in each spot always make that
                    //  be a list if we write to it.
                    // Idea being, we can't stop the duplicates
                    //  but we can at least put them all in the 
                    //  "same" bucket, and then in another 
                    //  shift, just pick the first item from
                    //  
                    "@3": "goodOptions[&4][]"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "id*": "&",
      "goodOptions": {
        "*": {
          "0": "matched[]"
        }
      }
    }
  }
]
```

**Comment by rvertigo** [comment]
That makes sense! You're a super hero.
