### ISSUE TITLE
Is it possible to do this kind of transfer ?

### ISSUE THREAD

**Issue by ca7erina** [bazaarvoice/jolt#654]
Input:
` {
  "AA": [
    {
      "A": "10",
      "B": "20",
      "C": "90",
      "D": "10"
    }
  ]
}`

Expected Output:
`{
  "AA": [
    {
      "A": "red",
      "B": "yellow",
      "C": "black",
      "D": "red"
    }
  ]
}
`

Question: Can we do a logic check in the spec? to get the expected result
-  if the value <=10, return red,
-  if the value >10, value <90 return yellow
-  if the value >=90, return black.

**Comment by milosimpson** [comment]
No.  Not using the OOTB transform operations.

**Comment by ca7erina** [comment]
Is it possible to achieve it with a customized transformer class?
Thanks a million!

**Comment by milosimpson** [comment]
Yes, but you would have to write it.   Implement the Transform Interface.

And then you can call your Transform by using it's fully qualified class name as the "operation".

Something like
```
[
  {
    "operation": "shift",
    "spec": {
      ...
    }
  },
  {
    "operation": "com.example.jolt.RedYellowBlackTransform"
  },
  {
    "operation": "default",
    "spec": {
      ...
    }
  }
]
```

**Comment by ca7erina** [comment]
Hi milosimpson, thanks for the quick reply. I think I need a simple example that could show me how to do the following transform. I have current code set up just return whatever the input is:
Main:
```
public class Trans {
  public static void main(final String[] args) throws IOException {
    final List chainrSpecJSON = JsonUtils.classpathToList("/json/sample/spec.json");
    final Chainr chainr = Chainr.fromSpec(chainrSpecJSON);
    final Object inputJSON = JsonUtils.classpathToObject("/json/sample/input.json");
    final Object transformedOutput = chainr.transform(inputJSON);
    System.out.println(JsonUtils.toJsonString(transformedOutput));
  }
}
```
Spec:
`[
  {
    "operation": "com.MyTransform",
    "spec":{}
  }
]`

Input:
 `{ "A": "10", "B": "20", "C": "90", "D": "10" }`

Expected Output:
`{  "A": "red", "B": "yellow", "C": "black", "D": "red"  }`

How to use the "input" object passed in the "transform" method and return what I expected.
```
public class MyTransform implements SpecDriven, Transform {
  private final Object spec;
  @Inject
  public MyTransform(final Object spec) {
    this.spec = spec; 
    if (spec == null) {
      throw new SpecException("MyTransform expected a spec of Map type, got 'null'.");
    }
    if (!(spec instanceof Map)) {
      throw new SpecException(
          "MyTransform expected a spec of Map type, got " + spec.getClass().getSimpleName());
    }
  }
  @Override
  public Object transform(Object input) {
    // TODO how to do the transform with input, and what should i return.
    return new TransformResult(input, spec);
  }
}
```

**Comment by milosimpson** [comment]
Start simple / don't need a spec driven transform.

This is assuming that the input data is just a single top level map with "A", "B", etc as keys.

```
public class MyTransform implements Transform {

  @Override
  public Object transform(Object input) {
     if ( ! input instanceof Map) {  return input; }

    Map<String, Object> inputMap = (Map<String,Object>) input;

    // psudocode
    int A = Integer.valueOf( inputMap.get("A") );

    if ( A <= 10 ) {
       inputMap.put("A", "red" );
    }
    /// etc
  }
}
```
