### ISSUE TITLE
Transform where field is string escaped JSON

### ISSUE THREAD

**Issue by garnesen** [bazaarvoice/jolt#655]
I receive an input that I can use ObjectMapper to get the following class:
```java
public class InputWrapper {
    private Map<String, List<String>> httpHeaders;
    private String payload;

    public InputWrapper(Map<String, List<String>> httpHeaders, String payload) {
        this.httpHeaders = httpHeaders;
        this.payload = payload;
    }

    // Getters and setters...
}
```
The `payload` is a string representing a JSON object. I want to input `InputWrapper` into Jolt to transform the `httpHeaders` and `payload`. To do this, I must first parse `payload` to an object. To do this, I do
```java
Object objPayload = JsonUtils.jsonToObject(inputWrapper.getPayload());
```
Then, I create a new object `OutgoingWrapper` that will hold the new information. `OutgoingWrapper` is the same as `InputWrapper` except the `payload` field is an object. Now, if I do this..
```java
OutgoingWrapper wrapper = new OutgoingWrapper(inputWrapper.getHttpHeaders(), objPayload);
Object transformedWrapper = chainr.transform(wrapper);
```
it does not work.

The only way I have gotten this to work is turning the wrapper into a string and back into an Object like so
```java
OutgoingWrapper wrapper = new OutgoingWrapper(inputWrapper.getHttpHeaders(), objPayload);
String wrapperJson = JsonUtils.toJsonString(wrapper);
Object wrapperAsObject = JsonUtils.jsonToObject(wrapperJson);
Object transformedWrapper = chainr.transform(wrapperAsObject);
```

Is there any way for me to avoid these two middle lines of code?

**Comment by milosimpson** [comment]
No.   The core transform logic only works on _actual_ Java Map, List, String, etc data-structures.

To be really clear, if your input is a single JSON document as a String, and you want to return a JSON document as a String, to use Jolt you have to convert in and out of Java objects.

**Comment by garnesen** [comment]
Got it, thanks!
