### ISSUE TITLE
nested array to  single  data

### ISSUE THREAD

**Issue by guangjianwu** [bazaarvoice/jolt#659]
how to write  spec?

input:

     [
       {
        "status": "success", 

            "result": [
                {
                    "cashierUid": 1111,
                    "items": [
                        {
                            "name": "name1"

                        }
                    ] 
  
                }, 
                {
                    "cashierUid": 2222, 
                    "items": [
                        {
                            "name": "name2"
  
                        }, 
                        {
                            "name": "name22"
                        }
                    ]
                }
            ], 
            "pageSize": 2
        
    }, 
    {
        "status": "success", 

            "result": [
                {
                    "cashierUid": 3333,
                    "items": [
                        {
                            "name": "name3"
                        }
                    ]
                }, 
                {
                    "cashierUid": 4444, 
                    
                    "items": [
                        {
                            "name": "name4"
                        }, 
                        {
                            "name": "name44"
                        }
                    ]
                }
            ], 
            "pageSize": 2
        }
     ]

output:

"data":[{
	      "cashierUid": 1111,
	      "name": "name1"
             },
             {
	      "cashierUid": 2222, 
	      "name": "name2"
             },
            {
	      "cashierUid": 2222, 
	      "name": "name22"
           },
           {
	      "cashierUid": 3333,
	      "name": "name3"
           },
          {
	     "cashierUid": 4444, 
	     "name": "name4"
          },
          {
	     "cashierUid": 4444, 
	     "name": "name44"
          }]

**Comment by guangjianwu** [comment]
spec:

[spec.txt](https://github.com/bazaarvoice/jolt/files/2331713/spec.txt)

**Comment by milosimpson** [comment]
Ah you got it, well done.

**Comment by guangjianwu** [comment]
@milosimpson  thank you  all the same
