### ISSUE TITLE
Update Jolt version at jolt-demo.appspot.com to 0.1.1

### ISSUE THREAD

**Issue by pauleta7** [bazaarvoice/jolt#665]
Hello,

It's possible to upgrade the Jolt version of the jolt-demo.appspot.com tool to 0.1.1? 
I need to do some complex Jolt transformations using some of the new functions available at Jolt 0.1.1 and without the jolt-demo it's kind of difficult to test the development.

**Comment by milosimpson** [comment]
Fixed.   Also, fixed the issue where the Cursor was blinking a unicode "A".   Turns out it was a JavaScript minification problem the CDN hosting the CodeMirror libraries.
