### ISSUE TITLE
Most efficient way to flatten nested array

### ISSUE THREAD

**Issue by apiwoni** [bazaarvoice/jolt#666]
Given input:

```
{
  "id": "parentId",
  "questionnaire": {
    "questionnaireId": "questionnaire1",
    "questions": [
      {
        "questionId": "question1",
        "choices": [
          {
            "choiceId": "choice1",
            "label": "A"
          },
          {
            "choiceId": "choice2",
            "label": "B"
          }
        ]
      },
      {
        "questionId": "question2",
        "choices": [
          {
            "choiceId": "choice3",
            "label": "C"
          },
          {
            "choiceId": "choice4",
            "label": "D"
          },
          {
            "choiceId": "choice5",
            "label": "E"
          }
        ]
      }
    ]
  }
}
```

Expected output:
```
[ {
  "QuestionId" : "question1",
  "QuestionnaireId" : "questionnaire1",
  "ParentId" : "parentId",
  "ChoiceId" : "choice1",
  "ChoiceLabel" : "A"
}, {
  "QuestionId" : "question1",
  "QuestionnaireId" : "questionnaire1",
  "ParentId" : "parentId",
  "ChoiceId" : "choice2",
  "ChoiceLabel" : "B"
}, {
  "QuestionId" : "question2",
  "QuestionnaireId" : "questionnaire1",
  "ParentId" : "parentId",
  "ChoiceId" : "choice3",
  "ChoiceLabel" : "C"
}, {
  "QuestionId" : "question2",
  "QuestionnaireId" : "questionnaire1",
  "ParentId" : "parentId",
  "ChoiceId" : "choice4",
  "ChoiceLabel" : "D"
}, {
  "QuestionId" : "question2",
  "QuestionnaireId" : "questionnaire1",
  "ParentId" : "parentId",
  "ChoiceId" : "choice5",
  "ChoiceLabel" : "E"
} ]
```
Is spec below the most efficient way to get expected output? Can it be done in one pass?
```
[
  {
    "operation": "shift",
    "spec": {
      "questionnaire": {
        "questions": {
          "*": {
            "choices": {
              "*": {
                "@(2,questionId)": "[&3].[&1].QuestionId",
                "choiceId": "[&3].[&1].ChoiceId",
                "@(4,questionnaireId)": "[&3].[&1].QuestionnaireId",
                "label": "[&3].[&1].ChoiceLabel",
                "@(5,id)": "[&3].[&1].ParentId"
              }
            }
          }
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "*": {
        "*": "[]"
      }
    }
  }
]
```
Thank you,
Andre Piwoni

**Comment by milosimpson** [comment]
Can it be done in one pass?   -> No.

Is spec below the most efficient way to get expected output?  -> Using Jolt, it is the only way to do it.   If you need more efficiency than that, then you have to implement it.

**Comment by apiwoni** [comment]
Thank you

**Comment by romweinstein** [comment]
Continuing to the previous question.
In case the root element is Array
[
  {
    "questionId": "question1",
    "choices": [
      {
        "choiceId": "choice1",
        "label": "A"
      },
      {
        "choiceId": "choice2",
        "label": "B"
      }
    ]
  },
  {
    "questionId": "question2",
    "choices": [
      {
        "choiceId": "choice3",
        "label": "C"
      },
      {
        "choiceId": "choice4",
        "label": "D"
      },
      {
        "choiceId": "choice5",
        "label": "E"
      }
    ]
  }
]

**How can i flatten it to expected result :**
[ {

         "questionId":"question1",
        "choiceId": "choice1",
        "label": "A"
      },
      {
       "questionId":"question1",
        "choiceId": "choice2",
        "label": "B"
      },
   {
        "questionId":"question2",
        "choiceId": "choice3",
        "label": "C"
      },
      {
       "questionId":"question2",
        "choiceId": "choice4",
        "label": "D"
      },
      {
       "questionId":"question2",
        "choiceId": "choice5",
        "label": "E"
      }]


Thanks

**Comment by romweinstein** [comment]
Continuing to the previous example .
In case the root element is Array
[
  {
    "questionId": "question1",
    "choices": [
      {
        "choiceId": "choice1",
        "label": "A"
      },
      {
        "choiceId": "choice2",
        "label": "B"
      }
    ]

**Comment by milosimpson** [comment]
Spec

    [
      {
        "operation": "shift",
        "spec": {
          "*": {
            "choices": {
              "*": {
                "@(2,questionId)": "[&3].[&1].QuestionId",
                "choiceId": "[&3].[&1].ChoiceId",
                "label": "[&3].[&1].ChoiceLabel"
              }
            }
          }
        }
      },
      {
        "operation": "shift",
        "spec": {
          "*": {
            "*": "[]"
          }
        }
      }
    ]

**Comment by debuggerrr** [comment]
I went through the doc but since I am new to this can somebody help me to understand the spec for the first problem. Especially the choices part
