### ISSUE TITLE
JOLT : Grouped as array while transforming the json

### ISSUE THREAD

**Issue by ramuece09** [bazaarvoice/jolt#669]
Hello @milosimpson ,

I was trying to convert the json from one JSON Format to another JSON Format using JOLT, But i'm not able to get the expected output. I have included the my work around below. Any help will be appreciated. Thanks.

My input.json

```
{
    "Result": {
    },
    "Content": [
        {
            "MovieDetails": [
                {
                    "Key": "TicketNumber",
                    "Value": "DF-0001"
                },
                {
                    "Key": "MovieName",
                    "Value": "Test"
                }
            ]
        },
        {
            "MovieDetails": [
                {
                    "Key": "TicketNumber",
                    "Value": "DF-0002"
                },
                {
                    "Key": "MovieName",
                    "Value": "Test2"
                }
            ]
        },
        {
            "MovieDetails": [
                {
                    "Key": "TicketNumber",
                    "Value": "DF-0003"
                },
                {
                    "Key": "MovieName",
                    "Value": "Test3"
                }
            ]
        }
    ]
}

```

My Expected Output.json

```
{
"Result": {

},
"Content": [
    {
        "MovieDetails": {
            "TicketNumber": "DF-0001",
            "MovieName": "Test1"
        },
        "MovieDetails": {
            "TicketNumber": "DF-0002",
            "MovieName": "Test2"
        }.
        "MovieDetails": {
            "TicketNumber": "DF-0003",
            "MovieName": "Test3"
        }
    }
]
} 
```

My Actual Output.json

```
{
"Result": {

},
"Content": [
    {
        "MovieDetails": {
            "TicketNumber": ["DF-0001","DF-0002","DF-0003"],
            "MovieName": ["Test1","Test2","Test3"]
        }
    }
]
} 
```
My Spec.json

```
[
    {
        "operation": "shift",
        "spec": {
            "Result": {
                "*": "Result.&"
            },
            "Content": {
                "*": {
                    "MovieDetails": {
                        "*": {
                            "Value": "Content.MovieDetails.@(1,Key)"
                        }
                    }
                }
            }
        }
    }
]
```

**Comment by ramuece09** [comment]
@milosimpson

**Comment by milosimpson** [comment]
Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "Result": "Result",
      "Content": {
        "*": {
          "MovieDetails": {
            "*": {
              // [&3] --> lookup the index from 4 levels up
              //   which is the "*" under Context
              "Value": "Content[&3].MovieDetails.@(1,Key)"
            }
          }
        }
      }
    }
  }
]
```

**Comment by ramuece09** [comment]
Thanks a lot @milosimpson. Much appreciated your efforts.

**Comment by ramuece09** [comment]
Hi @milosimpson 

If there is an empty array object in input json, null object added in output as highlighted below. Kindly help to fix the same. thanks.

Input json


```
{
	"Result": {
		"ResultCode": "Success"
	},
	"Content": [
		{
			"MovieDetails": [
				{
					"Key": "TicketNumber",
					"Value": "DF-0001"
				},
				{
					"Key": "MovieName",
					"Value": "Test"
				}
			],
			"TicketDetails": {
				"List": [
				],
				"Attributes": [
					{
						"Key": "Test",
						"Value": "Test12345"
					}
				]
			}
		},
		{
			"MovieDetails": [
				{
					"Key": "TicketNumber",
					"Value": "DF-0002"
				},
				{
					"Key": "MovieName",
					"Value": "Test2"
				}
			],
			"TicketDetails": {
				"List": [
				],
				"Attributes": [
					{
						"Key": "Test2",
						"Value": "Test12345"
					}
				]
			}
		},
		{
			"MovieDetails": [
				{
					"Key": "TicketNumber",
					"Value": "DF-0003"
				},
				{
					"Key": "MovieName",
					"Value": "Test3"
				}
			],
			"TicketDetails": {
				"List": [
				],
				"Attributes": [
					{
						"Key": "Test3",
						"Value": "Test12345"
					}
				]
			}
		}
	]
}
```



Output.json

```
{
	"Result": {
		"ResultCode": "Success"
	},
	"Content": [
		{
			"MovieDetails": {
				"TicketNumber": "DF-0001",
				"MovieName": "Test"
			},
			"TicketDetails": [
				{
					"Attributes": {
						"Test": "Test12345"
					}
				}
			]
		},
		{
			"MovieDetails": {
				"TicketNumber": "DF-0002",
				"MovieName": "Test2"
			},
			"TicketDetails": [
				**null,**
				{
					"Attributes": {
						"Test2": "Test12345"
					}
				}
			]
		},
		{
			"MovieDetails": {
				"TicketNumber": "DF-0003",
				"MovieName": "Test3"
			},
			"TicketDetails": [
				**null,
				null,**
				{
					"Attributes": {
						"Test3": "Test12345"
					}
				}
			]
		}
	]
}
```


Spec.json

```

[
	{
		"operation": "shift",
		"spec": {
			"Result": "Result",
			"Content": {
				"*": {
					"MovieDetails": {
						"*": {
							"Value": "Content[&3].MovieDetails.@(1,Key)"
						}
					},
					"TicketDetails": {
						"List": {
							"*": {
								"Value": "Content[&4].TicketDetails[&4].List.@(1,Key)"
							}
						},
						"Attributes": {
							"*": {
								"Value": "Content[&4].TicketDetails[&4].Attributes.@(1,Key)"
							}
						}
					}
				}
			}
		}
	}
]

```

**Comment by milosimpson** [comment]
So previously there was no "TicketDetails".   Now it exists and has sub List of "List" and "Attributes".

And somehow you want the input Map of TicketDetails to turn into a List of TicketDetails.    Is that right?   Should the output list of TicketDetails be the merge of input List and input Attributes?

This does the Key-Value conversion for "List" and "Attributes" but keeps "TicketDetails" as a map.

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "Result": "Result",
      "Content": {
        "*": {
          "MovieDetails": {
            "*": {
              "Value": "Content[&3].MovieDetails[&1].@(1,Key)"
            }
          },
          "TicketDetails": {
            "List": {
              "*": {
                "Value": "Content[&4].TicketDetails.List[&1].@(1,Key)"
              }
            },
            "Attributes": {
              "*": {
                "Value": "Content[&4].TicketDetails.Attributes[&1].@(1,Key)"
              }
            }
          }
        }
      }
    }
  }
]
```


If you want to merge "List" and "Attributes", then do a 2nd shift to merge those.

**Comment by ramuece09** [comment]
yes @milosimpson . Small changes as you suggested fixed the issue. Thanks a lot...

**Comment by ramuece09** [comment]
Hi @milosimpson 

Can you please help to transform as below. I want to replace the matched values in the map.

Input json

```
{
	"Result": {
		"ResultCode": "Success"
	},
	"Content": [
		{
			"MovieDetails": [
				{
					"Key": "TicketNumber",
					"Value": "DF-0001,DFE-0001,DFS-0001"
				},
				{
					"Key": "MovieName",
					"Value": "Test,TEST_01"
				}
			],
			"TicketDetails": {
				"List": [
				],
				"Attributes": [
					{
						"Key": "Test",
						"Value": "Test12345"
					}
				]
			}
		},
		{
			"MovieDetails": [
				{
					"Key": "TicketNumber",
					"Value": "DF-0002,DFE-0002,DFS-0002"
				},
				{
					"Key": "MovieName",
					"Value": "Test2,TEST_02"
				}
			],
			"TicketDetails": {
				"List": [
				],
				"Attributes": [
					{
						"Key": "Test2",
						"Value": "Test12345"
					}
				]
			}
		},
		{
			"MovieDetails": [
				{
					"Key": "TicketNumber",
					"Value": "DF-0003"
				},
				{
					"Key": "MovieName",
					"Value": "Test3"
				}
			],
			"TicketDetails": {
				"List": [
				],
				"Attributes": [
					{
						"Key": "Test3",
						"Value": "Test12345"
					}
				]
			}
		}
	]
}
```

```
HashMap<String, String> hmap = new HashMap<String,String>();
hmap.put("DF-0001","DF_TICKET_1");
hmap.put("DFE-0001","DFE_TICKET_1");
hmap.put("DFS-0001","DFS_TICKET_1");
hmap.put("DF-0002","DF_TICKET_2");
hmap.put("DFE-0002","DFE_TICKET_2");
hmap.put("DFS-0002","DFS_TICKET_2");
```


Output Json
-----------

```
{
	"Result": {
		"ResultCode": "Success"
	},
	"Content": [
		{
			"MovieDetails": {
				"TicketNumber": "DF_TICKET_1,DFE_TICKET_1,DFS_TICKET_1",
				"MovieName": "Test"
			},
			"TicketDetails": [
				{
					"Attributes": {
						"Test": "Test12345"
					}
				}
			]
		},
		{
			"MovieDetails": {
				"TicketNumber": "DF_TICKET_2,DFE_TICKET_2,DFS_TICKET_2",
				"MovieName": "Test2"
			},
			"TicketDetails": [
				**null,**
				{
					"Attributes": {
						"Test2": "Test12345"
					}
				}
			]
		},
		{
			"MovieDetails": {
				"TicketNumber": "DF-0003",
				"MovieName": "Test3"
			},
			"TicketDetails": [
				**null,
				null,**
				{
					"Attributes": {
						"Test3": "Test12345"
					}
				}
			]
		}
	]
}
```

**Comment by ramuece09** [comment]
Spec Json

```
[
	{
		"operation": "shift",
		"spec": {
			"Result": "Result",
			"Content": {
				"*": {
					"MovieDetails": {
						"*": {
							"Value": "Content[&3].MovieDetails[&1].@(1,Key)"
						}
					},
					"TicketDetails": {
						"List": {
							"*": {
								"Value": "Content[&4].TicketDetails.List[&1].@(1,Key)"
							}
						},
						"Attributes": {
							"*": {
								"Value": "Content[&4].TicketDetails.Attributes[&1].@(1,Key)"
							}
						}
					}
				}
			}
		}
	},
	{
		"operation": "modify-overwrite-beta",
		"spec": {
			"Content": {
				"*": {
					"MovieDetails": {
						"TicketNumber": "^Content[&3].MovieDetails[&1].TicketNumber"
					}
				}
			}
		}
	}
]

```

**Comment by ramuece09** [comment]
Hi @milosimpson, Can you please help to transform above one!

**Comment by milosimpson** [comment]
So, that is a large problem.   I will demonstrate the core of the new request which is converting the string TicketNumber.

Given Input
```
{
  "TicketNumber": "DF-0001,DFE-0001,DFS-0001"
}
```

Spec
```
[
  {
    "operation": "modify-default-beta",
    "spec": {
      // add a mapping for the boolean to string conversion
      "strMapping": {
        "DF-0001": "DF_TICKET_1",
        "DFE-0001": "DFE_TICKET_1",
        "DFS-0001": "DFS_TICKET_1",
        "DF-0002": "DF_TICKET_2",
        "DFE-0002": "DFE_TICKET_2",
        "DFS-0002": "DFS_TICKET_2"
      },
      // split the TicketNumber string
      "tickets": "=split(',',@(1,TicketNumber))"
    }
  },
  {
    "operation": "shift",
    "spec": {
      "tickets": {
        "*": { // array index
          "*": { // ticket value
            // for each ticket string value, look it up in the strMapping
            // and write it to a TicketNumber array
            "@(3,strMapping.&)": "TicketNumber[&2]"
          }
        }
      }
    }
  },
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      // glue the array back into a String
      "TicketNumber": "=join(',',@(1,TicketNumber))"
    }
  }
]
```

Produces Output
```
{
  "TicketNumber" : "DF_TICKET_1,DFE_TICKET_1,DFS_TICKET_1"
}
```

**Comment by ramuece09** [comment]
Above one is produces "Null" output. This type of approach is like tightly coupled one. What I was expected Like if I have retrieve the Value from Database as a HashMap and I can refer the HashMap in the Spec and Change the Values.

```
Map<String, Object> hmap = new HashMap<>();
			hmap.put("DF-0001","DF_TICKET_1");
			hmap.put("DFE-0001","DFE_TICKET_1");
			hmap.put("DFS-0001","DFS_TICKET_1");
			hmap.put("DF-0002","DF_TICKET_2");
			hmap.put("DFE-0002","DFE_TICKET_2");
			hmap.put("DFS-0002","DFS_TICKET_2");
```

Object transformedOutput = chainr.transform(inputJSON, hmap);

**Comment by milosimpson** [comment]
So, there is a thing you can do, but it isn't testable on the Demo page.

It is possible to pass a "Context" to the Transform, and have the Modify spec reference it to do lookups.

We use it at BV to "decorate" multilingual labels.

See the tests for how to use it
* https://github.com/bazaarvoice/jolt/blob/master/jolt-core/src/test/resources/json/modifier/simpleLookup.json   and the other "Lookup" test fixutures.
* the Test class https://github.com/bazaarvoice/jolt/blob/master/jolt-core/src/test/java/com/bazaarvoice/jolt/ModifierTest.java#L141

**Comment by ramuece09** [comment]
I was trying with your last spec which expects the below output 
```
{
  "TicketNumber" : "DF_TICKET_1,DFE_TICKET_1,DFS_TICKET_1"
}
```
But It was giving null. Can you please guide me?

**Comment by ramuece09** [comment]
I can see the Split is not working properly. In **tickets = ","**  only seeing while debugging. so its returns null as output. Please help me to fix this.

**Comment by ramuece09** [comment]
Got null because of lower version. Changed version to 0.1.1 and works like a charm. You're always a superhero @milosimpson

**Comment by DanFServ** [comment]
Hello, I have some trouble arranging an array with "Content"{}. My input is a one level array with several elements:
"account": [
    {
   <field content>
    }
[...]
]
My shift command in the spec looks like this:
      "account": {
        "*": {
          "accountTypeid": "account.accountTypeid",
          "accountCurrency": "account.accountCurrency",
          "billingLevel": "account.billingLevel",
          "receiverCountry": "account.receiverCountry",
          "statementType": "account.statementType",
          "statementGeneration": "account.statementGeneration",
          "annualFeeDueDate": "account.annualFeeDueDate",
          "calendarType": "account.calendarType",
          "paymentReference": "account.paymentReference",
          "bankName": "account.payable.bankName"
        }
      }
    }

My output is ok, although nested.

  "account" : {
    "accountTypeid" : [ "170", "170", "493", "493" ],
    "accountCurrency" : [ "EUR", "JPY", "EUR", "JPY" ],
    "billingLevel" : [ "001", "001", "001", "001" ],
    "receiverCountry" : [ "040", "040", "040", "040" ],
    "statementType" : [ "900", "900", "900", "900" ],
    "statementGeneration" : [ "001", "001", "001", "001" ],
    "annualFeeDueDate" : null,
    "calendarType" : null,
    "paymentReference" : [ "75101998", "75101998", "75101998", "75101998" ],
    "payable" : {
      "bankName" : [ "FirstBank", "FirstBank", "FirstBank", "FirstBank" ]
    }
  }

If I use Content, with "account" : "account" followed by content, the whole source is copied over, and my target structure is discarded.

**Comment by DanFServ** [comment]
I have a similar arranging issue. Spec:
      "account": {
        "*": {
          "accountTypeid": "account.accountTypeid",
          "accountCurrency": "account.accountCurrency",
          "billingLevel": "account.billingLevel",
          "receiverCountry": "account.receiverCountry",
          "statementType": "account.statementType",
          "statementGeneration": "account.statementGeneration",
          "annualFeeDueDate": "account.annualFeeDueDate",
          "calendarType": "account.calendarType",
          "paymentReference": "account.paymentReference",
          "bankName": "account.payable.bankName"
        }
      }
output:
  "account" : {
    "accountTypeid" : [ "170", "170", "493", "493" ],
    "accountCurrency" : [ "EUR", "JPY", "EUR", "JPY" ],
    "billingLevel" : [ "001", "001", "001", "001" ],
    "receiverCountry" : [ "040", "040", "040", "040" ],
    "statementType" : [ "900", "900", "900", "900" ],
    "statementGeneration" : [ "001", "001", "001", "001" ],
    "annualFeeDueDate" : null,
    "calendarType" : null,
    "paymentReference" : [ "75101998", "75101998", "75101998", "75101998" ],
    "payable" : {
      "bankName" : [ "FirstBank", "FirstBank", "FirstBank", "FirstBank" ]
    }
  }

I need an array of jsons, not a nested one.
