### ISSUE TITLE
filter and transform array

### ISSUE THREAD

**Issue by dbazim** [bazaarvoice/jolt#670]
My goal is to split array to two arrays by condition and apply different transformation to those two arrays.
~~~json
{
  "characteristic": [
    {
      "name": "Unit",
      "value": "South West Cor^porate",
      "id": "123",
      "valueId": "456"
    },
    {
      "name": "Business Unit",
      "value": "London South West Cor^porate",
      "id": "333",
      "valueId": "43556"
    },
    {
      "name": "Contract Term",
      "value": "Contract Term balue",
      "id": "54543",
      "valueId": "767656"
    }
  ]
}
~~~

my transformation  is

~~~json
[
  {
    "operation": "shift",
    "spec": {
      "characteristic": {
        "*": {
          "name": {
            "Contract Term": {
              "@2": "orderTerm[]"
            },
            "*": {
              "@2": "characteristic[]"
            }
          }
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "characteristic": {
        "*": {
          "id": "characteristic.[&1].pocId",
          "valueId": "characteristic.[&1].pocValueId",
          "*": "characteristic.[&1].&"
        }
      },
      "*": "&"
    }
  }
]
~~~

the result looks like that
~~~json
{
  "characteristic" : [ {
    "name" : "Unit",
    "value" : "South West Cor^porate",
    "pocId" : "123",
    "pocValueId" : "456"
  }, {
    "name" : "Business Unit",
    "value" : "London South West Cor^porate",
    "pocId" : "333",
    "pocValueId" : "43556"
  } ],

  "orderTerm" : [ {
    "name" : "Contract Term",
    "value" : "Contract Term balue",
    "id" : "54543",
    "valueId" : "767656"
  } ]
}
~~~

I'd like to perform the replacement "id"->"pocId" and "valueId"->"pocValueId" of resulting characteristic array in the same transformation as for splitting source characteristic array into orderTerm and characteristic array. How can that may be done?

**Comment by milosimpson** [comment]
Can't do it in one shift.

Fundamentally there needs to be two steps.   One to "fix the data" ("id"->"pocId" and "valueId"->"pocValueId"), and one to bucket the data (split into two arrays by condition).

It is ok to perform multiple operations.    That is the intended design pattern of Jolt:  It is better to have multiple smaller transform steps, than one single "step" that does everything and is very complicated / it's own programming language.
