### ISSUE TITLE
Behaviour of Shiftr spec for '*' transformations

### ISSUE THREAD

**Issue by jashgala** [bazaarvoice/jolt#675]
**Behavior of Shiftr spec:**
```
[
  {
    "operation": "shift",
    "spec": {
      "rating": {
        "*": "allRatings"
      }
    }
  }
]
```

**Case 1:**

Input:
```
{
  "rating": {
    "A": "A-value"
  }
}
```

Output:
```
{
  "allRatings" : "A-value"
}
```
**Case 2:**

Input:
```
{
  "rating": {
    "A": "A-value",
    "B": "B-value"
  }
}
```

Output:
```
{
  "allRatings" : [ "A-value", "B-value" ]
}
```

Both the outputs are of different data type (string vs array) depending on the number of values for * in the spec.

1. Is this intended?
2. How can we standardize the output (i.e. always array despite there being 1 value only)

**Comment by milosimpson** [comment]
#### Q : "Is this intended?"  Yes.   Not this isn't just the "*" wildcard.

Input 
```
{
  "a": "A",
  "b": "B"
}
```

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "a": "pants",
      "b": "pants"
    }
  }
]
```

Output
```
{
  "pants" : [ "A", "B" ]
}
```

If you have shift send to scalar values to the same location in the output what should it do?    
- First one wins?  Last one wins?  Json maps are meant to be unordered...
- Throw an exception?   If someone caught it what would they do?

#### Q: How can we standardize the output (i.e. always array despite there being 1 value only)

Use the "cardinality" operation  https://github.com/bazaarvoice/jolt/blob/master/jolt-core/src/main/java/com/bazaarvoice/jolt/CardinalityTransform.java

**Comment by jashgala** [comment]
Ah! Missed the cardinality transform! Thanks a lot!
