### ISSUE TITLE
Modify Overwrite only if input value not empty

### ISSUE THREAD

**Issue by knicklicht** [bazaarvoice/jolt#682]
I have following Input:

> {
> 
>     "date": "2018-10-07",
>     "time": "03:00",
>     "v1": "101040.00",
>     "v2": "90.00",
>     "v3": "",
> }

v1 through v3 need to be renamed and modified but only elements where the input value is not "" should be present in the output JSON:

> {
>     "date": "2018-10-07",
>     "time": "03:00",
>     "value1": "1010.40",
>     "value2": "9.00"
> }

My current approach:

> [
>   {
>     "operation": "shift",
>     "spec": {
>       "*": {
>         "": null,
>         "*": {
>           "@1": "&2"
>         }
>       }
>     }
>   },
>   {
>     "operation": "shift",
>     "spec": {
>       "date": "D",
>       "time": "T",
>       "v1":"value1",
>       "v2":"value2",
>       "v3":"value3"
>     }
>    },
>   {
>     "operation": "modify-overwrite-beta",
>     "spec": {
>       "value1": "=divide(@(1,value1),100)",
>       "value2": "=divide(@(1,value2),10)",
>       "value3": "=doubleSum(@(1,value3),-100))",
>     }
> }
> ]

But this result contains an entry for "value3":

> {
>   "date": "2018-10-07",
>   "time": "03:00",
>   "value1": 1010.40,
>   "value2": 9.00,
>   "value3":-100.00
> }

Can I somehow remove the entries which where empty in the input?

**Comment by milosimpson** [comment]
Wow.   First usage of a feature outside of BV.

See https://github.com/bazaarvoice/jolt/releases/tag/jolt-0.0.22  

```
Additionally the "?" character can suppress the modify operation, to only operate if the key/index exists

    "key?": "..." ? means only act if input contains that key/index
```

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "*": { // key 
        "": null,
        "*": {
          "$": "&2"
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "date": "D",
      "time": "T",
      "v1": "value1",
      "v2": "value2",
      "v3": "value3"
    }
  }
  ,
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "value1": "=divide(@(1,value1),100)",
      "value2": "=divide(@(1,value2),10)",

     // the trailing "?" means only act "modify-overwrite" if the key "value3" exists in the input.
      "value3?": "=doubleSum(@(1,value3),-100)"
    }
 }
]

```
