### ISSUE TITLE
Difficulty in converting sibling JSON element as an array element

### ISSUE THREAD

**Issue by bhushanibm** [bazaarvoice/jolt#685]
I have my input json which is pasted below

I have my input json which is pasted below

Input JSON :-
```
{
  "eventbatch": [
    {
      "version": "1",
      "channel": "",
      "events": [
        {
          "code": "shipmentModified",
          "timestamp": "2018-08-30T00:45:40-0400",
          "version": "1",
          "attributes": [
            {
              "name": "shipmentKey",
              "value": "201808300045402163057816",
              "type": "String",
              "isSync": false
            },
            {
              "name": "shipmentNo",
              "value": "111936351",
              "type": "String",
              "isSync": false
            },
            {
              "name": "status",
              "value": "1100.70.06.10",
              "type": "String",
              "isSync": false
            },
            {
              "name": "trackingNo",
              "value": "",
              "type": "String",
              "isSync": false
            },
            {
              "name": "enterprise",
              "value": "RETAIL",
              "type": "String",
              "isSync": false
            },
            {
              "name": "requestedDeliveryDate",
              "value": "2018-10-03T00:00:00-0400",
              "type": "Time",
              "isSync": false
            }
          ],
          "source": null
        },
        {
          "code": "shipmentLine",
          "version": "1",
          "attributes": [
            {
              "name": "shipmentKey",
              "value": "201808300045402163057816",
              "type": "String",
              "isSync": false
            },
            {
              "name": "shipmentLineKey",
              "value": "201808300045402163057784",
              "type": "String",
              "isSync": false
            },
            {
              "name": "productID",
              "value": "Dusters-0843",
              "type": "String",
              "isSync": false
            },
            {
              "name": "productDesc",
              "value": "LD Dusters-0843 Core10 Galactic Label4 Depends author7 Super sticky material8  Windows 7 Low Outdoor Super3 D-ManufacturerName-0806 I-Environmental-0047 G-Color-1079 Q-Brand-3290",
              "type": "String",
              "isSync": false
            },
            {
              "name": "productClass",
              "value": " ",
              "type": "String",
              "isSync": false
            }
          ]
        },
        {
          "code": "shipmentLine",
          "version": "1",
          "attributes": [
            {
              "name": "shipmentKey",
              "value": "201808300045402163057816",
              "type": "String",
              "isSync": false
            },
            {
              "name": "shipmentLineKey",
              "value": "201808300045402163057785",
              "type": "String",
              "isSync": false
            },
            {
              "name": "productID",
              "value": "Dusters-0313",
              "type": "String",
              "isSync": false
            },
            {
              "name": "productDesc",
              "value": "LD Dusters-0313 Core13 Huge Label3 Yes author4  kind of sticky material2  Windows Vista Tall Outdoor Super D-ManufacturerName-0625 E-Environmental-0044 G-Color-0876 K-Brand-4152",
              "type": "String",
              "isSync": false
            }
          ],
          "x1Id": null,
          "source": null
        },
        {
          "code": "shipmentLine",
          "version": "1",
          "attributes": [
            {
              "name": "shipmentKey",
              "value": "201808300045402163057816",
              "type": "String",
              "isSync": false
            },
            {
              "name": "shipmentLineKey",
              "value": "201808300045402163057786",
              "type": "String",
              "isSync": false
            },
            {
              "name": "productID",
              "value": "Dusters-0446",
              "type": "String",
              "isSync": false
            },
            {
              "name": "productDesc",
              "value": "LD Dusters-0446 Core1 Galactic Label9 Depends author4  kind of sticky material1  Windows Vista Large Outdoor None4 M-ManufacturerName-0187 L-Environmental-0072 I-Color-1322 V-Brand-6366",
              "type": "String",
              "isSync": false
            },
            {
              "name": "productClass",
              "value": " ",
              "type": "String",
              "isSync": false
            },
            {
              "name": "unitOfMeasure",
              "value": "EACH",
              "type": "String",
              "isSync": false
            }
          ]
        }
      ]
    }
  ]
}
```

I need to convert it to output JSON which is pasted below
```
[
  {
    "shipmentKey":"201808300045402163057816",
    "shipmentNo":"111936351",
    "status":"1100.70.06.10",
    "trackingNo":"",
    "enterprise":"RETAIL",
    "requestedDeliveryDate":"2018-10-03T00:00:00-0400",
    "shipmentLineKey":"201808300045402163057784",
    "productID":"Dusters-0843",
    "productDesc":"LD Dusters-0843 Core10 Galactic Label4 Depends author7 Super sticky material8  Windows 7 Low Outdoor Super3 D-ManufacturerName-0806 I-Environmental-0047 G-Color-1079 Q-Brand-3290",
    "productClass":""
  },
 {
   "shipmentKey":"201808300045402163057785",
   "shipmentNo":"111936351",
   "status":"1100.70.06.10",
       "trackingNo":"",
    "enterprise":"RETAIL",
    "shipmentLineKey":"201808300045402163057784",
     "productID":"Dusters-0313",
    "productDesc":"LD Dusters-0313 Core13 Huge Label3 Yes author4  kind of sticky material2  Windows Vista Tall Outdoor Super D-ManufacturerName-0625 E-Environmental-0044 G-Color-0876 K-Brand-4152"
 },
 {
   "shipmentKey":"201808300045402163057786",
   "shipmentNo":"111936351",
   "status":"1100.70.06.10",
       "trackingNo":"",
    "enterprise":"RETAIL",
    "shipmentLineKey":"201808300045402163057784",
    "productID":"Dusters-0446",
    "productDesc":"LD Dusters-0446 Core1 Galactic Label9 Depends author4  kind of sticky material1  Windows Vista Large Outdoor None4 M-ManufacturerName-0187 L-Environmental-0072 I-Color-1322 V-Brand-6366",
    "productClass":"",
    "unitOfMeasure":"EACH"
 }
]
```

I tried below spec and I am getting the below output. Any idea what I am doing wrong in the spec ?

```
[
  {
    "operation": "shift",
    "spec": {
      "eventbatch": {
        "*": {
          "events": {
            "*": {
              "code": {
                "shipmentLine": {
                  // if we matched code : orderLineStatus
                  //  reset back up the tree to the attributes array
                  "@(2,attributes)": {
                    "*": {
                      // check the name, if name == orderLineKey
                      //  route that differently than the rest
                      "name": {
                        "shipmentKey": {
                          "@2": {
                            // &10 here references  back to the array element 
                            //  input "eventbatch" is currently matched 
                            "value": "shipment[&10].shipmentKey"
                          }
                        },
                        "*": {
                          "@2": {
                            "value": "shipment[&10].lineStatus[0].@(1,name)"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
]
```
Any ideas what going wrong here ?

**Comment by bhushanibm** [comment]
I was able to come up with below script but it does not add attributes of shipmentModified in to shipmentLine. This capability is missing. Any help here ?

Spec 
[
  {
    // get rid of the inner "events" array by pivoting
    //  the data based on the "code"
    "operation": "shift",
    "spec": {
      "eventbatch": {
        "*": {
          "events": {
            "*": {
              "code": {
                "*": {
                  "@2": "eventbatch2[&5].&1"
                }
              }
            }
          }
        }
      }
    }
  },
  {
    // get rid of the inner "attributes" arrays by pivoting
    //  the data based on the "name"
    "operation": "shift",
    "spec": {
      "eventbatch2": {
        "*": { // array index
          "*": { // orderModified, orderLine, orderLineStatus
            //
            // process the attributes array
            "attributes": {
              "*": {
                "@value": "eventbatch3[&4].shipment1.attributes.&1"
              }
            },
            // pass the rest of the data thru
            "*": "eventbatch3[&2].&1.&"
          }
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "eventbatch3": {
        "*": {
          "shipmentLine": {
            "*": {
              "attributes": {
                "*": {
                  "@value": "[&3].@name"
                }
              }
            }
          }
        }
      }
    }
  }
]

Output 
[ {
  "shipmentKey" : "201808300045402163057816",
  "shipmentLineKey" : "201808300045402163057784",
  "productID" : "Dusters-0843",
  "productDesc" : "LD Dusters-0843 Core10 Galactic Label4 Depends author7 Super sticky material8 Windows 7 Low Outdoor Super3 D-ManufacturerName-0806 I-Environmental-0047 G-Color-1079 Q-Brand-3290",
  "productClass" : " "
}, {
  "shipmentKey" : "201808300045402163057816",
  "shipmentLineKey" : "201808300045402163057785",
  "productID" : "Dusters-0313",
  "productDesc" : "LD Dusters-0313 Core13 Huge Label3 Yes author4 kind of sticky material2 Windows Vista Tall Outdoor Super D-ManufacturerName-0625 E-Environmental-0044 G-Color-0876 K-Brand-4152"
}, {
  "shipmentKey" : "201808300045402163057816",
  "shipmentLineKey" : "201808300045402163057786",
  "productID" : "Dusters-0446",
  "productDesc" : "LD Dusters-0446 Core1 Galactic Label9 Depends author4 kind of sticky material1 Windows Vista Large Outdoor None4 M-ManufacturerName-0187 L-Environmental-0072 I-Color-1322 V-Brand-6366",
  "productClass" : " ",
  "unitOfMeasure" : "EACH"
} ]

**Comment by bhushanibm** [comment]
@milosimpson Any help on the jolt spec for this usecase ?

**Comment by milosimpson** [comment]
So your input is 4 items in an array, and your output is 3 items in an array.

It seems like the bulk of the data in the ouput is from the "shipmentLine", and for each shipment line you are trying to pull some data from the "shipmentModified" entry.

A) Is there always going to be only one shipmentModified?
B) Is it always going to be the first thing in the input array, or can it be anywhere in the list?

**Comment by bhushanibm** [comment]
It will be only one shipmentModified. Yes it may be first element too. We can make that assumption

**Comment by bhushanibm** [comment]
Is it possible to get rid of some attributes while it is merging shipmentModified in to shipmentLine ?

**Comment by milosimpson** [comment]
Yeah, it means add 2 steps in the middle.
1) doing the "value": "[&3].@(1,name)" pivot logic in it's own step, then 
2) do a "remove" operation or another "shift" where you send things you don't want to null.

Then do the merge, and accumulate.

**Comment by bhushanibm** [comment]
@milosimpson I tried pivoting but it does not seem to work. Can you please help us to show some elements can be removed. Below is one of the script tried after second step, but it does not seem to copy the rest of elements

[
  {
    "operation": "shift",
    "spec": {
      "eventbatch2": {
        "shipmentModified": {
          "*": {
            "@(attributes)": {
              "*": {
                "name": {
                  "releaseNo": "",
                  "*": "111"
                }
              }
            }
          }
        }
      }
    }
  }
]
