### ISSUE TITLE
Requesting help to create jolt spec for nested array scenario.

### ISSUE THREAD

**Issue by ksrikanthh1990** [bazaarvoice/jolt#687]
Hello, I wanted to seek help from jolt team to create a spec for my below scenario which i am unable to create one. Can you please help 

json input -

{
   "metadata":{
      "total_count":1,
      "result_count":1,
      "offset":1
   },
   "customerInfo":[
      {
         "customerHeaderInfo":{
            "id":"1"
         },
         "customerListInfo":{
            "number":"1",
            "status":"active",
            "customerDetail":{
               "customerNumber":"1",
               "customerStatus":"active"
            }
         },
         "customerAddress":[
            {
               "type":"home",
               "city":"city1",
               "state":"state1"
            },
            {
               "type":"office",
               "city":"city2",
               "state":"state2"
            }
         ]
      },
	  
	  {
         "customerHeaderInfo":{
            "id":"2"
         },
         "customerListInfo":{
            "number":"2",
            "status":"active",
            "customerDetail":{
               "customerNumber":"1",
               "customerStatus":"active"
            }
         },
         "customerAddress":[
            {
               "type":"home",
               "city":"city1",
               "state":"state1"
            },
            {
               "type":"office",
               "city":"city2",
               "state":"state2"
            }
         ]
      }
   ]
}
json output -

{
   "customerInfo":[
      {
         "id":"1",
         "customerList":[
            {
               "customerNumber":"1",
               "customerStatus":"active",
               "customerAddress":[
                  {
                     "city":"test1",
                     "state":"test2"
                  },
                  {
                     "city":"test3",
                     "state":"test4"
                  }
               ]
            },
            {
               "customerNumber":"2",
               "customerStatus":"active",
               "customerAddress":[
                  {
                     "type":"home",
                     "city":"city1",
                     "state":"state2"
                  },
                  {
                     "type":"office",
                     "city":"city2",
                     "state":"state2"
                  }
               ]
            }
         ]
      }
   ]
}

**Comment by milosimpson** [comment]
1. Please format your input, it is a mess right now.
2. What have you tried, what spec gets you the closest.   This request is basically just a "Do My Work For" request.
