### ISSUE TITLE
google analytics JOLT spec help

### ISSUE THREAD

**Issue by shrikant-pa** [bazaarvoice/jolt#690]
I am trying to play around on JOLT demo app for converting a google analytics json response in a proper format. I am finding it very difficult to create this spec. I have created a spec to flatten out everything but not able to move beyond that. 

Any help would be appreciated. 

Input JSON 
---
`{
  "reports": [
    {
      "columnHeader": {
        "dimensions": [
          "ga:dimension5",
          "ga:dimension2"
        ],
        "metricHeader": {
          "metricHeaderEntries": [
            {
              "name": "ga:sessions",
              "type": "INTEGER"
            },
            {
              "name": "ga:newUsers",
              "type": "INTEGER"
            },
            {
              "name": "ga:users",
              "type": "INTEGER"
            },
            {
              "name": "ga:bounceRate",
              "type": "PERCENT"
            },
            {
              "name": "ga:uniqueDimensionCombinations",
              "type": "INTEGER"
            },
            {
              "name": "ga:sessionDuration",
              "type": "TIME"
            },
            {
              "name": "ga:organicSearches",
              "type": "INTEGER"
            }
          ]
        }
      },
      "data": {
        "rows": [
          {
            "dimensions": [
              "VIDPPPPPPP4-9fe1-983a-161d-YYYaedd87a06",
              "SIDXXXXXX41-ae3b-d611-7fab-6900000116a3"
            ],
            "metrics": [
              {
                "values": [
                  "1",
                  "1",
                  "1",
                  "0.0",
                  "1",
                  "22.0",
                  "0"
                ]
              }
            ]
          },
          {
            "dimensions": [
              "VIDXXXXXXX8-abb9-46cc-32a8-6YYYY628e97c",
              "SIDYYYYY324-5ac8-XXXX-0908-9f211111ef9d"
            ],
            "metrics": [
              {
                "values": [
                  "1",
                  "1",
                  "1",
                  "0.0",
                  "1",
                  "1087.0",
                  "1"
                ]
              }
            ]
          }
        ]
      }
    }
  ]
}`

Expected JSON 
--- 

{
  "row0": {
    "ga_dimension5": "VIDPPPPPPP4-9fe1-983a-161d-YYYaedd87a06",
    "ga_dimension2": "SIDXXXXXX41-ae3b-d611-7fab-6900000116a3",
    "ga_sessions": "1",
    "ga_newUsers": "1",
    "ga_users": "1",
    "ga_bounceRate": "0.0",
    "ga_uniqueDimensionCombinations": "1",
    "ga_sessionDuration": "22.0",
    "ga_organicSearches": "0.0"
  },
  "row1": {
    "ga_dimension5": "VIDXXXXXXX8-abb9-46cc-32a8-6YYYY628e97c",
    "ga_dimension2": "SIDYYYYY324-5ac8-XXXX-0908-9f211111ef9d",
    "ga_sessions": "1",
    "ga_newUsers": "1",
    "ga_users": "1",
    "ga_bounceRate": "0.0",
    "ga_uniqueDimensionCombinations": "1",
    "ga_sessionDuration": "1087.0",
    "ga_organicSearches": "1"
  }
}

**Comment by shrikant-pa** [comment]
Ok. I was able to do this. 

 [
   {
     "operation": "shift",
     "spec": {
       "reports": {
         "*": {
           "data": {
             "rows": {
               "*": {
                 "@(dimensions[0])": "rows&.@(4,columnHeader.dimensions[0])",
                 "@(dimensions[1])": "rows&.@(4,columnHeader.dimensions[1])",
                 "@(metrics[0].values[0])": "rows&.@(4,columnHeader.metricHeader.metricHeaderEntries[0].name)",
                 "@(metrics[0].values[1])": "rows&.@(4,columnHeader.metricHeader.metricHeaderEntries[1].name)",
                 "@(metrics[0].values[2])": "rows&.@(4,columnHeader.metricHeader.metricHeaderEntries[2].name)",
                 "@(metrics[0].values[3])": "rows&.@(4,columnHeader.metricHeader.metricHeaderEntries[3].name)",
                 "@(metrics[0].values[4])": "rows&.@(4,columnHeader.metricHeader.metricHeaderEntries[4].name)",
                 "@(metrics[0].values[5])": "rows&.@(4,columnHeader.metricHeader.metricHeaderEntries[5].name)",
                 "@(metrics[0].values[6])": "rows&.@(4,columnHeader.metricHeader.metricHeaderEntries[6].name)"
               }
             }
           }
         }
       }
     }
  }
 ]

**Comment by milosimpson** [comment]
A more generic / less hardcoded indices version.

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "reports": {
        "*": {
          "data": {
            "rows": {
              "*": {
                // write the value of each element of the dimenstions array
                //  to value of the columnHeader dimenstion of the same index
                "dimensions": {
                  "*": "rows&2.@(5,columnHeader.dimensions[&])"
                },
                "metrics": {
                  "0": {
                    // loop over all the values in metrics[0]
                    //  and write its value to the columnHeader.metricHeader.metricHeaderEntries 
                    //  of the same index
                    "values": {
                      "*": "rows&4.@(7,columnHeader.metricHeader.metricHeaderEntries[&].name)"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
]
```
