### ISSUE TITLE
How can i make the function about substract available

### ISSUE THREAD

**Issue by niernier007** [bazaarvoice/jolt#692]
I want to use the function "doubleSubtract". I test on the flowing website:
http://jolt-demo.appspot.com/#modify-mathFunctions
The title of the website is "Jolt Transform Demo Using v0.1.1" , but when i click the link "Math Functions", thers is no function about substract.  How can i make the function about substract available?

**Comment by milosimpson** [comment]
Ah, so doubleSubtract will only subtract Double values.

There is an issue with the Demo Site client side Json validation, that if you write
```
  "a" : 10.0  // to make that be a Double
```
it changes it to 
```
  "a" : 10  // which is not a double
```

So for testing on the demo site, make all of your Doubles have a non-zero "dot" value.

Example
```
Input
{
  "a": 10.1,
  "b": 5.1
}

Spec
[
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "Subtract": "=doubleSubtract(@(1,a),@(1,b))"
    }
  }
]

Output
{
  "a" : 10.1,
  "b" : 5.1,
  "Subtract" : 5.0
}
```

```

**Comment by niernier007** [comment]
Thank you, you solved my problem @milosimpson
