### ISSUE TITLE
Nested json array with a twist

### ISSUE THREAD

**Issue by shivam2103** [bazaarvoice/jolt#707]
Hello team , I am trying to create a spec for the below mentioned input and output json and I am unable to create one. Can you please help to solve it -

Also attached Spec which have tried further.

---------Input ---------
```
{
  "level1": [
    {
      "market_price_point": {        
        "code1": "428",        
        "code2": "405"
      },
      "level2": [
        {
          "dates": {
            "bdate": "2018-01-07",
            "edate": "2018-11-07"
			},
          "pricing": {
            "future": {              
              "price": 11,
              "unit": 12
              
            },
            "basis": {
              "price": 13,
              "unit": 14
             },            
            "flat": {
              "price": 15,
              "unit": 16
            }
          }
        },
		{
          "dates": {
            "bdate": "2018-02-07",
            "edate": "2018-12-07"
			},
          "pricing": {
            "future": {              
              "price": 21,
              "unit": 22
              
            },
            "basis": {
              "price": 23,
              "unit": 24
             },            
            "flat": {
              "price": 25,
              "unit": 26
            }
          }
        }
      ]
    },
	
	    {
      "market_price_point": {        
        "code1": "429",        
        "code2": "406"
      },
      "level2": [
        {
          "dates": {
            "bdate": "2018-01-08",
            "edate": "2018-11-08"
			},
          "pricing": {
            "future": {              
              "price": 12,
              "unit": 13
              
            },
            "basis": {
              "price": 14,
              "unit": 15
             },            
            "flat": {
              "price": 16,
              "unit": 17
            }
          }
        },
		{
          "dates": {
            "bdate": "2018-02-08",
            "edate": "2018-12-08"
			},
          "pricing": {
            "future": {              
              "price": 22,
              "unit": 23
              
            },
            "basis": {
              "price": 24,
              "unit": 25
             },            
            "flat": {
              "price": 26,
              "unit": 27
            }
          }
        }
      ]
    }
  ]
}
```
------Jolt Spec -----------
```
[
  {
    "operation": "shift",
    "spec": {
      "level1": {
        "*": {
          "market_price_point": {
            "code1": "LocBid[#].Location.Name"
          },
          "level2": {
            "*": {
              "dates": {
                "bdate": "LocBid[#].Location.startDate",
                "edate": "LocBid[#].Location.endDate"
              },
              "pricing": {
                "future": {
                  "price": "LocBid[#].Pricing.futuresPrice",
                  "unit": "LocBid[#].Pricing.futuresUnit"
                },
                "basis": {
                  "price": "LocBid[#].Pricing.basisPrice",
                  "unit": "LocBid[#].Pricing.basisUnit"
                },
                "flat": {
                  "price": "LocBid[#].Pricing.flatPrice",
                  "unit": "LocBid[#].Pricing.flatUnit"
                }
              }
            }
          }
        }
      }
    }
  }
]
```
-------Jolt Desired Ouptput --------
```
{  
   "delLoc":[  
      {  
         "LocBid":[  
            {  
               "Location":{  
                  "Name":"428"
               },
               "Pricing":{  
                  "futuresPrice":11,
                  "futuresUnit":12,
                  "basisPrice":13,
                  "basisUnit":14,
                  "flatPrice":15,
                  "flatUnit":16
               }
            }
         ],
         "startDate":"2018-01-07",
         "endDate":"2018-11-07"
      },
      {  
         "LocBid":[  
            {  
               "Location":{  
                  "Name":"428"
               },
               "Pricing":{  
                  "futuresPrice":21,
                  "futuresUnit":22,
                  "basisPrice":23,
                  "basisUnit":24,
                  "flatPrice":25,
                  "flatUnit":26
               }
            }
         ],
         "startDate":"2018-01-07",
         "endDate":"2018-11-07"
      },
      {  
         "LocBid":[  
            {  
               "Location":{  
                  "Name":"429"
               },
               "Pricing":{  
                  "futuresPrice":12,
                  "futuresUnit":13,
                  "basisPrice":14,
                  "basisUnit":15,
                  "flatPrice":16,
                  "flatUnit":17
               }
            },
            {  
               "Location":{  
                  "Name":"428"
               },
               "Pricing":{  
                  "futuresPrice":22,
                  "futuresUnit":23,
                  "basisPrice":24,
                  "basisUnit":25,
                  "flatPrice":26,
                  "flatUnit":27
               }
            }
         ],
         "startDate":"2018-01-08",
         "endDate":"2018-11-08"
      },
      {  
         "LocBid":[  
            {  
               "Location":{  
                  "Name":"428"
               },
               "Pricing":{  
                  "futuresPrice":22,
                  "futuresUnit":23,
                  "basisPrice":24,
                  "basisUnit":25,
                  "flatPrice":26,
                  "flatUnit":27
               }
            }
         ],
         "startDate":"2018-02-07",
         "endDate":"2018-12-07"
      }
   ]
}
```

**Comment by milosimpson** [comment]
This is a standard "Merging of Nested Arrays", but I think with a twist of having to "fix" the "market_price_point" data first.

This spec, gets the data into the "outer[]/inner[]" format, which should then be straight forward to finish up.

See examples https://github.com/bazaarvoice/jolt/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Merging+Arrays%22+


Spec
```
[
  {
    // fix / manually convert market_price_point
    //  into a zero based array, cause it looks
    //  like you want "code1" to tie to level2[0]'s
    //  data, and "code2" to goto level2[1]'s data.
    "operation": "shift",
    "spec": {
      "level1": {
        "*": {
          "market_price_point": {
            "code1": "level1[&2].mpp[0]",
            "code2": "level1[&2].mpp[1]",
            "code3": "level1[&2].mpp[2]",
            "code4": "level1[&2].mpp[3]"
            // add more if needed
          },
          "level2": "level1[&1].level2"
        }
      }
    }
  },
  {
    // now for each level2 item, referenc/pull
    //  the approriate market_price_point value
    //  using the array index.
    "operation": "shift",
    "spec": {
      "level1": {
        "*": {
          "level2": {
            "*": {
              "@(2,mpp[&])": "outer[&3].inner[&1].Name",
              "*": "outer[&3].inner[&1].&"
            }
          }
        }
      }
    }
  }
]
```

**Comment by shivam2103** [comment]
Hi MiloSimpson,

Thanks for your response and sharing the spec.

I guess there is some naming convention that i need to correct in my output what i am expecting.

Before that will clear two things for creating the spec : 
a. The StartDate and EndDate has to moved out from level2 array and should be kept in level1 array. And code1 and code2 has to be moved into inner object.
b. Is there a way to do filtering between dates. Suppose there are two level1 object's with same bdate and eDate , can we put the level2 two object's of both in single array? If there is a way, can you include that too while creating the spec.

Please find the below output :

{  
   "level1":[  
      {  
         "level2":[  
            {  
               "Location":{  
                  "code1":"428"
               },
               "Pricing":{  
                  "futuresPrice":11,
                  "futuresUnit":12,
                  "basisPrice":13,
                  "basisUnit":14,
                  "flatPrice":15,
                  "flatUnit":16
               }
            }
         ],
         "bdate":"2018-01-07",
         "edate":"2018-11-07"
      },
      {  
         "level2":[  
            {  
               "Location":{  
                  "Name":"428"
               },
               "Pricing":{  
                  "futuresPrice":21,
                  "futuresUnit":22,
                  "basisPrice":23,
                  "basisUnit":24,
                  "flatPrice":25,
                  "flatUnit":26
               }
            }
         ],
         "bdate":"2018-01-07",
         "eDate":"2018-11-07"
      },
      {  
         "level2":[  
            {  
               "Location":{  
                  "Name":"429"
               },
               "Pricing":{  
                  "futuresPrice":12,
                  "futuresUnit":13,
                  "basisPrice":14,
                  "basisUnit":15,
                  "flatPrice":16,
                  "flatUnit":17
               }
            },
            {  
               "Location":{  
                  "Name":"428"
               },
               "Pricing":{  
                  "futuresPrice":22,
                  "futuresUnit":23,
                  "basisPrice":24,
                  "basisUnit":25,
                  "flatPrice":26,
                  "flatUnit":27
               }
            }
         ],
         "bdate":"2018-01-08",
         "eDate":"2018-11-08"
      },
      {  
         "level2":[  
            {  
               "Location":{  
                  "Name":"428"
               },
               "Pricing":{  
                  "futuresPrice":22,
                  "futuresUnit":23,
                  "basisPrice":24,
                  "basisUnit":25,
                  "flatPrice":26,
                  "flatUnit":27
               }
            }
         ],
         "bdate":"2018-02-07",
         "eDate":"2018-12-07"
      }
   ]
}

So, in the above output all are in the different level1 objects. Now will share you one more example where dates can be similar for two level2 different objects and we need the output in single level2 array object.

**Input** : Please note, i am sharing only two level1 objects but there will be n no of like these scenario's :

{
  "level1": [
    {
      "market_price_point": {        
        "code1": "428",        
        "code2": "405"
      },
      "level2": [
        {
          "dates": {
            "bdate": "2018-01-07",
            "edate": "2018-11-07"
			},
          "pricing": {
            "future": {              
              "price": 11,
              "unit": 12
              
            },
            "basis": {
              "price": 13,
              "unit": 14
             },            
            "flat": {
              "price": 15,
              "unit": 16
            }
          }
        },
		{
          "dates": {
            "bdate": "2018-01-07",
            "edate": "2018-11-07"
			},
          "pricing": {
            "future": {              
              "price": 21,
              "unit": 22
              
            },
            "basis": {
              "price": 23,
              "unit": 24
             },            
            "flat": {
              "price": 25,
              "unit": 26
            }
          }
        }
      ]
    }
  ]
}

**Expected Output :**
{  
   "level1":[  
      {  
         "level2":[  
            {  
               "Location":{  
                  "code1":"428"
               },
               "Pricing":{  
                  "futuresPrice":11,
                  "futuresUnit":12,
                  "basisPrice":13,
                  "basisUnit":14,
                  "flatPrice":15,
                  "flatUnit":16
               }
            },
			  {
               "Location":{  
                  "code1":"428"
               },
               "Pricing":{  
                  "futuresPrice":21,
                  "futuresUnit":22,
                  "basisPrice":23,
                  "basisUnit":24,
                  "flatPrice":25,
                  "flatUnit":26
               }
            }
         ],
         "bdate":"2018-01-07",
         "edate":"2018-11-07"
      }
   ]
}
