### ISSUE TITLE
adding element to array, but element is not part loop

### ISSUE THREAD

**Issue by prasadrao82** [bazaarvoice/jolt#708]
Hi, I am trying to add an element to array, but this element is not part of the iteration,

for example: 

input: 
```
{
  "groups": [],
  "doors": [
    {
      "serial": "12343",
      "caqi-type": "121",
      "location": {
        "street": "s1",
        "city": "dsd",
        "height": 43.82746563,
        "width": 41.16276735
      },
      "windows": [
        {
          "timestamp": 1531555200000,
          "type": "P",
          "value": 29.605948026672625,
          "unit": "inHg",
          "aqi": "n/a"
        },
        {
          "timestamp": 1531555200000,
          "type": "usaqi",
          "value": 18,
          "pollutant": "PM2.5"
        },
        {
          "timestamp": 1531555200000,
          "type": "caqi",
          "value": 18,
          "pollutant": "PM2.5"
        }
      ]
    }
  ]
}
```

Expected Output:
```
{
  "properties": {
    "deviceid": "12343",
    "devicetype": "121",
    "devicename": "aq",
    "date": "test",
    "messagetype": "Uplink",
    "deviceclass": "NA",
    "devicedescription": "ss"
  },
  "deviceinfo": [
    {
      "key": "P",
      "value": "29.605948026672625"
    },
    {
      "key": "usaqi",
      "value": "18"
    },
    {
      "key": "caqi",
      "value": "18"
    },
    {
      "key": "height",
      "value": "43.82746563"
    },
    {
      "key": "width",
      "value": "41.16276735"
    }
  ]
}
```
Used following jolt spec
```
[
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "doors": {
        "*": {
          "location": {
            "height": "=toString(@(1,height))",
            "width": "=toString(@(1,width))"
          },
          // loop thru all the elements gateways array
          "windows": {
            // loop thru all the elements things array
            "*": {
              "value": "=toString(@(1,value))"
            }
          }
        }
      }
    }
  },

  {
    "operation": "shift",
    "spec": {
      "doors": {
        // loop thru all the elements gateways array
        "*": {
          "serial": "properties.deviceid",
          "caqi-type": "properties.devicetype",
          "airqualityIndex": "properties.devicename",
          /** "location": {
             "height": {
               "$": "deviceinfo.[#4].key",
               "@": "deviceinfo.[#4].value"
             }
           },
           **/
          "windows": {
            // loop thru all the elements things array
            "*": {
              //"$": "deviceinfo.items[#2].Name",
              //"@": "deviceinfo.items[#2].Value"
              "type": "deviceinfo.[&1].key",
              "value": "deviceinfo.[&1].value"
                //  "[&1].value": "=toString",
                //"value": "=toString"
            }
          }
        }
      }
    }
  },


/**
  {
    "operation": "shift",
    "spec": {
      "gateways": {
        // loop thru all the elements gateways array
        "*": {
          "location": {
            "longitude": "deviceinfo.[0].key",
            "latitude": "deviceinfo.[0].value"
          }
        }
      }
    }
  },
**/

  {
    "operation": "default",
    "spec": {
      "properties": {
        "devicename": "aq",
        "devicedescription": "ss",
        "deviceclass": "NA",
        "messagetype": "Uplink",
        "date": "test"
      }
    }
  }
]
```

**Comment by milosimpson** [comment]
Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "doors": {
        "*": {
          "serial": "properties.deviceid",
          "caqi-type": "properties.devicetype",
          "airqualityIndex": "properties.devicename",
          //
          // pivot height and width into key 
          //  value pairs, but don't put them
          //  in an array yet, just leave them 
          //  as nested maps
          "location": {
            "height|width": {
              "$": "fixedHeightAndWidth.&1.key",
              "@": "fixedHeightAndWidth.&1.value"
            }
          },
          "windows": {
            "*": {
              // key/value the windows entries
              "type": "windows[&1].key",
              "value": "windows[&1].value"
            }
          }
        }
      }
    }
  },
  {
    // accumulate all the window array entries
    //  and the height/width "entries" into 
    //  a deviceinfo array
    "operation": "shift",
    "spec": {
      "properties": "properties", // pass thru
      "windows": {
        "*": "deviceinfo[]"
      },
      "fixedHeightAndWidth": {
        "*": "deviceinfo[]"
      }
    }
  },
  {
    // one shot at the end, toString
    //  all the "value" fields in deviceinfo
    "operation": "modify-overwrite-beta",
    "spec": {
      "deviceinfo": {
        "*": {
          "value": "=toString"
        }
      }
    }
  }
]
```

**Comment by prasadrao82** [comment]
Hi milosimpson, 

could you please help me out , if the input is multiple records instead of one, like 

input 

{
  "groups": [],
  "doors": [
    {
      "serial": "12343",
      "caqi-type": "121",
      "location": {
        "street": "s1",
        "city": "dsd",
        "height": 43.82746563,
        "width": 41.16276735
      },
      "windows": [
        {
          "timestamp": 1531555200000,
          "type": "P",
          "value": 29.605948026672625,
          "unit": "inHg",
          "aqi": "n/a"
        },
        {
          "timestamp": 1531555200000,
          "type": "usaqi",
          "value": 18,
          "pollutant": "PM2.5"
        },
        {
          "timestamp": 1531555200000,
          "type": "caqi",
          "value": 18,
          "pollutant": "PM2.5"
        }
      ]
    },
	  {
      "serial": "223232",
      "caqi-type": "16276735",
      "location": {
        "street": "s1",
        "city": "dsd",
        "height": 56.82746563,
        "width": 56.16276735
      },
      "windows": [
        {
          "timestamp": 1531555200000,
          "type": "P",
          "value": 42.605948026672625,
          "unit": "inHg",
          "aqi": "n/a"
        },
        {
          "timestamp": 1531555200000,
          "type": "usaqi",
          "value": 18,
          "pollutant": "PM2.5"
        },
        {
          "timestamp": 1531555200000,
          "type": "caqi",
          "value": 18,
          "pollutant": "PM2.5"
        }
      ]
    }
  ]
}

expected output :


{outdata:[{
  "properties": {
    "deviceid": "12343",
    "devicetype": "121",
    "devicename": "aq",
    "date": "test",
    "messagetype": "Uplink",
    "deviceclass": "NA",
    "devicedescription": "ss"
  },
  "deviceinfo": [
    {
      "key": "P",
      "value": "29.605948026672625"
    },
    {
      "key": "usaqi",
      "value": "18"
    },
    {
      "key": "caqi",
      "value": "18"
    },
    {
      "key": "height",
      "value": "43.82746563"
    },
    {
      "key": "width",
      "value": "41.16276735"
    }
  ]
}

 "properties": {
    "deviceid": "16276735",
    "devicetype": "121",
    "devicename": "aq",
    "date": "test",
    "messagetype": "Uplink",
    "deviceclass": "NA",
    "devicedescription": "ss"
  },
  "deviceinfo": [
    {
      "key": "P",
      "value": "42.605948026672625"
    },
    {
      "key": "usaqi",
      "value": "18"
    },
    {
      "key": "caqi",
      "value": "18"
    },
    {
      "key": "height",
      "value": "56.82746563"
    },
    {
      "key": "width",
      "value": "56.16276735"
    }
  ]
}
]
}

**Comment by prasadrao82** [comment]
could you please extend your support on this
