### ISSUE TITLE
Need to do multiple string functions

### ISSUE THREAD

**Issue by andrew-greiner** [bazaarvoice/jolt#709]
Good evening,
     Seems like a simple one. Just to do multiple string functions. I suspect I do multiple modify-overwrite-beta and so each operation, but wasn't certain.

INPUT
```
{
	"City": "Newark",
	"StateProvince": "New Jersey",
	"Country": "United States",
}
```

SPEC
```
[
  {
    "operation": "shift",
    "spec": {
      "City": "city",
      "StateProvince": "state",
      "Country": "country"
    }
  },
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "\\_id": "=concat(@(1,city),'-',@(1,state))"
    }
  }
]
```

HOPING FOR
```
{
	"city": "NEwark",
	"state": "New Jersey",
	"country": "United States",
	"_id": "newark-newjersey" **<<<<< spaces removed and to lower as well as concat (i'll settle for concat and tolower**
}
```

Thanks in advance

**Comment by milosimpson** [comment]
So you can do two passes of "modify".  One to do the concat and one to do a "=toLower".   

There isn't a function that removes / squashes white space.

**Comment by andrew-greiner** [comment]
> So you can do two passes of "modify". One to do the concat and one to do a "=toLower".
> 
> There isn't a function that removes / squashes white space.

Thanks Milo. Much appreciate you continued support. Maybe you should work on a chatbot that can do the transforms so you can take a break ;)
