### ISSUE TITLE
Question Flattening Name / Value pairs

### ISSUE THREAD

**Issue by smozely** [bazaarvoice/jolt#710]
Hi there, trying to use JOLT to map some data of this form... 

```
"custom_fields": [
  {
    "name": "source",
    "value": "PGLB"
  },
  {
    "name": "status",
    "value": "O"
  },
  {
    "name": "open_date",
    "value": "19/08/2015"
  }
]  
```

To the form ...
```
{
  "source": "PGLB",
  "status": "O",
  "open_date": "19/08/2015"
}
```

To then do more processing on it, but just struggling at the moment to figure out how I can combine the value of name as a key and the value of value as the value for that key.

Thanks BTW ... I've done 90% of what I need to do so far and its been pretty simple. Just this one tripping me up

**Comment by milosimpson** [comment]
Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "custom_fields": {
        "*": {
          "value": "@(1,name)"
        }
      }
    }
  }
]
```

**Comment by smozely** [comment]
Wow, now I see it, it makes complete sense (I was almost there) ... but I had "name" on the LHS.

Thanks
