### ISSUE TITLE
Output field value dependant on multiple (sometimes present) input fields

### ISSUE THREAD

**Issue by hamiltoneri** [bazaarvoice/jolt#712]
I am wondering if it is possible with Jolt to have one output field from two possible input fields, where one might not exist.  Take the following JSON format:
```
{
  "ExternalID" : {
    "ID" : "ext-id"
  },
  "InternalIDs" : [
    {
      "ID" : "int-id-1",
      "type" : "type-1"
    },
    {
      "ID" : "int-id-2",
      "type" : "type-2"
    }
  ]
}
```
The ExternalID object will always be present, the InternalIDs array may be present, and if it is present, it may or may not have an object with the type of "type-1" in the array.

For the output, I'm looking for a single ID field: If no InternalIDs exist, the ID field will be the ExternalID.ID value.  If InternalIDs exist, I want the ID from the InternalID with "type-1" and this value will need to be placed in a secondary field as well.

Using the input above, since InternalIDs are present and one of them is of type "type-1", the expected output should be:
```
{
  "id" : "int-id-1",
  "secondary" : "int-id-1"
}
```
I know I can achieve pulling this specific case out using the following spec:
```
[
  {
    "operation": "shift",
    "spec": {
      "InternalIDs": {
        "*": {
          "type": {
            "type-1": {
              "@(2,ID)": ["id", "secondary"]
            }
          }
        }
      }
    }
  }
]
```
However, if the input looks like
```
{
  "ExternalID" : {
    "ID" : "ext-id"
  }
}
```
or
```
{
  "ExternalID" : {
    "ID" : "ext-id"
  },
  "InternalIDs" : [
    {
      "ID" : "int-id-2",
      "type" : "type-2"
    },
    {
      "ID" : "int-id-3",
      "type" : "type-3"
    }
  ]
}
```
The output should look like
```
{
  "ID" : "ext-id"
}
```

Is there any ways Jolt can be used to essentially always pull out the external ID and in the case of the correct internal ID being present, overwrite the field that external ID is in?

*** Quick Edit:
I want to note that the ID values in ExternalID and the InternalIDs objects are completely numeric, not specifically "int-id-*" or "ext-id". So, I can't really lump all the IDs together in an array and filter out based on the IDs values.

**Comment by milosimpson** [comment]
Yes, but it is hokey.

First you need to identify the "possible" id : externalId and type-1-Id.   Then do two defaults operations.   

If "type-1-Id" was never populated in the shift then the first default will do nothing, and the 2nd default will default in the "always there" externalId.

Otherwise, the first default will fill in a value for ID, and the 2nd won't overwrite it.

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "ExternalID": {
        "ID": "externalId"
      },
      "InternalIDs": {
        "*": {
          "type": {
            "type-1": {
              // if we match type:type-1 then go back up
              //  the tree and grabe the value of ID and 
              //  write it to the key "type-1-Id
              "@(2,ID)": "type-1-Id"
            }
          }
        }
      }
    }
  },
  {
    "operation": "modify-default-beta",
    "spec": {
      "ID": "@(1,type-1-Id)"
    }
  },
  {
    "operation": "modify-default-beta",
    "spec": {
      "ID": "@(1,externalId)"
    }
  },
  {
    "operation": "remove",
    "spec": {
      "externalId": "",
      "type-1-Id": ""
    }
  }
]
```

**Comment by hamiltoneri** [comment]
Thanks for the help!

After playing around some more with the modify operations, I found you can reduce the number of operations by using modify-overwrite-beta:

[
  {
    "operation": "shift",
    "spec": {
      "ExternalID": {
        "ID": "id"
      },
      "InternalIDs": {
        "*": {
          "type": {
            "type-1": {
              "@(2,ID)": ["int-id-key", "secondary"]
            }
          }
        }
      }
    }
  },
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "id": "@(1,int-id-key)"
    }
  },
  {
    "operation": "remove",
    "spec": {
      "int-id-key": ""
    }
  }
]

The shift operation always defaults the output's "id" field to be the ExternalID.ID input field.  The InternalID.ID field is saved in a temporary int-id-key field.  In the modify-overwrite-beta operation, we overwrite the "id" field (currently holding the ExternalID.ID value) with the int-id-key.  However, if this int-id-key does not exist, then the modify-overwrite-beta operation will have no effect leaving the original ExternalID.ID value as the "id".

Thanks again!
