### ISSUE TITLE
Mapping multiple objects to a single array.

### ISSUE THREAD

**Issue by danielamaya** [bazaarvoice/jolt#713]
Hello, I have the following input:

    {
       "name": "Bob Odenkirk",
        "experience": [
            {
                "title": "Software Engineer",
                "company": [{
                    "name": "Microsoft"
                }],
                "start": "2012-09",
                "end": "2014-09"
            },
            {
                "title": "Developer",
                "company": [{
                    "name": "Oracle"
                }],
                "start": "2012-09",
                "end": "2014-09"
            },
        ],
        "experienceCurrent": [
            {
                "position": "Programmer",
                "company": "Google",
                "start_date": "2017-09"
            },
            {
                "position": "Contractor",
                "company": "WeWork",
                "start_date": "2017-10"
            }
        ]
    }

I am trying to map these objects to a new array. Here is my desired output:

    {
        "fullName": "Bob Odenkirk",
        "experience": [
            {
                "companyName": "Microsoft",
                "title": "Software Engineer"
            }
            {
                "companyName": "Oracle",
                "title": "Developer"
            },
            {
                "companyName": "Google",
                "title": "Programmer"
            },
            {
                "companyName": "WeWork",
                "title": "Contractor"
            }
        ]
    }

And finally, here's my spec, which is not working. I cannot get the experienceCurrent data to append to the experience array in output.

    [
        {
            "operation": "shift",
            "spec": {
                "_source": {
                    "name": "fullName",
                    "experience|experienceCurrent": {
                        "*": {
                            "title": "experience.[&1].title",
                            "position": "experience.[&1].title",
                            "company": "experience.[&1].companyName",
                            "company": {
                                "0": {
                                    "name": "experience.[&3].companyName"
                                }
                            }
                        }
                    }
                }
            }
        }
    ]

**Comment by danielamaya** [comment]
I was thinking it may be easier to join all of these beforehand with modify-default-beta, but not sure how to concatenate two arrays:


```
{
    "operation": "modify-default-beta",
    "spec": {
      "*": {
        "experienceTest": "@(1,experienceCurrent)",
        "experienceTest": "@(1,experience)"
      }
    }
  }

```

**Comment by milosimpson** [comment]
See examples https://github.com/bazaarvoice/jolt/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Merging+Arrays%22+

You need to do two shifts.   First, to get each item in the "experience" and "experienceCurrent" arrays, into the "right" format.    Then a 2nd shift to "accumulate" them in to the single desired "experience" array.
