### ISSUE TITLE
Converting Array->Map->Array->Map to Array->Map

### ISSUE THREAD

**Issue by murthy80** [bazaarvoice/jolt#715]
Hi,

Input:

 "abc" : [ 
        {
            "xyz" : "test1",
            "type" : "type1",
            "keyValues" : [ 
                {
                    "key" : "key1",
                    "values" : [ 
                        "value1"
                    ]
                },
                {
                    "key" : "key2",
                    "values" : [ 
                        "value2"
                    ]
                }                
            ]
        }, 
        {
            "xyz" : "test2",
            "type" : "type2",
            "keyValues" : [ 
                {
                    "key" : "key3",
                    "values" : [ 
                        "value3"
                    ]
                }
            ]
        }
    ]

Expected Output:

    "abc" : [ 
        {
            "xyz" : "test1",
            "type" : "type1",
            "key" : "key1",
            "values" : ["value1"]
        }, 
        {
            "xyz" : "test1",
            "type" : "type1",
            "key" : "key2",
            "values" : ["value2"]
        }, 
        {
            "xyz" : "test2",
            "type" : "type2",
            "key" : "key3",
            "values" : ["value3"]
        }
    ] 

Please help

**Comment by dinesh-rajaveeran** [comment]
You may start to work with this.

`[
  {
    "operation": "shift",
    "spec": {
      "abc": {
        "*": {
          "xyz": "abc[&1].xyz",
          "type": "abc[&1].type",
          "keyValues": {
            "*": {
              "key": "abc[&3].key",
              "values": "abc[&3].values"
            }
          }
        }
      }
    }
  }
]`
