### ISSUE TITLE
Changing Property Key in Nested Array

### ISSUE THREAD

**Issue by aginghippy** [bazaarvoice/jolt#718]
This is quite embarrassing. How do i change "memberName" to "name" below. And then add another object (default) to displayFormat arrays (say {"memberCompany: "Google"} 

{
    "contentDataObject": [
      [
        {
          "displayFormat": [
            {
              "memberName": "Neil Malgaonkar",
              "memberTitle": "President & CEO"
            }
          ]
        }
      ],
      [
        {
          "displayFormat": [
            {
              "memberName": "Sunil Shenoy",
              "memberTitle": "Managing Director"
            }
          ]
        }
      ]
    ]
  }

**Comment by milosimpson** [comment]
The level of array nesting in your input makes it tough / fiddly.

Spec

        [
          {
            "operation": "shift",
            "spec": {
              "contentDataObject": {
                "*": {
                  "0": {
                    "displayFormat": {
                      "*": {
                        "memberName": "contentDataObject[&4][0].displayFormat[&1].name",
                        "memberTitle": "contentDataObject[&4][0].displayFormat[&1].title"
                      }
                    }
                  }
                }
              }
            }
          },
          {
            "operation": "modify-default-beta",
            "spec": {
              "contentDataObject": {
                "*": {
                  "*": {
                    "displayFormat": {
                      "*": {
                        "memberCompany": "Google"
                      }
                    }
                  }
                }
              }
            }
          }
        ]
