### ISSUE TITLE
How to convert the input file with subtle difference from the same spec configuration file

### ISSUE THREAD

**Issue by wwang2016** [bazaarvoice/jolt#719]
I have a couple of files that can be:
{ "file":
   {"mimeType":"audio/mpeg",
    "url":"http://audio"
   }
}
or
{ "file"
   {"mimeType":"image/jpeg",
   "url":"http://image"
   }
}

I would like to write a spec that can understand the input files so that the first input file can be converted  to:
{
  "request":
      "audioFile":{
         "url":"http://audio",
         "mimeType": "audio/mpeg"
       }
}

and the second one to:

{
  "request":
      "imageFile":{
         "url":"http://image",
         "mimeType": "image/jpeg"
       }
}

**Comment by dinesh-rajaveeran** [comment]
Try this: 

`[
  {
    "operation": "shift",
    "spec": {
      "file": {
        "mimeType": {
          "audio": {
            "@2": "request.audioFile"
          },
          "image*": {
            "@2": "request.imageFile"
          }
        }
      }
    }
  }
]`

**Comment by wwang2016** [comment]
It works!

I actually need the result to be used for converting the original file to a destination file, and the shift operation does not seem to be an option since all the other data will be gone with the solution.

I ended up with doing a modify operation to add an element:

    [
       {
           "operation": "modify-overwrite-beta",
           "spec": {
               "messageType": "=substring(@(2,file.mimeType),0,5)"
           }
        }
    ]

Afterwards, I use a shift operation to differentiate the type by messageType. This way the original file can be further defined as either image or audio

Thanks
