### ISSUE TITLE
Can I create new element on condition?

### ISSUE THREAD

**Issue by wwang2016** [bazaarvoice/jolt#722]
I need to implement conditional logic during transformation of json payload. There is no if/else syntax for the shift spec. So I would like to create additional element in the original json payload before shift operation. However, it looks like I can not assign different values to an new element on condition.

For example, I have the following payload:

    {
        "type": "text",
        "display": "test",
        ....
    }

or

    {
        "type": "file",
        "display": "test",
        ....
    }

or

    {
        "type": "audio",
        "display": "test",
        ....
    }
 
I need to process these two json payload differently so I need to create an element with value based on the type such that if the type is text or file, I assign the element (category=file), and if it is audio, I assign the element as (category=audio). I use the following:

    [
        {
           "operation": "modify-overwrite-beta",
           "spec": {
             "type": {
                 "text": {
                     "category": "file"
                  },
                 "file"{
                     "category": "file"
                 },
                 "audio": {
                      "category": "audio"
                 }
              }
    ]

But it did not work.

**Comment by milosimpson** [comment]
Outline of a Spec

    [
      {
        "operation": "shift",
        "spec": {
          "type" : {
            "text" : {
              "@2" : {
                // process the doc as type text
              }
            },
            "file" : {
              "@2" : {
                // process the doc as type file
              }
            }
            // etc
          }
        }
      }
    ]
