### ISSUE TITLE
Issue with not being able to copy the nested structure to another

### ISSUE THREAD

**Issue by wwang2016** [bazaarvoice/jolt#724]
The input:

	{
	  "cards": [
	    {
	      "title": "card1",
	      "suggestions": [
	        {
	          "type": "reply",
	          "label": "reply1 label1",
	          "postbackData": "reply1 postback"
	        },
	        {
	          "type": "openUrl",
	          "label": "url action label1",
	          "postbackData": "url action postback1",
	          "url": "http://urlaction1"
	        }
	      ]
	    },
	    {
	      "title": "card2",
	      "suggestions": [
	        {
	          "type": "reply",
	          "label": "reply label2",
	          "postbackData": "reply postback2"
	        },
	        {
	          "type": "openUrl",
	          "label": "url action label2",
	          "postbackData": "url action postback2",
	          "url": "http://urlaction2"
	        }
	      ]
	    }
	  ]
	}

I would like to be converted to:

	{
	  "content" : [ {
	    "title" : "card1",
	    "suggestions" : [ {
	      "reply" : {
	        "displayText": "reply1 label1",
	        "postback" : {
	          "data" : "reply postback2"
	        }
	      }
	    } ]
	  }, {
	    "title" : "card2",
	    "suggestions" : [ {
	      "reply" : {
	        "displayText" : "reply label2",
	        "postback" : {
	          "data" : "reply postback2"
	        }
	      }
	    } ]
	
	  } ]
	}

with the following spec:

	[
	  {
	    "operation": "shift",
	    "spec": {
	      // can not use messageType again
	      "cards": {
	        "*": {
	          "title": "content[#2].title",
	          "": "content[#2].suggestions[]",
	          "suggestions": {
	            "*": {
	              "type": {
	                "reply": {
	                  "@(2,label)": "content[#1].suggestions[#1].reply.displayText",
	                  "@(2,postbackData)": "content[#1].suggestions[#1].reply.postback.data"
	                }
	              }
	            }
	          }
	        }
	      }
	    }
	  }
	]

It actually produces:

	{
	  "content" : [ {
	    "title" : "card1",
	    "suggestions" : [ {
	      "reply" : {
	        "displayText" : [ "reply1 label1", "reply label2" ],
	        "postback" : {
	          "data" : [ "reply1 postback", "reply postback2" ]
	        }
	      }
	    } ]
	  }, {
	    "title" : "card2"
	  } ]
	}

What is a correct spec?

**Comment by milosimpson** [comment]
Spec

[
  {
    "operation": "shift",
    "spec": {
      // can not use messageType again
      "cards": {
        "*": {
          "title": "content[&1].title",
          "suggestions": {
            "0": {
              "type": {
                "reply": { // match type:reply
                  //
                  // grab the "label" and write it as displayText
                  "@(2,label)": "content[&5].suggestions[0].reply.displayText",
                  // 
                  // only if type === reply, then go back up the tree
                  //  and grab the postbackData from suggestions[1]
                  "@3": {
                    "1": {
                      "postbackData": "content[&7].suggestions[0].reply.postback.data"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
]
