### ISSUE TITLE
Jolt:to generate multiple attribute from a single json attribute

### ISSUE THREAD

**Issue by TanmayGumaste** [bazaarvoice/jolt#725]
My Sample input:

{
  "mode": "Bake"
}

desired ouput:

{	    "OvenUpperCavity_CycleSetCommonMode":2,
	   "OvenUpperCavity_CycleSetTargetTemp": "1767",
	   "OvenUpperCavity_OpSetOperations": "2"  
                            
  }
=================================
what shoud i write in the spec,

all the values in my desired output are fixed

**Comment by milosimpson** [comment]
Jolt isn't really the right tool for that.
