### ISSUE TITLE
Rounding Decimal

### ISSUE THREAD

**Issue by prasadrao82** [bazaarvoice/jolt#726]
Hi, 

I have the following input and required to round the decimal values after the dot to 2 if the number of digits after the dot is more than 2.

[ {
  
  "weatherInfo" : [ {
    "key" : "NO",
    "value" : "10"
  }, {
    "key" : "NO2",
    "value" : "90.34132078299744"
  }, {
    "key" : "PM1",
    "value" : "6.3366932944297005"
  }, {
    "key" : "PM2.5",
    "value" : "7.36015808706224"
  }, {
    "key" : "PM10",
    "value" : "8.365356442967816"
  } ]
}, {
  
  "weatherInfo" : [ {
    "key" : "NO",
    "value" : "10"
  }, {
    "key" : "NO2",
    "value" : "90.34132078299744"
  }, {
    "key" : "PM1",
    "value" : "6.3366932944297005"
  }, {
    "key" : "PM2.5",
    "value" : "7.36015808706224"
  }, {
    "key" : "PM10",
    "value" : "8.365356442967816"
  } ]
} ]

expected output is 

[ {
  
  "weatherInfo" : [ {
    "key" : "NO",
    "value" : "10"
  }, {
    "key" : "NO2",
    "value" : "90.34"
  }, {
    "key" : "PM1",
    "value" : "6.33"
  }, {
    "key" : "PM2.5",
    "value" : "7.36"
  }, {
    "key" : "PM10",
    "value" : "8.36"
  } ]
}, {
  
  "weatherInfo" : [ {
    "key" : "NO",
    "value" : "10"
  }, {
    "key" : "NO2",
    "value" : "90.3"
  }, {
    "key" : "PM1",
    "value" : "6.33"
  }, {
    "key" : "PM2.5",
    "value" : "7.36"
  }, {
    "key" : "PM10",
    "value" : "8.36"
  } ]
} ]

could you please help me in providing spec for the same.

**Comment by milosimpson** [comment]
There is not a round function in OOTB Jolt.
