### ISSUE TITLE
Changing the key name of result

### ISSUE THREAD

**Issue by ranjithkh** [bazaarvoice/jolt#727]
Hello,

Could someone help me to solve the issue:

My Input JSON:
--------------
```
{
  "phones": [
    {
      "value": "123456789",
      "type": "home"
    },
    {
      "value": "080-123456",
      "type": "office"
    }
  ]
}
```

Spec:
--------------
```
[
  {
    "operation": "shift",
    "spec": {
      "phones": {
        "*": {
          "value": "phone.@(1,type)"
        }
      }
    }
  }
]
```

Output:
--------------
```
{
  "phone" : {
    "home" : "123456789",
    "office" : "080-123456"
  }
}
```

This works fine as per the requirement. Now if I want to change the key "home" to "house" and "office" to "work", How can I do it. This array can be more than 2. There may be a landline, secondary phone etc.

**Comment by milosimpson** [comment]
Spec

    [
      {
        // manually "fix" the phones type field
        //  for known types
        "operation": "shift",
        "spec": {
          "phones": {
            "*": {
              "value": "phones[&1].value",
              "type": {
                "home": {
                  "#house": "phones[&3].type"
                },
                "office": {
                  "#work": "phones[&3].type"
                },
                // if type isn't home or office
                //  then pass it thru
                "*": {
                  "$": "phones[&3].type"
                }
              }
            }
          }
        }
      },
      {
        "operation": "shift",
        "spec": {
          "phones": {
            "*": {
              "value": "phone.@(1,type)"
            }
          }
        }
      }  
    ]
