### ISSUE TITLE
Need help if same element type is repeated in array

### ISSUE THREAD

**Issue by PBR1** [bazaarvoice/jolt#728]
**input Request:**
{
  "regions": [
    {
      "region": "MIAM",
      "type": "ap",
      "branches": [
        {
          "branch": "07"
        }
      ]
    },
    {
      "region": "APL2",
      "type": "tx",
      "branches": [
        {
          "branch": "AD"
        },
        {
          "branch": "QA"
        }
      ]
    }
  ]
}

**Expected OutPut:**
{
  "organizationUnit" : [ {
    "identifier" : [ {
      "type" : "payrollRegionCode",
      "value" : "MIAM"
    }, {
      "type" : "branchCode",
      "value" : "07"
    } ],
    "paySystem" : {
      "type" : "ap"
    }
  }, {
    "identifier" : [ {
      "type" : "payrollRegionCode",
      "value" : "APL2"
    }, {
      "type" :  "branchCode",
      "value" : "AD"
    } ,
                   {
      "type" :  "branchCode",
      "value" : "QA"
    }],
    "paySystem" : {
      "type" : "tx"
    }
  } ]
}

**But when i am using below spec, i am getting response as below:**
[
  {
    "operation": "shift",
    "spec": {
      "regions": {
        "*": {
          "type": "organizationUnit[&1].paySystem.type",
          "region": "organizationUnit[&1].identifier[0].value",
          "#payrollRegionCode": "organizationUnit[&1].identifier[0].type",
          "branches": {
            "*": {
              "branch": "organizationUnit[&3].identifier[1].value",
              "#branchCode": "organizationUnit[&3].identifier[1].type"
            }
          }
        }
      }
    }
  }
]

**Response with this spec**
{
  "organizationUnit" : [ {
    "identifier" : [ {
      "type" : "payrollRegionCode",
      "value" : "MIAM"
    }, {
      "type" : "branchCode",
      "value" : "07"
    } ],
    "paySystem" : {
      "type" : "ap"
    }
  }, {
    "identifier" : [ {
      "type" : "payrollRegionCode",
      "value" : "APL2"
    }, {
      "type" : [ "branchCode", "branchCode" ],
      "value" : [ "AD", "QA" ]
    } ],
    "paySystem" : {
      "type" : "tx"
    }
  } ]
}

**Comment by milosimpson** [comment]
Requires two shifts.  In the first shift build the "payrollRegionCode" type/value pair, and separately build the type/value pairs from the branches array.

Then in a 2nd shift, accumulate all the type/value pairs into an identifier array.

**Comment by milosimpson** [comment]
See the "Merging Arrays" examples   https://github.com/bazaarvoice/jolt/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Merging+Arrays%22+

In your case you are trying to merge a "single data" item 'payrollRegionCode' and and array of branches data.
