### ISSUE TITLE
Assign array values to some keys

### ISSUE THREAD

**Issue by ranjithkh** [bazaarvoice/jolt#731]
Hello,

Could you please help me to get this done:
Input
```
{
	"testblock": [
		[
			"a,
			"b",
			"c"
		],
		[
			"aa",
			"bb",
			"cc"
		]
}
```
Expected Output:
```
{
    "test":[{
        "one":"a",
        "two":"b",
        "three":"c"
    }, {
        "one":"aa",
        "two":"bb",
        "three":"cc"
    }]
}
```

**Comment by milosimpson** [comment]
Spec

    [
      {
        "operation": "shift",
        "spec": {
          "testblock": {
            "*": { // outer array
              // explicitly match the array indices for the innter arrays
              "0": "test[&1].one",
              "1": "test[&1].two",
              "2": "test[&1].three"
            }
          }
        }
      }
    ]

**Comment by ranjithkh** [comment]
Thanks a lot.
