### ISSUE TITLE
How to separate String and number

### ISSUE THREAD

**Issue by ranjithkh** [bazaarvoice/jolt#732]
Could you please help here to separate string and integer

Input
```
[
  {
    "fname": "fname1",
    "lname": "lname1",
    "contact": "12345678"
  },  {
    "fname": "fname2",
    "lname": "lname2",
    "contact": "test@test.com"
  }
]
```
Expected Output
```
{
  "contacts" : [ {
    "firstname" : "fname1",
    "lastname" : "lname1",
    "phone" : "12345678"
  }, {
    "firstname" : "fname2",
    "lastname" : "lname2",
    "email" : "test@test.com"
  } ]
}
```

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "*": {
        "fname": "contacts[#2].firstname",
        "lname": "contacts[#2].lastname",
        "contact": "contacts[#2].phone"
      }
    }
  }
]
```
How can I put a condition to check whether contact value is email or phone no and assign to "email" or "phone". Thank you.

**Comment by milosimpson** [comment]
Can kinda do it, but it is fragile.

    [
      {
        "operation": "shift",
        "spec": {
          "*": {
            "fname": "[&1].fname",
            "lname": "[&1].lname",
            "contact": {
              // crappy match of an email address by looking for '*@*.*' but have to 
              //   escape the "@"
              // and if it does not match then assume it is a phone number
              "*\\@*.*": {
                "$": "[&3].email"
              },
              "*": {
                "$": "[&3].phone"
              }
            }
          }
        }
      }
    ]

**Comment by ranjithkh** [comment]
Great. Thank you.
