### ISSUE TITLE
Can't filter an array based on input data

### ISSUE THREAD

**Issue by alarregoity-inflexsys** [bazaarvoice/jolt#733]
Given the input:
```json
{
	"maxQuality": 15,
	"items": [
		{
			"id": 1,
			"quality": 10
		},
		{
			"id": 2,
			"quality": 15
		},
		{
			"id": 3,
			"quality": 5
		}
		
	]
}
```

I would like to get the following output:
```json
{
	"itemWithMaxQuality": {
		"id": 2,
		"quality": 15
	}
}
```
It works ith the following spec, where the filter is hardcoded ("15"):
```json
[
	{
		"operation": "shift",
		"spec": {
			"items": 
				{
					"*": {
						"quality" : {
							"15" : {
								"@2": "itemWithMaxQuality"
							}
						}
					}
				}
		}
	}
]
```

But with the following spec where I reference the maxQuality value ("@(3,maxQuality)" instead of "15"):
```json
[
	{
		"operation": "shift",
		"spec": {
			"items": 
				{
					"*": {
						"quality" : {
							"@(3,maxQuality)" : {
								"@2": "itemWithMaxQuality"
							}
						}
					}
				}
		}
	}
]
```

I get:
```json
{
  "itemWithMaxQuality" : [ {
    "id" : 1,
    "quality" : 10
  }, {
    "id" : 2,
    "quality" : 15
  }, {
    "id" : 3,
    "quality" : 5
  } ]
}
```

Is it a bug?

**Comment by milosimpson** [comment]
Not a bug.   Just doesn't work the way you are trying to use it.

**Comment by milosimpson** [comment]
The '@' wildcard is for moving around the stack of the tree traversal.   If you want to match on two values in the data, you have to use '&' on the 'key' side of the json.

Spec

    [
      {
        "operation": "shift",
        "spec": {
          "maxQuality": {
            "*": { // capture the 15
              "@2": { // reset match tree to the root 
                "items": {
                  "*": {
                    "quality": {
                      "&4": { // lookup the maxQuality
                        // and if the value matches 
                        // then reset the tree again
                        // and pull the itemWithMaxQuality
                        "@2": "itemWithMaxQuality"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    ]

**Comment by alarregoity-inflexsys** [comment]
I think I understand (but not sure).
Don't you think it would be nice if we could do the matching against a value somewhere else in the json tree?

Anyway Thanks a lot for your quick answer!

**Comment by milosimpson** [comment]
You can, you just have to "capture" that "value somewhere else in the json tree" first, and then match on it.
