### ISSUE TITLE
Pass data that has effective_state=1

### ISSUE THREAD

**Issue by SudhakarReddyPeddinti** [bazaarvoice/jolt#735]
I tried different ways to handle the nulls, but not able to remove them. Reaching out here for help.

input data:
```{
 "_items": [
    {
      "cat_id": "1213",
      "name": "testManualShelf-1",
      "properties": {
        "tango": {
          "data": [
            {
              "effective_state": "0",
              "updated_time": 1528747175775,
              "id": 0
            },
            {
              "effective_state": "1",
              "updated_time": 1428748275565,
              "id": 1
            },
            {
              "effective_state": "0",
              "updated_time": 1328748275565,
              "id": 2
            },
            {
              "effective_state": "1",
              "updated_time": 1588748275565,
              "id": 3
            }
          ]
        }
      }
    },
    {
      "cat_id": "1213",
      "name": "testManualShelf-1",
      "properties": {
        "tango": {
          "data": [
            {
              "effective_state": "0",
              "updated_time": 1528747175775,
              "id": 0
            },
            {
              "effective_state": "1",
              "updated_time": 1428748275565,
              "id": 1
            },
            {
              "effective_state": "0",
              "updated_time": 1328748275565,
              "id": 2
            }
          ]
        }
      }
    }
  ]
}
```

Spec:
```
[
  {
    "operation": "shift",
    "spec": {
      "_items": {
        "*": {
          "properties": {
            "tango": {
              "data": {
                "*": {
                  "effective_state": {
                    "1": {
                      "@(2,updated_time)": "collections.[&7].[&3].updated_time"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
]
```

Output:
```{
  "collections" : [ [ null, {
    "updated_time" : 1428748275565
  }, null, {
    "updated_time" : 1588748275565
  } ], [ null, {
    "updated_time" : 1428748275565
  } ] ]
}
```

Expected Output:
```{
"collections" : [ [ {  
      "updated_time" : 1428748275565  
    }, {  
      "updated_time" : 1588748275565  
    } ], [ {  
      "updated_time" : 1428748275565  
    } ] ]
}
```

**Comment by milosimpson** [comment]
The nulls are coming from the elements of the data array that are getting "filtered out" by not being "effective_state" "1".

I.e. the input of "_items[0].properties.tango.data" is an array with 4 things in it, elements 1 and 3 are effective_state : 1, and elements 0 and 2 are not.

The output path from your spec of "collections.[&7].[&3].updated_time" ends up evaluating to
1. collections.[0].[1].updated_time  and 
2. collections.[0].[3].updated_time

Thus leaving holes/nulls at collections.[0].[0] and collections.[0].[2]

To get what you want you need to do two shifts, first one where you just pair down the data you want, and then the 2nd one to build your final array.

Spec

    [
      {
        "operation": "shift",
        "spec": {
          "_items": {
            "*": {
              "properties": {
                "tango": {
                  "data": {
                    "*": {
                      "effective_state": {
                        "1": {
                          // Accumulate all the "data" entries that are
                          //  effective state:1 into a new array.
                          "@2": "temp[&7].goodData[]"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      {
        "operation": "shift",
        "spec": {
          "temp": {
            "*": {
              "goodData": {
                "*": {
                  // pull out the one part that is needed
                  "updated_time": "collections[&3][&1].updated_time"
                }
              }
            }
          }
        }
      }
    ]

**Comment by SudhakarReddyPeddinti** [comment]
@milosimpson Thank you very much for the quick response. Much appreciate your work. A quick suggestion is that you could update the presentation deck in the READ.ME with more complex examples. I referred the presentation and the examples in the source code. But I feel they are not sufficient.

**Comment by SudhakarReddyPeddinti** [comment]
@milosimpson If I have huge data and have spec with multiple shift operations, will there be performance impact? Is it correct that the processor has to walk through the all the shift operations after each transformation?

**Comment by milosimpson** [comment]
If I have huge data and have spec with multiple shift operations, will there be performance impact?   --> Maybe.  Measure it.  Freak out if it is acutally too slow.

Is it correct that the processor has to walk through the all the shift operations after each transformation? -->  Jolt specifically makes the trade off to be human friendly vs machine friendly.   Machines get faster all the time, human do not.
