### ISSUE TITLE
How to remove null from the output

### ISSUE THREAD

**Issue by gitnmg** [bazaarvoice/jolt#736]
**Input** :
```
[
  [
    {
      "a": 1,
      "b": 21
    },
    {
      "a": 2,
      "b": 22
    }
  ],
  [
    {
      "a": 3,
      "b": 23
    },
    {
      "a": 3
    }
  ]
]
```

**Output I want**:
```
[ [ {
  "a" : 3,
  "b" : "NOT_CREATED"
} ] ]
```

**Output I am getting**:
```
[ null, [ {
  "a" : 3,
  "b" : "NOT_CREATED"
} ] ]
```

**My spec** :
```
[
  {
    "operation": "default",
    "spec": {
      "*[]": {
        "*": {
          "b": "NOT_CREATED"
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "*": {
        "*": {
          "b": {
            "NOT_CREATED": {
              "@2": "[&4][]"
            }
          }
        }
      }
    }
  }
]

```
Out put structure should be array of arrays. In my result I want to **remove the null** when value of **b** is present in first array for all the elements. 
If in the first array, value of **b** is **not** present for at least one element I'm getting the desired result using the spec.
```
[ [ {
  "a" : 2,
  "b" : "NOT_CREATED"
} ], [ {
  "a" : 3,
  "b" : "NOT_CREATED"
} ] ]
```

Thanks in advanced.

**Comment by milosimpson** [comment]
Spec

    [
      {
        "operation": "default",
        "spec": {
          "*[]": {
            "*": {
              "b": "NOT_CREATED"
            }
          }
        }
      },
      {
        "operation": "shift",
        "spec": {
          "*": { // outer array
            "*": { // imner array
              "b": {
                "NOT_CREATED": {
                  // because there may be outer array elements that don't
                  //  have any b:NOT_CREATED elements, we make a outerMap
                  //  instead of an outerArray, so that we don't end up
                  //  with nulls in the desired outerarray
                  "@2": "outerMap.&4.innerArray[]"
                }
              }
            }
          }
        }
      },
      {
        "operation": "shift",
        "spec": {
          "outerMap": {
            "*": { // match stringified array indexes
              // Accumulate all the innerArrays to a top level outerArray
              //  so that there are no nulls in the outerArray
              "innerArray": "[]"
            }
          }
        }
      }
    ]

**Comment by gitnmg** [comment]
Thanks a lot.
