### ISSUE TITLE
How to rename json keys? change attribute names to camelcasing

### ISSUE THREAD

**Issue by bnrs2006** [bazaarvoice/jolt#739]
Thankyou Verymuch @milosimpson  .. for helping me out with issue 729 on json to csv conversion.

Thankyou for your help..I appreciate it! 

I'm dealing with one more challenge .. not the json to csv...is it possible to rename all the keys in the json?

I have a output from datawarehouse tool which doesnt have camelcase attribute names but they are db column names, for eg.  no_of_employees is a field name, I want it to be json standard say noOfEmployees.

But there are lot of fields, I cant hardcode them one by one..not sure if there is an easy way to transform the casing for all keys to get rid of underscores and do camelcasing.

Please suggest if there is a way to handle that.

Current Output:
~~~
{
  "rows": [
    {
      "columns": {
        "start_date": "2018-12-22",
        "end_date": "2018-12-24",
        "month_year": "December",
        "limits": [
          2000000,
          "null"
        ],
        "num_of_employers": "null"
      }
    },
    {
      "columns": {
        "start_date": "2018-12-22",
        "end_date": "2018-12-24",
        "month_year": "December",
        "limits": [
          1000000,
          "null"
        ],
        "num_of_employers": 3000
      }
    }
  ]
}
~~~
Expected Output:

~~~
{
  "rows": [
    {
      "columns": {
        "startDate": "2018-12-22",
        "endDate": "2018-12-24",
        "month": "December",
        "limits": [
          2000000,
          "null"
        ],
        "numOfEmployers": "null"
      }
    },
    {
      "columns": {
        "startDate": "2018-12-22",
        "endDate": "2018-12-24",
        "month": "December",
        "limits": [
          1000000,
          "null"
        ],
        "numOfEmployers": 3000
      }
    }
  ]
}
~~~

I appreciate your help. Not sure if this is even possible with jolt spec. Your suggestions will be helpful.
TIA
Thanks
@bnrs2006

_Originally posted by @bnrs2006 in https://github.com/bazaarvoice/jolt/issues/729#issuecomment-456885587_

**Comment by milosimpson** [comment]
"not sure if there is an easy way to transform the casing for all keys to get rid of underscores and do camelcasing"

Nope.  There isn't an Out of the Box way to do that.   You would need to use a different tool, or write a custom transform.

**Comment by bnrs2006** [comment]
> Thankyou Verymuch @milosimpson .. for helping me out with issue 729 on json to csv conversion.
> 
> Thankyou for your help..I appreciate it!
> 
> I'm dealing with one more challenge .. not the json to csv...is it possible to rename all the keys in the json?
> 
> I have a output from datawarehouse tool which doesnt have camelcase attribute names but they are db column names, for eg. no_of_employees is a field name, I want it to be json standard say noOfEmployees.
> 
> But there are lot of fields, I cant hardcode them one by one..not sure if there is an easy way to transform the casing for all keys to get rid of underscores and do camelcasing.
> 
> Please suggest if there is a way to handle that.
> 
> Current Output:
> 
> ```
> {
>   "rows": [
>     {
>       "columns": {
>         "start_date": "2018-12-22",
>         "end_date": "2018-12-24",
>         "month_year": "December",
>         "limits": [
>           2000000,
>           "null"
>         ],
>         "num_of_employers": "null"
>       }
>     },
>     {
>       "columns": {
>         "start_date": "2018-12-22",
>         "end_date": "2018-12-24",
>         "month_year": "December",
>         "limits": [
>           1000000,
>           "null"
>         ],
>         "num_of_employers": 3000
>       }
>     }
>   ]
> }
> ```
> 
> Expected Output:
> 
> ```
> {
>   "rows": [
>     {
>       "columns": {
>         "startDate": "2018-12-22",
>         "endDate": "2018-12-24",
>         "month": "December",
>         "limits": [
>           2000000,
>           "null"
>         ],
>         "numOfEmployers": "null"
>       }
>     },
>     {
>       "columns": {
>         "startDate": "2018-12-22",
>         "endDate": "2018-12-24",
>         "month": "December",
>         "limits": [
>           1000000,
>           "null"
>         ],
>         "numOfEmployers": 3000
>       }
>     }
>   ]
> }
> ```
> 
> I appreciate your help. Not sure if this is even possible with jolt spec. Your suggestions will be helpful.
> TIA
> Thanks
> @bnrs2006
> 
> _Originally posted by @bnrs2006 in [#729 (comment)](https://github.com/bazaarvoice/jolt/issues/729#issuecomment-456885587)_

Thanksyou @milosimpson I missed your reply on splitting the keys. That really helps..but for this request I made the change in service to return the response in camelcasing. Sorry for the lates response.

**Comment by msoni9** [comment]
HI milosimpson.

I was trying to reach you for my doubts. could you please share you mail id.
