### ISSUE TITLE
Adding Strings to Existing Array

### ISSUE THREAD

**Issue by sietekk** [bazaarvoice/jolt#740]
**Task**
I am working in an Apache Nifi pipeline and need to modify some incoming JSON using the new `JoltTransformJSON` processor.

In particular, my incoming data looks like this:
```
{
  "filenName": "/some/file/name",
  "className": "blah.blah.blah.Main",
  "args": [
    "--arg1",
    "argument1",
    "--arg2",
    "argument2",
    "--arg3",
    "argument3"
  ]
}
```
and I need to append an array to the `args` array. That array looks like this:
```
[
        "--dbUrl", "123",
        "--dbUser", "456",
        "--hiveMetastoreUrl", "789",
        "--anotherUrl", "000"
]
```
The final result should look like this:
```
{
  "filenName": "/some/file/name",
  "className": "blah.blah.blah.Main",
  "args": [
     "--arg1", "argument1",
     "--arg2", "argument2",
     "--arg3", "argument3",
     "--dbUrl", "123",
     "--dbUser", "456",
     "--hiveMetastoreUrl", "789",
     "--anotherUrl", "000"
  ]
}
```

**What I've Accomplished so Far**
My current spec is working... sort of... and looks like:
```
[
  {
    "operation": "default",
    "spec": {
      "args": "args",
      "temp": [
        "--dbUrl", "123",
        "--dbUser", "456",
        "--hiveMetastoreUrl", "789",
        "--anotherUrl", "101112"
      ]
    }
  },
  {
    "operation": "shift",
    "spec": {
      "args": { "*": "args[]" },
      "temp": { "*": "args[]" }
    }
   }
]
```
It's generating the `args` array correctly, but I'm losing all other key-values at the top level like `"filenName": "/some/file/name"` and `"className": "blah.blah.blah.Main"`. I have not figured out how to get those back in the result.

By the way, the demo website is awesome! Thanks for creating that!

**Comment by milosimpson** [comment]
Spec

    [
      {
        "operation": "default",
        "spec": {
          "args": "args",
          "temp": [
            "--dbUrl", "123",
            "--dbUser", "456",
            "--hiveMetastoreUrl", "789",
            "--anotherUrl", "101112"
          ]
        }
      },
      {
        "operation": "shift",
        "spec": {
          // pass thru / manually copy across filenName and className
          "filenName": "filenName",
          "className": "className",
          // merge args and temp
          "args": { "*": "args[]" },
          "temp": { "*": "args[]" }
        }
      }
    ]

**Comment by sietekk** [comment]
Thanks for your time!

**Comment by singhvishwanath** [comment]
how to transform below Json
Input:
```
{
	"empId": "AGHAA5V0AHWKHAPW97DVMD6UNEGFU0",
	"info": {
		"miscInfo": [
			{
				"Name": "empNo",
				"Value": "2019091643954866"
			},
			{
				"Name": "deskNo",
				"Value": "8191234567"
			}
		],
		"task": [
			{
				"status": "DISPATCHED",
				"miscellaneousInfo": [
					{
						"Name": "dispatchId",
						"Value": "76316785"
					},
					{
						"Name": "diagnose_result",
						"Value": ""
					}
				]
			},
			{
				"status": "DELEVERED",
				"miscellaneousInfo": [
					{
						"Name": "delId",
						"Value": "42365437"
					},
					{
						"Name": "diagnose_result",
						"Value": ""
					}
				]
			}
		]
	}
}

```
Output:
```
{
	"empId": "AGHAA5V0AHWKHAPW97DVMD6UNEGFU0",
	"task": [
		{
			"status": "DISPATCHED",
			"miscellaneousInfo": [
				{
					"Name": "dispatchId",
					"Value": "76316785"
				},
				{
					"Name": "diagnose_result",
					"Value": ""
				},
				{
					"Name": "empNo",
					"Value": "2019091643954866"
				},
				{
					"Name": "deskNo",
					"Value": "8191234567"
				}
			]
		},
		{
			"status": "DELEVERED",
			"miscellaneousInfo": [
				{
					"Name": "delId",
					"Value": "42365437"
				},
				{
					"Name": "diagnose_result",
					"Value": ""
				},
				{
					"Name": "empNo",
					"Value": "2019091643954866"
				},
				{
					"Name": "deskNo",
					"Value": "8191234567"
				}
			]
		}
	]
}
```

any help will be appreciated.
Thanks in advance

**Comment by wisthy** [comment]
please create a new issue instead of re-using a closed one.
