### ISSUE TITLE
Converting JSON into another JSON with conditions

### ISSUE THREAD

**Issue by IvanLiulko** [bazaarvoice/jolt#742]
Hello,
I started to use JOLT to transform JSON into another JSON and stucked with transformation.
could you please assist me?

So, have input:
```{
  "data": {
    "date": "2018-02-01",
    "finish_date": "2018-02-02",
    "specifications": [
      {
        "name": "Default",
        "id": 357,
        "parent_id": null
      },
      {
        "name": "Standard",
        "id": 377,
        "parent_id": 357
      }
    ],
    "programs": [
      {
        "prog_id": 270561,
        "prog_name": "Name1",
        "results": false
      },
      {
        "prog_id": 270562,
        "prog_name": "Name2",
        "results": false
      },
      {
        "prog_id": 270562,
        "prog_name": "Name3",
        "results": true
      },
      {
        "prog_id": 270562,
        "prog_name": "Name4",
        "results": true
      },
      {
        "prog_id": 270562,
        "prog_name": "Name5",
        "results": false
      }
    ]
  }
}```

Expected output:
```{
  "competition" : {
    "disciplines" : [ {
      "title": "Default",
      "id": 357, //get element where parent_id is 'null'
      "events" : [  {
        "id" : 270562,
        "title" : "Name3",
        "type" : "Standard" //get the specifications.name using 'specifications.id=parent_id' 
      }, {
        "id" : 270562,
        "title" : "Name4",
        "type" : "Standard" //get the specifications.name using 'specifications.id=parent_id' 
      } ]
    } ]
  }
}
```

Also have few rules, which have no idea how to map:
1. 'specifications.name' should be transferred if 'parent_id' = 'null' as competition.disciplines.title
2.  Need to find specifications.id by using parent_id and map it to corresponding competition.disciplines.events.type. Is it possible?

Started following spec however it is not work as expected.
```
[
  {
    "operation": "shift",
    "spec": {
      "data": {
        "specifications": {
          "*": {
            "parent_id": {
              "null": {
                "@(2,name)": "competition.disciplines[&3].title",
                "@(2,id)": "competition.disciplines[&3].id"
              }
            }
          }
        },
        "programs": {
          "*": {
            "results": {
              "true": {
                "@(2,prog_id)": "competition.disciplines[0].events[&3].id",
                "@(2,prog_name)": "competition.disciplines[0].events[&3].title",
                "@(4,specifications[1].name)": "competition.disciplines[0].events[&3].type",
                "@(4,event_date)": "competition.disciplines[0].events[&3].start.date",
                "@(4,event_finish_date)": "competition.disciplines[0].events[&3].end.date"
              }
            }
          }
        }
      }
    }
  }
]
```

Could you please help?

**Comment by milosimpson** [comment]
It is kinda unclear what you are trying to do.

Looking at your spec, I recommend pre-pending two steps, to deal with the parent_id of null, and to filter out the non-true results, so that you end up with a "correctly" sized array of just the true results.

Spec

    [
      {
        // shift can't match nulls, so use default to fill in a 'default'
        //  value for parent_id if it was null that can be matched later
        "operation": "default",
        "spec": {
          "data": {
            "specifications[]": {
              "*": {
                "parent_id": "WAS_NULL"
              }
            }
          }
        }
      },
      {
        // filter out programs that are not results:true
        "operation": "shift",
        "spec": {
          "data": {
            "*": "data.&",
            "programs": {
              "*": {
                "results": {
                  "true": {
                    // build a small list with just the true results
                    "@2": "data.trueResults[]"
                  }
                }
              }
            }
          }
        }
      },
      {
        "operation": "shift",
        "spec": {
          "data": {
            "specifications": {
              "*": {
                "parent_id": {
                  "WAS_NULL": {
                    "@(2,name)": "competition.disciplines[0].title",
                    "@(2,id)": "competition.disciplines[0].id"
                  }
                }
              }
            },
            "trueResults": {
              "*": { // array index
                "prog_id": "competition.disciplines[0].events[&1].id",
                "prog_name": "competition.disciplines[0].events[&1].title",
                // lookup values
                "@(2,date)": "competition.disciplines[0].events[&1].start-date",
                "@(2,finish_date)": "competition.disciplines[0].events[&1].end-date",
                "@(4,specifications[1].name)": "competition.disciplines[0].events[&1].type"
              }
            }
          }
        }
      }
    ]

**Comment by IvanLiulko** [comment]
Hi Milo,
Got it with null! Thanks a lot for answer!

However, still not understood how to handle following case. 
Let's simplify it input json and expected output:

Input:
```
{
  "specifications": [
    {
      "name": "FirstParent",
      "id": 1,
      "parent_id": null
    },
    {
      "name": "FirstChild",
      "id": 11,
      "parent_id": 1
    },
    {
      "name": "SecondParent",
      "id": 2,
      "parent_id": null
    },
    {
      "name": "SecondChild",
      "id": 22,
      "parent_id": 2
    }
  ]
}
```
Expected Output:
```
{
  "disciplines": [
    {
      "name": "FirstParent",
      "id": 1,
      "type": {
        "name": "FirstChild",
        "id": 11
      }
    },
    {
      "name": "SecondParent",
      "id": 2,
      "type": {
        "name": "SecondChild",
        "id": 22
      }
    }
  ]
}
```

Logic is the following:
1. Find the element with "parent_id": null, shift it as discipline.
2. Find the elements with parent_id = id of disciplines from step#1 and make them as 'type' child element of discipline.

Is it possible do by JOLT?
