### ISSUE TITLE
Unsure how to break flat array of values out

### ISSUE THREAD

**Issue by steveLandes** [bazaarvoice/jolt#745]
I'm trying to take some data like the following:  

```
{
"eligibleMarkets": [
        "FR",
        "HK",
        "ID"
      ]
}
```

and break it out in to the following:

```
{
  "data": [
    {"key" : "FR"},
    {"key" : "HK"},
    {"key" : "ID"}
  ]
}
```

I've been through quite a few different tutorials but none of them seem to have a good explanation of how to handle flat arrays of values w/o keys.  Any help would be appreciated, thanks!

EDIT:  Similarly, I also need to hard-code a value in to a flat array, I've just remembered.

Need to take the value "ONLINE_CODE" and hard code it in to a flat array like:

```
{
  "outer": ["ONLINE_CODE"]
}
```
That's a gross oversimplification of what I'm doing, the actual JSON structure is much bigger, but once I get the method I can apply to my current spec.  Thanks!

**Comment by milosimpson** [comment]
Spec

    [
      {
        "operation": "shift",
        "spec": {
          "eligibleMarkets": {
            // the "*" evaluates to the array index
            // 0,1,2... which "data[&0]" uses as
            // a reference
            "*": "data[&0].key"
          }
        }
      }
    ]

**Comment by milosimpson** [comment]
For the 2nd question.

Assuming Input of 

    {
      "key": "ONLINE_CODE"
    }

Use this Spec

    [
      {
        "operation": "shift",
        "spec": {
          "key": "outer[0]"
        }
      }
    ]
