### ISSUE TITLE
Escaping special characters for value filters

### ISSUE THREAD

**Issue by dinesh-rajaveeran** [bazaarvoice/jolt#747]
I would like to reference this issue, https://github.com/bazaarvoice/jolt/issues/197.
The escaping works fine for @, #, $ etc., until we start to filter on the keys. 

Say input
```
{
  "NormalizedInfo": [
    {
      "@Item": [
        {
          "@Name": "Title",
          "@Locale": "en",
          "@Type": "",
          "#text": "Snow by Orhan Pamuk."
        },
        {
          "@Name": "Abstract",
          "@Locale": "",
          "@Type": "",
          "#text": "Kerim \"Ka\" Alakusoglu, a poet"
        }
      ]
    }
  ]
}
```
And spec like:

```
[
  {
    "operation": "shift",
    "spec": {
      "NormalizedInfo": {
        "*": {
          "\\@Item": {
            "*": {
              "\\@Name": {
                "Title": {
                  "@(2,\\#text)": "results[&5].title.value",
                  "@(2,\\@Locale)": "results[&5].title.locale"
                },
                "Abstract": {
                  "@(2,\\#text)": "results[&5].abstract.value",
                  "@(2,\\@Locale)": "results[&5].abstract.locale"
                }
              }
            }
          }
        }
      }
    }
  }
]
```

Desired output:

```
{
  "results" : [ 
    "title" : {
      "value" : "Snow by Orhan Pamuk.",
      "locale" : "en"
    }, 
    "abstract" : {
      "value" : "Kerim \"Ka\" Alakusoglu, a poet",
      "locale" : ""
  } ]
}
```
How can I escape leading special characters on filters ??

**Comment by milosimpson** [comment]
"How can I escape leading special characters on filters?" ->  You can't, but the "@" logic you are using can be done another way in your case.

Spec

    [
      {
        "operation": "shift",
        "spec": {
          "NormalizedInfo": {
            "*": {
              "\\@Item": {
                "*": {
                  "\\@Name": {
                    "Title": {
                      "@2": {
                        "\\#text": "results[&6].title.value",
                        "\\@Locale": "results[&6].title.locale"
                      }
                    },
                    "Abstract": {
                      "@2": {
                        "\\#text": "results[&6].abstract.value",
                        "\\@Locale": "results[&6].abstract.locale"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    ]

**Comment by dinesh-rajaveeran** [comment]
Thank you @milosimpson I should have figured it out.  I am shameless.

**Comment by palivela98** [comment]
@milosimpson 

In my case:
Input is :
{
  "EEODisabled": [
    {
      "$": "notdisabled",
      "@code": "not_disabled"
    }
  ]
}


Spec is:
 [{
    "operation": "shift",
    "spec": {
      "EEODisabled": {
        "*": {
          "\\$": "a"
        }
      }
    }
 }
]

Expected output is :
{
  "a" : "Not Indicated"
}

When i am running above it is working in following link "https://jolt-demo.appspot.com/#inception"" but not working with my java code, It looks \\$ is not parsing with below code, Do you need to change my spec?
                Chainr chainr = Chainr.fromSpec(JsonUtils.jsonToList(jsonSpec));
		Object obj = JsonUtils.jsonToObject(jsonObject.toString());
		Object transformedOutput = chainr.transform(jsonobj);

Note: I am using jolt core 0.1.1
