### ISSUE TITLE
html entities are converted and deleted

### ISSUE THREAD

**Issue by richard-rasch** [bazaarvoice/jolt#748]
Is there a -flag to tell jolt cli to refrain from converting html entities. Some are converted and deleted in this transform:

INPUT:
`[
  {
    "Capital S, caron": "\u008A",
    "Less-than sign": "\u008B",
    "Capital OE ligature": "\u008C",
    "Left single quote": "\u0091",
    "Right single quote": "\u0092",
    "Left double quote": "\u0093",
    "Right double quote": "\u0094",
    "Bullet": "\u0095",
    "En dash": "\u0096",
    "Em dash": "\u0097",
    "Tilde": "\u0098",
    "Trademark": "\u0099",
    "Small s, caron": "\u009A",
    "Greater-than sign": "\u009B",
    "Small oe ligature": "\u009C",
    "Capital Y, umlaut": "\u009F",
    "Nonbreaking space": "\u00A0",
    "Inverted exclamation point": "\u00A1",
    "Cent sign": "\u00A2",
    "Pound sign": "\u00A3",
    "General currency sign": "\u00A4"
  }
]`

SPEC:
`[
  {
    "operation": "shift",
    "spec": {
      "*": {
        "*": "&"
      }
    }
  }
 ]`

OUTPUT:
`{
  "Capital S, caron" : "",
  "Less-than sign" : "",
  "Capital OE ligature" : "",
  "Left single quote" : "",
  "Right single quote" : "",
  "Left double quote" : "",
  "Right double quote" : "",
  "Bullet" : "",
  "En dash" : "",
  "Em dash" : "",
  "Tilde" : "",
  "Trademark" : "",
  "Small s, caron" : "",
  "Greater-than sign" : "",
  "Small oe ligature" : "",
  "Capital Y, umlaut" : "",
  "Nonbreaking space" : " ",
  "Inverted exclamation point" : "¡",
  "Cent sign" : "¢",
  "Pound sign" : "£",
  "General currency sign" : "¤"
}
`

**Comment by milosimpson** [comment]
No.   I suspect that that has to do with how Jackson is parsing the Json into Java native Java Maps, Lists, and Strings.
