### ISSUE TITLE
Hello, I have Jolt transformation issue. Integer number having  more digits transformed incorrectly

### ISSUE THREAD

**Issue by Sarankrishna** [bazaarvoice/jolt#749]
ISSUE:
====
Big integer number 1140939609444 is transformed to "-1521691292".

JSON:
====

{
  "id": 123232323232323,
  "name": "Saran",
  "custom_fields": [
    {
      "id": 1140939609444,
      "value": "10-10-2019"
    },
    {
      "id": 22733390,
      "value": "Computer Science"
    },
    {
      "id": 114093960913,
      "value": "Level1"
    },
    {
      "id": 33360527,
      "value": "Misc"
    }
  ]
}

Jolt Spec
=====
[
  {
    "operation": "shift",
    "spec": {
      "id": "id",
      "custom_fields": {
        "*": { "@value": "@id" }
      }
    }
  }
]

OUTPUT
======
{
  "id" : 123232323232323,
  "name" : "Saran",
  "-1521691292" : "10-10-2019",
  "22733390" : "Computer Science",
  "-1870156079" : "Level1",
  "33360527" : "Misc"
}

Expected Output
===========
{
  "id" : 123232323232323,
  "name" : "Saran",
  "1140939609444" : "10-10-2019",
  "22733390" : "Computer Science",
  "114093960913" : "Level1",
  "33360527" : "Misc"
}

**Comment by milosimpson** [comment]
There isn't a way to fix that in the spec.    

There are two possible places that can be breaking.
A) When Jolt is leveraging Jackson to read in the Json string and turn it into in memory Java Objects (Maps, String, Int ...) it is only converting to Int, or
B) When it is doing the "number" to "string" conversion.
