### ISSUE TITLE
Filter array and transform

### ISSUE THREAD

**Issue by srividrs** [bazaarvoice/jolt#750]
My input:
`[
  {
    "accountId": "OD11",
    "accountNickName": "VIJ",
"balances": [
      {
        "type": "totalBalance",
        "amountDetails": {
          "amount": 2000,
          "currency": "USD"
        }
      },
      {
        "type": "availableBalance",
        "amountDetails": {
          "amount": 1040,
          "currency": "USD"
        }
      }
    ]}]
`I want to get the amount and currency correspondong to "totalbalance".. how do i do this?
My spec:
`{
    "operation": "shift",
    "spec": {
      "*": {"balances": {
          "*": {
            "type": {
              "totalBalance": {
                "@2": 
                {
                  "amountDetails": {
                    "amount": "[&5].balanceAmount",
                    "currency": "[&5].balanceCurrency"
                  }
                }
              }
            }
          }
        }`

Expected output:
`{"balanceAmount" : "2000",
  "balanceCurrency" :"USD"}`

But my output has all other balances of other objects in the first array like below
`
"balanceAmount" : [ 2000000000, 2111111111040 ],
  "balanceCurrency" : [ "USD", "USD" ]
`
Balance amount should be a single value

**Comment by milosimpson** [comment]
Try 

                    "amount": "[&7].balanceAmount",
                    "currency": "[&7].balanceCurrency"

What it sounds like is that your "real" input data has many items in the top level array, whereas the example you gave only has one.

The "[&5]" in your spec was referencing the array index of the balances array, not of the top level input array.
