### ISSUE TITLE
Hello need help with list inside list transformation

### ISSUE THREAD

**Issue by saikumar123** [bazaarvoice/jolt#752]
I am currently transforming below input to output using spec. I am not seeing the proper arrangement of values in the array.

{"event_payload":{"orderLines":[{"unitPrice":{"currencyAmount":25,"currencyUnit":"CAD"},"shippingMethod":"STANDARD"},{"unitPrice":{"currencyAmount":50,"currencyUnit":"CAD"},"shippingMethod":"PREMIUM"}],"purchaseOrders":[{"purchaseOrderLines":[{"orderedQty":{"measurementValue":1,"unitOfMeasure":"EACH"},"primeLineNo":"1"}]},{"purchaseOrderLines":[{"orderedQty":{"measurementValue":1,"unitOfMeasure":"EACH"},"primeLineNo":"2"}]}]}}

**to below output**

{"purchaseOrders":[{"purchaseOrderLines":[{"orderedQty":{"measurementValue":1,"unitOfMeasure":"EACH"},"purchaseOrderLineNumber":"1","unitPrice":{"currencyAmount":25,"currencyUnit":"CAD"},"shippingMethod":"STANDARD"}]},{"purchaseOrderLines":[{"orderedQty":{"measurementValue":1,"unitOfMeasure":"GROUP"},"purchaseOrderLineNumber":"2","unitPrice":{"currencyAmount":50,"currencyUnit":"CAD"},"shippingMethod":"PREMIUM"}]}]}

**the spec I tried**

[{"operation":"shift","spec":{"event_payload":{"purchaseOrders":{"*":{"purchaseOrderLines":{"*":{"@(4,orderLines)":{"*":{"unitPrice":"purchaseOrders[&1].purchaseOrderLines[&3].unitPrice","shippingMethod":"purchaseOrders[&1].purchaseOrderLines[&3].shippingMethod"}},"orderedQty":"purchaseOrders[&1].purchaseOrderLines[&3].orderedQty","primeLineNo":"purchaseOrders[&1].purchaseOrderLines[&3].purchaseOrderLineNumber"}}}}}}}]

Any help is highly appreciated. Thanks in advance.

**Comment by milosimpson** [comment]
You need to do it in two steps.   First group your data together (get order lines and purchaseOrderLines "together"), then merge/reformat them.

Spec
```
  [
    {
      // This assumes that orderLines and purchaseOrders
      //  arrays are always the same length, and that
      //  every purchaseOrderLines is always an array
      //  of length 1.
      // First, smush the data together.
      "operation": "shift",
      "spec": {
        "event_payload": {
          // write the orderLines and the nested 
          //  "singular" purchaseOrderLines to the same
          //  place in the output.
          "orderLines": {
            "*": "PO[&0].OL"
          },
          "purchaseOrders": {
            "*": {
              "purchaseOrderLines": {
                "0": "PO[&2].POL"
              }
            }
          }	
        }
      }
    },
    {
      // Now for each "purchaseOrder" smush the data
      //  from the OL and the POL
      "operation": "shift",
      "spec": {
        "PO": {
          "*": {
            "OL": {
              "*": "purchaseOrders[&2].purchaseOrderLines[0].&"
            },
            "POL": {
              "orderedQty": "purchaseOrders[&2].purchaseOrderLines[0].&",
              "primeLineNo": "purchaseOrders[&2].purchaseOrderLines[0].purchaseOrderLineNumber"
            }
          }
        }
      }
    }
  ]
```

**Comment by saikumar123** [comment]
Thank you @milosimpson
