### ISSUE TITLE
Urgent : Require Help in transformation of JSON using Jolt : 

### ISSUE THREAD

**Issue by theamitojha** [bazaarvoice/jolt#754]
Could you please help us on the transformation for below input json to expected Output Json. We have written Jolt spec but the O/P which we are getting is not as expected. Thanks in Advance for Help

I/P Json : 

{
  "appId": "ThirdPartyApp1",
  "messageRev": 2,
  "messageId": "5103fbfa-f700-11e8-8eb2",
  "businessId": "DB",
  "tenantId": "DB_C",
  "deviceId": "DB_1234_SMM",
  "deviceModel": "DR2000",
  "deviceModelId": "F12182",
  "messageTime": 16772223422,
  "messageType": "thirdparty-timeseries",
  "assetId": "DB_1234",
  "assetType": "Loc",
  "parameters": [
    {
      "deviceManufacturer": "get",
      "deviceModelName": "QT",
      "deviceModelId": "F12082",
      "deviceUniqueID": "987398739873",
      "name": "Speed",
      "timestamp": 1479589859,
      "refParamAttrs": [
        {
          "name": "BOGIE_1_BRAKE_PRESS_TRANSDUCER_VOLTS",
          "value": 420,
          "dataType": "Integer"
        },
        {
          "name": "TRACTION_MOTOR_VOLTAGE_6",
          "value": 5,
          "dataType": "Integer"
        }
     ]
    },
    {
      "deviceManufacturer": "get",
      "deviceModelName": "WaterSensor",
      "deviceModelId": "F16082",
      "deviceUniqueID": "987398739873",
      "name": "WaterLevel",
      "timestamp": 1479589860,
      "refParamAttrs": [
        {
          "name": "CYL_3_INJECTOR_RESPONSE_TIME",
          "value": 578345,
          "dataType": "Integer"
        },
        {
          "name": "CYL_11_INJECTOR_RESPONSE_TIME",
          "value": 258175,
          "dataType": "Integer"
        }
      ]
    }
  ]
}

Expected O/P Json :

{
  "tags" : [ {
    "tagId" : "67029.OilQuality",
    "data" : [ {
      "ts" : 1451673360000,
      "v" : "10",
      "q" : "3"
    }, {
      "ts" : 1473931815000 ,
      "v" : "13",
      "q" : "3"
    }, {
      "ts" : 1494840615000,
      "v" : "15",
      "q" : "3"
    },  {
      "ts" : 1510738215000,
      "v" : "17",
      "q" : "3"
    } , {
      "ts" : 1529055015000,
      "v" : "14",
      "q" : "3"
    }]
  } ]
}

Jolt Spec :

[{
    "operation": "modify-overwrite-beta",
    "spec": {
      "parameters": {
        "*": {
          "refParamAttrs": {
            "*": {
              "tagId": "=concat(@(5,assetId),'.',@(1,name))",
              "value": "=toString"
            }
          }
        }
      }
    }
},
  {
    "operation": "shift",
    "spec": {
      "parameters": {
        "*": {
          "refParamAttrs": {
            "*": {
              "tagId": "tags[&1].tagId",
              "@(2,timestamp)": "tags[&1].data[&3].ts",
              "value": "tags[&1].data[&3].v"
            }
          }
        }
      }
    }
},
  {
    "operation": "default",
    "spec": {
      "tags[]": {
        "*": {
          "data[]": {
            "*": {
              "q": "3"
            }
          }
        }
      }
    }
}
]

O/P from Spec which we created  :

{
  "tags" : [ {
    "data" : [ {
      "ts" : 1479589859,
      "v" : "420",
      "q" : "3"
    }, {
      "ts" : 1479589860,
      "v" : "578345",
      "q" : "3"
    } ],
    "tagId" : [ "DB_1234.BOGIE_1_BRAKE_PRESS_TRANSDUCER_VOLTS", "DB_1234.CYL_3_INJECTOR_RESPONSE_TIME" ]
  }, {
    "data" : [ {
      "ts" : 1479589859,
      "v" : "5",
      "q" : "3"
    }, {
      "ts" : 1479589860,
      "v" : "258175",
      "q" : "3"
    } ],
    "tagId" : [ "DB_1234.TRACTION_MOTOR_VOLTAGE_6", "DB_1234.CYL_11_INJECTOR_RESPONSE_TIME" ]
  } ]
}

**Comment by milosimpson** [comment]
This is closer.   You can't modify items and accumulate them into an array in a single shift.

Spec
    [
      {
        "operation": "modify-overwrite-beta",
        "spec": {
          "parameters": {
            "*": {
              "refParamAttrs": {
                "*": {
                  "tagId": "=concat(@(5,assetId),'.',@(1,name))",
                  "value": "=toString"
                }
              }
            }
          }
        }
      },
      {
        "operation": "shift",
        "spec": {
          "parameters": {
            "*": {
              "refParamAttrs": {
                "*": {
                  // pull timestamp and maintain the doubly
                  // nested list structure of the input
                  //
                  // no idea what you are doing with tagId
                  //"tagId": "outer[&3].inner[&1].tagId",
                  "@(2,timestamp)": "outer[&3].inner[&1].ts",
                  "value": "outer[&3].inner[&1].v"
                }
              }
            }
          }
        }
      },
      {
        // now that each item of inner array "looks" right
        //  accumulate them into a data array
        "operation": "shift",
        "spec": {
          "outer": {
            "*": {
              "inner": {
                "*": "tags[0].data[]"
              }
            }
          }
        }
      },
      {
        "operation": "default",
        "spec": {
          "tags[]": {
            "*": {
              "data[]": {
                "*": {
                  "q": "3"
                }
              }
            }
          }
        }
      }
    ]

**Comment by theamitojha** [comment]
Thanks for quick response.

Sorry I think Expected O/P which was mentioned before was incorrect , Please find below the expected O/P 
tagId is concat of assetId and name attribute in refParamAttrs. As per our Jolt spec we are able to create O/P in desired format but the only issue which we are still facing is tagIds under parameters are coming as an Array. Every "tagId" should have its own "data" tag.

"tags" : [ {
"tagId" : "DB_1234.BOGIE_1_BRAKE_PRESS_TRANSDUCER_VOLTS",
"data" : [ {
"ts" : 1479589859,
"v" : "10",
"q" : "3"
 } ]
}
, {
"tagId" : "DB_1234.TRACTION_MOTOR_VOLTAGE_6",
"data" : [ {
"ts" : 1479589859,
"v" : "5",
"q" : "3"
 } ]
} , {
"tagId" : "DB_1234.CYL_3_INJECTOR_RESPONSE_TIME",
"data" : [ {
"ts" : 1479589860,
"v" : "578345",
"q" : "3"
 } ]
} , {
"tagId" : "DB_1234.CYL_11_INJECTOR_RESPONSE_TIME",
"data" : [ {
"ts" : 1479589860,
"v" : "258175",
"q" : "3"
 } ]
} 
]


Thanks in Advance.

**Comment by milosimpson** [comment]
Spec

    [
      {
        "operation": "modify-overwrite-beta",
        "spec": {
          "parameters": {
            "*": {
              "refParamAttrs": {
                "*": {
                  "tagId": "=concat(@(5,assetId),'.',@(1,name))",
                  "value": "=toString"
                }
              }
            }
          }
        }
      },
      {
        "operation": "shift",
        "spec": {
          "parameters": {
            "*": {
              "refParamAttrs": {
                "*": {
                  // make tagId and data be siblings
                  // Also, every output tag has a data array that is one element long,
                  //  so just hard coding that to be data[0]
                  "tagId":          "outer[&3].inner[&1].tagId",
                  "@(2,timestamp)": "outer[&3].inner[&1].data[0].ts",
                  "value":          "outer[&3].inner[&1].data[0].v"
                }
              }
            }
          }
        }
      },
      {
        // now that each item of inner array "looks" right
        //  accumulate them into a data array
        "operation": "shift",
        "spec": {
          "outer": {
            "*": {
              "inner": {
                "*": "tags[]"
              }
            }
          }
        }
      },
      {
        "operation": "default",
        "spec": {
          "tags[]": {
            "*": {
              "data[]": {
                "*": {
                  "q": "3"
                }
              }
            }
          }
        }
      }
    ]

Also please learn how to have your Json data nicely formatted in github.

**Comment by theamitojha** [comment]
Thanks , it is working as Expected. Could you please provide link for Jolt Documentation for our future references. We want to know/learn transformation operations performed in JOLT. (for example "@" "&" etc)
