### ISSUE TITLE
Is PascalCase to CamelCasing now possible with v0.1.1 for keys ?

### ISSUE THREAD

**Issue by dinesh-rajaveeran** [bazaarvoice/jolt#755]
Is PascalCase to CamelCase now possible with v0.1.1 for JSON keys without parsing through each and every field?
Input
```
{
  "ratings": {
    "Primary": 5,
    "Quality": 4,
    "Design": 5
  }
}
 ```

Expected output:

```
{
  "ratings": {
    "primary": 5,
    "quality": 4,
    "design": 5
  }
}
```

**Comment by milosimpson** [comment]
No.

**Comment by PeterWippermann** [comment]
@dinesh-rajaveeran you should write your own transformer for this. Maybe you could share it here afterwards?
