### ISSUE TITLE
Urgent : Need help with JOLT Transformation 

### ISSUE THREAD

**Issue by samdash** [bazaarvoice/jolt#756]
I need to convert JSON to JSON using Nifi JoltTransform JSON, also i do not want to loose other attributes like name and email ,I have tried different spec's , but sure how to do this one

Input JSON 
```
{
"name": "xyz",
"table": [{
        "data": {
            "counter": 1234,
            "customer": 2,
            "locale": "en"
        },
        "oldId": "345",
        "deleted": false,
       "details":{
        "a":1,
       "bb":2
        }
        }],
        "pKeys": ["data"],
            "pKeyVals": [{
                "counter": 1234,
                "customer": 2,
                "locale": "en"
            }],
          "email":"xyz@gmail.com"
            }
```

And my Expected output JSON: 

```
{
    "name": "xyz",
    "table": [{
        "counter": 1234,
        "customer": 2,
        "locale": "en",
        "oldId": "1234",
        "deleted": false,
         "details":{
         "a":1,
         "bb":2
        }
        }],
    "pKeys": ["[counter","customer","locale]"],
    "pKeyVals": [ "[1234,2,"en"]"],
    "email":"xyz@gmail.com"
}
```

**Comment by samdash** [comment]
I have tried below spec for table array, but deleted and oldId is put in array. need urgent help

```

[
  {
    "operation": "shift",
    "spec": {
      "name": "name",
      "*": {
        "*": {
          "*": {
            "counter": "tableDataList[&2].counter",
            "customer": "tableDataList[&2].customer",
            "locale": "tableDataList[&2].locale",
            "@(1,deleted)": "tableDataList[#1].deleted",
            "@(1,oldId)": "tableDataList[#1].oldId"
          }
        }
      }
    }
  }
]
```

and i am getting output as : 
```

{
  "name" : "xyz",
  "tableDataList" : [ {
    "deleted" : [ false, false, false ],
    "oldId" : [ "345", "345", "345" ],
    "counter" : 1234,
    "customer" : 2,
    "locale" : "en"
  } ]
}

```

**Comment by milosimpson** [comment]
You are trying to make a string version of Json as a Json value.   Which is a weird thing to do.

I can kinda be done by modify concat.

Spec

    [
      {
        "operation": "shift",
        "spec": {
          "name": "name",
          "table": {
            "*": {
              "data": {
                "counter": "table[&2].counter",
                "customer": "table[&2].customer",
                "locale": "table[&2].locale",
                "@(1,deleted)": "table[#1].deleted",
                "@(1,oldId)": "table[#1].oldId",
                "@locale": "OGpKeyVals[&2]",
                "@customer": "OGpKeyVals[&2]",
                "@counter": "OGpKeyVals[&2]"
              },
              "details": "table[&1].&"
            }
          }
        }
      },
      {
        "operation": "modify-default-beta",
        "spec": {
          "pKeys": "[[counter,customer,locale]]",
          "pKeyVals": "=concat('[[',@(1,OGpKeyVals[0][0]),',',@(1,OGpKeyVals[0][1]),',',@(1,OGpKeyVals[0][2]),']]')"
        }
      },
      {
        "operation": "remove",
        "spec": {
          "OGpKeyVals": ""
        }
      }
    ]
