### ISSUE TITLE
Conditional Shift Greater Than

### ISSUE THREAD

**Issue by CH-AhmetBombaci** [bazaarvoice/jolt#760]
I would like to generate JSON array elements based on different conditions. I have several amounts in my input JSON and I would like to generate mapping JSON object if its value is greater than zero. In this example; both values are greater than zero so output array will include both of them.

**Input**:
{
  "amountDetails": {
    "totalX1Amount": 100,
    "totalX2Amount": 50
  }
}

**Expected Output:**
"sampleArray" : [
  {
    "group": "GRP",
    "code": "PR",
    "subCode": "1",
    "amount": 50
  },
  {
    "segment": "GRP",
    "code": "PR",
    "subCode": "3",
    "amount": 100
  }
]

Is there any expression that I can use?

I also need to add two different elements to the same array so I am not so sure if it is possible.

My spec is not ideal at the moment since I am still trying to figure how to convert a field to an array but I will update that part when I make some progress about it.

Spec file:

[
  {
    "operation": "shift",
    "spec": {
      "amountDetails": {
        "totalX1Amount": "result.amount"
      }
    }
  },
  {
    "operation": "default",
    "spec": {
      "result": {
        "group": "GRP",
        "code": "PR",
        "subcode": "1"
      }
    }
  }
]

**Comment by milosimpson** [comment]
No.   Jolt Shift doesn't have conditional greater than / less than logic.

**Comment by OwenCowley** [comment]
@milosimpson Is there a recommended approach on NiFi which would enable condition filtering in a flow file?
Many thanks
