### ISSUE TITLE
Jolt timezone conversion

### ISSUE THREAD

**Issue by saideep12345** [bazaarvoice/jolt#761]
Hi @milosimpson , 
I have an use case where i needed to convert local timezoned DATE columns to UTC which should be taking care of DST aslo .

Is there a way we can achieve this in jolt transformation .

If Yes , could you please specify how do we transform those .

Thanks in Advance .

**Comment by PeterWippermann** [comment]
You would need to write your own transformer (an implementation of [Transform](https://github.com/bazaarvoice/jolt/blob/master/jolt-core/src/main/java/com/bazaarvoice/jolt/Transform.java)). I duplicated the Removr transformer and customised it to my needs.

However, I would not recommend to do it this way. Have you considered to have your JSON serialiser do this for you? Jackson has [a nice feature for this](https://fasterxml.github.io/jackson-databind/javadoc/2.2.0/com/fasterxml/jackson/databind/DeserializationFeature.html#ADJUST_DATES_TO_CONTEXT_TIME_ZONE).
