### ISSUE TITLE
Exporting Jolt transformation logic as a jar distribution?

### ISSUE THREAD

**Issue by viveksaikia22** [bazaarvoice/jolt#763]
I have created a project which does some structural transformation as well as some custom transformation using JOLT.
I would like to distribute this project as a jar file. Is it doable?

Can I input string object as input to Chainr rather than a file?

**Comment by milosimpson** [comment]
Yes.

If you have a String, then you need to convert that string into a List<Objects> then pass that to Chainr.fromSpec( Object input );
