### ISSUE TITLE
How can I move top level object to array property

### ISSUE THREAD

**Issue by kiranparab0** [bazaarvoice/jolt#764]
Here I am trying to add group as a property in every item of the array.

My input is like
`{
  "ABC": {
    "news": [{
        "datetime": "2019-03-06T14:12:00-05:00",
        "source": "source 1",
        "summary": "asd ada dsd f ef sdf vert"
      }
    ]
  },
  "XYZ": {
    "news": [{
        "datetime": "2019-03-06T14:12:00-05:00",
        "source": "source 1",
        "summary": "asd ada dsd f ef sdf vert"
      }
    ]
  }
}`

and the expected output is 
`"news": [{
    "symbol": "ABC",
    "datetime": "2019-03-06T14:12:00-05:00",
    "source": "source 1",
    "summary": "asd ada dsd f ef sdf vert"
  },
  {
    "symbol": "XYZ",
    "datetime": "2019-03-06T14:12:00-05:00",
    "source": "source 1",
    "summary": "asd ada dsd f ef sdf vert"
  }
]`

by using below spec I could merge two arrays, but now I am struggling to add symbol in the item.

`[{
  "operation": "shift",
  "spec": {
    "*": {
      "news": {
        "*": ""
      }
    }
  }
}]`

**Comment by milosimpson** [comment]
Two Shifts

    [
      {
        "operation": "shift",
        "spec": {
          "*": { // ABC
            "news": {
              "*": { // array index
                "*": "&3.news[&1].&", // replicate the imput
                // pull ABC / XYX down as "symbol"
                "$2": "&3.news[&1].symbol"
              }
            }
          }
        }
      },
      {
        "operation": "shift",
        "spec": {
          "*": { // ABC / XYZ
            "news": {
              // accumulate all the news items into 
              //  a top level news array
              "*": "news[]"
            }
          }
        }
      }
    ]
