### ISSUE TITLE
Need help in starting with spec

### ISSUE THREAD

**Issue by gopalkrishan77** [bazaarvoice/jolt#766]
I am extracting data from my HL7 message and getting in a JSON of form
{
"AA.CONTROLKEY"="KeyVal",
"AA.Col1":"VAL1",
"AA.Col2":"VAL2",
"BB.COL3":"VAL3",
"BB.col4":"VAL4"
}

It has only one CONTROLKEY and also a mix of uppercase and lowercase for all other key names and is flat. I am trying to subgroup the data and also convert all keys to lowercase. Problem I am facing is that I try to subgroup, then I can get to only first (AA) and if I try to convert to lowercase in that then I get null. I have been trying to find some reference guide to understand @&$ usage, but have not been that successful.

The outcome I am expecting to generate is
{
"controlid":"KeyVal",
"aa":{
  "col1":"VAL1",
  "col2":"VAL2"
  },
"bb":{
  "col3":"VAL3",
  "col4":"VAL4"
  }
}

I would appreciate any help and this would help me get started on my final spec. 
Regards,

**Comment by milosimpson** [comment]
The modify function that does toLower only works on values (right hand side) not keys (left hand side).   So first you need to pivot everything in to key/value pairs.   Lower case the keys, then pivot them back.

Spec

    [
      {
        // First find the controlid
        "operation": "shift",
        "spec": {
          "*.CONTROLKEY": "controlid",
          "*": "&" // passthru everything else
        }
      },
      {
        // next split AA.Col1 and pivot to key value pairs
        "operation": "shift",
        "spec": {
          "controlid": "controlid", // passthru controlid
          //
          // match things like AA.Col1
          // this assumes there is only one "."
          "*.*": {
            "$(0,1)": "pivoted.&1.key1",
            "$(0,2)": "pivoted.&1.key2",
            "@": "pivoted.&1.value"
          }
        }
      },
      {
        "operation": "modify-overwrite-beta",
        "spec": {
          "pivoted": {
            "*": {
              "key1": "=toLower",
              "key2": "=toLower"
            }
          }
        }
      },
      {
        "operation": "shift",
        "spec": {
          "controlid": "controlid", // passthru
          "pivoted": {
            "*": {
              // use lowercassed key1 and key2 to build the
              //  output path
              "value": "@(1,key1).@(1,key2)"
            }
          }
        }
      }
    ]

Run this in the demo site one operation at a time to see what it is doing.
