### ISSUE TITLE
Unit Testing of RESTful API services using Jolt Transform/Mapping gives RunTimeException

### ISSUE THREAD

**Issue by amitmangotra** [bazaarvoice/jolt#767]
Hi,

I am very new to jolt and am trying to write some unit tests to test RESTful API services which uses Jolt Transform/Mapping. When I try to do so, I get a RunTimeException:

> `java.lang.RuntimeException: Unable to load JSON file from: <FILE_PATH>`

while the API services work fine when I test them within the main function of those services.

I am not sure what I am missing or doing wrong here.

Can anyone please guide me through it?

Thanks.

**Comment by milosimpson** [comment]
If you are using JsonUtils to load spec or data files out of the classpath, then I have seen issues with Servlet ClassLoaders.

I.e. To be able to redeploy a war file with a bunch of servlets, the servlet container does a bunch of dark voodoo to be able to unload and reload classes with the same name via special ClassLoaders.

I assume you have a jar/war with your Java classes and Jolt Spec files.   Try using one of your Java classes to do the .getResourceAsStream() call, that way it is trying to pull from the same Jar.
