### ISSUE TITLE
Help while transforming the json using jolt spec

### ISSUE THREAD

**Issue by jdvlpr520** [bazaarvoice/jolt#768]
I am trying to jolt transformation spec for the below input :
`{
  "a": {
    "serviceTesta": "Testa1",
    "b": {
      "serviceTestb": "Testb1",
      "c": [
        {
          "name": "x",
          "value": "100",
          "desc": "this is description of X"
        },
        {
          "name": "y",
          "value": "200",
          "desc": "this is description of y"
        }
      ]
    }
  }
}`

and the expected output is as below :

`[
  {
    "Testa1_Testb1_x": "100",
    "Testa1_Testb1_x_desc": "this is description of X"
  },
  {
     "Testa1_Testb1_y": "100",
    "Testa1_Testb1_y_desc": "this is description of y"
  }
]`

My Spec :
`[
  {
    "operation": "shift",
    "spec": {
      "a": {
        "b": {
          "c": {
            "*": {
              "value": "@(4,serviceTesta).@(3,serviceTestb)@(1,name)"
            }
          }
        }
      }
    }
 }
 ]`

I  tried different ways , but couldnt get desired output. Any help is highly appreciated.

Thank you

**Comment by jdvlpr520** [comment]
@milosimpson 
Can you please help here ?
I have been trying from my end too, just that i am out of ideas :-(

Thank you

**Comment by milosimpson** [comment]
Spec

    [
      {
        "operation": "shift",
        "spec": {
          "a": {
            "b": {
              "c": {
                "*": {
                  // build nested structure of the data
                  "value": "[&1].@(4,serviceTesta).@(3,serviceTestb).@(1,name).value",
                  "desc":  "[&1].@(4,serviceTesta).@(3,serviceTestb).@(1,name).desc"
                }
              }
            }
          }
        }
      },
      {
        // then flatten the intermediate levels into a single string
        "operation": "shift",
        "spec": {
          "*": { // outer array index
            "*": { //Testa1
              "*": { // Testb1
                "*": { // x or y
                  "value": "[&4].&3_&2_&1",
                  "desc":  "[&4].&3_&2_&1_desc"
                }
              }
            }
          }
        }
      }
    ]
