### ISSUE TITLE
Help transforming the timestamp value

### ISSUE THREAD

**Issue by SudhakarReddyPeddinti** [bazaarvoice/jolt#769]
Input:
`{
"timeInMilli":1552434706457
}`

Output:
`{
"timeinSec":1552434706
}`

The divideAndRound function is giving value in this format`1.533871682E9` (Exponential representation is shown when the input number is more than 6 characters) when I divide by 1000. Is there any way around this?

**Comment by milosimpson** [comment]
Not that I know of.
