### ISSUE TITLE
Remove duplicates from the output

### ISSUE THREAD

**Issue by rogeriao** [bazaarvoice/jolt#770]
Hi guys, 

I went through some posts here and on the internet but I can't seem to find a way to remove duplicates from my output json. Any help or tip is really appreciated. 

Input Json 

`[
  {
    "manufacturerName": "COMPANY",
    "manufacturerCode": 1,
    "machineTypeCode": "ATMF"
  },
  {
    "manufacturerName": "COMPANY",
    "manufacturerCode": 1,
    "machineTypeCode": "ATMF"
  },
  {
    "manufacturerName": "COMPANY",
    "manufacturerCode": 1,
    "machineTypeCode": "DESK"
  }
]` 

Then I have the Jolt Spec 

[
  {
    "operation": "shift",
    "spec": {
      "*": {
        "manufacturerName": {
          "*": {
            "@2": "temp.&1[]"
          }
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "temp": {
        "*": {
          "0": {
            "manufacturerName": "[#3].manufacturerName",
            "manufacturerCode": "[#3].manufacturerCode",
            "machineTypeCode": "[#3].machineTypeCodes"
          },
          "*": {
            "machineTypeCode": "[#3].machineTypeCodes"
          }
        }
      }
    }
  }
]

And I get this result 

`[ {
  "manufacturerName" : "COMPANY",
  "manufacturerCode" : 1,
  "machineTypeCodes" : [ "ATMF", "ATMF", "DESK" ]
} ]`

My objective is to get rid of duplicates machineTypeCodes (like ATMF above)

Thanks,
Rogerio

**Comment by milosimpson** [comment]
Possible but not straightforward

Spec

    [
      // First pivot the data by name, manufacturerCode, machineTypeCode
      //  into a map structure, which "gets rid of" the duplicate 
      //  machineTypeCodes
      {
        "operation": "shift",
        "spec": {
          "*": { // array index
            "manufacturerName": {
              "*": { // match any manufacturerName
                "@2": {
                  "manufacturerCode": {
                    "*": { // match any manufacturerCode
                      "@5": {
                        "machineTypeCode": {
                          "*": "&6.&3.&"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      // Unpivot the "deduped" data back into a list with one item
      {
        "operation": "shift",
        "spec": {
          "*": {
            "$": "[0].manufacturerName",
            "*": {
              "$": "[0].manufacturerCode",
              "*": {
                // accumulate the distinct machineTypeCode into an array
                "$": "[0].machineTypeCodes[]"
              }
            }
          }
        }
      }
    ]

**Comment by rogeriao** [comment]
Hi Milo, thanks a lot for your reply! 

Along with some co-workers, we ended up with a spec. A little more verbose than yours tough... Thanks for being active on the responses and congratulations for the project. 

[
  {
    "operation": "shift",
    "spec": {
      "*": {
        "machineTypeName": {
          "*": {
            "@2": "temp.&1[]"
          }
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "temp": {
        "*": {
          "0": {
            "machineTypeName": "[#3].machineTypeName",
            "machineTypeCode": "[#3].machineTypeCode",
            "machineModelCode": "[#3].machineModels",
            "manufacturerCode": { "*": "[#0].ids.&[]" }
          },
          "*": {
            "machineModelCode": "[#3].machineModels",
            "manufacturerCode": { "*": "[#0].ids.&[]" }
          }
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "*": {
        "machineTypeName": "[#3].machineTypeName",
        "machineTypeCode": "[#3].machineTypeCode",
        "machineModels": "[#3].machineModels",
        "ids": {
          "*": {
            "$": "[#0].manufacturers[]"
          }
        }
      }
    }
  }
]

**Comment by rogeriao** [comment]
issue closed
