### ISSUE TITLE
Spec needed for input and output data

### ISSUE THREAD

**Issue by atomicspaj** [bazaarvoice/jolt#771]
I would JSON spec for transforming the input and output

input

{
"currentUser": "rob",
"decisionName": "complete",
"taskPIDs": [ "1234::BPM Process3::DataVerification::123::5000::201","1235::BPM Process3::DataVerification::123::5001::201" ],
"sourceOfBusiness" :true
}

OutPut
[
{
"currentUser": "rob",
"decisionName": "complete",
"taskPIDs":  "1234::BPM Process3::DataVerification::123::5000::201",
"sourceOfBusiness" :true
},
{
"currentUser": "rob",
"decisionName": "complete",
"taskPIDs":  "1235::BPM Process3::DataVerification::123::5001::201" ,
"sourceOfBusiness" :true
}
]

**Comment by milosimpson** [comment]
Spec

    [
      {
        "operation": "shift",
        "spec": {
          "taskPIDs": {
            "*": { // arrayIndex of taskPIDs array
              // "[&1]" means lookup the value 2 levels up the tree
              //        and use it as an array index in the output
              //
              // "@" is grab the value of the parent
              // "@(2,currentUser)" means navitate back up the tree 3 levels
              //      and then come down and grab the value of currentUser
              "@": "[&1].taskPID",
              "@(2,currentUser)": "[&1].currentUser",
              "@(2,decisionName)": "[&1].decisionName",
              "@(2,sourceOfBusiness)": "[&1].sourceOfBusiness"
            }
          }
        }
      }
    ]
