### ISSUE TITLE
Can I transform multiple input JSONs to a single output?

### ISSUE THREAD

**Issue by gauravabburi** [bazaarvoice/jolt#772]
Example:
Input 1 -
{
"email":"abc@xyg.com",
"name":"abc"
}

Input 2-
{
"educationalists":{
"postgraduate":"no",
"graduate":"yes"
}
}

Expected Output  

{
"name":"abc",
"mailId":"abc@abc.com",
"education":{
"higherdegree":"graduate"
}
}

**Comment by henry701** [comment]
Using code, wrap your JSONs into a map, and adjust the mapping to reflect it?

Input:
{
   inputs: [
{
"email":"abc@xyg.com",
"name":"abc"
},
{
"educationalists":{
"postgraduate":"no",
"graduate":"yes"
}
   ]
}

**Comment by milosimpson** [comment]
Yeah, what Henry said.   Outside of Jolt, "smush" your Json into a single file/Json and then you can have Jolt reformat it.
