### ISSUE TITLE
Jolt List to Map conversion

### ISSUE THREAD

**Issue by mamoray3** [bazaarvoice/jolt#773]
Hi Guys, 
I need help to transform the 
Input 
```
{
  "options" : [ {
    "key" : "account"
  }, {
    "key" : "member"
  } ]
}
```
To Output 
```
{
  "options" : [ {
    "key" : "account", 
	"value" : "account", 
	"enabled" : "true", 
  }, {
    "key" : "member", 
	"value" : "member", 
	"enabled" : "true", 
  } ]
}

```

**Comment by mamoray3** [comment]
I am able to transfer using below specification, in case if someone else is looking for the same 
```
 [{
    "operation": "shift",
    "spec": {
      "options": {
        "*": {
          "key": ["options.[&1].key", "options.[&1].value"]
        }
      }
    }
    }
]
```

**Comment by niernier007** [comment]
[
  {
    "operation": "shift",
    "spec": {
      "options": {
        "*": {
          "@": "options[&1]"
        }
      }
    }
  }, {
    "operation": "modify-default-beta",
    "spec": {
      "options": {
        "*": {
          "enabled": "true",
          "value": "@(1,key)"
        }
      }
    }
}]
