### ISSUE TITLE
Flat repeating JSON (with wildcard index) to array

### ISSUE THREAD

**Issue by calkno** [bazaarvoice/jolt#800]
I have a large flat JSON from a toJSONAttributes processor that I need to clean up in JOLT. It has repeating items that have indexes, but I've been unable to get a spec working correctly.

Input:
`{
"IN1_1.SetIDIN1": "1",
"IN1_1.InsurancePlanID.Identifier": "UNIT HLTH",
"IN1_1.InsuredsRelationshipToPatient.Identifier": "SELF",
"IN1_1.NameOfInsured.SecondAndFurtherGivenNamesOrInitialsThereof": "MATTHEW",
"IN1_1.NameOfInsured.GivenName": "GALE",
"IN1_1.NameOfInsured.FamilyName": "SEIBERT",
"IN1_1.NameOfInsured.DegreeEgMD": "MME"
"IN1_2.SetIDIN1": "2",
"IN1_2.InsurancePlanID.Identifier": "Medicare",
"IN1_2.InsuredsRelationshipToPatient.Identifier": "SELF",
"IN1_2.NameOfInsured.SecondAndFurtherGivenNamesOrInitialsThereof": "MATTHEW",
"IN1_2.NameOfInsured.GivenName": "GALE",
"IN1_2.NameOfInsured.FamilyName": "SEIBERT",
"IN1_2.NameOfInsured.DegreeEgMD": "MME"
}`

Desired Output:
`{
	"Insurance":[
	{
		"IN1_1.SetIDIN1": "1",
		"IN1_1.InsurancePlanID.Identifier": "UNIT HLTH",
		"IN1_1.InsuredsRelationshipToPatient.Identifier": "SELF",
		"IN1_1.NameOfInsured.SecondAndFurtherGivenNamesOrInitialsThereof": "MATTHEW",
		"IN1_1.NameOfInsured.GivenName": "GALE",
		"IN1_1.NameOfInsured.FamilyName": "SEIBERT",
		"IN1_1.NameOfInsured.DegreeEgMD": "MME"
	 },
	 {
		"IN1_2.SetIDIN1": "2",
		"IN1_2.InsurancePlanID.Identifier": "Medicare",
		"IN1_2.InsuredsRelationshipToPatient.Identifier": "SELF",
		"IN1_2.NameOfInsured.SecondAndFurtherGivenNamesOrInitialsThereof": "MATTHEW",
		"IN1_2.NameOfInsured.GivenName": "GALE",
		"IN1_2.NameOfInsured.FamilyName": "SEIBERT",
		"IN1_2.NameOfInsured.DegreeEgMD": "MME"
	}
	]
}`

**Comment by MagdaToczek** [comment]
Is it working for you?

```
[
  {
    "operation": "shift",
    "spec": {
      "IN1_*.*": {
        "@": "Insurance[&(1,1)].&1"
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "Insurance": {
        "*": "&1"
      }
    }
  }
]
```

**Comment by calkno** [comment]
Yes, that appears to have worked perfect. Could you please comment the spec to kind of explain what is happening?

**Comment by MagdaToczek** [comment]
I've done my best - hope it helps to clarify things for you
```
[
  {
    "operation": "shift",
    "spec": {
      // It is used for dividing key into sections to use value under each "*" later
      "IN1_*.*": {
        // @ means grab the value, and write it to "Insurance[&(1,1)].&1"
        // &(1,1) that matches value from first "*" (those above) with number of each children 
        // &1 means, go up one level and grab that value and substitute it 
        "@": "Insurance[&(1,1)].&1"
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "Insurance": {
        // It is used for removing null values
        "*": "&1"
      }
    }
  }
]

```

**Comment by calkno** [comment]
Thank you for your help. Now that I added this to my overall spec, my basic shifts that are not a part of the "Insurance" no longer work. How would I incorporate additional renaming for other values in the input json?

**Comment by MagdaToczek** [comment]
Yould should attach those to each operation, like this:
```
[
  {
    "operation": "shift",
    "spec": {
      "MSH.SendingFacility.NamespaceID": "sender",
      "IN1_*.*": {
        "@": "Insurance[&(1,1)].&1"
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "sender": "sender",
      "Insurance": {
        "*": "&1"
      }
    }
  }
]
```

**Comment by calkno** [comment]
ohhh, wow, that makes sense now that I see it. Thank you for all of your help
