### ISSUE TITLE
Merging element of Json Array by concatenating common attributes and others as it is

### ISSUE THREAD

**Issue by RaviNaganagouda** [bazaarvoice/jolt#804]
The input is like( NOTE: The attributes are dynamic so not sure always going to have these attributes)

```
[
  {
    "firstName": "Sam1",
    "lastName": "Achom1",
    "place": "Silchar1"
  },
  {
    "firstName": "Saya2",
    "lastName": "Singh2",
    "place": "Macherial2",
    "Second1stAttribute": "SomeValue"
  },
  {
    "firstName": "Sam3",
    "lastName": "Achom3",
    "place": "Silchar3",
    "Third2ndAttribute": "SomeValue2"
  }
]
```

And Expecting the output as

```
{ "firstName" : "Sam1 Saya2 Sam3",
  "lastName" : "Achom1 Singh2 Achom3",
  "place" : "Silchar1 Mancherial2 Silchar3",
  "Second1stAttribute" : "SomeValue",
  "Third2ndAttribute" : "SomeValue2"
}
```

Any suggestion would be very helpful. Thanks in advance

**Comment by MagdaToczek** [comment]
Something like that could works
```
[
  {
    "operation": "shift",
    "spec": {
      "*": {
        "firstName": "firstNameM",
        "lastName": "lastNameM",
        "place": "placeM",
        "Second1stAttribute": "Second1stAttribute",
        "Third2ndAttribute": "Third2ndAttribute"
      }
    }
  },
  {
    "operation": "modify-default-beta",
    "spec": {
      "firstName": "=join(' ',@(1,firstNameM))",
      "lastName": "=join(' ',@(1,lastNameM))",
      "place": "=join(' ',@(1,placeM))"
    }
  },
  {
    "operation": "shift",
    "spec": {
      "firstName": "firstName",
      "lastName": "lastName",
      "place": "place",
      "Second1stAttribute": "Second1stAttribute",
      "Third2ndAttribute": "Third2ndAttribute"
    }
  }
]

```

**Comment by RaviNaganagouda** [comment]
Thanks @MagdaToczek for reply. This spec is working perfect, but the only problem is all the Json array's attributes are dynamic. So I will be not knowing what attributes I will get, out of which what will be the common attributes in all element of array and what will be unique. If you can look into this it will great help. Thank you.

**Comment by MagdaToczek** [comment]
You meant to treat all arguments the same way?

```
[
  {
    "operation": "shift",
    "spec": {
      "*": {
        "firstName": "firstNameM[]",
        "lastName": "lastNameM[]",
        "place": "placeM[]",
        "Second1stAttribute": "Second1stAttributeM[]",
        "Third2ndAttribute": "Third2ndAttributeM[]"
      }
    }
  },
  {
    "operation": "modify-default-beta",
    "spec": {
      "firstName": "=join(' ',@(1,firstNameM))",
      "lastName": "=join(' ',@(1,lastNameM))",
      "place": "=join(' ',@(1,placeM))",
      "Second1stAttribute": "=join(' ',@(1,Second1stAttributeM))",
      "Third2ndAttribute": "=join(' ',@(1,Third2ndAttributeM))"
    }
  },
  {
    "operation": "shift",
    "spec": {
      "firstName": "firstName",
      "lastName": "lastName",
      "place": "place",
      "Second1stAttribute": "Second1stAttribute",
      "Third2ndAttribute": "Third2ndAttribute"
    }
  }
]

```

**Comment by RaviNaganagouda** [comment]
I meant other times I can have other attributes as well other than firstName, lastName in the NiFi flow. I can have payload like this also
```
[
  {
    "Institute": "InstiDyna",
    "description": "Digitize the Coperate World",
    "place": "Ny"
  },
  {
    "Institute": "QualityProd",
    "CertifiedBy": "VTU Inc",
    "Year": "2015",
  },
  {
    "Product": "Vanze Tyres",
    "Quality": "E Category",
    "Ranges": "All Types",
    "Type": "WithTube and Tubeless"
  }
]
```
If any element of array is having common attribute, then have to concatenate while merging. Otherwise if it is unique then just have to mention as it is. I can not be sure what attribute I will get in flow. It is dynamically generated.

**Comment by RaviNaganagouda** [comment]
> I meant other times I can have other attributes as well other than firstName, lastName in the NiFi flow. I can have payload like this also
> 
> ```
> [
>   {
>     "Institute": "InstiDyna",
>     "description": "Digitize the Coperate World",
>     "place": "Ny"
>   },
>   {
>     "Institute": "QualityProd",
>     "CertifiedBy": "VTU Inc",
>     "Year": "2015",
>   },
>   {
>     "Product": "Vanze Tyres",
>     "Quality": "E Category",
>     "Ranges": "All Types",
>     "Type": "WithTube and Tubeless"
>   }
> ]
> ```
> 
> If any element of array is having common attribute, then have to concatenate while merging. Otherwise if it is unique then just have to mention as it is. I can not be sure what attribute I will get in flow. It gets dynamically generated.

P.S : Yes all arguments should be treated the same way

**Comment by RaviNaganagouda** [comment]
> > I meant other times I can have different attributes other than firstName, lastName in the NiFi flow. I can have payload like this also
> > ```
> > [
> >   {
> >     "Institute": "InstiDyna",
> >     "description": "Digitize the Coperate World",
> >     "place": "Ny"
> >   },
> >   {
> >     "Institute": "QualityProd",
> >     "CertifiedBy": "VTU Inc",
> >     "Year": "2015",
> >   },
> >   {
> >     "Product": "Vanze Tyres",
> >     "Quality": "E Category",
> >     "Ranges": "All Types",
> >     "Type": "WithTube and Tubeless"
> >   }
> > ]
> > ```
> > 
> > 
> > If any element of array is having common attribute, then have to concatenate while merging. Otherwise if it is unique then just have to mention as it is. I can not be sure what attribute I will get in flow. It gets dynamically generated.
> 
> P.S : Yes all arguments should be treated the same way

And expected output would be

```
{
	"Institute": "InstiDyna QualityProd",
	"description": "Digitize the Coperate World",
    "place": "Ny"
    "CertifiedBy": "VTU Inc",
    "Year": "2015",
    "Product": "Vanze Tyres",
    "Quality": "E Category",
    "Ranges": "All Types",
    "Type": "WithTube and Tubeless"
}
```

**Comment by MagdaToczek** [comment]
I see, unfortunately I don't have any idea...

**Comment by RaviNaganagouda** [comment]
Okay. Thank you very much for your time. :)
