### ISSUE TITLE
NEED URGENT HELP : How to convert complicated JSON nested array with JOLT?

### ISSUE THREAD

**Issue by nenyri** [bazaarvoice/jolt#806]
I'm trying to convert nested arrays into objects depending on the number of values in the second nested array. I can't seem to get the number of the value fields and use that as a key in my spec. Now this is my input JSON file:

    `{
    "meta": {
      "regId": "us",
      "cId": "SomeProduct",
      "weId": 15

    },
    "data": {
         "name": "R",
      "details": {
       "headers": [
         "id",
       "cityId",
       "cityName"

     ],
     "values": [
       [
         1539,
         17,
         "Moskow"
       ],
       [
         1540,
         18,
         "Berlin"
       ],
       [
        1541,
         19,
         "Vienna"
       ]
        ]
      }
    }
        }`

My desired output:
    `     [  {"regId": "us",
        "cId": "SomeProduct",
        "weId": 15,
        "name":"R",
        "id":1539,
        "cityId":17,
        "cityName":Moskow
    },
    {"regId": "us",
        "cId": "SomeProduct",
        "weId": 15,
        "name":"R",
        "id":1540,
        "cityId":18,
        "cityName":Berlin
    },
    {"regId": "us",
        "cId": "SomeProduct",
        "weId": 15,
        "name":"R",
        "id":1541,
        "cityId":19,
        "cityName":Vienna
    }
]`

My current spec:
`[
	{ "operation": "shift",
    "spec": {
      "meta": {
        "*": "&"
      },
      "data": {
        "name": "&",
        "details": {
          "values": {
            "*": {
              "*": "&1.@(3,headers[&0])"
            }
          }
        }
      }
    }
    }
]
`
  

Hey [@MagdaToczek](https://github.com/MagdaToczek) do you mind taking a look?

**Comment by nenyri** [comment]
The trick is, number of headers and values will never be the same. Can I make it more dynamic?

**Comment by nenyri** [comment]
HI all, 

I made some progress, but still can't nest the meta into the elements:

`[
  {
    "operation": "shift",
    "spec": {
      "meta": {
        "*": "&"
      },
      "data": {
        "name": "&",
        "details": {
          "values": {
            "*": {
              "*": "&1.@(3,headers[&0])"
            }
          }
        }
      }
    }
  }
]`

**Comment by MagdaToczek** [comment]
Unfortunately, I don't have much time today. For a now I have go smt like that:
```
[
  {
    "operation": "shift",
    "spec": {
      "meta": {
        "*": "data1.&"
      },
      "data": {
        "name": "&",
        "details": {
          "values": {
            "*": {
              "*": "data2.&1.@(3,headers[&0])"
            }
          }
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "data2": {
        "*": {
          "@": "values.&1",
          "@(2,name)": "values.&1",
          "@(2,data1)": "values.&1"
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "values": {
        "*": {
          "@": "&"
        }
      }
    }
  }
]
```

**Comment by nenyri** [comment]
@MagdaToczek  thank you so much. I came a little closer by replacing the bottom spec to "@": "[&0]". Still working on the solution though. @mattyb149 I'm sorry to tag you like this. Please check out if you have time. Thanks all!

**Comment by MagdaToczek** [comment]
@nenyri please checkout if this is what you ment:
```
[
  {
    "operation": "shift",
    "spec": {
      "meta": {
        "*": "data1.&"
      },
      "data": {
        "name": "&",
        "details": {
          "values": {
            "*": {
              "*": "data2.&1.@(3,headers[&0])"
            }
          }
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "data1": "&",
      "name": "&",
      "data2": {
        "*": {
          "*": {
            "@": "data2[&2].&"
          }
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "data2": {
        "*": {
          "id": "inner[&1].id",
          "cityId": "inner[&1].cityId",
          "cityName": "inner[&1].cityName",
          "@(2,name)": "inner[&1].name",
          "@(2,data1)": {
            "regId": "inner[&2].regId",
            "cId": "inner[&2].cId",
            "weId": "inner[&2].weId"
          }
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "inner": ""
    }
  }
]

```

**Comment by nenyri** [comment]
@MagdaToczek thank you for your help and your time! this provides the correct output but the header names are hardcoded and I need them to be dynamic.  

This is the closest I got so far:

`[
  {
    "operation": "shift",
    "spec": {
      "meta": {
        "*": "&1"
      },
      "data": {
        "name": "&",
        "details": {
          "values": {
            "*": {
              "*": "data2.&1.@(3,headers[&0])"
            }
          }
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "data2": {
        "*": {
          "@(2,meta)": "values.&1",
          "@": "values.&1",
          "@(2,name)": "values.&1.name", //grab the name value R second name is hardcoding basicly the R
          "@(2,data1)": "values.&2"
        }
      }
    }
  }
  ,
  {
    "operation": "shift",
    "spec": {
      "values": {
        "*": {
          "@": "[&0]" //this removes the 0,1,2 element names
        }
      }
    }
    }
]
`

**Comment by MagdaToczek** [comment]
```
[
  {
    "operation": "shift",
    "spec": {
      "data": {
        "details": {
          "values": {
            "*": {
              "*": {
                "@": "data2[&2].@(4,headers[&0])"
              },
              "@(3,name)": "data2[&1].name",
              "@(4,meta)": {
                "*": "data2[&2].&"
              }
            }
          }
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "data2": ""
    }
  }
]

```

**Comment by nenyri** [comment]
@MagdaToczek  yes! this is correct! Thank you so so much! God bless you!

**Comment by MagdaToczek** [comment]
The word "meta" is that the only one that can be written with the capital letter?

**Comment by nenyri** [comment]
@MagdaToczek the only one. yes.

**Comment by MagdaToczek** [comment]
So maybe solution like below? Maybe it is not elegant but is working.
```
[
  {
    "operation": "shift",
    "spec": {
      "data": {
        "details": {
          "values": {
            "*": {
              "*": {
                "@": "data2[&2].@(4,headers[&0])"
              },
              "@(3,name)": "data2[&1].name",
              "@(4,meta)": {
                "*": "data2[&2].&"
              },
              "@(4,Meta)": {
                "*": "data2[&2].&"
              }
            }
          }
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "data2": ""
    }
  }
]

```

**Comment by nenyri** [comment]
I love how you hack. :) 
This will work. There will be no meta & Meta in combination.
