### ISSUE TITLE
URGENT: Need to copy elements from one element to all array elements in the resulting json

### ISSUE THREAD

**Issue by monisbhattiphilips** [bazaarvoice/jolt#807]
Hi,
  I need to perform a transformation from the input file to the expected output(both attached). I tried with the spec (attached) but it is unable to copy element from nested json to the resulting array -
i.e. from CCLF1.CLM_EFCTV_DT to all array element created in the output json.

All the files are attached. Please respond soon as we are evaluating jolt and this is critical.

Quick help would be really appreciated! :)

Regards,
Monis

[expected_output.txt](https://github.com/bazaarvoice/jolt/files/3201419/expected_output.txt)
[spec_used.txt](https://github.com/bazaarvoice/jolt/files/3201435/spec_used.txt)

[input.txt](https://github.com/bazaarvoice/jolt/files/3201388/input.txt)

**Comment by MagdaToczek** [comment]
Is it ok?
```
[
  {
    "operation": "shift",
    "spec": {
      "CCLF2": {
        "*": {
          "CCLF2.CUR_CLM_UNIQ_ID": "[&1].record.data.ClmNbr.datum",
          "CCLF2.CLM_LINE_NUM": "[&1].record.data.ClmDtlLnNbr.datum",
          "#STRING": ["[&1].record.data.ClmNbr.type",
                     "[&1].record.data.ClmDtlLnNbr.type",
                     "[&1].record.data.ClmDtlPdDtsk.type"],
          "#NIFI": "[&1].record.source",
          "#ClmLine": "[&1].record.type",
          "@(2,CCLF1)": {
            "CCLF1.CLM_EFCTV_DT": "[&2].record.data.ClmDtlPdDtsk.datum"
          }
        }
      }
    }
  }
]
```

**Comment by monisbhattiphilips** [comment]
Awesome! Thanks a ton! :)
