### ISSUE TITLE
Transforming nested JSON array to flat JSON array via Jolt transform

### ISSUE THREAD

**Issue by Akit8994** [bazaarvoice/jolt#809]
I have a nested JSON which I am trying to convert in to flat array JSON.

My input JSON : 
[
  {
    "label": "Contact Info",
    "name": "contactInfo",
    "id": "20039",
    "fieldList": [
      {
        "id": "20040",
        "label": "Phone",
        "name": "phone",
        "maxLength": 0,
        "fieldList": [
          {
            "id": "20281",
            "label": "Home Phone Number",
            "name": "homePhone",
            "maxLength": 0,
            "fieldList": [
              {
                "roleType": "I",
                "id": "20041",
                "label": "Type",
                "name": "pType",
                "maxLength": 1
              },
              {
                "id": "20042",
                "label": "Region",
                "name": "region",
                "maxLength": 0
              }
            ]
          },
          {
            "id": "20282",
            "label": "Business Phone Number",
            "name": "businessPhone",
            "maxLength": 0,
            "fieldList": [
              {
                "id": "20041",
                "label": "Type",
                "name": "pType",
                "maxLength": 1
              },
              {
                "id": "20042",
                "label": "Region",
                "name": "region",
                "maxLength": 0
              }
            ]
          },
          {
            "id": "20283",
            "label": "Cellular Phone Number",
            "name": "cellularPhone",
            "maxLength": 0,
            "fieldList": [
              {
                "id": "20041",
                "label": "Type",
                "name": "pType",
                "maxLength": 1
              },
              {
                "id": "20042",
                "label": "Region",
                "name": "region",
                "maxLength": 0
              }
            ]
          },
          {
            "id": "20175",
            "label": "Additional Phone Numbers",
            "name": "additionalPhones",
            "maxLength": 0,
            "fieldList": [
              {
                "id": "20041",
                "label": "Type",
                "name": "pType",
                "maxLength": 1
              },
              {
                "id": "20042",
                "label": "Region",
                "name": "region"
              }
            ]
          }
        ]
      }
    ]
  }
]

Desired Output :
{
  "party": "111",
  "uniqueId": "",
  "hierarchy": "123",
  "hierarchyValue": "",
  "expandCollapseSection": "Y",
  "section": [
    {
      "name": "additionalPhones",
      "label": "Additional Phones Info",
      "type": "grid",
      "default_enable": "Y",
      "default_selected": "N",
      "grid_columns": [
        {
          "name": "region",
          "label": "region"
        },
        {
          "name": "number",
          "label": "number"
        },
        {
          "name": "extension",
          "label": "extension"
        },
        {
          "name": "pType",
          "label": "pType"
        }
      ]
    },
    {
      "name": "homePhone",
      "label": "Home Phone Info",
      "type": "label",
      "fields": [
        {
          "name": "region",
          "label": "region"
        },
        {
          "name": "number",
          "label": "number"
        },
        {
          "name": "pType",
          "label": "pType"
        }
      ]
    },
    {
      "name": "businessPhone",
      "label": "Business Phone Info",
      "type": "label",
      "fields": [
        {
          "name": "region",
          "label": "region"
        },
        {
          "name": "extension",
          "label": "extension"
        },
        {
          "name": "number",
          "label": "number"
        },
        {
          "name": "pType",
          "label": "pType"
        }
      ]
    },
    {
      "name": "cellularPhone",
      "label": "Cellular Phone Info",
      "type": "label",
      "fields": [
        {
          "name": "region",
          "label": "region"
        },
        {
          "name": "number",
          "label": "number"
        },
        {
          "name": "pType",
          "label": "pType"
        }
      ]
    }
  ]
}

Spec : 
[

  {
    "operation": "shift",
    "spec": {
      "*": {
        "fieldList": {
          "*": {
            "name": "root[&3].data.fields[&1].name",
            "label": "root[&3].data.fields[&1].label",
            "fieldList": {
              "*": {
                "name": "root[&5].data.fields[&3].fields[&1].name",
                "label": "root[&5].data.fields[&3].fields[&1].label",
                "fieldList": {
                  "*": {
                    "name": "root[&7].data.fields[&5].fields[&3].fields[&1].name",
                    "label": "root[&7].data.fields[&5].fields[&3].fields[&1].label",
                    "fieldList": {
                      "*": {
                        "@": "root[&9].data.fields[&7].fields[&5].fields[&3]"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "root": {
        "*": {
          "data": "[]"
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "@": "section"
    }
   }
]

Please ignore the extra properties/values in expected json.

**Comment by BobbySingla** [comment]
@Akit8994 Your mentioned input and output fields doesn't match. What are the actual requirements you want in output ?  please write the expected output ..

**Comment by MagdaToczek** [comment]
Below I prepared example Spec for you, but it is not complete - you should explain from where take data to make missing fields
```
[
  {
    "operation": "shift",
    "spec": {
      "*": {
        "fieldList": {
          "*": {
            "fieldList": {
              "*": {
                "name": "section[&1].name",
                "label": "section[&1].label",
                "fieldList": {
                  "*": {
                    "name": "section[&3].grid_columns[&1].name",
                    "label": "section[&3].grid_columns[&1].label"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
]
```
