### ISSUE TITLE
Unexpected nulls in the JSON Array output

### ISSUE THREAD

**Issue by Ribhu4** [bazaarvoice/jolt#810]
Hi... I am doing transformation using JOLT and getting lot of null values along with the desired output which is slowing down the process. To show huge no of nulls I had to attach the files instead of pasting sample inputs
//Input
[input.txt](https://github.com/bazaarvoice/jolt/files/3216666/input.txt)
//Spec
[spec.txt](https://github.com/bazaarvoice/jolt/files/3216676/spec.txt)
// Desired Output
[output.txt](https://github.com/bazaarvoice/jolt/files/3216678/output.txt)

Please help

**Comment by wisthy** [comment]
the reason for the null is the "skus.[&1]" where the "&1" match the id. So, if you add something at index 10 in the array, Jolt will put null for all indexed between 0 and 9.

**Comment by wisthy** [comment]
Found it :)
Changed the first transformation to use a map instead of the list and then added a second transformation to shift back the map in a list.

```
[
  {
    "operation": "shift",
    "spec": {
      "*": {
        "*": {
          "products": {
            "*": {
              "productId": "ProductInfoResponsePayload.products.[&1].productId",
              "*": {
                "*": {
                  "skuId": {
                    "*": {
                      "@(2,size)": "ProductInfoResponsePayload.products[#3].skus.&1.size",
                      "@(2,transactionDateTime)": "ProductInfoResponsePayload.products[#3].skus.&1.transactionDateTime",
                      "@(2,availabilityStatus)": "ProductInfoResponsePayload.products[#3].skus.&1.availabilityStatus",
                      "@(2,stockLevel)": "ProductInfoResponsePayload.products[#3].skus.&1.stockLevel",
                      "@(2,storeInventory)": "ProductInfoResponsePayload.products[#3].skus.&1.storeInventory",
                      "@(2,stockThreshold)": "ProductInfoResponsePayload.products[#3].skus.&1.stockThreshold",
                      "@(2,showThresholdMessage)": "ProductInfoResponsePayload.products[#3].skus.&1.showThresholdMessage",
                      "@(2,msrp)": "ProductInfoResponsePayload.products[#3].skus.&1.msrp",
                      "@(2,salePrice)": "ProductInfoResponsePayload.products[#3].skus.&1.salePrice",
                      "@(2,listPrice)": "ProductInfoResponsePayload.products[#3].skus.&1.listPrice",
                      "@(2,currency)": "ProductInfoResponsePayload.products[#3].skus.&1.currency",
                      "@(2,promoMessage)": "ProductInfoResponsePayload.products[#3].skus.&1.promoMessage",
                      "@(2,priceStartDate)": "ProductInfoResponsePayload.products[#3].skus.&1.priceStartDate",
                      "@(2,promoCode)": "ProductInfoResponsePayload.products[#3].skus.&1.promoCode",
                      "@(2,promoPrice)": "ProductInfoResponsePayload.products[#3].skus.&1.promoPrice",
                      "@(2,errors)": "ProductInfoResponsePayload.products[#3].skus.&1.errors",
                      "$": "ProductInfoResponsePayload.products[#3].skus.&1.skuId"
                    }
                  }
                }
              }
            }
          }
        },
        "error": "error"
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "*": "&",
      "ProductInfoResponsePayload": {
        "*": "ProductInfoResponsePayload.&",
        "products": {
          "*": {
            "*": "ProductInfoResponsePayload.products[#3].&",
            "skus": {
              "*": {
                "*": {
                  "@": "ProductInfoResponsePayload.products[#3].skus[#5].&"
                }
              }
            }
          }
        }
      }

    }
  },
  {
    "operation": "cardinality",
    "spec": {
      "ProductInfoResponsePayload": {
        "products": {
          "*": {
            "*": "ONE",
            "skus": {
              "*": {
                "skuId": "ONE"
              }
            }
          }
        }
      },
      "error": "MANY"
    }
  }
]
```

**Comment by Ribhu4** [comment]
Thanks @wisthy This does the trick :)

Thanks for looking into this

> Found it :)
> Changed the first transformation to use a map instead of the list and then added a second transformation to shift back the map in a list.
> 
> ```
> [
>   {
>     "operation": "shift",
>     "spec": {
>       "*": {
>         "*": {
>           "products": {
>             "*": {
>               "productId": "ProductInfoResponsePayload.products.[&1].productId",
>               "*": {
>                 "*": {
>                   "skuId": {
>                     "*": {
>                       "@(2,size)": "ProductInfoResponsePayload.products[#3].skus.&1.size",
>                       "@(2,transactionDateTime)": "ProductInfoResponsePayload.products[#3].skus.&1.transactionDateTime",
>                       "@(2,availabilityStatus)": "ProductInfoResponsePayload.products[#3].skus.&1.availabilityStatus",
>                       "@(2,stockLevel)": "ProductInfoResponsePayload.products[#3].skus.&1.stockLevel",
>                       "@(2,storeInventory)": "ProductInfoResponsePayload.products[#3].skus.&1.storeInventory",
>                       "@(2,stockThreshold)": "ProductInfoResponsePayload.products[#3].skus.&1.stockThreshold",
>                       "@(2,showThresholdMessage)": "ProductInfoResponsePayload.products[#3].skus.&1.showThresholdMessage",
>                       "@(2,msrp)": "ProductInfoResponsePayload.products[#3].skus.&1.msrp",
>                       "@(2,salePrice)": "ProductInfoResponsePayload.products[#3].skus.&1.salePrice",
>                       "@(2,listPrice)": "ProductInfoResponsePayload.products[#3].skus.&1.listPrice",
>                       "@(2,currency)": "ProductInfoResponsePayload.products[#3].skus.&1.currency",
>                       "@(2,promoMessage)": "ProductInfoResponsePayload.products[#3].skus.&1.promoMessage",
>                       "@(2,priceStartDate)": "ProductInfoResponsePayload.products[#3].skus.&1.priceStartDate",
>                       "@(2,promoCode)": "ProductInfoResponsePayload.products[#3].skus.&1.promoCode",
>                       "@(2,promoPrice)": "ProductInfoResponsePayload.products[#3].skus.&1.promoPrice",
>                       "@(2,errors)": "ProductInfoResponsePayload.products[#3].skus.&1.errors",
>                       "$": "ProductInfoResponsePayload.products[#3].skus.&1.skuId"
>                     }
>                   }
>                 }
>               }
>             }
>           }
>         },
>         "error": "error"
>       }
>     }
>   },
>   {
>     "operation": "shift",
>     "spec": {
>       "*": "&",
>       "ProductInfoResponsePayload": {
>         "*": "ProductInfoResponsePayload.&",
>         "products": {
>           "*": {
>             "*": "ProductInfoResponsePayload.products[#3].&",
>             "skus": {
>               "*": {
>                 "*": {
>                   "@": "ProductInfoResponsePayload.products[#3].skus[#5].&"
>                 }
>               }
>             }
>           }
>         }
>       }
> 
>     }
>   },
>   {
>     "operation": "cardinality",
>     "spec": {
>       "ProductInfoResponsePayload": {
>         "products": {
>           "*": {
>             "*": "ONE",
>             "skus": {
>               "*": {
>                 "skuId": "ONE"
>               }
>             }
>           }
>         }
>       },
>       "error": "MANY"
>     }
>   }
> ]
> ```
