### ISSUE TITLE
Issue with concatenation with prefix

### ISSUE THREAD

**Issue by tmtanzeel** [bazaarvoice/jolt#814]
Why 'full' is empty

Input:-
{
  "CCLF6": [
    {
      "CCLF6.BENE_EQTBL_BIC_HICN_NUM": "801463155A",
      "CCLF6.CLM_CNTL_NUM": "first"
    },
    {
      "CCLF6.BENE_EQTBL_BIC_HICN_NUM": "801463155A",
      "CCLF6.CLM_CNTL_NUM": "second"
    },
    {
      "CCLF6.BENE_EQTBL_BIC_HICN_NUM": "801463155A",
      "CCLF6.CLM_CNTL_NUM": "third"
    },
    {
      "CCLF6.BENE_EQTBL_BIC_HICN_NUM": "801463155A",
      "CCLF6.CLM_CNTL_NUM": "fourth"
    }
  ]
}

Spec:-
[
  {
    "operation": "modify-default-beta",
    "spec": {
      "CCLF6": {
        "*": {
          "CCLF6.full": "=concat(@(1,BENE_EQTBL_BIC_HICN_NUM),' ',@(1,CLM_CNTL_NUM))"
        }
      }
    }
  }
]

output:-
{
  "CCLF6" : [ {
    "CCLF6.BENE_EQTBL_BIC_HICN_NUM" : "801463155A",
    "CCLF6.CLM_CNTL_NUM" : "first",
    "CCLF6.full" : " "
  }, {
    "CCLF6.BENE_EQTBL_BIC_HICN_NUM" : "801463155A",
    "CCLF6.CLM_CNTL_NUM" : "second",
    "CCLF6.full" : " "
  }, {
    "CCLF6.BENE_EQTBL_BIC_HICN_NUM" : "801463155A",
    "CCLF6.CLM_CNTL_NUM" : "third",
    "CCLF6.full" : " "
  }, {
    "CCLF6.BENE_EQTBL_BIC_HICN_NUM" : "801463155A",
    "CCLF6.CLM_CNTL_NUM" : "fourth",
    "CCLF6.full" : " "
  } ]
}

**Comment by BobbySingla** [comment]
@tmtanzeel what are your actual requirements in the output file. Please write your expected output file

**Comment by tmtanzeel** [comment]
output should be a combo of both the values :-
{
"CCLF6" : [ {
"CCLF6.BENE_EQTBL_BIC_HICN_NUM" : "801463155A",
"CCLF6.CLM_CNTL_NUM" : "first",
"CCLF6.full" : "801463155A first"
}, {
"CCLF6.BENE_EQTBL_BIC_HICN_NUM" : "801463155A",
"CCLF6.CLM_CNTL_NUM" : "second",
"CCLF6.full" : "801463155A second"
}, {
"CCLF6.BENE_EQTBL_BIC_HICN_NUM" : "801463155A",
"CCLF6.CLM_CNTL_NUM" : "third",
"CCLF6.full" : "801463155A third"
}, {
"CCLF6.BENE_EQTBL_BIC_HICN_NUM" : "801463155A",
"CCLF6.CLM_CNTL_NUM" : "fourth",
"CCLF6.full" : "801463155A fourth "
} ]
}

**Comment by tmtanzeel** [comment]
@BobbySingla 

output should be a combo of both the values :-
{
"CCLF6" : [ {
"CCLF6.BENE_EQTBL_BIC_HICN_NUM" : "801463155A",
"CCLF6.CLM_CNTL_NUM" : "first",
"CCLF6.full" : "801463155A first"
}, {
"CCLF6.BENE_EQTBL_BIC_HICN_NUM" : "801463155A",
"CCLF6.CLM_CNTL_NUM" : "second",
"CCLF6.full" : "801463155A second"
}, {
"CCLF6.BENE_EQTBL_BIC_HICN_NUM" : "801463155A",
"CCLF6.CLM_CNTL_NUM" : "third",
"CCLF6.full" : "801463155A third"
}, {
"CCLF6.BENE_EQTBL_BIC_HICN_NUM" : "801463155A",
"CCLF6.CLM_CNTL_NUM" : "fourth",
"CCLF6.full" : "801463155A fourth "
} ]
}

**Comment by priyadharshini13** [comment]
Jolt can not access the value if the key contains dot(.) operator as delimiter. '@(1,CCLF6.BENE_EQTBL_BIC_HICN_NUM) is not returning the corresponding value as it contains dot operator in key. Hence, I have first replaced the key with its substring (removed the prefix-CCLF6) then performed concat operation. 

**Spec**
[
  {
    "operation": "shift",
    "spec": {
      "CCLF6": {
        "*": {
          "CCLF6.*": "&2[#2].&(0,1)"
        }
      }
    }
},
  {
    "operation": "modify-default-beta",
    "spec": {
      "CCLF6": {
        "*": {
          "CCLF6.full": "=concat(@(1,BENE_EQTBL_BIC_HICN_NUM),' ',@(1,CLM_CNTL_NUM))"
        }
      }
    }
}
]

**Output**
{
  "CCLF6" : [ {
    "BENE_EQTBL_BIC_HICN_NUM" : "801463155A",
    "CLM_CNTL_NUM" : "first",
    "CCLF6.full" : "801463155A first"
  }, {
    "BENE_EQTBL_BIC_HICN_NUM" : "801463155A",
    "CLM_CNTL_NUM" : "second",
    "CCLF6.full" : "801463155A second"
  }, {
    "BENE_EQTBL_BIC_HICN_NUM" : "801463155A",
    "CLM_CNTL_NUM" : "third",
    "CCLF6.full" : "801463155A third"
  }, {
    "BENE_EQTBL_BIC_HICN_NUM" : "801463155A",
    "CLM_CNTL_NUM" : "fourth",
    "CCLF6.full" : "801463155A fourth"
  } ]
}
