### ISSUE TITLE
How to remove/filter nulls from the output/transformed JSON by JOLT

### ISSUE THREAD

**Issue by sudhakothari** [bazaarvoice/jolt#816]
The JSON output produced using the JOLT spec has null values in the nested array. I want to remove the null values and the children array in the example shudn't have any null values. That is it shud be filtered out.

I am attaching the input json, jolt spec and the output json produced and the desired one.
Desired/Expected output is not to have any null value in children.

[Jolt_spec.txt](https://github.com/bazaarvoice/jolt/files/3239904/Jolt_spec.txt)

[Json_expected.txt](https://github.com/bazaarvoice/jolt/files/3236544/Json_expected.txt)
[Json_input.txt](https://github.com/bazaarvoice/jolt/files/3236545/Json_input.txt)
[Json_output.txt](https://github.com/bazaarvoice/jolt/files/3236546/Json_output.txt)

**Comment by sudhakothari** [comment]
[Jolt_spec.txt](https://github.com/bazaarvoice/jolt/files/3239819/Jolt_spec.txt)

**Comment by MagdaToczek** [comment]
This added to the end of yours spec should work.
```
{
    "operation": "modify-overwrite-beta",
    "spec": {
      "*": "=recursivelySquashNulls"
    }
  }
```

**Comment by sudhakothari** [comment]
It works! Thanks so much!

**Comment by rustoherox** [comment]
Hello, guys!

Do you know how to squash full array if there is null?
Input:
`{ "uids" : [ [ 1, 2, null ], [ 1, 2, "3" ], [ 3, 4, "5" ]], "eventAttrs" : [ [ 12301, "A" ], [ 12309, null]] }`
Output:
`{ "uids" : [[ 1, 2, "3" ], [ 3, 4, "5" ]], "eventAttrs" : [[ 12301, "A" ]] }`
