### ISSUE TITLE
INTERESTING ISSUE: JSON Timestamp conversion to ISO 8601

### ISSUE THREAD

**Issue by nenyri** [bazaarvoice/jolt#818]
Hello all,

is it possible to convert a string to a timestamp of a certain format (ISO8601)? Actually, what I really need to do is check if a for instance dataFrom is in a certain format, and if it's not then convert it? can that be done through JOLT?
`[
  {
    "regId": "B2",
    "clId": "Some",
    "siId": 24,
    "dataFrom": "2019-04-24T11:11:02Z",
    "dataTo": "2019-04-24T11:22:02Z",
    "periodA": "00:01:32",
    "periodN": null
  },
  {
    "regId": "B2",
    "clId": "Some",
    "siId": 25,
    "dataFrom": "2019-02-24T11:11:02Z",
    "dataTo": "2019-02-24T11:22:02Z",
    "periodA": "00:01:32",
    "periodN": null
  },
  {
   "regId": "B2",
    "clId": "Some",
    "siId": 26,
    "dataFrom": "2019-03-24T11:11:02Z",
    "dataTo": "2019-03-24T11:22:02Z",
    "periodA": "00:01:32",
    "periodN": null
  }
]`

Spec:
`[
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "*": {
        "regId": "=toString",
        "clId": "=toString",
        "siId": "=toString",
        "dataFrom": "convert to date",
        "dataTo": "convert to date",
        "periodA": "convert to duration",
        "periodN": "convert to duration"
      }
    }
  }
]
`

@MagdaToczek do you mind taking a look?

**Comment by MagdaToczek** [comment]
I have no clue how to manage it...

**Comment by nenyri** [comment]
Thanks Magda!
