### ISSUE TITLE
Removing nulls from nested array is creating duplicates

### ISSUE THREAD

**Issue by gopimandava** [bazaarvoice/jolt#825]
I'm trying to remove all nulls from a JSON that has nested arrays. The spec is removing all the nulls but the nested arrays are duplicated in the output. Attached are the spec, input, output and the expected output. 

[spec.txt](https://github.com/bazaarvoice/jolt/files/3273931/spec.txt)
[input.txt](https://github.com/bazaarvoice/jolt/files/3273932/input.txt)
[output.txt](https://github.com/bazaarvoice/jolt/files/3273933/output.txt)
[expected_output.txt](https://github.com/bazaarvoice/jolt/files/3273934/expected_output.txt)

Can someone please help me fix the spec. Thanks.

**Comment by MagdaToczek** [comment]
Maybe such a spec solves your problem?
```
[
  {
    "operation": "shift",
    "spec": {
      "shpmtId": "t.shpmtId",
      "filrIdNbr": "t.filrIdNbr",
      "xprt": {
        "status": "t.xprt.status",
        "port": "t.xprt.port",
        "xprtLneList": {
          "*": {
            "id": "t.xprt.xprtLneList[&1].uid",
            "qty": "t.xprt.xprtLneList[&1].quantity",
            "val": "t.xprt.xprtLneList[&1].value"
          }
        }
      }
    }
  },
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "*": "=recursivelySquashNulls"
    }
  },
  {
    "operation": "shift",
    "spec": {
      "t": ""
    }
  }
]

```

**Comment by gopimandava** [comment]
That works perfectly. Thanks! Can you please explain what the last "shift" is doing, with "t" : "" ?

**Comment by MagdaToczek** [comment]
Firstly, I put everything into "t" object so I can use "=recursivelySquashNulls" for all input, and in the last step I removed "t" object.

**Comment by gopimandava** [comment]
thanks
