### ISSUE TITLE
NEED URGENT HELP With nested JOLT

### ISSUE THREAD

**Issue by nenyri** [bazaarvoice/jolt#826]
Hi All, 

I need to modify the spec for the following input:
    `{
  "header": {
    "namespace": "com.some.data",
    "version": "1.0.0"
  },
  "body": {
    "dataModel": {
      "sourceModel": [
        {
          "name": "countryName",
          "type": "string"
        },
        {
          "name": "cityName",
          "type": "string"
        },
        {
          "name": "neighbourhood Name",
          "type": "string"
        },
        {
          "name": "variable",
          "type": "string"
        },
        {
          "name": "unit",
          "type": "string"
        },
        {
          "name": "type",
          "type": "string"
        }
      ],
      "valueModel": [
        {
          "name": "timestamp",
          "type": "date-time"
        },
        {
          "name": "value",
          "type": "string"
        },
        {
          "name": "quality",
          "type": "integer"
        },
        {
          "name": "error",
          "type": "string"
        }
      ]
    },
    "data": [
      {
        "source": [
          "Uganda",
          "Kampala",
          "Some",
          "0",
          "NA",
          "NA"
        ],
        "values": [
          [
            "2019-06-10T08:17:44.431Z",
            "23",
            0,
            ""
          ],
		   [
            "2019-05-10T08:17:44.431Z",
            "21",
            1,
            ""
          ]
        ]
      }
    ]
  }
}`

To this output:
   `[
  {
    "countryName": "Uganda",
    "cityName": "Kampala",
    "neighbourhood Name": "Some",
    "variable": "0",
    "unit": "NA",
    "type": "NA",
    "timestamp": "2019-06-10T08:17:44.431Z",
    "value": "23",
    "quality": 0,
    "error": ""
  },
  {
    "countryName": "Uganda",
    "cityName": "Kampala",
    "neighbourhood Name": "Some",
    "variable": "0",
    "unit": "NA",
    "type": "NA",
    "timestamp": "2019-05-10T08:17:44.431Z",
    "value": "21",
    "quality": 1,
    "error": ""
  }
]`

I got stuck with the second SHIFT Transformation:
`[
  {
    "operation": "shift",
    "spec": {
      "body": {
        "data": {
          "*": {
            "source": {
              "*": "newdata.[&2].@(4,dataModel.sourceModel.[&].name)"
            },
            "values": {
              "*": {
                "*": "newdata.[&3].@(5,dataModel.valueModel[&].name)"
              } 
            }
          }
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "newdata": {
        "*": {
          "timestamp": {
            "*": {}
          }
        }
      }
    }
  }
]`

Current output is:
`{
  "newdata" : [ {
    "countryName" : "Uganda",
    "cityName" : "Kampala",
    "neighbourhood Name" : "Some",
    "variable" : "0",
    "unit" : "NA",
    "type" : "NA",
    "timestamp" : [ "2019-06-10T08:17:44.431Z", "2019-05-10T08:17:44.431Z" ],
    "value" : [ "23", "21" ],
    "quality" : [ 0, 1 ],
    "error" : [ "", "" ]
  } ]
}`

**Comment by nenyri** [comment]
UPDATE; 

I've managed to get all the elements except "header"  with the following spec? 
   `[
  {
    "operation": "shift",
    "spec": {
      "body": {
        "data": {
          "*": {
            "source": {
              "*": "newdata.[&2].@(4,dataModel.sourceModel.[&].name)"
            },
            "values": {
              "*": {
                "*": "newdata.[&3].@(5,dataModel.valueModel[&].name)"
              }
            }
          }
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "newdata": {
        "*": {
          "timestamp": {
            "*": {
              "@(2,countryName)": "better[&3].[&1].countryName",
              "@(2,cityName)": "better[&3].[&1].cityName",
              "@(2,neighbourhoodName)": "better[&3].[&1].neighbourhoodName",
              "@(2,variable)": "better[&3].[&1].variable",
              "@(2,unit)": "better[&3].[&1].unit",
              "@(2,type)": "better[&3].[&1].type",
              "@": "better.[&3].[&1].timestamp",
              "@(2,value[&])": "better.[&3].[&1].value",
              "@(2,quality[&])": "better.[&3].[&1].quality",
              "@(2,error[&])": "better.[&3].[&1].error"
            }
          }
        }
      }
    }
    }
  ,
  {
    "operation": "shift",
    "spec": {
      "better": {
        "*": {
          "*": ""
        }
      }
    }
  }
]`

**Comment by nenyri** [comment]
@mattyb149 do you mind taking a look?

**Comment by niernier007** [comment]
[
  {
    "operation": "shift",
    "spec": {
      "body": {
        "data": {
          "*": {
            "source": {
              "*": "@(4,dataModel.sourceModel.[&].name)"
            },
            "values": {
              "*": {
                "*": "model[&1].@(5,dataModel.valueModel.[&].name)"
              }
            }
          }
        }
      }
    }
  }, {
    "operation": "shift",
    "spec": {
      "model": {
        "*": {
          "@": "[&1]",
          "@(2,countryName)": "[&1].countryName",
          "@(2,cityName)": "[&1].cityName",
          "@(2,neighbourhood Name)": "[&1].neighbourhood Name",
          "@(2,variable)": "[&1].variable",
          "@(2,unit)": "[&1].unit",
          "@(2,type)": "[&1].type"
        }
      }
    }
  }
]

**Comment by nenyri** [comment]
@niernier007 I'm sorry, but your solution returns null. Anyhow, the solution above works ok.
