### ISSUE TITLE
Collapse multiple into a single object (and vice versa)

### ISSUE THREAD

**Issue by deveraben** [bazaarvoice/jolt#841]
I have an array of objects and I want to iterate through the objects and collapse every two sequentially into one object.. Please see below

**Input**

[
  {
    "type": "Buy",
    "amount": 250,
    "currency": "USD"
  },
  {
    "type": "Sell",
    "amount": 238,
    "currency": "EUR"
  },
  {
    "type": "Buy",
    "amount": 100,
    "currency": "CAD"
  },
  {
    "type": "Sell",
    "amount": 70,
    "currency": "USD"
  }
]

**Output**

[
  {
    "buyAmount": 250,
    "buyCurrency": "USD",
    "sellAmount": 238,
    "sellCurrency" : "EUR"
  },
  {
    "buyAmount": 100,
    "buyCurrency": "CAD",
    "sellAmount": 70,
    "sellCurrency" : "USD"
  }
]

Does anyone have an idea how this can be done?

**Comment by wisthy** [comment]
I did it by splitting first all the buys and sells in two differents arrays and then merging them in a second transformation.

```
[
  {
    "operation": "shift",
    // put all buys in an array and all sells in a second array
    "spec": {
      "*": {
        "type": {
          "Buy": {
            "@2": "buy[]"
          },
          "Sell": {
            "@2": "sell[]"
          }
        }
      }
    }
  },
  {
    "operation": "shift",
    // merge both arrays and rename fields
    "spec": {
      "*": {
        "*": {
          "amount": "[#2].&2Amount",
          "currency": "[#2].&2Currency"
        }
      }
    }
  }
]
```

**Comment by deveraben** [comment]
This worked!  Thanks!
