### ISSUE TITLE
JSON transform to String type

### ISSUE THREAD

**Issue by youtNa** [bazaarvoice/jolt#851]
Input is:
```
{
  "key": 342,
  "data": {
    "t1": 1234,
    "t2": "test"
  }
}
```

Expect output is:
```
{
  "key": 342,
  "data": "{
    \"t1\": 1234,
    \"t2\": \"test\",
  }"
}
```

I have use last spec to test:
```
[
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "data": "=toString(@(1,data))"
    }
  }
]
```
but it output:
```
{
	"key": 342,
	"data": "{t1=1234, t2=test}"
}
```
the output of data is not JSON.

can some one help me ? thanks

**Comment by wisthy** [comment]
basically, your expected output is not valid from a JSON point of view. It should us \n instead of line return. So something like

```
{
  "key": 342,
  "data": "{\n\"t1\": 1234, \n\"t2\": \"test\",\n}"
}
```

**Comment by youtNa** [comment]
Sorry
My Expect output is:
```
{
  "key": 342,
  "data": "{\"t1\": 1234,\"t2\": \"test\"}"
}
```
data is a JSON type String. 

But when i use `=toString` method to transform JSON, it out put like `t2= test ` not `t2:"test"`

**Comment by wisthy** [comment]
I was already working with the \n, you can remove it :)
```
[
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "data": "=concat('{\n\"t1\": ',@(0,t1),',\n\"t2\": \"',@(0,t2),'\"\n}')"
    }
  }
]
```

**Comment by youtNa** [comment]
thanks for your answer.

if i do not know definite key of data
maybe it is :
```
{
  "key": 342,
  "data": {
    "t1": 1234,
    "t2": "test",
    "d1": 20.12
  }
}
```
or 
```
{
  "key": 342,
  "data": {
    "a1": "test1",
    "t2": "test",
    "c1": 472
  }
}
```
or some other type. 

How can i do that?

**Comment by wisthy** [comment]
the point is if you don't know, how can jolt know?
in my version, I specified which fields to put quotes.
Another approach can be to put it everywhere.
Or if you have something that can be recognized in the name, we can use that.

**Comment by youtNa** [comment]
Is there some method to loop keys and concat to one key.

**Comment by youtNa** [comment]
Because i just want transform a json to string. So i do not need know the keys of data

**Comment by wisthy** [comment]
well, you can store the key iteself in a field as a first transformation and then concat them in a second trasnformation but not sure if you can loop

**Comment by wisthy** [comment]
will something like that help?
```
[
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "data": {
        "*": "=concat('\"',@(1,&),'\"')"
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "*": "&",
      "data": {
        "*": "data.\"&\""
      }
    }
  }
  ,

  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "data": "=toString(@(1,data))"
    }
    }

]

```


which given one of your last input gives

```
{
  "key" : 342,
  "data" : "{\"t1\"=\"1234\", \"t2\"=\"test\", \"d1\"=\"20.12\"}"
}

```

**Comment by wisthy** [comment]
hum, Just notice that ToString is using equal and not ":"

**Comment by youtNa** [comment]
yes. i think this requirement is so difficult . [cry]

**Comment by wisthy** [comment]
with a lot of tricks, got most of it right:

```
{
  "key" : 342,
  "data" : "{\"t1\":\"1234\",\"t2\":\"test\",\"d1\":\"20.12\"}"
}
```

with spec:
```
[
  {
    "operation": "shift",
    "spec": {
      "*": "&",
      "data": {
        "*": {
          "$": "tmp.field",
          "@": "tmp.value"
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "*": "&",
      "tmp": {
        "*": {
          "*": "tmp[#1].&1"
        }
      }
    }
  },
  {
    "operation": "modify-default-beta",
    "spec": {
      "tmp": {
        "*": {
          "tst": "=concat('\"',@(1,field),'\":\"',@(1,value),'\"')"
        }
      }
    }
  }
  ,
  {
    "operation": "shift",
    "spec": {
      "*": "&",
      "tmp": {
        "*": {
          "tst": "data"
        }
      }
    }
    },
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "data": "=join(',', @(1,data))"
    }
  },
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "data": "=concat('{', @(1,data), '}')"
    }
  }
]
``` 

There are probably way to make it more concise but wanted to move step by step

**Comment by youtNa** [comment]
thanks so much.

**Comment by youtNa** [comment]
Thanks so mush. your response is very useful. This also has some little problem. Such as `int` may transform to `string `and `null` also transform to empty string.
