### ISSUE TITLE
Nested array transform to array

### ISSUE THREAD

**Issue by deepuec** [bazaarvoice/jolt#852]
Hi, need your help in writing spec file to convert nested arrays.

Body and product arrays are merging from other objects

Input JSON:
`[
  {
    "ID": 1,
    "ProfileID": 12,
    "CreatedDateUtc": "2019-03-07T03:44:10Z",
    "Items": [
      {
        "ID": 1234,
        "Quantity": 1,
        "Products": [
          {
            "ID": 56
          }
        ]
      },
      {
        "ID": 99,
        "Quantity": 1,
        "Products": [
          {
            "ID": 6
          }
        ]
      }
    ]
  },
  {
    "ID": 2,
    "ProfileID": 12,
    "CreatedDateUtc": "2019-03-07T03:44:10Z",
    "Items": [
      {
        "ID": 12345,
        "Quantity": 2,
        "Products": [
          {
            "ID": 567
          }
        ]
      }
    ]
  }
]`

Spec:
`[
  {
    "operation": "shift",
    "spec": {
      "*": {
        "ID": "[&1].Order.Head.ID",
        "Items": {
          "*": {
            "ID": "[&1].Order.Body.[&1].Item_Id",
            "Products": {
              "*": {
                "ID": "[&1].Order.Product.[&1].ID"
              }
            }
          }
        },
        "CreatedDateUtc": {
          "*T*": {
            "$(0,1)": "[&1].Order.Head.Date",
            "$(0,2)": "[&1].Order.Head.Time"
          }
        }
      }
    }
    }

]`

Actual Output:
`[ {
  "Order" : {
    "Head" : {
      "ID" : 1
    },
    "Body" : [ {
      "Item_Id" : [ 1234, 12345 ]
    } ],
    "Product" : [ {
      "ID" : [ 56, 6, 567 ]
    } ]
  }
}, {
  "Order" : {
    "Body" : [ null, {
      "Item_Id" : 99
    } ],
    "Head" : {
      "ID" : 2
    }
  }
} ]
`

Expected output:
`[ {
  "Order" : {
    "Head" : {
      "ID" : 1,
      "Date":"2019-03-07",
      "Time":"03:44:10Z"
    },
    "Body" : [ {
      "Item_Id" : 1234
    },
     {
      "Item_Id" : 12345
    } ],
    "Product" : [ {
      "ID" : 56
    },
     {
      "ID" : 6
    }]
  }
}, {
  "Order" : {
    "Body" : [ {
      "Item_Id" : 99
    } ],
    "Product" : [ {
      "ID" : 56
    }],
    "Head" : {
      "ID" : 2,
      "Date":"2019-03-07",
      "Time":"03:44:10Z"
    }
  }
} ]
`

**Comment by wisthy** [comment]
Here you are, some tweaks on array index and issue is solved :)

```
[
  {
    "operation": "shift",
    "spec": {
      "*": {
        "ID": "[&1].Order.Head.ID",
        "CreatedDateUtc": {
          "*T*": {
            "$(0,1)": "[&3].Order.Head.Date",
            "$(0,2)": "[&3].Order.Head.Time"
          }
        },
        //["[&1].Order.Head.Date", "[&1].Order.Head.Time"],
        "Items": {
          "*": {
            "ID": "[&3].Order.Body.[&1].Item_Id",
            "Products": {
              "*": {
                "ID": "[&5].Order.Product.[&3].ID"
              }
            }
          }
        }
      }
    }
  }
]
```

**Comment by deepuec** [comment]
@wisthy  Thank you very much.

**Comment by wisthy** [comment]
please close the issue if it is solved for you
