### ISSUE TITLE
Looking to transform my input json

### ISSUE THREAD

**Issue by homewised** [bazaarvoice/jolt#853]
Hi,

I am looking to transform my input json;
{
  "aggregations": {
    "geocountry": {
      "buckets": [
        {
          "key": "country1",
          "geostate": {
            "buckets": [
              {
                "key": "state1",
                "geocity": {
                  "buckets": [
                    {
                      "key": "city1",
                      "centroid": {
                        "location": {
                          "lat": -10.1111111,
                          "lon": 11.22222222
                        },
                        "count": 5
                      }
                    },
					{
                      "key": "city2",
                      "centroid": {
                        "location": {
                          "lat": -10.333333,
                          "lon": 11.444444
                        },
                        "count": 5
                      }
                    }
                  ]
                }
              },
              {
                "key": "state2",
                "geocity": {
                  "buckets": [
                    {
                      "key": "city3",
                      "centroid": {
                        "location": {
                          "lat": -12.5555555,
                          "lon": 13.666666666
                        }
                      }
                    },
					{
                      "key": "city4",
                      "centroid": {
                        "location": {
                          "lat": -12.777777777,
                          "lon": 13.88888888888
                        }
                      }
                    }
                  ]
                }
              }
            ]
          }
        },
        {
          "key": "country2",
          "geostate": {
            "buckets": [
              {
                "key": "state1",
                "geocity": {
                  "buckets": [
                    {
                      "key": "city1",
                      "centroid": {
                        "location": {
                          "lat": -14.9999999,
                          "lon": -15.99999999
                        },
                        "count": 5
                      }
                    }
                  ]
                }
              }
            ]
          }
        }
      ]
    }
  }
}

Expected Output:
{
  "users_by_location" : [ {
    "location" : "country1,state1,city1,-10.1111111,11.22222222"
  },
 {
    "location" : "country1,state1,city2, -10.333333,11.444444"
  },
 {
    "location" : "country1,state2,city3,-12.5555555,13.666666666"
  },
 {
    "location" : "country1,state2,city4,-12.777777777,13.88888888888"
  },  {
    "location" : "country2,state1,city1,-14.9999999,-15.99999999"
  } ]
}

Getting below out put.. country2 data is good for me 

{
  "users_by_location" : [ {
    "location" : "country1,[state1, state2],[city1, city2, city3, city4],[-10.1111111, -10.333333, -12.5555555, -12.777777777],[11.22222222, 11.444444, 13.666666666, 13.88888888888]"
  }, {
    "location" : "country2,state1,city1,-14.9999999,-15.99999999"
  } ]
}

I have used below Jolt spec

[
  {
    "operation": "shift",
    "spec": {
      "aggregations": {
        "geocountry": {
          "buckets": {
            "*": {
              "key": "[&1].country",
              "geostate": {
                "buckets": {
                  "*": {
                    "key": "[&4].state",
                    "geocity": {
                      "buckets": {
                        "*": {
                          "key": "[&7].city",
                          "centroid": {
                            "location": {
                              "lat": "[&9].lat",
                              "lon": "[&9].lon"
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "*": {
        "users_by_location": {
          "[0]": {
            "location": "=concat(@(3,country),',',@(3,state),',',@(3,city),',',@(3,lat),',',@(3,lon))"
          }
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "*": {
        "users_by_location": {
          "*": "users_by_location"
        }
      }
    }
  }
]

**Comment by wisthy** [comment]
basically, you started properly by having a separate entry for each country but after that you loose the separation for different states, different countries and worst, you loose the link between state and city. 

After your first transformation it's not possible anymore to tell if city3 belongs to state1 or state2 for example.

So, instead, I went the other way. First crawl to the deepest item (lat/lon) and copy all the parents (city,state,country) info needed. All of that stored in a bunch of synchronized array (see that like a 2D array)
Then, do a small trick to transpose the array in a way easier to run the concat
Then, concat it (same as your second transfo)
Then, a new shift to get rid of all the fields except the location (again, same as you)

So, you had most of it right except the grouping at the beginning.

```
[
  {
    "operation": "shift",
    "spec": {
      "*": {
        "*": {
          "*": {
            "*": {
              //"key": "user_by_location[#1].country",
              "geostate": {
                "buckets": {
                  "*": {
                    "geocity": {
                      "buckets": {
                        "*": {
                          //"key": "user_by_location[#7].a[#4].b[#1].city",
                          "centroid": {
                            "location": {
                              "*": {
                                "@": "user_by_location.&1"
                              },
                              "@(2,key)": "user_by_location.city",
                              "@(5,key)": "user_by_location.state",
                              "@(8,key)": "user_by_location.country"
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "*": {
        "*": {
          "*": {
            "@": "user_by_location.[&1].&2"
          }
        }
      }
    }
  },
  {
    "operation": "modify-default-beta",
    "spec": {
      "user_by_location": {
        "*": {
          "location": "=concat(@(1,country), ',' ,@(1,state), ',' ,@(1,city), ',' ,@(1,lat), ',' ,@(1,lon))"
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "*": {
        "*": {
          "location": "user_by_location.[&1].&"
        }
      }
    }
  }
  ]
```

**Comment by homewised** [comment]
Thank you very much Wisthy for your quick response. It is working fine for above json sample.
Actually, I am new to jolt transformation and have not posted my whole json in my revious request, after adding your users_by_location to my existing spec it is not returning any data.

Could you please help me here.

{
  "aggregations": {
    "app_name": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 0,
      "buckets": [
        {
          "key": "App3",
          "doc_count": 10,
          "cdouble_key": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": [
              {
                "key": "Age1",
                "doc_count": 5,
                "cdouble_value,stats": {
                  "count": 5,
                  "min": 25,
                  "max": 25,
                  "avg": 25,
                  "sum": 125
                }
              },
              {
                "key": "Age2",
                "doc_count": 5,
                "cdouble_value,stats": {
                  "count": 5,
                  "min": 25,
                  "max": 25,
                  "avg": 25,
                  "sum": 125
                }
              }
            ]
          }
        }
      ]
    },
    "users": {
      "value": 10
    },
    "retention": {
      "value": 5
    },
    "geolocation": {
      "buckets": [
        {
          "key": "AU",
          "geostate": {
            "buckets": [
              {
                "key": "TASMANIA",
                "geocity": {
                  "buckets": [
                    {
                      "key": "PELVERATA",
                      "centroid": {
                        "location": {
                          "lat": -68.2048502471298,
                          "lon": 141.61519965156913
                        }
                      }
                    }
                  ]
                }
              },
              {
                "key": "WESTERN AUSTRALIA",
                "geocity": {
                  "buckets": [
                    {
                      "key": "GREEN HEAD",
                      "centroid": {
                        "location": {
                          "lat": -30.87930000387132,
                          "lon": 111.10809998586774
                        }
                      }
                    }
                  ]
                }
              }
            ]
          }
        },
        {
          "key": "CL",
          "geostate": {
            "buckets": [
              {
                "key": "ANTOFAGASTA",
                "geocity": {
                  "buckets": [
                    {
                      "key": "CAMINO DEL YESO",
                      "centroid": {
                        "location": {
                          "lat": -23.257900066673756,
                          "lon": -72.94730013236403
                        }
                      }
                    }
                  ]
                }
              },
              {
                "key": "MAGALLANES Y DE LA ANTARTICA CHILENA",
                "geocity": {
                  "buckets": [
                    {
                      "key": "SAN JUAN",
                      "centroid": {
                        "location": {
                          "lat": -81.37880003079772,
                          "lon": -88.23090009391308
                        }
                      }
                    }
                  ]
                }
              },
              {
                "key": "VALPARAISO",
                "geocity": {
                  "buckets": [
                    {
                      "key": "CALETON",
                      "centroid": {
                        "location": {
                          "lat": -26.11280000768602,
                          "lon": -112.40620013326406
                        }
                      }
                    }
                  ]
                }
              }
            ]
          }
        },
        {
          "key": "BR",
          "doc_count": 5,
          "geostate": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": [
              {
                "key": "MATO GROSSO",
                "doc_count": 5,
                "geocity": {
                  "doc_count_error_upper_bound": 0,
                  "sum_other_doc_count": 0,
                  "buckets": [
                    {
                      "key": "PEIXE DE COURO",
                      "doc_count": 5,
                      "centroid": {
                        "location": {
                          "lat": -17.435900028795004,
                          "lon": -55.258700139820576
                        },
                        "count": 5
                      }
                    }
                  ]
                }
              }
            ]
          }
        },
        {
          "key": "CA",
          "doc_count": 5,
          "geostate": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": []
          }
        },
        {
          "key": "ID",
          "doc_count": 5,
          "geostate": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": [
              {
                "key": "NUSA TENGGARA TIMUR",
                "doc_count": 5,
                "geocity": {
                  "doc_count_error_upper_bound": 0,
                  "sum_other_doc_count": 0,
                  "buckets": [
                    {
                      "key": "NEMBRALA",
                      "doc_count": 5,
                      "centroid": {
                        "location": {
                          "lat": -13.025500075891614,
                          "lon": 122.0490999519825
                        },
                        "count": 5
                      }
                    }
                  ]
                }
              }
            ]
          }
        },
        {
          "key": "KE",
          "doc_count": 5,
          "geostate": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": [
              {
                "key": "EASTERN",
                "doc_count": 5,
                "geocity": {
                  "doc_count_error_upper_bound": 0,
                  "sum_other_doc_count": 0,
                  "buckets": [
                    {
                      "key": "SKWATA",
                      "doc_count": 5,
                      "centroid": {
                        "location": {
                          "lat": -1.9846000615507364,
                          "lon": 38.50779991596937
                        },
                        "count": 5
                      }
                    }
                  ]
                }
              }
            ]
          }
        },
        {
          "key": "NO",
          "doc_count": 5,
          "geostate": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": [
              {
                "key": "FINNMARK",
                "doc_count": 5,
                "geocity": {
                  "doc_count_error_upper_bound": 0,
                  "sum_other_doc_count": 0,
                  "buckets": [
                    {
                      "key": "SORVAER",
                      "doc_count": 5,
                      "centroid": {
                        "location": {
                          "lat": 74.99199994839728,
                          "lon": 20.828599892556667
                        },
                        "count": 5
                      }
                    }
                  ]
                }
              }
            ]
          }
        },
        {
          "key": "NZ",
          "doc_count": 5,
          "geostate": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": [
              {
                "key": "HAWKE'S BAY",
                "doc_count": 5,
                "geocity": {
                  "doc_count_error_upper_bound": 0,
                  "sum_other_doc_count": 0,
                  "buckets": [
                    {
                      "key": "POUKAWA",
                      "doc_count": 5,
                      "centroid": {
                        "location": {
                          "lat": -39.79250008240342,
                          "lon": 176.7517999559641
                        },
                        "count": 5
                      }
                    }
                  ]
                }
              }
            ]
          }
        },
        {
          "key": "PF",
          "doc_count": 5,
          "geostate": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": []
          }
        },
        {
          "key": "PN",
          "doc_count": 5,
          "geostate": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": []
          }
        }
      ]
    }
  }
}

================ Expected Json output ===========


[{
"users" : 10,
  "retention" : 5,
  "kpis_d" : [ {
    "mName" : "Age1",
    "mSum" : 125,
    "mCount" : 5
  }, {
    "mName" : "Age2",
    "mSum" : 125,
    "mCount" : 5
  } ],
  "user_by_location" : [ {
    "location" : "AU,TASMANIA,PELVERATA,-68.2048502471298,141.61519965156913"
  }, {
    "location" : "AU,WESTERN AUSTRALIA,GREEN HEAD,-30.87930000387132,111.10809998586774"
  }, {
    "location" : "CL,ANTOFAGASTA,CAMINO DEL YESO,-23.257900066673756,-72.94730013236403"
  }, {
    "location" : "CL,MAGALLANES Y DE LA ANTARTICA CHILENA,SAN JUAN,-81.37880003079772,-88.23090009391308"
  }, {
    "location" : "CL,VALPARAISO,CALETON,-26.11280000768602,-112.40620013326406"
  }, {
    "location" : "BR,MATO GROSSO,PEIXE DE COURO,-17.435900028795004,-55.258700139820576"
  }, {
    "location" : "ID,NUSA TENGGARA TIMUR,NEMBRALA,-13.025500075891614,122.0490999519825"
  }, {
    "location" : "KE,EASTERN,SKWATA,-1.9846000615507364,38.50779991596937"
  }, {
    "location" : "NO,FINNMARK,SORVAER,74.99199994839728,20.828599892556667"
  }, {
    "location" : "NZ,HAWKE'S BAY,POUKAWA,-39.79250008240342,176.7517999559641"
  } ]
}]

===== Jolt Spec for other than location ========
[
  {
    "operation": "shift",
    "spec": {
      "aggregations": {
        "users": {
          "value": "[#2].users"
        },
        "retention": {
          "value": "[#1].retention"
        },
        "app_name": {
          "buckets": {
            "*": {
              "cdouble_key": {
                "buckets": {
                  "*": {
                    "key": "[#3].kpis_d.[#2].mName",
                    "cdouble_value,stats": {
                      "sum": "[#4].kpis_d.[#3].mSum",
                      "count": "[#4].kpis_d.[#3].mCount"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
]

**Comment by homewised** [comment]
Thank you very much Wisthy for your quick response. It is working fine for above sample.
I am new to jolt transformation and tried for my requirement and i was able to transform some portion of the json.  After adding your solution to my working jolt spec it is not returning any data. I am facing problem to merge both spec to get consolidated json format.

Could you please help me here.


{
  "took": 11,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 10,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "app_name": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 0,
      "buckets": [
        {
          "key": "App3",
          "doc_count": 10,
          "cdouble_key": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": [
              {
                "key": "Age1",
                "doc_count": 5,
                "cdouble_value,stats": {
                  "count": 5,
                  "min": 25,
                  "max": 25,
                  "avg": 25,
                  "sum": 125
                }
              },
              {
                "key": "Age2",
                "doc_count": 5,
                "cdouble_value,stats": {
                  "count": 5,
                  "min": 25,
                  "max": 25,
                  "avg": 25,
                  "sum": 125
                }
              }
            ]
          }
        }
      ]
    },
    "users": {
      "value": 10
    },
    "retention": {
      "value": 5
    },
    "geocountry": {
      "buckets": [
        {
          "key": "country1",
          "geostate": {
            "buckets": [
              {
                "key": "state1",
                "geocity": {
                  "buckets": [
                    {
                      "key": "city1",
                      "centroid": {
                        "location": {
                          "lat": -10.1111111,
                          "lon": 11.22222222
                        },
                        "count": 5
                      }
                    },
                    {
                      "key": "city2",
                      "centroid": {
                        "location": {
                          "lat": -10.333333,
                          "lon": 11.444444
                        },
                        "count": 5
                      }
                    }
                  ]
                }
              },
              {
                "key": "state2",
                "geocity": {
                  "buckets": [
                    {
                      "key": "city3",
                      "centroid": {
                        "location": {
                          "lat": -12.5555555,
                          "lon": 13.666666666
                        }
                      }
                    },
                    {
                      "key": "city4",
                      "centroid": {
                        "location": {
                          "lat": -12.777777777,
                          "lon": 13.88888888888
                        }
                      }
                    }
                  ]
                }
              }
            ]
          }
        },
        {
          "key": "country2",
          "geostate": {
            "buckets": [
              {
                "key": "state1",
                "geocity": {
                  "buckets": [
                    {
                      "key": "city1",
                      "centroid": {
                        "location": {
                          "lat": -14.9999999,
                          "lon": -15.99999999
                        },
                        "count": 5
                      }
                    }
                  ]
                }
              }
            ]
          }
        }
      ]
    }
  }
}

================ Expected Json output ===========


[{
"users" : 10,
  "retention" : 5,
  "kpis_d" : [ {
    "mName" : "Age1",
    "mSum" : 125,
    "mCount" : 5
  }, {
    "mName" : "Age2",
    "mSum" : 125,
    "mCount" : 5
  } ],
 
  "user_by_location" : [ {
    "location" : "country1,state1,city1,-10.1111111,11.22222222"
  }, {
    "location" : "country1,state1,city2,-10.333333,11.444444"
  }, {
    "location" : "country1,state2,city3,-12.5555555,13.666666666"
  }, {
    "location" : "country1,state2,city4,-12.777777777,13.88888888888"
  }, {
    "location" : "country2,state1,city1,-14.9999999,-15.99999999"
  } ]


}]

===== Jolt Spec for other than users_by_location ========
[
  {
    "operation": "shift",
    "spec": {
      "aggregations": {
        "users": {
          "value": "[#2].users"
        },
        "retention": {
          "value": "[#1].retention"
        },
        "app_name": {
          "buckets": {
            "*": {
              "cdouble_key": {
                "buckets": {
                  "*": {
                    "key": "[#3].kpis_d.[#2].mName",
                    "cdouble_value,stats": {
                      "sum": "[#4].kpis_d.[#3].mSum",
                      "count": "[#4].kpis_d.[#3].mCount"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
]

**Comment by wisthy** [comment]
here you are. Basically, some "as-is copy" to be added and of course the indexed to shift 

```
[
  {
    "operation": "shift",
    "spec": {
      "aggregations": {
        "users": {
          "value": "[#2].users"
        },
        "retention": {
          "value": "[#1].retention"
        },
        "geocountry": {
          "buckets": {
            "*": {
              "geostate": {
                "buckets": {
                  "*": {
                    "geocity": {
                      "buckets": {
                        "*": {
                          "centroid": {
                            "location": {
                              "*": {
                                "@": "[#12].user_by_location.&1"
                              },
                              "@(2,key)": "[#11].user_by_location.city",
                              "@(5,key)": "[#11].user_by_location.state",
                              "@(8,key)": "[#11].user_by_location.country"
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "app_name": {
          "buckets": {
            "*": {
              "cdouble_key": {
                "buckets": {
                  "*": {
                    "key": "[#3].kpis_d.[#2].mName",
                    "cdouble_value,stats": {
                      "sum": "[#4].kpis_d.[#3].mSum",
                      "count": "[#4].kpis_d.[#3].mCount"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
},

  {
    "operation": "shift",
    "spec": {
      "*": {
        "*": "[#2].&",
        "user_by_location": {
          "*": {
            "*": {
              "@": "[#5].&3.[&1].&2"
            }
          }
        }
      }
    }
    }
  ,
  {
    "operation": "modify-default-beta",
    "spec": {
      "*": {
        "user_by_location": {
          "*": {
            "location": "=concat(@(1,country), ',' ,@(1,state), ',' ,@(1,city), ',' ,@(1,lat), ',' ,@(1,lon))"
          }
        }
      }
    }
    }
  ,
  {
    "operation": "shift",
    "spec": {
      "*": {
        "*": "[&1].&",
        "user_by_location": {
          "*": {
            "location": "[&3].&2.[&1].&"
          }
        }
      }
    }
      }
]
```

**Comment by homewised** [comment]
Thank you Wisthy. It is working fine.

**Comment by wisthy** [comment]
happy to help. Don't forget to close the issue :)
