### ISSUE TITLE
jolt transform left joining arrays

### ISSUE THREAD

**Issue by jayachandrakumar** [bazaarvoice/jolt#856]
I tried JOLT for performing Left join on arrays but it was unsuccessful. Please help me on jolt spec for below.

Input Json:
{  
   "state":[  
      {  
         "statecode":"1",
         "statename":"AP",
         "description":"V1"
      },
      {  
         "statecode":"2",
         "statename":"KN",
         "description":"V2"
      }
   ],
   "schools":[  
      {  
         "statecode":"1",
         "schoolcode":123,
         "schoolname":"George",
         "schoolstatus":"active"
      },
      {  
         "statecode":"1",
         "schoolcode":589,
         "schoolname":"Kenneth",
         "schoolstatus":"active"
      },
      {  
         "statecode":"2",
         "schoolcode":234,
         "schoolname":"StJhons",
         "schoolstatus":"active"
      },
      {  
         "statecode":"9",
         "schoolcode":789,
         "schoolname":"Jhonson",
         "schoolstatus":"active"
      }
   ]
}

output Json:

{  
   "state":[  
      {  
         "statecode":"1",
         "statename":"AP",
         "description":"V1",
         "schools":[  
            {  
               "schoolcode":123,
               "schoolname":"George",
               "schoolstatus":"active"
            },
            {  
               "schoolcode":589,
               "schoolname":"Kenneth",
               "schoolstatus":"active"
            }
         ]
      },
      {  
         "statecode":"2",
         "statename":"KN",
         "description":"V2",
         "schools":[  
            {  
               "schoolcode":234,
               "schoolname":"StJhons",
               "schoolstatus":"active"
            }
         ]
      }
   ]
}

**Comment by wisthy** [comment]
here is the tricks:

- transform sate into a map using statecode as the key
- move school to proper state using that key as a map to avoid null items in it
- transform school map back to array 
- transform state map back to array and filter state that contains only school data

```
[
  {
    "operation": "shift",
    "spec": {
      "state": {
        "*": {
          "*": "state.@(1,statecode).&"
        }
      },
      "schools": {
        "*": {
          "statecode": {
            "*": {
              "@(2,schoolcode)": "state.&1.school.&3.schoolcode",
              "@(2,schoolname)": "state.&1.school.&3.schoolname",
              "@(2,schoolstatus)": "state.&1.school.&3.schoolstatus"
            }
          }
        }
      }
    }
   },
  {
    "operation": "shift",
    "spec": {
      "state": {
        "*": {
          "*": "state[&1].&",
          "school": {
            "*": {
              "@": "state[&3].scholl[]"
            }
          }
        }
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "state": {
        "*": {
          "statecode": {
            "@1": "state[]"
          }
        }
      }
    }
    }
]
```

**Comment by jayachandrakumar** [comment]
Thanks @wisthy for the spec, it is working fine.
