### ISSUE TITLE
Transform one level in n depth array

### ISSUE THREAD

**Issue by rajimanu** [bazaarvoice/jolt#868]
Hi @milosimpson

Input Json:

{

"customers": [{
		"timestamp": "2016-07-29T00:20:11+0000",
		"attributes": [{

				"categ": "Width",
				"values": [{
						"id": 12,
						"name": {
							"val1": "",
							"val2": ""
						}
					},
					{
						"id": 14,
						"name": {
							"val1": "",
							"val2": ""
						}
					}
				]
			},
			{
				"values": [{
						"id": 18,
						"name": {
							"val1": "",
							"val2": ""
						}
					},
					{
						"id": 17,
						"name": {
							"val1": "",
							"val2": ""
						}
					}

				],
				"categ": "eee"
			}
		]
	},
	{
		"timestamp": "2019-07-29T00:20:11+0000",
		"attributes": [{

			"name": "Width",
			"values": [{
				"id": 12,
				"name": {
					"val1": "",
					"val2": ""
				}
			}]
		}]
	}
]
}

Expected output:

{

"customers": [{
		"timestamp": "2016-07-29T00:20:11+0000",
		"attributes": [{

				"categ": "Width",
				"values": [{
						"id": 12,
						"name": {
							"val1": "",
							"val2": ""
						}
					},
					{
						"id": 14,
						"name": {
							"val1": "",
							"val2": ""
						}
					}
				]
			},
			{
				"categ": "eee",
				"values": [

					{
						"id": "an",
						"name": {
							"code": [18, 17]

						}
					}

				]

			}
		]
	},
	{
		"timestamp": "2019-07-29T00:20:11+0000",
		"attributes": [{

			"name": "Width",
			"values": [{
				"id": 12,
				"name": {
					"val1": "",
					"val2": ""
				}
			}]
		}]
	}
]
}

I am new to jolt .Please help me with the transformation. I really appreciate the help

**Comment by wisthy** [comment]
the trick in the first place, is that the transformation to apply is driven by the value of one of the field. So, first step is to go down to leaf value, isolate the "eee" and then process the field and the neighboor based on that.

The second trick needed, is that on the neighboor field "id", the structure is too complex to do it on the fly with the "@(....)" in the left hand side. So, to make it easier, we transfer the full field in the temporary variable and we do a second spec to get what we need in it and to put it back in the right place in the customers tree.

```
[
  {
    "operation": "shift",
    "spec": {
      "customers": {
        "*": {
          "*": "customers[&1].&",
          "attributes": {
            "*": {
              "name": {
                "*": {// that * level is not really required but it allows to copy/paste from the categ field, so from a laziness point of view, it's better :)
                  "@(2,categ)": "customers[&5].attributes[&3].categ",
                  "@(2,values)": "customers[&5].attributes[&3].values"
                }
              },
              "categ": {
                "eee": {
                  "@(2,categ)": "customers[&5].attributes[&3].categ",
                  "#an": "customers[&5].attributes[&3].values[0].id",
                  "@(2,values)": "tmp.&5.&3" // using a map instead of an array to avoid null in it
                },
                "*": {
                  "@(2,categ)": "customers[&5].attributes[&3].categ",
                  "@(2,values)": "customers[&5].attributes[&3].values"
                }
              }
            }
          }
        }
      }
    }
  }

    ,
  {
    "operation": "shift",
    "spec": {
      "customers": "customers",
      "tmp": {
        "*": {
          "*": {
            "*": {
              "id": "customers[&3].attributes[&2].values[0].name.code"
            }
          }
        }
      }
    }
      }
]

```

**Comment by rajimanu** [comment]
Hi wisthy ,
Can you Please explain   "#an": "customers[&5].attributes[&3].values[0].id"  this step.

**Comment by wisthy** [comment]
sure. 
`"#XXX":"YYY"` mean that we want to create a new field with value XXX and put it at the address YYY.
So, in this case, we want to put "an" in the field id, in the index 0 of the array values in ... (guess I don't have to decompose all the addressing :))

**Comment by rajimanu** [comment]
Thank you so much.. It working... Please explain( customers[&5].attributes[&3]) indexing. why its 5 and  3 here."id": "customers[&3].attributes[&2].values[0].name.code"( 3 and 2 here)

**Comment by rajimanu** [comment]
Hi witsy,
Please help me to transorm this

Input JSON
{
	"result": {
		"timestamp": "2016-07-29T00:20:11+0000",
		"attr": {
			"attributes": [{

				"categ": "Width",
				"values": [{
						"id": 12,
						"name": {
							"val1": "",
							"val2": ""
						}
					},
					{
						"id": 14,
						"name": {
							"val1": "",
							"val2": ""
						}
					}
				]
			}]
		},


		"customers": [{
				"timestamp": "2016-07-29T00:20:11+0000",
				"attributes": [{

						"categ": "Width",
						"values": [{
								"id": 12,
								"name": {
									"val1": "",
									"val2": ""
								}
							},
							{
								"id": 14,
								"name": {
									"val1": "",
									"val2": ""
								}
							}
						]
					},
					{
						"values": [{
								"id": 18,
								"name": {
									"val1": "",
									"val2": ""
								}
							},
							{
								"id": 17,
								"name": {
									"val1": "",
									"val2": ""
								}
							}

						],
						"categ": "eee"
					}
				]
			},
			{
				"timestamp": "2019-07-29T00:20:11+0000",
				"attributes": [{

					"name": "Width",
					"values": [{
						"id": 12,
						"name": {
							"val1": "",
							"val2": ""
						}
					}]
				}]
			}
		]
	}
}

Expected Output:

{
	"result": {
		"timestamp": "2016-07-29T00:20:11+0000",
		"attr": {
			"attributes": [{

				"categ": "Width",
				"values": [{
						"id": 12,
						"name": {
							"val1": "",
							"val2": ""
						}
					},
					{
						"id": 14,
						"name": {
							"val1": "",
							"val2": ""
						}
					}
				]
			}]
		},


		"customers": [{
				"timestamp": "2016-07-29T00:20:11+0000",
				"attributes": [{

						"categ": "Width",
						"values": [{
								"id": 12,
								"name": {
									"val1": "",
									"val2": ""
								}
							},
							{
								"id": 14,
								"name": {
									"val1": "",
									"val2": ""
								}
							}
						]
					},
					{
 					"categ": "eee",
 					"values": [

 						{
 							"id": "an",
 							"name": {
 								"code": [18, 17]

 							}
 						}

 					]

 				}
				]
			},
			{
				"timestamp": "2019-07-29T00:20:11+0000",
				"attributes": [{

					"name": "Width",
					"values": [{
						"id": 12,
						"name": {
							"val1": "",
							"val2": ""
						}
					}]
				}]
			}
		]
	}
}

**Comment by wisthy** [comment]
let's start with the question first. Indexing is done backward. &0 is the element you are currently at. &1 is the parent, &2 the parent's parent and so on.

```
...
      "*": { // &5 index array of customers
          "attributes": { //&4
            "*": { //&3 - index array of attributes
              "name": { // &2
                "*": {// &1
                  "@(2,categ)": "customers[&5].attributes[&3].categ",
...
```

Now, I'll have a look a your next message

**Comment by wisthy** [comment]
ok, straitforward, just add result a little bit everywhere :)

```
[
  {
    "operation": "shift",
    "spec": {
      "result": {
        "*": "result.&",
        "customers": {
          "*": {
            "*": "result.customers[&1].&",
            "attributes": {
              "*": {
                "name": {
                  "*": { // that * level is not really required but it allows to copy/paste from the categ field, so from a laziness point of view, it's better :)
                    "@(2,categ)": "result.customers[&5].attributes[&3].categ",
                    "@(2,values)": "result.customers[&5].attributes[&3].values"
                  }
                },
                "categ": {
                  "eee": {
                    "@(2,categ)": "result.customers[&5].attributes[&3].categ",
                    "#an": "result.customers[&5].attributes[&3].values[0].id",
                    "@(2,values)": "tmp.&5.&3" // using a map instead of an array to avoid null in it
                  },
                  "*": {
                    "@(2,categ)": "result.customers[&5].attributes[&3].categ",
                    "@(2,values)": "result.customers[&5].attributes[&3].values"
                  }
                }
              }
            }
          }
        }
      }
    }
  }

    ,
  {
    "operation": "shift",
    "spec": {
      "result": "result",
      "tmp": {
        "*": {
          "*": {
            "*": {
              "id": "result.customers[&3].attributes[&2].values[0].name.code"
            }
          }
        }
      }
    }
      }
]
```

**Comment by rajimanu** [comment]
Hi wisthy,
Kindly explain the following 
@(2,values)": "tmp.&5.&3(why it's 5 & 3 and what does it mean)
"id": "result.customers[&3].attributes[&2].values[0].name.code"(How the index are 3 and 2 here)
