### ISSUE TITLE
Transform input json as the value of another json

### ISSUE THREAD

**Issue by harshadloya** [bazaarvoice/jolt#869]
Cannot do the following:

Input Json:
{
"x" : {
    "a" : "123",
    "b" : "456",
    "c" : {
        "d" : "789"
    }
  }
}

Output Json Expected:
{
"data" : "x={
    a=123, b=456,
    c={d=789}}"
}

**Comment by wisthy** [comment]
Hello,
First of all, please put your json extract in between \`\`\` to increase readability.

Regarding your issue, jolt is not really meant for that kind of transformation. It's probably doable  for your specific example but will need rework as soon as you change a single field name in it. And it will be very complex even for such a small input.

So, not sure it's worth doing it in jolt. My advice would be to do such transformation inside your application directly.

**Comment by wisthy** [comment]
hum, I played a little bit on it to see how hard it would be and in fact I was wrong, it's doable and not that hard. Just had a little trick at the end to have `"data" : "x={...}"` while jolt is going for `"data":"{x={...}}"`

```
[
  {
    "operation": "shift",
    "spec": {
      "x": "data.x"
    }
  },
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "data": "=toString(@(1,data.x))"
    }
  },
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "data": "=concat('x=', @(1,data))"
    }
  }
]
```

which gives as output:


```
{
  "data" : "x={a=123, b=456, c={d=789}}"
}

```

**Comment by harshadloya** [comment]
Thank you so much!
