### ISSUE TITLE
Displaying Default value in Array of objects

### ISSUE THREAD

**Issue by uday40** [bazaarvoice/jolt#870]
Trying to display the default value in transform objects 
**Actual JSON**

{
  "data": {
    "item": [
      {
        "clientId": "35",
        "hidden": false
      },
      {
        "clientId": "35",
        "hidden": false
      }
    ]
  }
}

Expected 
=========
{
  "Item": [
    {
      "id": "35",
      "defaultvalue": "testing"
    },
    {
      "id": "36",
      "defaultvalue": "testing"
    }
  ]
}

**Comment by wisthy** [comment]
what you need is the constant value. Putting `"#aaa":"bbb"` would put text *aaa* in the field *bbb*
```
[
  {
    "operation": "shift",
    "spec": {
      "data": {
        "item": {
          "*": {
            "clientId": "item[&1].&",
            "#testing": "item[&1].defaultValue"
          }
        }
      }
    }
      }
]
```

**Comment by uday40** [comment]
Thank you very much, it worked 
But could you please help me to get the below output. 3 Different keys with same default value 
I tried below one but it's not working as expected . Please suggest

[
  {
    "operation": "shift",
    "spec": {
      "data": {
        "item": {
          "*": {
            "clientId": "item[&1].&",
            "#testing": "item[&1].defaultValue",
            "#testing": "item[&1].defaultValue1",
            "#testing": "item[&1].defaultValue2"
          }
        }
      }
    }
      }
]


Expected output
=============


{
  "item": [
    {
      "defaultValue": "testing",
      "defaultValue1": "testing",
      "defaultValue2": "testing",
      "clientId": "35"
    },
    {
      "defaultValue": "testing",
      "defaultValue1": "testing",
      "defaultValue2": "testing",
      "clientId": "36"
    }
  ]
}

**Comment by wisthy** [comment]
Jolt is not allowing several time the same key (left side value). 
But the good news is that you can put several addressess (right side value) for the same key using an array `"#aaa":["bbb","ccc"]`

```
[
  {
    "operation": "shift",
    "spec": {
      "data": {
        "item": {
          "*": {
            "clientId": "item[&1].&",
            "#testing": [
              	"item[&1].defaultValue",
              	"item[&1].defaultValue1",
              	"item[&1].defaultValue2"
              ]
          }
        }
      }
    }
      }
]
```

**Comment by uday40** [comment]
Thank you very much !!

**Comment by uday40** [comment]
Thanks

**Comment by wisthy** [comment]
you're welcome :)
