### ISSUE TITLE
Jolt transformation help

### ISSUE THREAD

**Issue by heman2019** [bazaarvoice/jolt#871]
Hi Team,

I want to do json transformation using jolt. below is the input and expected output. But not really getting much options to do so. Please let me know anyone has any clue on it 

Input 
[ 
{
"county" : "IN"},
{"state" : "MH"},
{"city" : "MUM"}
]

Output
[ 
{"county" : "IN", "state" : "MH"},
{"county" : "IN", "city" : "MUM"}
]

Basically the requirement is to copy tags from 1st record to 2nd onwards.

Thanks,
Hemant

**Comment by wisthy** [comment]
Hello,

First thing first, please put all your json fragments in between \`\`\`, it make it a lot more readable.

Now with the actual problem. To make it work without knowing the number of items in the array of the name of the field to duplicate, it requires some tricks. I documented the specs while doing it, should be clear. If you have question, feel free to ask it :)

```
[
  {
    "operation": "shift",
    "spec": {
      "0": null, // we don't display the first index
      "*": {
        "@(2,[0])": "tmp.&1", // we copy the value of first index in a tmp map
        "@": "tmp.&1" // we copy the current index in the same tmp map node
      }
    }
  },
  {
    "operation": "shift",
    "spec": {
      "tmp": {
        "*": {
          "*": {
            "*": "tmp.&2.&" // get rid of inner array [{a=x},{b=y}] => {a=x,b=y}
          }
        }
      }
    }
  },

  {
    "operation": "shift",
    "spec": {
      "tmp": {
        "*": "" // replace temporary map to root level array. Temporary map was required to avoid a null index in the array
      }
    }
    }
]
```

**Comment by heman2019** [comment]
Hi Wisthy,

Thank you very much for the reply, it covers my requirement. may be one slight addition, one of my incoming field is timestamp in India (Asia/Kolkata) time in milliseconds (1370368714000000000), where as I need to convert it to UTC considering daylight savings. Is that possible in jolt or I need to use some scripting like python 

[
{
"county" : "IN"},
{"state" : "MH"},
{"city" : "MUM"},
....
{"time" : "1370368714000000000"}
]


Again thanks for the quickest reply.

Thanks,
Hemant

**Comment by wisthy** [comment]
well, jolt is not meant for that to start with. 
Now, is it doable? 
Changing the timezone when you have time in milliseconds is just a matter of adding or substracting a fix number. So, that much is doable using the `longSum` spec.
Taking care of the daylight savings need you to extract the day/month out of the date, then figure out a way in jolt to test if that date fragment is between two others fragments and then add or remove one hour. That's a lot of work so I'll definitely suggest to do it elsewhere :)

**Comment by heman2019** [comment]
Thanks for your help and suggestion
