### ISSUE TITLE
Spec errors should have location and context

### ISSUE THREAD

**Issue by Tihamer54** [bazaarvoice/jolt#88]
I'm a fumble-fingered fugitive from typing class who couldn't data-enter a JSON file correctly if my life depended on it. So I really appreciate the fix you made in 0.13 that identifies row and column for JSON format mistakes. Unfortunately, even if I get the JSON format correct, I can still make Jolt DSL mistakes and then have no clue on where I did something wrong. For example, if I have a JSON-legal leaf that reads:

 {  "value": "&$3.DollarsEarned" }

Then Jolt gives me the error:

 DotNotation (write key) can not contain '@', '*', or '$'.

This is nice, but it does not give me row and column. I know, the location information is probably lost when the json file was sucked into a Chainr object, but there are ways to preserve it (as attributes called joltRow and joltColumn if nothing else; I have modified XML parsers to do the same thing). At any rate, without too much work, I changed line 46 of ShiftrWriter.java to read:

 throw new SpecException("DotNotation (write key) can not contain '@', '*', or '$' at " + dotNotation + ".");

Now, the error output gives me some context:

 DotNotation (write key) can not contain '@', '*', or '$' at root.&$3.DollarsEarned.

Giving context and location in every SpecException would be nice. The problem is that there are lots of them (which is a great thing, BTW). I'd change them all myself, except:
1. I might break something,
2. I'm not so familiar with the code that I know exactly how to get location.
3. Some people might not like to see more error information (IMHO, they are silly), and
4. Upper management might not approve of my giving away source code.

So all I can do is ask.

Pretty please.

**Comment by milosimpson** [comment]
All / Most spec exceptions should now return as much context as they can in their error message.  
Also the Demo Site was updated to return the server side error message.

Closing this as fixed.
