### ISSUE TITLE
Last Four Digits of a value

### ISSUE THREAD

**Issue by ChristopherVishoot** [bazaarvoice/jolt#882]
Hey guys,
I'm trying to get the last four digits from the startTime number. What I'm currently doing is as follows:
1) To String the number
2) Get the size of the string
3) Then use that size of the string to get the last four digits.
Input:
{
  "itineraries": [
    {
      "duration": 4682,
      "startTime": 1526096837000,
      "endTime": 1526101519000,
      "walkTime": 0,
      "transitTime": 4248,
      "waitingTime": 434,
      "walkDistance": 0,
      "walkLimitExceeded": false,
      "elevationLost": 0,
      "elevationGained": 0,
      "transfers": 2,
      "legs": [
        {
          "startTime": 1526096838000,
          "endTime": 1526099496000,
          "departureDelay": 0
        }
      ],
      "tooSloped": false
    }
  ]
}

Spec:
[
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "plan": {
        "itineraries": {
          "*": {
            "startTime": "=toString",
            "startSize": "=size(@(1,startTime))"
          }
        }
      }
    }
  },
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "plan": {
        "itineraries": {
          "*": {
            "value": "",
            "startTime": "=substring(@(1,startTime),startSize-4,startSize)"
          }
        }
      }
    }
  }
]
And the desired output:
{
  "itineraries" : [ {
    "duration" : 4682,
    "startTime" : "7000" <-- I want this value to be 7000, instead its "1526096837000",
    "endTime" : 1526101519000,
    "walkTime" : 0,
    "transitTime" : 4248,
    "waitingTime" : 434,
    "walkDistance" : 0,
    "walkLimitExceeded" : false,
    "elevationLost" : 0,
    "elevationGained" : 0,
    "transfers" : 2,
    "legs" : [ {
      "startTime" : 1526096838000,
      "endTime" : 1526099496000,
      "departureDelay" : 0
    } ],
    "tooSloped" : false
  } ],
  "plan" : { }
}

**Comment by wisthy** [comment]
jolt is not doing math on the fly. So, your substr(@(...), size, size -4) will not work. You need to do it in a separate field. 

```
[
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "itineraries": {
        "*": {
          "\\_time": "=toString(@(1,startTime))",
          "\\_size": "=size(@(1,_time))",
          "\\_start": "=intSum(-4, @(1,_size))",
          "startTime": "=substring(@(1,_time), @(1,_start), @(1,_size))"
        }
      }
    }
},
  {
    "operation": "shift",
    "spec": {
      "itineraries": {
        "*": {
          "_*": null,
          "*": "itineraries[&1].&"
        }
      }
    }
  }
] 
```
