### ISSUE TITLE
@(2, amount) - doesnt seem to resolve

### ISSUE THREAD

**Issue by balaji-jagan** [bazaarvoice/jolt#888]
Hi,
I am using shift transform as below. If type is tax, I would like to put the value of amount into cl.sl.subLineItems[1].price. I can see that @2 is working fine. However @(2, amount) is not working for me. Can you please help me point out what is wrong here?

Input:
{
  "charges": [
    {
      "type": "total",
      "amount": 205
    },
    {
      "type": "subtotal",
      "amount": 180
    },
    {
      "type": "totalfee",
      "amount": 250
    },
    {
      "type": "tax",
      "amount": 20
    }
  ]
}

Spec:
[
  {
    "operation": "shift",
    "spec": {
      "charges": {
        "*": {
          "type": {
            "subtotal": {
              "@2": "cl.sl.subLineItems[0].price"
            },
            "tax": {
              "@(2, amount)": "cl.sl.subLineItems[1].price"
            }
          }
        }
      }
    }
  }
]

I am getting below output:
{
  "cl" : {
    "sl" : {
      "subLineItems" : [ {
        "price" : {
          "type" : "subtotal",
          "amount" : 180
        }
      } ]
    }
  }
}

while I am expecting below:
{
  "cl" : {
    "sl" : {
      "subLineItems" : [ {
        "price" : {
          "type" : "subtotal",
          "amount" : 180
        }
      },
      {
        "price": 20
      } ]
    }
  }
}

I see I am getting value of @2 as expected, however @(2, amount) is not working as I was expecting.

Thanks,
Bala

**Comment by ydbondt** [comment]
Have you tried using @(2,amount) without the space in between ?

**Comment by balaji-jagan** [comment]
Hi ydbondt....yes, that fixed it. Thanks very much for your suggestion!
