### ISSUE TITLE
Replacing value inside array is causing merging values into one array

### ISSUE THREAD

**Issue by candres** [bazaarvoice/jolt#898]
Hi there!

I'm trying to replace one value which is inside an array of values, but it is creating a new array with similar values instead of  assign that value to each element of the array.

This is the input: 

> 
> {
>   "office_list": [
>     {
>       "isValid": "1",
>       "test": "asdesa"
>     },
>     {
>       "isValid": "0",
>       "test": "asdesa"
>     },
>     {
>       "isValid": "1",
>       "test": "asdesa"
>     },
>     {
>       "isValid": "0",
>       "test": "asdesa"
>     }
>   ]
> }

I tried with this Jolt transformer:

> [
>   {
>     "operation": "shift",
>     "spec": {
>       "office_list": {
>         "*": {
>           "test": "office_list[&1].test",
>           "isValid": {
>             "0": {
>               "#false": "office_list[&1].isValid"
>             },
>             "1": {
>               "#true": "office_list[&1].isValid"
>             }
>           }
>         }
>       }
>     }
>   }
> ]

But the result is this: 

> {
>   "office_list" : [ {
>     "test" : "asdesa",
>     "isValid" : [ "false", "false" ]
>   }, {
>     "isValid" : [ "true", "true" ],
>     "test" : "asdesa"
>   }, {
>     "test" : "asdesa"
>   }, {
>     "test" : "asdesa"
>   } ]
> }

Actually, I want to have this result: 

> {
>   "office_list" : [ {
>     "test" : "asdesa",
>     "isValid" : "true"
>   }, {
>     "isValid" : "false"
>     "test" : "asdesa"
>   }, { 
>     "isValid" : "true"
>     "test" : "asdesa"
>   }, {
>    "isValid" : "false"
>     "test" : "asdesa"
>   } ]
> }
> 

I have tried several things but I don't know how . to get rid of this issue. I appreciate any help.

Thanks!

**Comment by niernier007** [comment]
[{
	"operation": "shift",
	"spec": {
		"office_list": {
			"*": {
				"test": "office_list[&1].test",
				"isValid": {
					"0": {
						"#false": "office_list[&3].isValid"
					},
					"1": {
						"#true": "office_list[&3].isValid"
					}
				}
			}
		}
	}
}]

**Comment by candres** [comment]
Thanks niernier007, it works!
