### ISSUE TITLE
Create key/value pair from 2 values

### ISSUE THREAD

**Issue by rsdb** [bazaarvoice/jolt#91]
I am trying to convert this json:

```
{
    "id": "1234",
    "classification": "aclass",
    "condition": "poor",
    "links": [
        {
            "name": "self",
            "href": "https://selfurl.com"
        },
        {
            "name": "events",
            "href": "https://eventurl.com"
        }
    ],
    "eventList": {
        "totalCount": 2,
        "criticalCount": 1,
        "majorCount": 1,
        "minorCount": 2,
        "okCount": 0,
        "informationalCount": 0,
        "events": [
            {
                "id": "event1",
                "elementId": "element1",
                "requestedFields": [
                    {
                        "name": "Severity",
                        "value": "Fatal"
                    },
                    {
                        "name": "status_url",
                        "value": "https://statusurl.com"
                    }
                ]
            },
            {
                "id": "event2",
                "elementId": "element2",
                "requestedFields": [
                    {
                        "name": "Severity",
                        "value": "Medium"
                    },
                    {
                        "name": "status_url",
                        "value": "https://statusurl.com"
                    }
                ]
            }
        ]
    }
}
```

with this spec:

```
[
    {
        "operation": "shift",
        "spec": {
            "id": "summary.id",
            "classification": "summary.classification",
            "condition": "summary.condition",
            "eventList": {
                "informationalCount": "summary.informationcount",
                "majorCount": "summary.majorcount",
                "minorCount": "summary.minorcount",
                "okCount": "summary.okcount",
                "totalCount": "summary.totalcount",
                "events": {
                    "0": {
                        "*": {
                            "$": "headers[]",
                            "@": "rows[]"
                        }
                    },
                    "*": {
                        "*": {
                            "@": "rows[]"
                        }
                    }
                }
            }
        }
    }
]
```

which produces:

```
{
  "headers" : [ "id", "elementId", "requestedFields" ],
  "rows" : [ "event1", "element1", [ {
    "name" : "Severity",
    "value" : "Fatal"
  }, {
    "name" : "status_url",
    "value" : "https://statusurl.com"
  } ], "event2", "element2", [ {
    "name" : "Severity",
    "value" : "Medium"
  }, {
    "name" : "status_url",
    "value" : "https://statusurl.com"
  } ] ],
  "summary" : {
    "classification" : "aclass",
    "condition" : "poor",
    "id" : "1234",
    "informationcount" : 0,
    "majorcount" : 1,
    "minorcount" : 2,
    "okcount" : 0,
    "totalcount" : 2
  }
}
```

I want to make 'rows' an array of arrays where each event is stored in a nested array. I would also like to flatten the events and move any nested elements up a level. To do this the 'name' and 'value' values would have to become key/value pairs in the parent (event). So the output would be:

```
{
  "headers" : [ "id", "elementId", "requestedFields" ],
  "rows" : [ ["event1", "element1", "Severity" : "Fatal", "status_url" : "https://statusurl.com"], ["event2", "element2", "Severity" : "Medium", "status_url" : "https://statusurl.com" ] ],
  "summary" : {
    "classification" : "aclass",
    "condition" : "poor",
    "id" : "1234",
    "informationcount" : 0,
    "majorcount" : 1,
    "minorcount" : 2,
    "okcount" : 0,
    "totalcount" : 2
  }
}
```

Is this possible? 

Thanks, 

Rob

**Comment by PujaShankar-Inmarsat** [comment]
Hi. Can you please suggest how can i use values from exchange header in spec.

**Comment by PujaShankar-Inmarsat** [comment]
Hi
I want to incorporate values from exchange header in my spec. Can you please suggest, how can i do that.

**Comment by apiwoni** [comment]
> So your question is "Create key/value pair from 2 values", and generally you can not.
> Aka given
> 
> {
>     "id": "1234",
>     "classification": "aclass"
> }
> There is no way to get
> 
> {
>    "1234" : "aclass" 
> }

This comment has been made in 2014 but I seem to be able to accomplish this task as follows:

[
  {
    "operation": "shift",
    "spec": {
      "classification": "@(1,id)"
    }
  }
]

Is it my misunderstanding of a question or resolution of this limitation since 2014?

**Comment by Raaz43857** [comment]
Hi ,

I need spec for below input and i need output become like below.can you pls help me on this .

Input:
{
  "Result": {
    "requestStatus": 0,
    "requestCode": "SUCCESS",
    "totalReq": 3
  },
  "APrequest": [
    {
      "requestor": [
        {
          "Key": "name",
          "Value": "Raj"
        },
        {
          "Key": "id",
          "Value": "1234"
        },
        {
          "Key": "branch",
          "Value": "IT"
        }
      ],
      "ticketDetails": [
        {
          "Key": "role",
          "Value": "admin"
        },
        {
          "Key": "dept",
          "Value": "skit"
        },
        {
          "Key": "subdept",
          "Value": "skht-skit"
        }
      ]
    }
  ]
}
-----------------------------

expected output:


{
  "Result": {
    "requestStatus": 0,
    "requestCode": "SUCCESS",
    "totalReq": 3
  },
  "APrequest": [
    {
      "requestor": 
        {"name": "Raj","id":"1234","branch":"branch"},  
      "ticketDetails": 
      {"role":"admin","dept":"sk","subdept":"skt"}
    }
    
  ]
}
-----------------------
i have tried below spec  ,but am not getting what i expected above.Can anyone help on this.

[
  {
    "operation": "shift",
    "spec": {
      "Result": { "requestStatus": "requestStatus", "requestCode": "requestCode" },
      "APrequest": {
        "*": {
          "requestor": {
            "*": { "Value": "@(1,Key)" }
          },
            "ticketDetails": {
            "*": { "Value": "@(1,Key)" }
          }
          
        }
      }
    }
  }
]
