### ISSUE TITLE
How to remove first and last element from array of any size and store remaining result in string space separated

### ISSUE THREAD

**Issue by buckyballs** [bazaarvoice/jolt#917]
```
input
{
  "list": [
    [
      "A",
      "B",
      "C",
      "D",
      "E"
    ]
  ]
}
```

```
output
{
  "output": "B C D"
}
```

**Comment by zeshuai007** [comment]
@buckyballs Hi! I don't remember that remover can remove the last element of the array, which is a bit cumbersome
But I have a standard idea, remover removes 0, sortr reverses order, remover removes index0 again, and finally uses modify-join or modify-concat, you can try it.

**Comment by zeshuai007** [comment]
I believe there should be a better way, smart you can share your specifications

**Comment by buckyballs** [comment]
Requirement is to not disturb the insertion order.

**Comment by zeshuai007** [comment]
Hi! If the order cannot be disturbed, I think it can be handled using functions.
But I still have two questions:
1. Are you sure your input is a two-dimensional array, and each element is a string?
2. Did you create a new Issue? Is it the same question?

**Comment by zeshuai007** [comment]
@buckyballs  Hi there is an interesting way to meet your expectations
```
[
  {
    "operation": "modify-overwrite-beta",
    "spec": {
	      		"first":"=firstElement(@(1,list))",
	      		"last":"=lastElement(@(1,list))",
	      		"firstSize":"=size(@(1,first))",
	      		"lastSize":"=size(@(1,last))",
	      		"sum":"=intSum(@(1,firstSize),@(1,lastSize))",
	      		"listJoin": "=join(' ' , @(1,list))",
	      		"listSize":"=size(@(1,listJoin))",
	      		"endLength":"=intSubtract(@(1,listSize), @(1,sum))",
	      		"startIndex":"=intSum(@(1,firstSize),1)",
	      		"list":"=substring(@(1,listJoin), @(1,startIndex), @(1,endLength))"
    }
  },
  {
    "operation": "shift",
    "spec": {
    	"list":"&"
    }
  }
]
```

**Comment by zeshuai007** [comment]
As you can see, this is very tedious. Is there a function nesting function?

**Comment by buckyballs** [comment]
@zeshuai007 thanks for bringing this I think that will work.
