### ISSUE TITLE
Need key from source as value in the transformed outp at end of the array

### ISSUE THREAD

**Issue by myanamadala1** [bazaarvoice/jolt#924]
**input:**
{
  "accessory": {
    "comfort": {
      "en": [
        "(subscription required thereafter)",
        "Bluetooth  Connectivity"
      ]
    },
    "safety": {
      "en": [
        "24-Hour Roadside Assistance Program",
        "Active Brake Assist"
      ]
    },
    "performance": {
      "en": [
        "2.0L Inline-4 Turbo Engine",
        "208 Horsepower"
      ]
    },
    "options": [
      {
        "code": "H06",
        "description": {
          "en": "Black Ash Matte Wood Trim",
          "fr": ""
        }
      },
      {
        "code": "868",
        "description": {
          "en": "Smartphone Integration",
          "fr": ""
        }
      }
    ]
  }
}

**current spec:**
[{
    "operation": "shift",
    "spec": {
      "@accessory": {
        "comfort": {
          "$": "productEquipments[].name.parentPack",
          "en": {
            "*": "productEquipments[].name[].value"
          }
        },
        "safety": {
          "$": "productEquipments[].parentPack",
          "en": {
            "*": "productEquipments[].name[].value"
          }
        },
        "performance": {
          "$": "productEquipments[].parentPack",
          "en": {
            "*": "productEquipments[].name[].value"
          }
        },
        "options": {
          "$": "productEquipments[].parentPack",
          "*": {
            "description": {
              "en": "productEquipments[].name[].value"
            }
          }
        }
      }
    }
	},
  {
    "operation": "default",
    "spec": {
      "productEquipments[]": {
        "*": {
          "name[]": {
            "*": {
              "languageCode": "en"
            }
          }
        }
      }
    }
	}
]

**desired output:**
{
	"productEquipments": [{
			"name": [{
				"value": "(subscription required thereafter)",
				"languageCode": "en"
			}],
			"parentPack": "comfort"
		}, {
			"name": [{
				"value": "Bluetooth  Connectivity",
				"languageCode": "en"
			}],
			"parentPack": "comfort"
		}, {
			"name": [{
				"value": "Active Brake Assist",
				"languageCode": "en"
			}],
			"parentPack": "saftey"
		}, {
			"name": [{
				"value": "ATTENTION ASSIST",
				"languageCode": "en"
			}],
			"parentPack": "saftey"
		}, {
			"name": [{
				"value": "2.0L Inline-4 Turbo Engine",
				"languageCode": "en"
			}],
			"parentPack": "performance"
		},
		{
			"name": [{
				"value": "208 Horsepower",
				"languageCode": "en"
			}],
			"parentPack": "performance"
		},
		{
			"name": [{
				"value": "Black Ash Matte Wood Trim",
				"languageCode": "en"
			}],
			"parentPack": "options"
		},
		{
			"name": [{
				"value": "18\" 5-Twin-Spoke Wheels",
				"languageCode": "en"
			}],
			"parentPack": "options"
		}

	]
}

**Comment by zeshuai007** [comment]
"languageCode": "en"
Is this language encoding fixed?

**Comment by zeshuai007** [comment]
Hi @myanamadala1 When you map to list, you need to pay attention to the number and index of the list.
 If you can solve the index number of the list at one time, the spec will be very concise.
But I used two methods and did not solve the indexing problem of list. E.g
```
[
    {
        "operation": "shift",
        "spec": {
            "accessory": {
                "*": {
                    "en": {
                    	"*":{
                    		"@":"productEquipments[0].name[0].value",
                    		"$1":"productEquipments[0].name[0].languageCode",
                    		"$2":"productEquipments[0].parentPack"
                    	}
                    }
                    
                }
                ,"options":{
                	"*":{
                		"description":{
	                		"en":{
	                			"@":"productEquipments[0].name[0].value",
	                			"$":"productEquipments[0].name[0].languageCode",
	                			"$3":"productEquipments[0].parentPack"
	                		}
                		}
                	}
                }
            }
        }
    },
    {
        "operation": "shift",
        "spec": {
                "productEquipments": {
                    	"0":{
	                    	"name":{
	                    		"0":{
	                    			"value":{
		                    			"*":{
		                    				"@":"productEquipments[&1].name[0].value"
		                    			}
	                    			},
	                    			"languageCode":{
		                    			"*":{
		                    				"@":"productEquipments[&1].name[0].languageCode"
		                    			}
	                    			}
	                    		}
	                    	},
	                    	"parentPack":{
	                    		"*":{
		                    				"@":"productEquipments[&1].parentPack"
		                    			}
	                    	}
                    	}
                }
        }
    }
]
```

**Comment by zeshuai007** [comment]
E.g:
```
[{
        "operation": "shift",
        "spec": {
            "accessory": {
                "comfort": {
                    "en": {
                    	"*":{
                    		"@":"comfort[#2].name[0].value",
                    		"$1":"comfort[#2].name[0].languageCode",
                    		"$2":"comfort[#2].parentPack"
                    	}
                    }
                },
                "safety": {
                    "en": {
                    	"*":{
                    		"@":"safety[#2].name[0].value",
                    		"$1":"safety[#2].name[0].languageCode",
                    		"$2":"safety[#2].parentPack"
                    	}
                    }
                },
                "performance": {
                    "en": {
                    	"*":{
                    		"@":"performance[#2].name[0].value",
                    		"$1":"performance[#2].name[0].languageCode",
                    		"$2":"performance[#2].parentPack"
                    	}
                    }
                },
                "options":{
                	"*":{
                		"description":{
	                		"en":{
	                			"@":"options[#4].name[0].value",
	                			"$":"options[#4].name[0].languageCode",
	                			"$3":"options[#4].parentPack"
	                		}
                		}
                	}
                }
                
            }
        }
    },
    {"operation": "shift",
        "spec": {
                "comfort": {
                    	"*":{"@":"productEquipments[]"}
                },
                "safety":{
                    	"*":{"@":"productEquipments[]"}
                },
                "performance": {
                    	"*":{"@":"productEquipments[]"}
                },
                "options":{
                    	"*":{"@":"productEquipments[]"}
                }
        }
}]
```

**Comment by myanamadala1** [comment]
Thank You Zezeng Wang, how do i build a new array similar to productEquiptment with in the same spec.

**Comment by myanamadala1** [comment]
> "languageCode": "en"
> Is this language encoding fixed?

not a fixed value
