### ISSUE TITLE
Diacritics are changed to "?" after transformation

### ISSUE THREAD

**Issue by jastka4** [bazaarvoice/jolt#936]
Hi, I saw an issue with special characters from my language. When I use an input like the one below and transform it, I get question marks instead of special chars from my input. It looks to me like a bug because the input should not be changed during the transformation.

Tested using https://jolt-demo.appspot.com

**Input:**
```
{
  "text": "zażółć gęślą jaźń"
}
```

**Output:**
```
{
  "transformedText" : "za?ó?? g??l? ja??"
}
```

**Comment by zeshuai007** [comment]
I use UTF-8 to verify that I do n’t have this garbled error. 
This may be a problem with the jolt-demo.appspot environment encoding.

**Comment by jastka4** [comment]
Yeah, it seems that this is an encoding issue. I tested it locally and everything works fine, but not on the website.

**Comment by buinhatminh7899** [comment]
> I use UTF-8 to verify that I do n’t have this garbled error. This may be a problem with the jolt-demo.appspot environment encoding.

how did you implement UTF-8 to verify?
