### ISSUE TITLE
Add/Extend custom functions

### ISSUE THREAD

**Issue by fjavierponce** [bazaarvoice/jolt#959]
Hello, is it possible to add my own class and implement custom function to the ChainrBuilder implementation? I am getting a `ClassNotFoundException` and saw the ClassLoader related is here https://github.com/bazaarvoice/jolt/blob/master/jolt-core/src/main/java/com/bazaarvoice/jolt/chainr/ChainrBuilder.java#L32. My spec is the following.

```
  {
    "operation": "com.transform.Evaluatr",
    "spec": {
      "appliedRateUpdate": {
           "amountAboveRates": {
                "*": {
                  "onePersonRate": "=evalRoundIfFloat(%s + %s, @(1,baseOnePersonRate), @(1,onePersonAmountAbove))",
                 "twoPersonRate": "=evalRoundIfFloat(%s + %s, @(1,baseTwoPersonRate), @(1,twoPersonAmountAbove))"
          }    
      }
    }
}
```

**Comment by arvindnitr** [comment]
We can achieve custom transformation using our java class. Need to mention that in spec file array.

 {
    "operation": "com.arvind.transformers.MyTransformer",
    "spec": {
      "input": "output"
    }
  }

public class MyTransformer implements Transform {
    @Override
    public Object transform(Object input) {
        System.out.println("In custom Pre-transform:" + input);
        return input;
    }
}

**Comment by fjavierponce** [comment]
Yea that works, thank you!
